### ISSUE TITLE
getKey();

### ISSUE THREAD

**Issue by sfxworks** [distriqt/ANE-Firebase#100]
I need to be able to get my reference's key after a push. Currently there is no function in this to mirror the one in the [Android SDK](https://firebase.google.com/docs/database/android/read-and-write#update_specific_fields).

**Comment by marchbold** [comment]
Appears we have missed that, will get it into the next update.

**Comment by kakarlus** [comment]
or at least make it available in the event `DatabaseReferenceEvent.SET_VALUE_COMPLETE` as a snapshot of type `DataSnapshot`. right now i'm getting snapshot=null

**Comment by marchbold** [comment]
We will be adding a `getKey` function to the reference.

**Comment by marchbold** [comment]
Reference:

https://distriqt.github.io/ANE-Firebase/asdocs/com/distriqt/extension/firebase/database/DatabaseReference.html#getKey()
