### ISSUE TITLE
Cannot package Android application

### ISSUE THREAD

**Issue by david-daal** [distriqt/ANE-Firebase#101]
Hi guys

I am not sure that problem is relate to Firebase ANE, but as we stuck to it while firebase implementation I am creating issue here. :)

We are not able to package AIR application when using following extension
```
    <extensions>
        <extensionID>com.distriqt.Notifications</extensionID>
        <extensionID>com.distriqt.ApplicationRater</extensionID>
        <extensionID>com.distriqt.Application</extensionID>
        <extensionID>com.distriqt.NetworkInfo</extensionID>
        <extensionID>com.distriqt.Dialog</extensionID>
        <extensionID>com.distriqt.FacebookAPI</extensionID>
        <extensionID>com.distriqt.Bolts</extensionID>
        <extensionID>com.distriqt.Core</extensionID>
        <extensionID>com.distriqt.Firebase</extensionID>
        <extensionID>com.distriqt.firebase.Auth</extensionID>
        <extensionID>com.distriqt.firebase.Database</extensionID>
        <extensionID>com.distriqt.firebase.Config</extensionID>
        <extensionID>com.distriqt.playservices.Base</extensionID>
        <extensionID>com.distriqt.androidsupport.AppCompatV7</extensionID>
        <extensionID>com.distriqt.androidsupport.V4</extensionID>
        <extensionID>com.distriqt.androidsupport.CustomTabs</extensionID>
        <extensionID>com.distriqt.androidsupport.CardViewV7</extensionID>
    </extensions>
```

We use latest versions of ANEs from github.

We receive following exception.

```   
unexpected failure: duplicate entry: air/com/plexonic/meln2/R.class
                java.util.zip.ZipException: duplicate entry: air/com/plexonic/meln2/R.class
                at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
                at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
                at com.adobe.air.apk.ResourceBytecodeGenerator.generateFromRFile(ResourceBytecodeGenerator.java:85)
                at com.adobe.air.apk.APKOutputStream.generateByteCodeFromRFile(APKOutputStream.java:1058)
```

Do you have any idea how can this be fixed?

**Comment by marchbold** [comment]
Hi, 

Sounds like there's an issue with the firebase Config ANE you have generated. I think we may have an issue in our documentation. Try leaving the package name as the default in the script rather than changing to your application package.

**Comment by david-daal** [comment]
Hi that doesnt help.

Also I noticed that there is no "config" folder with Config ane building resources there.
So I generated Config.ANE using the latest one I had downloaded before.
Is that possible that it is outdated? And Config anes should be regenerated?

**Comment by marchbold** [comment]
Yes, the config directory should never have been used. You should use the custom resources script.

https://github.com/distriqt/ANE-CustomResources/

**Comment by marchbold** [comment]
Do you get the error if you remove the custom resources ane?

**Comment by david-daal** [comment]
Now I get following error:

dx tool failed:<br>UNEXPECTED TOP-LEVEL ERROR:<br>java.lang.OutOfMemoryError: GC overhead limit exceeded<br>    at com.android.dx.util.ByteArray.slice(ByteArray.java:98)<br>    at com.android.dx.cf.cst.ConstantPoolParser.parseUtf8(ConstantPoolParser.java:368)<br>    at com.android.dx.cf.cst.ConstantPoolParser.parse0(ConstantPoolParser.java:262)<br>    at com.android.dx.cf.cst.ConstantPoolParser.parse(ConstantPoolParser.java:150)<br>    at com.android.dx.cf.cst.ConstantPoolParser.parseIfNecessary(ConstantPoolParser.java:124)<br>    at com.android.dx.cf.cst.ConstantPoolParser.getPool(ConstantPoolParser.java:115)<br>    at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:482)<br>    at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)<br>    at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)<br>    at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)<br>    at com.android.dx.command.dexer.Main.processClass(Main.java:709)<br>    at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)<br>    at com.android.dx.command.dexer.Main.access$300(Main.java:83)<br>    at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)<br>    at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)<br>    at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)<br>    at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)<br>    at com.android.dx.command.dexer.Main.processOne(Main.java:637)<br>    at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)<br>    at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)<br>    at com.android.dx.command.dexer.Main.run(Main.java:245)<br>    at com.android.dx.command.dexer.Main.main(Main.java:215)<br>    at com.android.dx.command.Main.main(Main.java:106)

**Comment by marchbold** [comment]
You'll need to increase the memory available to java when executing adt . This is normally a config option for your ide.

**Comment by david-daal** [comment]
Hi that helps thanks
Also the main error was fixed when followed these instructions.

> Hi,
 Sounds like there's an issue with the firebase Config ANE you have generated. I think we may have  an issue in our documentation. Try leaving the package name as the default in the script rather than changing to your application package.

**Comment by marchbold** [comment]
Excellent! Let us know if you have any further issues.

Cheers
