### ISSUE TITLE
Background Operations

### ISSUE THREAD

**Issue by sfxworks** [distriqt/ANE-Firebase#104]
98% of testing has resulted in my current tests subjects, as long as they have a connection, posting whatever they may to the database within seconds. 

However, two instances of the same user (with him being in a bad area) resulted in an order being saved on his device but not posted until 20-40 minutes later.

Is there a way for me to detect whether or not the local database successfully posted to the main one? I know I can detect whether or not the user is online with the [.info](https://firebase.google.com/docs/database/android/offline-capabilities#section-connection-state) node. Though I wasn't able to gather enough testing data to determine whehter or not the database was considered "online". Only a report that the device was successfully connected via WWAN but not able to post during that time. Does ANE-Firebase get throttled or shutdown at all while the application is in the background? Or does it actively seek a connection and post it even with the AIR application out of focus? What about when it is completely closed? Does google play services or another service produced by the ANE perhaps handle it from there in that worst-case scenario so the information will eventually post? I know there is also a dependency on the expiration of the login token.

**Comment by marchbold** [comment]
The way the database synchronises in the background is part of the Firebase SDK and outside the control of the ANE. 

There is some information here about the offline handling:

https://firebase.google.com/docs/database/android/offline-capabilities
