### ISSUE TITLE
Need info on Firebase FCM integration with Push notifications

### ISSUE THREAD

**Issue by edt-developer** [distriqt/ANE-Firebase#106]
We use your ANE's quite heavily, and we have a project to implement FCM in our IOS/Android Air apps, but I cannot seem to find any info on how the Firebase ane works with Firebase Cloud Messaging. All I can find is that it works in conjunction with the Push Notifications ane, but can't find any documentation on how to set it up, how the two work together, and what limitations there are if any. 

Here are my basic questions:
2. Can the app receive messages sent from the firebase web console?
3. Is there any detailed documentation and wiki on how to set it all up on the client side? 
4. Are there any known limitations in terms of receiving FCM messages in an Air app for IOS/Android?
5. Are there any Air developers actually using this functionality now(the Firebase and  Push Notification ANE's with FCM) across IOS and Android? 

Thanks!

**Comment by marchbold** [comment]
Hi,

FCM is definitely supported and is in use by AIR devs. We use it ourselves in several applications. 

Our approach has been to keep the FCM implementation in the PushNotifications ANE. You could equally say the PushNotifications ANE is `com.distriqt.firebase.FCM` however as the PushNotifications ANE allows you to implement many other notification platforms we decided to keep all the push related implementations in the one ANE.

So basically you add Firebase as normal and then add the PushNotifications ANE as per the guide.

- Yes you can receive messages sent from the web console
- Documentation for setting up FCM is part of the PushNotifications wiki: [FCM wiki](https://github.com/distriqt/ANE-PushNotifications/wiki/s.Firebase-Cloud-Messaging)
- There are no major limitations aside from how the platforms restrict their usage. 
  - iOS has a minor significance issue to do with customising rich media notifications on iOS. We have only been able to provide basic rich media (eg images) and not the deep integration with other widgets (eg calendars).
  - Android has an issue with the latest AndroidSupport libs meaning we are having to hold off on an update to fully support "Channels" in Android 8.0 (If possible, please add your support to get the issue fixed: https://tracker.adobe.com/#/view/AIR-4198465)

**Comment by edt-developer** [comment]
Thank you very much for the info. I get a 404 when clicking the FCM Wiki link, which accounts for why I can't find any detailed info. https://github.com/distriqt/ANE-PushNotifications/wiki/s.Firebase-Cloud-Messaging

**Comment by marchbold** [comment]
Ah yeah I assumed you were subscribed. The public link is here (apologies for the formatting we are working on that):

http://distriqt.github.io/ANE-PushNotifications/s.Firebase%20Cloud%20Messaging

**Comment by sfxworks** [comment]
> http://distriqt.github.io/ANE-PushNotifications/s.Firebase%20Cloud%20Messaging

Side menu a bit buggy. Only visible if you zoom out with it. Not scroll-able and cluttered when zoomed at 100%.

![image](https://user-images.githubusercontent.com/5921035/31498121-2a873e98-af2f-11e7-8790-9d7a73b87a1a.png)
![image](https://user-images.githubusercontent.com/5921035/31498132-307825f6-af2f-11e7-91d3-ade3f31f3824.png)

**Comment by marchbold** [comment]
Thanks, we are aware of this and have an update rolling out across all our ANEs. Obviously the subscriber docs are correctly formatted in the wiki.
