### ISSUE TITLE
Cannot build both iOS and Android after Firebase integration

### ISSUE THREAD

**Issue by WienerGames** [distriqt/ANE-Firebase#107]
Hello guys,

After integrating the Firebase library I cannot make release builds anymore. It seems like the library is conflicting with some of the other libraries (mainly GoogleIdentity). Both iOS and Android builds fail with different reasons. I have attached my descriptor xml.

##### Expected behaviour

Succesfull builds.

##### Actual behaviour

The packager fails with the following errors:

**On Android:**
Failed to package AIR application XXXXXXXX.apk:
				aapt tool failed:C:\Users\herrd\AppData\Local\Temp\8c973ab4-6d4c-4d2f-911d-adaacd775253\appcompat-v7-26.1.0-res\values-v26\values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

**On iOS:**
Check the attached error.txt file.

##### Environment 

- AIR SDK version: 27 (tried 26 also - same result)
- Device OS: Doesn't matter - cannot build
- Device version: N/A
- Development IDE: IntelliJ IDEA
- Development OS: Windows / Mac OS (same results)

##### Logs

Attached
[Archive.zip](https://github.com/distriqt/ANE-Firebase/files/1359972/Archive.zip)

**Comment by marchbold** [comment]
Hi,

With Android please use v25.3.1 of the Android support libraries. There is an issue with the AIR SDK and v26. We have reported it here: https://tracker.adobe.com/#/view/AIR-4198465 and have published v26 to help adobe resolve the issue.

With iOS appears you have a conflict with another ANE. What other ANEs are you using in your project.

**Comment by WienerGames** [comment]
Hey,

Thanks for the response. Using the older Android support libs resolved the Android build problems indeed - thanks.

As for the iOS - we have tried to remove all non-distriqt ANEs from the project - it still throws the error. After some tryouts it turns out that the conflicting ANEs are:
com.distriqt.GoogleIdentity
com.distriqt.Firebase

If we remove either of them - the build passes. When they are both in - we get this error. We use the latest versions from GIT for both. Any idea how to solve that?

**Comment by marchbold** [comment]
This issue appears to be a conflict between the native Firebase and Google Identity frameworks. 

I'm looking into solutions but currently they seem to involve altering the frameworks, which we generally don't like to do but may be the only solution here.

**Comment by WienerGames** [comment]
Hey,

Thanks for the clarification. That's quite unfortunate :( A quick question - if we use Firebase for the social logins, would that solve the problem? Or it still goes through the GoogleIdentity ANE?

**Comment by marchbold** [comment]
Unfortunately Firebase uses these libs for login so currently I can't offer a solution. I've found some references with people modifying the Google frameworks to make them compatible so I'm going to try that out with our Google Identity ANE to see if we can make them work together. 

Will have an update for you later this week.

**Comment by WienerGames** [comment]
Hello guys,

Any news on the topic?

**Comment by marchbold** [comment]
We are working on a solution. Will let you know as soon as we have something to test.

**Comment by marchbold** [comment]
Hi, I'm moving this issue to the Google Identity extension issue tracker. I'll post a beta version there today.

https://github.com/distriqt/ANE-GoogleIdentity/issues/42

**Comment by WienerGames** [comment]
Thanks a lot for the quick reaction! Will start testing the beta as soon as it's available.
