### ISSUE TITLE
Firebase is compatible with the Amazon App Store?

### ISSUE THREAD

**Issue by railnation** [distriqt/ANE-Firebase#110]
Hi, 

Could you give me a statement about Firebase and the Amazon App Store?

Best 

Christian

**Comment by marchbold** [comment]
Firebase relies on Google Play Services which is only available on compatible Android devices, generally only available to apps distributed via the Google Play Store. 

Amazon devices run FireOS which does not have Google Play Services and makes services like Firebase not supported. 

In the [prerequisites](https://firebase.google.com/docs/android/setup#prerequisites):

> - A device running Android 4.0 (Ice Cream Sandwich) or newer, and Google Play services 11.4.2 or higher 

There are reports of some of the Firebase services working on Amazon, including analytics and realtime database however they aren't supported so use at your own risk.

**Comment by railnation** [comment]
Hi, 

Thank you for the information. Do you see any chance to build a Rest Wrapper if the app is for the amazon app store or is it possible to package the Google Play Services inside the Native Extension?

**Comment by marchbold** [comment]
Unfortunately it's not allowed to distribute the play services. 

You should be able to use the rest API if you wish to fallback to that on unsupported devices. There's no particular need for an ANE for that though as it should be available through the normal AS3 APIs.

**Comment by sfxworks** [comment]
Rest also doesn't support as many features as the ANE itself (offline db, crash reporting, ext).

I have built a rest API if you want to use/contribute to it. https://github.com/sfxworks/FirebaseREST

If you want to build one from scratch, check out phantomappdev's guides.

**Comment by railnation** [comment]
@sfxworks Thank you for your help. I will have a look at your FirebaseREST

**Comment by marchbold** [comment]
@sfxworks That looks great! What's functioning in the API so far?

**Comment by sfxworks** [comment]
@marchbold Thank you! I have database read/write/real-time, email auth/registration and upload/downloading for storage. Still working out a few kinks when it comes to keeping the session alive but my main goal is to fix that today.

**Comment by marchbold** [comment]
Do you think the REST API would work as a default implementation for the ANEs at all?

**Comment by sfxworks** [comment]
I think it would. I have been working with an offline cache script that works with the REST service. Putting that in there would make the REST Database nearly identical to FirebaseDatabase. This would let railnation and other amazon publishers have basic access to Firebase services.

**Comment by railnation** [comment]
Does the Analytics works in the REST API?

**Comment by sfxworks** [comment]
Unfortunately no. However, you could always use [Google Analytics](https://developers.google.com/analytics/devguides/collection/other/flashTrackingIntro) and then transport your results to Firebase.
