### ISSUE TITLE
Firestore

### ISSUE THREAD

**Issue by sfxworks** [distriqt/ANE-Firebase#111]
Implementation of Firestore in Firebase would be sweet

https://firebase.googleblog.com/2017/10/introducing-cloud-firestore.html

**Comment by marchbold** [comment]
We have actually started looking into this already. Will get it into development soon.

Documentation:
- https://firebase.google.com/docs/firestore/

**Comment by gevorg-gsar** [comment]
@marchbold is there any hope for FireStore implementation in Firebase ANE?

**Comment by marchbold** [comment]
Yes, development is well underway on the Firestore ANE we are hoping for a release this month.

**Comment by marchbold** [comment]
Hi all,

Apologies for the delay on this one. We have a beta version available at the link below. 

https://www.dropbox.com/s/6uruvraebovu8vu/com.distriqt.Firebase.v2.3.063.zip?dl=0

I'll push all the documentation into the wiki as well so you'll have access to the current documentation.

https://github.com/distriqt/ANE-Firebase/wiki/Firestore---Introduction

If you have any feedback please let us know. We are planning to push this into release at the end of next week.
