### ISSUE TITLE
Firebase Database. UpdateChildren bad performance on Android platform

### ISSUE THREAD

**Issue by david-daal** [distriqt/ANE-Firebase#113]
Hi guys.

We experienced performance issues on UpdateChildren method in Firebase Database.

On Android devices duration of UpdateChildren execution takes ages;
We tested for Android and IOS devices for different length of Array;

The code
```
/*
rootNode equals to "/users"
/node equals to  "progress"
values Array containing user progress
*/
    public function updateChildren(node:String, values:Array, rootNode:String, callback:Function):void {
        var ref:DatabaseReference = FirebaseDatabase.service.getReference(rootNode);
        var builder:UpdateChildrenBuilder = new UpdateChildrenBuilder();
            
        builder.update(node, values);
            
        ref.addEventListener(DatabaseReferenceEvent.UPDATE_CHILDREN_COMPLETE, updateChildrenCompleteHandler);
        var o:Object = builder.build();
        var startTime:Number = getTimer();
        ref.updateChildren(o);
        function updateChildrenCompleteHandler(event:DatabaseReferenceEvent):void {
            trace("updateChildren platform = " + Agent.instance.platform + " duration = " + (getTimer() - startTime) + "ms values length = " + values.length);
            ref.removeEventListener(DatabaseReferenceEvent.UPDATE_CHILDREN_COMPLETE, updateChildrenCompleteHandler);
        }
    }
```
`values` in example is the list of `{highscore:100, id:"", index:0, stars:3}` objects

Here are the results of test execution for different `values` array sizes:
```
updateChildren platform = IOS duration = 407ms values length = 100
updateChildren platform = AND duration = 6249ms values length =100
updateChildren platform = IOS duration = 578ms values length = 200
updateChildren platform = AND duration = 7865ms values length = 200
updateChildren platform = IOS duration = 581ms values length = 300
updateChildren platform = AND duration = 15369ms values length = 300
updateChildren platform = IOS duration = 628ms values length = 400
updateChildren platform = AND duration = 20373ms values length = 400
```

Looks like something is wrong with Android ANE, could you please take a look?

**Comment by marchbold** [comment]
Can you  provide a complete test to illustrate this issue, not really sure what your parameters are to this function.

There are inherit differences between Android and iOS especially in the conversion of values, the C base of iOS is faster in object conversion than java on Android and leads to issues when converting a large number of values from AS3 to native.

**Comment by david-daal** [comment]
Hi marchbold
Any news on this?

**Comment by marchbold** [comment]
Hi, We are working on replicating the issue and will get back to you as soon as we discover the issue.

**Comment by marchbold** [comment]
Unfortunately this just appears to be the result of the time taken to convert values from FREObjects to Java. 

What device are you testing on? We haven't seen anything like your numbers, more in the 2-4 seconds for 400 values. 4 seconds on a 5 year old device so nothing like the 20s listed above?

We don't recommend doing so many updates in a single call.

**Comment by david-daal** [comment]
Hi marchbold.
You are right on most of devices it takes about 4 seconds. 
Same data on IOS devices processed in 400ms.
But we have a device where it takes much longer  about a 15-20seconds.
It's HTC One E9 Dual SIM and we don't have any idea why.

**Comment by marchbold** [comment]
Can you break your timings up and see if its the function call or the async processing that's taking 20seconds?

The FREObject conversion happens in the function call whereas the event is dispatched after the asynchronous call to firebase is completed.
