### ISSUE TITLE
iOS not reporting metadata

### ISSUE THREAD

**Issue by sfxworks** [distriqt/ANE-Firebase#114]
On android, I use a storage meta data reference to get the md5 to check and see if I need to download it again. Works fine. No problems. However, when using the same code for iOS, the event gets fired as successful but the md5 is an empty string. 

##### Expected behaviour

e.metadata.md5 returns a value.

##### Actual behaviour

e.metadata.md5 returns no value with other values populated ok.
##### Environment 

- AIR SDK version: 25
- Device OS: iOS
- Device version: 11
- Development IDE: Animate 
- Development OS: Windows

##### Logs

**IOS**
````
Getting file for Rounds Peach Ice
Meta success for reference:Rounds Water Dragon Ice
Storage meta data = {"values":{},"keys":[],"cacheControl":null,"contentDisposition":"inline; filename*=utf-8''Rounds%20Water%20Dragon%20Ice.jpg","creationTime":1507827959460,"updatedTime":1507827959460,"contentEncoding":"identity","name":"Rounds Water Dragon Ice.jpg","path":"Rounds Water Dragon Ice.jpg","contentLanguage":null,"bucket":"mobile-vape-distro.appspot.com","size":74893,"contentType":"image/jpeg","downloadUrl":"https://firebasestorage.googleapis.com/v0/b/mobile-vape-distro.appspot.com/o/Rounds%20Water%20Dragon%20Ice.jpg?alt=media&token=af2fa9ce-e470-42a7-9b69-cab98b701272","generation":"1507827959498741","metadataGeneration":"1","md5Hash":""}
MD5 hash = 
````

**Android**:
````
Getting file for Rounds Peach Ice
Meta succes for reference:Rounds Peach
Storage meta data = {"keys":[],"values":{},"downloadUrl":"https://firebasestorage.googleapis.com/v0/b/mobile-vape-distro.appspot.com/o/Rounds%20Peach.jpg?alt=media&token=83b9efde-1c54-447f-ab8f-b1c7bd7aa9be","creationTime":1504790938260,"path":"Rounds Peach.jpg","updatedTime":1504790938260,"bucket":"mobile-vape-distro.appspot.com","generation":"1504790938402388","metadataGeneration":"1","md5Hash":"nXJn8JKSteKhrj/h3FtZHQ==","name":"Rounds Peach.jpg","contentType":"image/jpeg","size":71923,"cacheControl":"","contentDisposition":"inline; filename*=utf-8''Rounds%20Peach.jpg","contentEncoding":"","contentLanguage":""}
MD5 hash = nXJn8JKSteKhrj/h3FtZHQ==
````

Edit: Note, files are different in this log because they were hard to capture but both of them have an md5hash property.

**Comment by sfxworks** [comment]
File get is not on sync with file meta success log due to it loading multiple at one. Although both files should have a b64 of an md5 in the md5 and both files work fine on Android.

**Comment by marchbold** [comment]
Unfortunately the Firebase iOS SDK doesn't report the MD5 for a file. Here is the reference for the storage metadata on iOS:

https://firebase.google.com/docs/reference/ios/firebasestorage/api/reference/Classes/FIRStorageMetadata
