### ISSUE TITLE
why this repo is visible to users that not purchased this plugin ?

### ISSUE THREAD

**Issue by Xgamefactory** [distriqt/ANE-Firebase#115]
Hi,
We did not buy this plugin and not free plugin github repos are not visible.
Is it sort of demo ? Downloading anes in this repo will work for a trial period ?
Or it just a public readonly repo ?

**Comment by marchbold** [comment]
This is a trial of making the repository public. It was originally public for the beta and we are seeing how it goes as leaving it public.

The ANEs still require an application key generated through our site with a purchased license to work.
