### ISSUE TITLE
Android: Firebase Analytics Events do not appear in the Firebase Console

### ISSUE THREAD

**Issue by sashthecash** [distriqt/ANE-Firebase#118]
##### Expected behaviour
logged Events from my Android App appear in the Firebase Console under Events and StreamView

##### Actual behaviour
No Events visible neither under Events nor StreamView

##### Environment 

- AIR SDK version: 27.0.0 build 128
- Device OS: Android (Pixel XL)
- Device version: 8.0.0
- Development IDE: IntelliJ IDEA 2017.1
- Development OS: macOS Sierra Version 10.12.6 

##### Logs

`V/FA: App package, google app id: air.com.myapp.package, X:XXXXXXXX:android:XXXXXXXX`

I have added the Firebase ANE to use Firebase Analytics. I followed the Instructions under https://distriqt.github.io/ANE-Firebase/Setup%20-%20Configuration%20Files to create a CustomResources ANE. One thing I noticed is that Firebase seemed to initialize with the wrong settings, i found that out by looking in the logcat logs where it printed a google app id that matches  the one found in this example project: https://github.com/distriqt/ANE-Firebase/blob/master/example/core/starling/src/google-services.json. I guess that somehow IntelliJ cached the ANE and ignored all changes i made to the CustomResources ANE. After changing the bundle ID in build_config/extensions.xml IntelliJ seems to pick up the right ANE and logcat prints the correct google app id:
`V/FA: App package, google app id: air.com.myapp.package, X:XXXXXXXX:android:XXXXXXXX`
Also this line `var success:Boolean = Firebase.service.initialiseApp();` produces `success == true`.
I also made all necessary adjustments to the Manifest part in the descriptor file.
Unfortunately i can't find any Events logged in the Firebase Console.

Maybe this is also relevant, logcat prints:
```
E/FA: AppMeasurementService not registered/enabled
E/FA: Uploading is not possible. App measurement disabled
```
but later:
```
V/FA: Using measurement service
V/FA: Connecting to remote service
V/FA: Activity paused, time: 5553805930
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 1
```

Everything works fine on iOS. Also Notifications sent using the Firebase Message Composer work too, both on iOS and Android.

**Comment by marchbold** [comment]
Sounds like an issue with your configuration. Can you post the entire log around when your application starts up? 

Which version of the ANE are you using?

**Comment by sashthecash** [comment]
I updated all ANEs on 22.11.2017, so i guess it's all up to date.

Here are the logs:

```
11-27 17:35:10.013 25309-25309/? I/zygote: Late-enabling -Xcheck:jni
11-27 17:35:10.111 25309-25309/air.my.bundle.id I/MultiDex: VM with version 2.1.0 has multidex support
11-27 17:35:10.112 25309-25309/air.my.bundle.id I/MultiDex: install
11-27 17:35:10.112 25309-25309/air.my.bundle.id I/MultiDex: VM has multidex support, MultiDex support library is disabled.
11-27 17:35:10.119 25309-25309/air.my.bundle.id D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
11-27 17:35:10.134 25309-25309/air.my.bundle.id D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
11-27 17:35:10.145 25309-25309/air.my.bundle.id I/FA: App measurement is starting up, version: 11020
11-27 17:35:10.145 25309-25309/air.my.bundle.id I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
11-27 17:35:10.156 25309-25309/air.my.bundle.id V/FA: Collection enabled
11-27 17:35:10.156 25309-25309/air.my.bundle.id V/FA: App package, google app id: air.my.bundle.id, 1:CRYPTIC_NUMBERS:android:MORE_CRYPTIC_NUMBERS
11-27 17:35:10.157 25309-25309/air.my.bundle.id I/FA: To enable faster debug mode event logging run:
                                                                 adb shell setprop debug.firebase.analytics.app air.my.bundle.id
11-27 17:35:10.157 25309-25309/air.my.bundle.id D/FA: Debug-level message logging enabled
11-27 17:35:10.162 25309-25309/air.my.bundle.id V/FA: Cancelling job. JobID: -303290482
11-27 17:35:10.163 25309-25309/air.my.bundle.id V/FA: Registered activity lifecycle callback
11-27 17:35:10.165 25309-25309/air.my.bundle.id I/FirebaseInitProvider: FirebaseApp initialization successful
11-27 17:35:10.177 25309-25337/air.my.bundle.id E/FA: AppMeasurementService not registered/enabled
11-27 17:35:10.177 25309-25337/air.my.bundle.id E/FA: Uploading is not possible. App measurement disabled
11-27 17:35:10.188 25309-25309/air.my.bundle.id V/FA: onActivityCreated
11-27 17:35:10.188 25309-25309/air.my.bundle.id I/StartupTime1: :1511800510188
11-27 17:35:10.292 25309-25337/air.my.bundle.id V/FA: Using measurement service
11-27 17:35:10.293 25309-25337/air.my.bundle.id V/FA: Connecting to remote service
11-27 17:35:10.311 25309-25337/air.my.bundle.id V/FA: Activity resumed, time: 5819212780
11-27 17:35:10.315 25309-25337/air.my.bundle.id I/FA: Tag Manager is not found and thus will not be used
11-27 17:35:10.441 25309-25314/air.my.bundle.id I/zygote: Do partial code cache collection, code=31KB, data=23KB
11-27 17:35:10.442 25309-25314/air.my.bundle.id I/zygote: After code cache collection, code=31KB, data=23KB
11-27 17:35:10.442 25309-25314/air.my.bundle.id I/zygote: Increasing code cache capacity to 128KB
11-27 17:35:10.532 25309-25309/air.my.bundle.id W/System.err: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
11-27 17:35:10.532 25309-25309/air.my.bundle.id W/System.err:     at android.app.ContextImpl.checkMode(ContextImpl.java:2392)
11-27 17:35:10.532 25309-25309/air.my.bundle.id W/System.err:     at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:383)
11-27 17:35:10.532 25309-25309/air.my.bundle.id W/System.err:     at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:370)

... (clipped stacktrace here)

11-27 17:35:10.803 25309-25309/air.my.bundle.id D/StartupTime2: :1511800510659
11-27 17:35:10.803 25309-25309/air.my.bundle.id I/__BUILD_NO: #27.0.0.128
11-27 17:35:10.840 25309-25309/air.my.bundle.id D/com.distriqt.Firebase: FirebaseController::initialiseApp()
11-27 17:35:10.841 25309-25309/air.my.bundle.id D/com.distriqt.Firebase: FirebaseController::initialiseApp(): Already initialised
11-27 17:35:10.857 25309-25309/air.my.bundle.id D/com.distriqt.Firebase: FirebaseAnalyticsController::setUserID( 4e70373c771c2f7f2e16ea0b8e32d94e02a6 )
11-27 17:35:10.885 25309-25314/air.my.bundle.id I/zygote: Do partial code cache collection, code=62KB, data=45KB
11-27 17:35:10.885 25309-25314/air.my.bundle.id I/zygote: After code cache collection, code=62KB, data=45KB
11-27 17:35:10.885 25309-25314/air.my.bundle.id I/zygote: Increasing code cache capacity to 256KB
11-27 17:35:10.892 25309-25309/air.my.bundle.id I/AVC: d600ea00
11-27 17:35:10.893 25309-25309/air.my.bundle.id I/Choreographer: Skipped 32 frames!  The application may be doing too much work on its main thread.
11-27 17:35:10.939 25309-25309/air.my.bundle.id I/Adreno: QUALCOMM build                   : 7142022, Ib5823dd10c
                                                                   Build Date                       : 06/23/17
                                                                   OpenGL ES Shader Compiler Version: EV031.18.00.00
                                                                   Local Branch                     : O11A
                                                                   Remote Branch                    : 
                                                                   Remote Branch                    : 
                                                                   Reconstruct Branch               : 
11-27 17:35:10.941 25309-25309/air.my.bundle.id I/Adreno: PFP: 0x005ff087, ME: 0x005ff063
11-27 17:35:11.014 25309-25309/air.my.bundle.id I/AVC: d600ea00
11-27 17:35:11.023 25309-25337/air.my.bundle.id D/FA: Connected to remote service
11-27 17:35:11.023 25309-25337/air.my.bundle.id V/FA: Processing queued up service tasks: 1
11-27 17:35:12.940 25309-25309/air.my.bundle.id D/com.distriqt.Firebase: LogEventFunction::params[is_it_a_test] (String) = 
11-27 17:35:12.947 25309-25309/air.my.bundle.id D/com.distriqt.Firebase: FirebaseAnalyticsController::logEvent( [test_action], Bundle{
                                                                                   is_it_a_test => true;
                                                                                   }Bundle )
```

**Comment by marchbold** [comment]
Did you say you saw a google app id in the log?

**Comment by sashthecash** [comment]
yes, line 10. i replaced the actual app id with `1:CRYPTIC_NUMBERS:android:MORE_CRYPTIC_NUMBERS`. and also my bundle id with `air.my.bundle.id`

**Comment by marchbold** [comment]
Can you double check you have correctly specified the values in your custom resources ANE?

Simply unzip the CustomResources ANE file and ensure the values.xml file contains your firebase details.

**Comment by sashthecash** [comment]
i unzipped the ANE and the contents look like this:

![image](https://user-images.githubusercontent.com/278527/33363927-a32ecd24-d4e2-11e7-8561-0d384c1b76c0.png)

both values.xml files have the correct details.

maybe i should mention that i removed the `ga_trackingId` field, since it's optional and my google-services.json file doesn't have this field: `{YOUR_CLIENT}/services/analytics-service/analytics_property/tracking_id`

there's only
```
      "services": {
        "analytics_service": {
          "status": 1
        },
        "appinvite_service": {
          "status": 1,
          "other_platform_oauth_client": []
        },
        "ads_service": {
          "status": 2
        }
      }
```

**Comment by marchbold** [comment]
That's very odd that's its displaying a different id in the logs then. What ANEs are you including in your project?

**Comment by sashthecash** [comment]
what do you mean with different id? it's actually the correct one, i just replaced it in the logs myself to obscure my real details here.

I'm including these ANEs
```
		<extensionID>com.distriqt.Core</extensionID>
		<extensionID>com.distriqt.playservices.Base</extensionID>
		<extensionID>com.distriqt.androidsupport.V4</extensionID>
		<extensionID>com.distriqt.androidsupport.CustomTabs</extensionID>
		<extensionID>com.distriqt.androidsupport.CardViewV7</extensionID>
		<extensionID>com.distriqt.androidsupport.AppCompatV7</extensionID>
		<extensionID>com.distriqt.ApplicationRater</extensionID>
		<extensionID>com.distriqt.PushNotifications</extensionID>
		<extensionID>com.distriqt.Calendar</extensionID>
		<extensionID>com.distriqt.Dialog</extensionID>
		<extensionID>com.distriqt.Message</extensionID>
		<extensionID>com.distriqt.Application</extensionID>
		<extensionID>com.distriqt.FacebookAPI</extensionID>
		<extensionID>com.distriqt.Share</extensionID>
		<extensionID>com.distriqt.ForceTouch</extensionID>
		<extensionID>com.distriqt.NativeWebView</extensionID>
		<extensionID>com.distriqt.Firebase</extensionID>
		<extensionID>com.distriqt.firebase.Crash</extensionID>
		<extensionID>my.bundle.id.CustomResources</extensionID>
```

**Comment by marchbold** [comment]
Sorry I'm confused, I thought you said *"One thing I noticed is that Firebase seemed to initialize with the wrong settings"* 

Can you explain exactly what you are seeing again, just so we are on the same page.

**Comment by sashthecash** [comment]
yes, it did so in the beginning, but after changing the bundle id in `build_config/extension.xml` it logged the correct id. I guess that I built the ANE once without including my details and IntelliJ cached it. and even after including everything and making the necessary changes it still loaded the 'wrong' ANE. only changing the bundle ID fixed this. A coworker also told me he had this problem before where he had to always manually bump up the ID like `my.bundle.id123`for Android every time he made a change to his ANE.

Is that maybe the problem? that I changed the bundle ID in the extension.xml?

**Comment by marchbold** [comment]
Right, we definitely don't have that problem with IntelliJ, have had some caching issues with AnimateCC though.

Besides, if it's logging the correct ids and you are getting a success when calling initialiseApp then you shouldn't have a problem there. 

Can you confirm the ids are infact the correct ids from your firebase application? Also have you correctly set the signature etc in your application configuration, using the same certificate to sign your application?

**Comment by sashthecash** [comment]
I created a sample project (same bundle ID) with Android Studio and added Firebase using the Firebase Assistant. It worked, Events are appearing in the StreamView. I copied the values.xml generated by Android Studio into my CustomResources ANE and rebuilt it, no luck, still no Events.
I noticed that Android Studio added a fingerprint to my App's settings in Firebase Console so I thought this was the missing puzzle piece, but after removing the fingerprint Events still worked, so it didn't have anything to do with it ... I'm completely lost at this point.

**Comment by marchbold** [comment]
Hi, This may be due to the version of the Firebase library on Android. We are currently stuck at 11.0.4 until Adobe fix this issue: https://tracker.adobe.com/#/view/AIR-4198465

Firebase is up to 11.6.2 on Android, so we are a few releases behind now.

Please vote for the issue and hopefully we can get Adobe to resolve it soon.

**Comment by sashthecash** [comment]
voted. i just downloaded the AIR 28 SDK Beta and it works!

**Comment by marchbold** [comment]
What exactly is working with the beta? Do you mean the v26 android support tools? That's exciting if they've updated the sdk finally.

**Comment by sashthecash** [comment]
Looks like it, because we're finally getting Firebase Analytics Events in the Firebase Console

**Comment by marchbold** [comment]
Great news, so you've just updated to the AIR 28 beta and they started working for you?

**Comment by sashthecash** [comment]
yes, exactly.

**Comment by marchbold** [comment]
Are you using v26.1.0 of the Android Support libs or still v25.3.1?

**Comment by sashthecash** [comment]
using v25.3.1, v26.1.0 still produces this error message:
```
aapt tool failed:/private/var/folders/dz/9g4326m912502z4wzj2rk0vh0000gp/T/1f3dbb2c-9353-4ffa-a2ca-87f71ba62228/appcompat-v7-26.1.0-res/values-v26/values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
```

**Comment by marchbold** [comment]
Yeah I reconfirmed myself today. Adobe really needs to update the build tools for us. Holding back Android ANEs atm.
