### ISSUE TITLE
Firebase events issue

### ISSUE THREAD

**Issue by alamboley** [distriqt/ANE-Firebase#121]
Hello,

I've several issues concerning events:
- on iOS when I report screens, their name isn't displayed by Firebase.
- on iOS firing events aren't visible in Firebase, or I could not find them.
- on Android there is a black hole, nothing is received in Firebase. Same issue than #118?

**Comment by marchbold** [comment]
Firebase events are batch uploaded together every hour or so to prevent battery drain. You can attempt to force an upload by backgrounding your application, this sometimes triggers the upload.

Once uploaded they can take several hours to appear in the console. What we have found the most effective is to look at the stream view and identify a user to get to the following screen:

![screen shot 2017-12-02 at 09 54 27](https://user-images.githubusercontent.com/442356/33508631-45a41d14-d747-11e7-960d-e5d2622438ce.png)

On this screen you'll see a `custom_event_name` that we are firing in our application:

```as3
var event:EventObject = new EventObject();
event.name = "custom_event_name";
Firebase.service.analytics.logEvent( event );
```

And I've expanded the `firebase_screen` parameter where you can see our random custom screen names (`screen_test_4` and `screen_test_3`):

```as3
var screenName:String = "screen_test_"+String(Math.floor(Math.random()*10));
Firebase.service.analytics.setCurrentScreen( screenName );
```

You also should see `screen_view` events here:

![screen shot 2017-12-02 at 10 04 38](https://user-images.githubusercontent.com/442356/33508766-477bd2e8-d748-11e7-9c65-f90c41809430.png)

If you aren't seeing these sorts of events, make sure you are using the latest ANE and have correctly configured it.

**Comment by Lydecker** [comment]
I was about to request this feature - I don't see it in the documentation!
Firebase.service.analytics.setCurrentScreen()

**Comment by marchbold** [comment]
Yeah we haven't documented every feature in firebase analytics as they are often documented in the official Firebase docs. You can check the ASdocs for complete implementation:

https://distriqt.github.io/ANE-Firebase/asdocs/com/distriqt/extension/firebase/analytics/FirebaseAnalytics.html
