### ISSUE TITLE
Conflict with Firebase Invites on iOS

### ISSUE THREAD

**Issue by dannycortesv** [distriqt/ANE-Firebase#123]
I'm getting this error when try to compile:

Conflict in file name : GINInviteResources.bundle/af.lproj/GooglePlus.strings

Any idea about what's happening?

Thanks

- AIR SDK version:  27
- Device OS: iOS
- Device version: iPhone 6
- Development IDE: Flash Builder
- Development OS: MacOS

**Comment by marchbold** [comment]
What other ANEs are you using in your project?

**Comment by dannycortesv** [comment]
I'm using these ones too:

        <extensionID>com.distriqt.Application</extensionID>
        <extensionID>com.distriqt.Bolts</extensionID>
        <extensionID>com.distriqt.Core</extensionID>
        <extensionID>com.distriqt.Firebase</extensionID>
        <extensionID>com.distriqt.firebase.Auth</extensionID>
        <extensionID>com.distriqt.firebase.Crash</extensionID>
        <extensionID>com.distriqt.firebase.Database</extensionID>
        <extensionID>com.distriqt.firebase.DynamicLinks</extensionID>
        <extensionID>com.distriqt.firebase.Performance</extensionID>
        <extensionID>com.distriqt.firebase.RemoteConfig</extensionID>
        <extensionID>com.distriqt.firebase.Storage</extensionID>
        <extensionID>com.distriqt.Image</extensionID>
        <extensionID>com.distriqt.CustomResources</extensionID>
        <extensionID>com.distriqt.PushNotifications</extensionID>
	<extensionID>com.distriqt.FacebookAPI</extensionID>
	<extensionID>com.distriqt.CameraUI</extensionID>
	<extensionID>com.distriqt.MediaPlayer</extensionID>
	<extensionID>com.distriqt.playservices.Auth</extensionID>
        <extensionID>com.distriqt.playservices.Base</extensionID>
        <extensionID>com.distriqt.playservices.Identity</extensionID>
        <extensionID>com.distriqt.playservices.AppInvite</extensionID>
    	<extensionID>com.distriqt.GoogleIdentity</extensionID>

**Comment by marchbold** [comment]
In order to get Google Identity to work with Firebase you'll need to use the firebase compatible version. 

https://github.com/distriqt/ANE-GoogleIdentity/tree/master/lib

Are you using the `Firebase/com.distriqt.GoogleIdentity.Firebase.ane` in your app?

**Comment by dannycortesv** [comment]
Yes i'm using it, actually GoogleIdentity is working well (while using other Firebase extensions) but if i add Invites ANE the error comes out.

**Comment by marchbold** [comment]
Do you have the latest version of all the ANEs? 

Mainly referring to Firebase / Google Play Services and Google Identity here.

**Comment by dannycortesv** [comment]
Yes i just rechecked and i'm using the latest ones.

**Comment by marchbold** [comment]
Ah, you've got the DynamicLinks ANE in there as well. 

You can only use DynamicLinks or Invites. They aren't compatible due to the implementation of Invites. 

However all the dynamiclinks functionality is replicated in Invites:

https://github.com/distriqt/ANE-Firebase/wiki/Invites---Dynamic-Links

**Comment by marchbold** [comment]
Did that solve your issue?

**Comment by dannycortesv** [comment]
Yes i did, thanks @marchbold  for the help :)
