### ISSUE TITLE
Don't have values.xml in APK

### ISSUE THREAD

**Issue by sol-digital** [distriqt/ANE-Firebase#124]
Using the first method of configuration ANE with values.xml for Android. There is com.distriqt.CustomResources.ane\META-INF\ANE\Android-ARM\distriqt-extension-customresources-res\values\values.xml in ANE file. 
![ane](https://user-images.githubusercontent.com/22980447/33719056-9d6ca994-db70-11e7-8339-94121f349e63.PNG)

But when APK packaged (AIR 27), had no values.xml there. Other files from ANE is in right place. It's ok? Perhaps this is why I don't see any activity and event in Firebase Console?
![apk](https://user-images.githubusercontent.com/22980447/33719060-a2655b08-db70-11e7-845d-049ea5041e62.PNG)

**Comment by marchbold** [comment]
The values xml will be contained with in the custom resources extension.

```
assets/META-INF/AIR/extensions/com.distriqt.CustomResources/META-INF/ANE/Android-ARM/customresources/values/values.xml
```

**Comment by sol-digital** [comment]
thanks
