### ISSUE TITLE
Many crashes in Android (java.lang.SecurityException) only in Sony Xperia devices

### ISSUE THREAD

**Issue by sol-digital** [distriqt/ANE-Firebase#125]
We have many new crashes in Android after adding Firebase ANE to out app.
![crashes](https://user-images.githubusercontent.com/22980447/33809059-b12ae1b0-de01-11e7-8ccf-005dc3aafd98.PNG)

Looks like crashes has been only in Sony Xperia devices. This is data from the Google Play Console.
![list](https://user-images.githubusercontent.com/22980447/33809163-8a9df38c-de03-11e7-8176-6695dcf00cda.PNG)

In all incidents the same listing
`java.lang.SecurityException: `
`  at android.os.Parcel.readException (Parcel.java:1683)`
`  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:188)`
`  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:140)`
`  at android.content.ContentProviderProxy.insert (ContentProviderNative.java:476)`
`  at android.content.ContentResolver.insert (ContentResolver.java:1325)`
`  at android.content.AsyncQueryHandler$WorkerHandler.handleMessage (AsyncQueryHandler.java:96)`
`  at android.os.Handler.dispatchMessage (Handler.java:110)`
`  at android.os.Looper.loop (Looper.java:203)`
`  at android.os.HandlerThread.run (HandlerThread.java:61)`

Don’t use events or something else only init ANE for collecting default analytics data.

Can you do something to avoid this error? Thank.

**Comment by marchbold** [comment]
Hi, That error doesn't look related to the ANE code so not sure what's causing this issue for you. Any chance you've implemented FCM as well or is this just a result of adding the core `com.distriqt.Firebase.ane`? 

Unfortunately at the moment we are a few versions behind the main Firebase version on Android due to an issue in the AIR SDK (https://tracker.adobe.com/#/view/AIR-4198465) that we are waiting to be fixed. We believe there are a few bugs that are due to this, and this may be one of those.

**Comment by sol-digital** [comment]
Yes, this just a result of adding the core com.distriqt.Firebase.ane and 
`Firebase.init(Config.DISTRIQT_APP_ID);`
`if ( Firebase.isSupported ) {`
`    Firebase.service.initialiseApp();`
`}`

uses ANE
`<extensionID>com.distriqt.CustomResources</extensionID>`
`<extensionID>com.distriqt.Adverts</extensionID>`
`<extensionID>com.distriqt.androidsupport.V4</extensionID>`
`<extensionID>com.distriqt.Core</extensionID>`
`<extensionID>com.distriqt.Firebase</extensionID>`
`<extensionID>com.distriqt.InAppBilling</extensionID>`
`<extensionID>com.distriqt.Notifications</extensionID>`
`<extensionID>com.distriqt.playservices.Ads</extensionID>`
`<extensionID>com.distriqt.playservices.Base</extensionID>`
`<extensionID>com.distriqt.Share</extensionID>`

**Comment by marchbold** [comment]
Have you updated the Notifications ANE recently? Did you add in the new permissions for badges?

https://github.com/distriqt/ANE-Notifications/wiki/u.Set-Badge-Number

**Comment by sol-digital** [comment]
Hm... Yes, we update all other extensions to lates versions (about 2017.11) with adding Firebase ANE.

Before that we uses v4.3.028 of Notifications ANE but don't uses setBadgeNumber or something with badges. 

Ok, add that uses-permission tags to Android manifest and check this build.

**Comment by marchbold** [comment]
Yeah if you have updated the Notifications ANE recently that would explain it. 

We are looking into that exception with the notifications ane when the permissions are missing from the manifest but in the meantime adding them in should resolve the issue.

Let me know how it goes.

**Comment by sol-digital** [comment]
We added all that permissions to Android manifest in new build
https://distriqt.github.io/ANE-Notifications/u.Set%20Badge%20Number

Look like no more that java.lang.SecurityException . Waiting Google Play day report.

**Comment by marchbold** [comment]
Excellent, sounds hopeful.

**Comment by sol-digital** [comment]
Thanks. All is fine. No more java.lang.SecurityException in new build deployed 2017.12.11.

![crashes](https://user-images.githubusercontent.com/22980447/33932385-e6a3ee1e-e003-11e7-9a45-3af22f5532d0.PNG)

Previos build crashes
![crashes_last](https://user-images.githubusercontent.com/22980447/33932434-fa71e658-e003-11e7-87fa-c388311917fd.PNG)

New build crashes
![crashes_now](https://user-images.githubusercontent.com/22980447/33932442-009812e6-e004-11e7-8de2-2db5316cfb4a.PNG)

**Comment by cgascons** [comment]
@marchbold Any news on this exception? We are also having this issue on our recently updated App. We will use the workaround here explained in the meantime but we'd like to know when will it be ready. Thanks!
