### ISSUE TITLE
Facebook Auth Documentation

### ISSUE THREAD

**Issue by dse102** [distriqt/ANE-Firebase#126]
When will you add Facebook Auth documentation and examples?  Thanks

**Comment by marchbold** [comment]
Thanks for reminding us about this, we have them in progress and will release soon.

**Comment by marchbold** [comment]
Facebook Auth documentation has been completed:

https://github.com/distriqt/ANE-Firebase/wiki/Auth---Provider---Facebook

Let me know if you have any questions.
