### ISSUE TITLE
Adding Dynamic Links ANE causes build error

### ISSUE THREAD

**Issue by wussow-everi** [distriqt/ANE-Firebase#128]
##### Expected behaviour
Following the Dynamic Links Wiki to add it to our project.

To fix this problem we are using the 1.8 release of ANE-Firebase.

##### Actual behaviour
Cannot Build the client.

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_GIDSignIn", referenced from:
      objc-class-ref in FirebaseInvites(GINInvite+FIRApp_76d1761fc69568174eec9dc1c0550661.o)
ld: symbol(s) not found for architecture armv7
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GIDSignIn", referenced from:
      objc-class-ref in FirebaseInvites(GINInvite+FIRApp_94d38cb4cc52f9151461dab9575257da.o)
ld: symbol(s) not found for architecture arm64
Compilation failed while executing : ld64

##### Environment 
- AIR SDK version: 27
- Device OS: iOS 11
- Device version: iPhone 7 Plus
- Development IDE: IntelliJ IDEA
- Development OS: Windows

**Comment by marchbold** [comment]
Are you using Firebase Invites as well? These ANEs can not be used together. Instead use the dynamic links functionality built into the invites ANE

https://github.com/distriqt/ANE-Firebase/wiki/Invites---Dynamic-Links

**Comment by wussow-everi** [comment]
I've tried it with the 2 scenarios:
1. Just the Dynamic Links ANE - Same error as above
1. Just the Invites ANE - Same error as above

**Comment by marchbold** [comment]
Are you sure you have completely removed them from your project? ie removed from your ext dir and from your app xml and cleared any caches.

What other ANEs are you using?

**Comment by wussow-everi** [comment]
Yes, I am sure I've cleaned the build directories. I'm just using Core and Dynamic Links currently. Like I said though, I've gone back to 1.8 and everything is working.

**Comment by marchbold** [comment]
IntelliJ has an issue that if an selected ANE is in a directory with multiple ANEs it packages all the ANEs in that directory.

Try removing either the DynamicLinks or the Invites ANE from the directory or moving the ANEs you are using into a separate directory.

**Comment by wussow-everi** [comment]
You are right I think I had both in the directory when I was building before. I was able to build with the new version of Firebase.

**Comment by marchbold** [comment]
Excellent! Glad we found the issue.
