### ISSUE TITLE
Topics

### ISSUE THREAD

**Issue by fix89** [distriqt/ANE-Firebase#130]
Is it possible to subscribe to topics?

**Comment by marchbold** [comment]
Do you mean FCM topics? 

This is already implemented in the push notifications ANE which handles the FCM component.

See the following documentation in the Push Notifications ANE:

https://github.com/distriqt/ANE-PushNotifications/wiki/u.Topics

(Or http://distriqt.github.io/ANE-PushNotifications/u.Topics)
