### ISSUE TITLE
Firebase[Invitation]

### ISSUE THREAD

**Issue by railnation** [distriqt/ANE-Firebase#131]
Hi, 

I have a question about Firebase Invitation. Is it possible to use the 'normal' share dialog shown if you share something in an application? There are many options like Whats App ect. 

Best 

Christian

**Comment by railnation** [comment]
![screenshot_20180215-104140](https://user-images.githubusercontent.com/11500099/36250363-dad9b994-123d-11e8-965c-6e69383dc857.png)

**Comment by railnation** [comment]
Like on the screenshot. Just an example to share a simple image

**Comment by marchbold** [comment]
Looks like you are looking for the functionality in the Share ANE

https://airnativeextensions.com/extension/com.distriqt.Share

**Comment by railnation** [comment]
Ah okay sorry. Would this work with the DynamicLink functionality?

**Comment by marchbold** [comment]
So Dynamic Links are url links that link to your application, there's no UI elements in that section. 

Invites are special dynamic links and a ui that allows you to send them to your contacts:

> When a user taps one of your app's Share buttons and chooses the Firebase Invites channel—usually named "Email and SMS"—the Firebase Invites sharing screen opens. From the sharing screen, the user selects recipients from their Google contacts and contacts stored locally on the device, optionally customizes the invitation message and sends the invitations. Invitations are sent by email or SMS, depending on the available contact information, and contain a Dynamic Link to your app.

If you wish to use the normal share methods, you can generate your own dynamic link and then use the Share ANE to share the link to other apps etc.

**Comment by railnation** [comment]
Okay thank you for your clarification. 

I have a simple question. How could I change the language for the Firebase invite email? Is this possible?

**Comment by marchbold** [comment]
Hi,

You directly control the content of the invite so you can alter it to suit the user's language as you require:

https://github.com/distriqt/ANE-Firebase/wiki/Invites---Invitations

**Comment by railnation** [comment]
I could translate the title and the message. But how could I set the correct language for the store description in the email which will be send?

**Comment by marchbold** [comment]
Unfortunately I haven't seen any options controlling that aspect of the invite so I'm not sure it's possible. 

May have to request a feature from the Firebase team.
