### ISSUE TITLE
Read data from Database

### ISSUE THREAD

**Issue by fix89** [distriqt/ANE-Firebase#132]
How can I simply read a value on Database?
Thanks

**Comment by marchbold** [comment]
Hi,

Probably the `once` function is what you are looking for. See the reference on "Read Data Once"

https://github.com/distriqt/ANE-Firebase/wiki/Database---Read-Data-and-Change-Events#read-data-once

**Comment by marchbold** [comment]
i.e.

```as3
var ref:DatabaseReference = FirebaseDatabase.service.getReference( "test" );

ref.once( function( value:Object ):void 
{
	if (value != null)
	{
		trace( JSON.stringify( value ) );
	}
	else 
	{
		// There was an error
	}
});
```
