### ISSUE TITLE
Android: Create Resource ANE - Build Failed

### ISSUE THREAD

**Issue by Shaunmax** [distriqt/ANE-Firebase#133]
Hello,

I got build failed, please check the logs below

##### Expected behaviour
BUILD SUCCESSFUL

##### Actual behaviour
BUILD FAILED

##### Environment 

- AIR SDK version: 28
- Device OS: Mac OS X
- Device version: 
- Development IDE: Animate CC
- Development OS: Android

##### Logs

    [exec] :app:mergeDebugProguardFiles UP-TO-DATE
     [exec] :app:packageDebugRenderscript UP-TO-DATE
     [exec] :app:compileDebugRenderscript
     [exec] :app:generateDebugResValues
     [exec] :app:generateDebugResources
     [exec] :app:packageDebugResources
     [exec] /TechFolder/ANE-CustomResources-master/platform/android/app/src/main/res/values/values.xml:4:7: Error: The content of elements must consist of well-formed character data or markup.
     [exec] :app:packageDebugResources FAILED
     [exec] 
     [exec] BUILD FAILED
     [exec] 
     [exec] Total time: 8.087 secs
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':app:packageDebugResources'.
     [exec] > /TechFolder/ANE-CustomResources-master/platform/android/app/src/main/res/values/values.xml:4:7: Error: The content of elements must consist of well-formed character data or markup.
     [exec] 
     [exec] * Try:
     [exec] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
     [exec] Result: 1

build_android_windows:

package:

package_android:

BUILD FAILED
/TechFolder/ANE-CustomResources-master/build.xml:228: The following error occurred while executing this line:
/TechFolder/ANE-CustomResources-master/build.xml:178: Warning: Could not find file /TechFolder/ANE-CustomResources-master/platform/android/app/build/intermediates/bundles/release/classes.jar to copy.

Total time: 24 seconds

**Comment by marchbold** [comment]
Hi,

The error message indicates something is amiss in the `values.xml` file you are using. Can you double check the values file is correct and post here if you can't identify the issue.

Cheers

**Comment by Shaunmax** [comment]
Okay I just removed the comments and it worked not sure what was the problem with comments!
