### ISSUE TITLE
Send Firebase Invites on iOS logging in with Facebook token only?

### ISSUE THREAD

**Issue by PippoApps** [distriqt/ANE-Firebase#135]
Is it possible to use Firebas eInvites to send invitations, loggin in as a Google Identity using Facebook as an identity provider only? Or is it necessary to login with a Google account?
cheers

**Comment by marchbold** [comment]
Hi, 

As far as I'm aware you have to log in with a Google Identity on iOS for this to work. I haven't seen any documentation about using an alternative authentication method sorry.

If you do find any references to the contrary though please let me know!
