### ISSUE TITLE
Android: App crashes on startup on older devices

### ISSUE THREAD

**Issue by sashthecash** [distriqt/ANE-Firebase#136]
Hi,

we are using the Firebase ANE for Analytics. Everything seemed to work but now we have a report that the App just stays black after starting on older devices, I reproduced it on a Nexus 4 with Android 4.3.

A debug session revealed this Error log right after App start:

```
[Fault] exception, information=Error: The native extension context could not be created
```

I was able to narrow the issue down and found that it has something to do with the CustomResources ANE. Removing it from the descriptor gets rid of the Error. 

I followed the instructions for the CustomResources ANE really carefully and made all the right adjustments. It does work on newer devices flawlessly but crashes on older ones.

Do you have any idea what the problem might be?

Thanks in advance!

##### Environment 

- AIR SDK version: 28
- Device OS: Android
- Device version: 4.3
- Development IDE: IntelliJ IDEA
- Development OS: macOS

**Comment by marchbold** [comment]
Hi,

Can you post the logs from the device? 

The most common issue with older 4.x devices is the multidex issue introduced by AIR. For 4.x devices you need to make sure you have an additional tag in the manifest additions:

```xml
<manifest android:installLocation="auto">
	<!-- PERMISSIONS -->

	<application android:name="android.support.multidex.MultiDexApplication">

		<!-- ACTIVITIES / RECEIVERS / SERVICES -->

	</application>
</manifest>
```

More information here:

https://github.com/distriqt/ANE-Firebase/wiki/Core---Add-the-extensions#multidex-applications

**Comment by sashthecash** [comment]
awesome, this fixed it!
Thank you very much for the help!

**Comment by marchbold** [comment]
Excellent! Glad it was a simple fix

Cheers
