### ISSUE TITLE
cannot display imageurl

### ISSUE THREAD

**Issue by jayeshbabuav** [distriqt/ANE-Firebase#138]
I added a imageUrl to the dynamic link. But when I share the link to Whatsapp or Facebook, it doesn't show the image.

**Comment by marchbold** [comment]
Hi,
Can you explain a little more what you have done so far and what you are experiencing? Include the platform and version you are having issues with.

Also confirm that you are using a valid image:
> The image should be at least 300x200 px, and less than 300 KB.

**Comment by jayeshbabuav** [comment]
i use the following code to add url:

```
new DynamicLink.SocialMetaTagParameters.Builder()
.setTitle("JobE")
.setDescription("Whatever")
.setImageUrl(Uri.parse("http://s347.photobucket.com/user/jayeshbabuav/media/jobe_icon_small_zpsi8eu38ss.png.html][IMG]http://i347.photobucket.com/albums/p456/jayeshbabuav/jobe_icon_small_zpsi8eu38ss.png[/IMG]"))
                                .build())
```

I created this url link "http://s347.photobucket.com/user/jayeshbabuav/media/jobe_icon_small_zpsi8eu38ss.png.html][IMG]http://i347.photobucket.com/albums/p456/jayeshbabuav/jobe_icon_small_zpsi8eu38ss.png[/IMG]" from photobucket.com

Image is 300x200 pixels and size is around 70kb

**Comment by marchbold** [comment]
What does your image url resolve to, as those urls don't seem to load an image directly?

```as3
Uri.parse("http://s347.photobucket.com/user/jayeshbabuav/media/jobe_icon_small_zpsi8eu38ss.png.html][IMG]http://i347.photobucket.com/albums/p456/jayeshbabuav/jobe_icon_small_zpsi8eu38ss.png[/IMG]")
``` 

Perhaps try with a direct link to an image file, and see if that works first?

**Comment by jayeshbabuav** [comment]
k.. let me try

**Comment by jayeshbabuav** [comment]
I used direct link and it worked.
