### ISSUE TITLE
Invalid class name length

### ISSUE THREAD

**Issue by Shaunmax** [distriqt/ANE-Firebase#139]
I am getting this error and dont see the event in debug view 👎 
(17218): Invalid class name length in setCurrentScreen. Length: 0

##### Expected behaviour

No error in the event
##### Environment 

- AIR SDK version: 
- Device OS: 
- Device version: 
- Development IDE: 
- Development OS:

##### Logs

Device logs if relevant

**Comment by marchbold** [comment]
Can you post the code you are using that's causing this issue?

**Comment by Shaunmax** [comment]
if (Firebase.isSupported) {
				var success: Boolean = Firebase.service.analytics.setCurrentScreen(current_state.getName());
				trace("posted = " + success);
			}

where current_state.getName() returns a string

**Comment by marchbold** [comment]
Have you tried setting the class name as well?

```as3
Firebase.service.analytics.setCurrentScreen( screenName, screenClassName );
```

**Comment by Shaunmax** [comment]
Hi,

Its working now with the screenClassName.

Is there a place where all these things are documented? I was using your example file and there was not screenClassName.

Not sure if its your sdk issue, but there is no code hinting after Firebase.service.analytics.
So its difficult for me to figure out how many parameters are required!

Let me know your thoughts!

**Comment by marchbold** [comment]
That's unusual, `Firebase.service.analytics` should be defined by an interface so unless your IDE has issues handling interfaces? 

I'll look into the example, I believe it used to be possible to send without a class name but that it's become a requirement so some of our examples may still be missing this.

**Comment by marchbold** [comment]
FYI if auto complete isn't working all the docs are here:

https://distriqt.github.io/ANE-Firebase/asdocs/

**Comment by Shaunmax** [comment]
I am using Adobe Animate CC.

I tried the same thing with SELECT_CONTENT the result was same no events in
debug view!

**Comment by marchbold** [comment]
What is SELECT_CONTENT?

**Comment by marchbold** [comment]
(Animate CC definitely isn't the best IDE for autodetection, does have a few issues with various things. If possible we highly recommend moving to an IDE if you are getting serious about app development. Animate is a great tool for developing graphical assets and animations but there are much better tools for coding.)

**Comment by Shaunmax** [comment]
https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event.html#SELECT_CONTENT

Till now, I am very comfortable with CC, no issues~

**Comment by marchbold** [comment]
Apologies, I wasn't clear, can you show us how you are using SELECT_CONTENT, are you passing it to `setCurrentScreen`? 

Can you show the sequence of options you are passing to your analytics before the failing event?
