### ISSUE TITLE
Best Option for Android Config Without Compiling Resource ANE

### ISSUE THREAD

**Issue by vinodlobo** [distriqt/ANE-Firebase#143]
We want to start using the Firebase ANE for Analytics both iOS and Android.
We have not created ANEs or used the Android SDK before.

What are the best alternatives for us to configure for Android?
Sounds like manual config is not fully operational.
Thanks,
-- Vinod

**Comment by marchbold** [comment]
Easy method is to grab the json from Firebase and create the values.xml from the documentation with your values, then send the file to us and we'll create the custom resources ANE for you.

**Comment by vinodlobo** [comment]
Got it, will send you the file when ready, thanks!
