### ISSUE TITLE
Remote Config:: firebaseconfig:fetch:error

### ISSUE THREAD

**Issue by railnation** [distriqt/ANE-Firebase#144]
##### Expected behaviour

FirebaseRemoteConfigEvent.FETCH_COMPLETE

##### Actual behaviour

FirebaseRemoteConfigEvent.FETCH_ERROR

##### Environment 

- AIR SDK version: 28.0.0.125
- Device OS: Android 6
- Device version: 
- Development IDE: FDT 64 Bit 
- Development OS: Windows

Created two properties today. Using dev mode

**Comment by marchbold** [comment]
Can you update to AIR 29.

it contains some important updates for Android that may affect your application with the latest version of this ane

**Comment by railnation** [comment]
Hi Marchbold, 

Thanks. The updated Adobe Air 29 fixed that issue. Would you recommend to update all native extensions?

I just use 1.8.017

**Comment by marchbold** [comment]
Yes definitely, there have been a lot of updates for Android in the past weeks since AIR 29 as it's allowed us to use the latest build tools and compatibility libraries.

**Comment by railnation** [comment]
Thank you for your help. :)
