### ISSUE TITLE
Firebase Auth cause application to crach

### ISSUE THREAD

**Issue by MuhammadMuradKhan** [distriqt/ANE-Firebase#146]
Hi i am trying to setup firebase for Animate CC (Flash application), i have succefully done following

1. API key from airnativeextensions for the application
2. Initialized firebase.init(API KEY)
3. connected with firebase.option to firebase.

however 

when i add auth.ane file to my project and compile, i can debugs succesfully but on the android device, application crashes every time. i have tested on Samsung note 5 and Samsung J7 Max

link to my source files is as follows.

https://drive.google.com/file/d/1hmvP4c33fd6BWTNE8C-8MJWswbPh9kp6/view?usp=sharing

please help me resolve this issue, i am stuck since 1 week

thank you.

##### Environment 

- AIR SDK version: 29.00
- Device OS: Android
- Device version: 7
- Development IDE: 
- Development OS:

##### Logs

Device logs if relevant

**Comment by marchbold** [comment]
Hi,

Is it possible for you to post the device logs? This often indicates the cause of a crash on Android and will greatly help us point you in the right direction:

https://airnativeextensions.github.io/tutorials/device-logs

**Comment by MuhammadMuradKhan** [comment]
04-24 17:22:29.038 25355 25408 E AndroidRuntime: Process: air.murad.disq1, PID: 25355
04-24 17:22:29.038 25355 25408 E AndroidRuntime: java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
04-24 17:22:29.038 25355 25408 E AndroidRuntime:        at com.google.android.gms.common.zzp.isGooglePlayServicesAvailable(Unknown Source)
04-24 17:22:29.038 25355 25408 E AndroidRuntime:        at com.google.android.gms.common.zzf.isGooglePlayServicesAvailable(Unknown Source)
04-24 17:22:29.038 25355 25408 E AndroidRuntime:        at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source)
04-24 17:22:29.038 25355 25408 E AndroidRuntime:        at com.google.android.gms.common.api.internal.zzbo.connect(Unknown Source)
04-24 17:22:29.038 25355 25408 E AndroidRuntime:        at com.google.android.gms.common.api.internal.zzbm.zzb(Unknown Source)
04-24 17:22:29.038 25355 25408 E AndroidRuntime:        at com.google.android.gms.common.api.internal.zzbm.handleMessage(Unknown Source)
04-24 17:22:29.038 25355 25408 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:98)
04-24 17:22:29.038 25355 25408 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
04-24 17:22:29.038 25355 25408 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61)
04-24 17:22:29.088 25355 25418 E FA      : Failed to load metadata: Metadata bundle is null
04-24 17:22:29.089 25355 25418 E FA      : Failed to load metadata: Metadata bundle is null
04-24 17:22:29.100 25355 25418 E FA      : Failed to load metadata: Metadata bundle is null
04-24 17:22:29.101 25355 25418 E FA      : Failed to load metadata: Metadata bundle is null
04-24 17:22:29.102 25355 25418 E FA      : AppMeasurementReceiver not registered/enabled
04-24 17:22:29.103 25355 25418 E FA      : AppMeasurementService not registered/enabled
04-24 17:22:29.103 25355 25418 E FA      : Uploading is not possible. App measurement disabled
04-24 17:22:29.178 25355 25418 E FA      : Task exception on worker thread: java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />: com.google.android.gms.internal.zzckg.zzyc(Unknown Source)
04-24 17:22:29.405 25355 25355 E ViewRootImpl: sendUserActionEvent() mView == null
04-24 17:22:29.687 25355 25414 E CrashCollectionEnabled: No crash enable meta data found Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String, boolean)' on a null object reference
04-24 17:22:31.829  4920  4981 E ContactsProvider_EventLog: Flush buffer to file cnt : 1 size : 3Kb duration : 3ms lastUpdatedAfter : 4946 ms mFlush_time_threasold : 2000 mCurrentSize : 1909
04-24 17:22:34.452  4214  4214 E SignalClusterView: setSlotFocusVisible : subId 1
04-24 17:22:34.452  4214  4214 E SignalClusterView: setSlotFocusVisible : subId 1

**Comment by MuhammadMuradKhan** [comment]
application only crash when i include Auth.ane file , sorage, database etc work fine

**Comment by marchbold** [comment]
2 things could be the issue here:

1. Check that you have the following line once only in your manifest: 
`<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />` 

2. Ensure that you have the latest version of all the Firebase and Google Play Services ANEs. Having conflicting / different versions of these ANEs will cause your application to fail.
