### ISSUE TITLE
Android app crashes when adding CustomResources ANE

### ISSUE THREAD

**Issue by mrfrasier** [distriqt/ANE-Firebase#148]
Android app compiles and runs fine with Firebase and related ANEs in place. Once the customresources ANE is added to the project however, the app crashes on launch with the error outlined below. I've checked that that package name matches (saw that as a potential issue in another thread)

##### Environment 

- AIR SDK version: 28
- Device OS: Android
- Development OS: Windows
- Development IDE: Adobe Animate CC

##### Logs

> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: FATAL EXCEPTION: main: com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: Process: com.mysite.mobile, PID: 29739: com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: java.lang.NoSuchMethodError: No static method isDeviceProtectedStorage(Landroid/content/Context;)Z in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/app/com.mysite.mobile-1/base.apk): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.zza(Unknown Source): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1730): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1705): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:5146): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4741): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4681): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:162): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1409): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5422): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914): com.mysite.mobile
> 05-11 13:01:32.485 29739 29739 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707): com.mysite.mobile
> 05-11 13:01:32.485   844  1693 E SurfaceComposerClient: ScreenshotClient::update requested width/height, miniactivity height : (384)(384)(0): system_server
>

**Comment by marchbold** [comment]
You actually shouldn't change the package name of the custom resources ANE, that doesn't work any more. You should find all the requirements in the documentation of the Custom Resources ANE 

https://github.com/distriqt/ANE-CustomResources

Perhaps send us your resources and we'll create a version of it for you to try. (airnativeextensions@distriqt.com)

**Comment by mrfrasier** [comment]
mail sent with resources. Thanks!

**Comment by marchbold** [comment]
Thanks, will get you the ANE today.

**Comment by mrfrasier** [comment]
Sadly, the error is the same even with the ANE provided. Any ETA on the other methods for providing the necessary info? I saw in the documentation that they were not yet ready.

**Comment by marchbold** [comment]
Can you make sure you are using the latest versions of all the Google Play Services, Android support and Firebase ANEs?

**Comment by mrfrasier** [comment]
Indeed. I wiped the directory and redownloaded them early on in testing. Adding the google json to the app, I see from the output that the ANE recognizes the values passed (as they are traced out), however I also repeatedly get notices that Analytics are disabled because the google_app_id is not set (even though the ANE traced it out upon init).

Having this work would be a good solution to fighting with custom resources and such.

**Comment by marchbold** [comment]
Unfortunately the way Firebase initialises means that you can't get all of the functionality to work from a "delayed" initialisation through code. (This is not even possible in a native app). 

It seems you can get most things working (which we have planned an update for in the next release) but analytics never works correctly without the resource initialisation method.



I just realised you are using AIR 28? Can you please update to AIR 29. You'll need this for the latest Android functionality.

**Comment by mrfrasier** [comment]
Sadly, same issue with AIR 29. I guess we'll need to go through ANEs one by one and figure out what, if anything, may be causing a conflict.

**Comment by mrfrasier** [comment]
Our test device is running Android 5.1.1 -- I believe targetSDK is set to 22

**Comment by mrfrasier** [comment]
Unsure why this would be, but tracked it down to an ANE that handles media playback. It does include an icon for the app like the customresources does, so thinking that may be the source. Will try rebuilding customresources without those resources.

**Comment by marchbold** [comment]
Does the icon have the same resource (file) name? 

Could you try increasing the target sdk to 26 (or removing)?

**Comment by mrfrasier** [comment]
Yeah, I don't think it's the target SDK as that didn't make a difference. I'm going through the source for the mediaplayer ANE and I do see it includes "android-support-v4.jar" in its own libs (probably for handling the mediaplayer controls in the notification center).

At a glance, I'm guessing this is the source of the issue.

**Comment by mrfrasier** [comment]
Problem solved (for the most part). Rebuilt the mediaplayer ANE without android-support jar, and it runs fine, though it seems to crash when testing on older versions of Android. Is 4.3 too old to run this ANE? 

And if so, any workarounds so that it doesn't just crash?

05-21 15:35:55.442  6858  6858 I dalvikvm: Could not find method android.content.Context.createDeviceProtectedStorageContext, referenced from method android.support.v4.content.ContextCompat.createDeviceProtectedStorageContext

**Comment by marchbold** [comment]
Yes a conflicting Android support lib will definitely cause this issue! 

Is this our MediaPlayer ANE? It shouldn't have android support libs packaged with it unless you are using a very old version. I'm guessing its not ours though.

Is there any more to that error log? What version of the Android support libs are you using now?

**Comment by mrfrasier** [comment]
No, it was not your MediaPlayer ANE (we hadn't found that back when we needed it).

I was incorrect in thinking it was older Android devices. It seems it's samsung devices in general. They crash on load (Unfortunately your app has stopped) whenever this line is included in the manifest:

<provider android:authorities="com.mysite.mobile.firebaseinitprovider" android:name="com.google.firebase.provider.FirebaseInitProvider" android:exported="false" android:initOrder="100" />

Remove that, and it works across devices just fine.

**Comment by marchbold** [comment]
Yeah I don't think that will work for AIR applications. 

Are you sure your application package is `com.mysite.mobile` and not `air.com.mysite.mobile`? 

Can you post the complete error that you are seeing now?
