### ISSUE TITLE
Reading image from storage

### ISSUE THREAD

**Issue by tomergott** [distriqt/ANE-Firebase#149]
i am trying to load and show image from the firebase storage without downloading the file to my mobile is it possible or i have to download the file to my device?
Thanks

**Comment by marchbold** [comment]
Can you explain how you are going to achieve this? Not sure I understand how you can display content without downloading it. Do you just want to reference a url?

**Comment by tomergott** [comment]
Hi Michael, i got it working finally thank you,I wanted to ask you, can i connect the database with air for desktop or it will work only on mobile?Thanks!


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Michael <notifications@github.com> Date: 5/31/18  04:13  (GMT+02:00) To: distriqt/ANE-Firebase <ANE-Firebase@noreply.github.com> Cc: tomergott <gt@netvision.net.il>, Author <author@noreply.github.com> Subject: Re: [distriqt/ANE-Firebase] Reading image from storage (#149) 
Can you explain how you are going to achieve this? Not sure I understand how you can display content without downloading it. Do you just want to reference a url?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/distriqt/ANE-Firebase/issues/149#issuecomment-393370242","url":"https://github.com/distriqt/ANE-Firebase/issues/149#issuecomment-393370242","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/distriqt/ANE-Firebase","title":"distriqt/ANE-Firebase","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/distriqt/ANE-Firebase"}},"updates":{"snippets":[{"icon":"PERSON","message":"@marchbold in #149: Can you explain how you are going to achieve this? Not sure I understand how you can display content without downloading it. Do you just want to reference a url?"}],"action":{"name":"View Issue","url":"https://github.com/distriqt/ANE-Firebase/issues/149#issuecomment-393370242"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [distriqt/ANE-Firebase] Reading image from storage (#149)",
"sections": [
{
"text": "",
"activityTitle": "**Michael**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@marchbold",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"distriqt/ANE-Firebase\",\n\"issueId\": 149,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"distriqt/ANE-Firebase\",\n\"issueId\": 149\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/distriqt/ANE-Firebase/issues/149#issuecomment-393370242"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 340575961\n}"
}
],
"themeColor": "26292E"
}

**Comment by marchbold** [comment]
Hi Firebase is currently only a mobile / web solution and as far as I'm aware they don't have any plans to make it available on desktop.

We are looking into options for integration the web api version for desktop implementations but haven't gotten very far with that approach as yet.

**Comment by tomergott** [comment]
Amazing thank you very much


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Michael <notifications@github.com> Date: 6/1/18  04:31  (GMT+02:00) To: distriqt/ANE-Firebase <ANE-Firebase@noreply.github.com> Cc: tomergott <gt@netvision.net.il>, Author <author@noreply.github.com> Subject: Re: [distriqt/ANE-Firebase] Reading image from storage (#149) 
Hi Firebase is currently only a mobile / web solution and as far as I'm aware they don't have any plans to make it available on desktop.
We are looking into options for integration the web api version for desktop implementations but haven't gotten very far with that approach as yet.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/distriqt/ANE-Firebase/issues/149#issuecomment-393731865","url":"https://github.com/distriqt/ANE-Firebase/issues/149#issuecomment-393731865","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/distriqt/ANE-Firebase","title":"distriqt/ANE-Firebase","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/distriqt/ANE-Firebase"}},"updates":{"snippets":[{"icon":"PERSON","message":"@marchbold in #149: Hi Firebase is currently only a mobile / web solution and as far as I'm aware they don't have any plans to make it available on desktop.\r\n\r\nWe are looking into options for integration the web api version for desktop implementations but haven't gotten very far with that approach as yet."}],"action":{"name":"View Issue","url":"https://github.com/distriqt/ANE-Firebase/issues/149#issuecomment-393731865"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [distriqt/ANE-Firebase] Reading image from storage (#149)",
"sections": [
{
"text": "",
"activityTitle": "**Michael**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@marchbold",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"distriqt/ANE-Firebase\",\n\"issueId\": 149,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/distriqt/ANE-Firebase/issues/149#issuecomment-393731865"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 340575961\n}"
}
],
"themeColor": "26292E"
}

**Comment by tomergott** [comment]
I am saving an image into firebase storage and i want my app to show a specific image from firebase is it possible?
Thnx
