### ISSUE TITLE
Packaging failed / Android

### ISSUE THREAD

**Issue by railnation** [distriqt/ANE-Firebase#15]
Hello,

I like to test this ANE as Beta Tester. I receive the following error while packaging for Android.

```
dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzanc;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:737)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:511)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:281)
	at com.android.dx.command.dexer.Main.run(Main.java:247)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
1 error; aborting
```

Compiling with AIR 23.0.0.257

**Comment by marchbold** [comment]
Looks like a conflict with the Google Play Services client library. This occurs if multiple ANEs are including the client library. We have separated these into the `com.distriqt.playservices.*` ANEs, however make sure you aren't using the old `com.distriqt.GooglePlayServices.ane`.

Can you list the ANEs you are using? Make sure you only have the ones listed in our wiki.

**Comment by marchbold** [comment]
How did you go? Manage to resolve the conflict?

**Comment by railnation** [comment]
<extensionID>com.distriqt.playservices.Analytics</extensionID>
    <extensionID>com.distriqt.playservices.Auth</extensionID>
    <extensionID>com.distriqt.playservices.Base</extensionID>
    <extensionID>com.distriqt.playservices.Drive</extensionID>
    <extensionID>com.distriqt.playservices.Games</extensionID>
    <extensionID>com.distriqt.playservices.GCM</extensionID>
    <extensionID>com.distriqt.playservices.Identity</extensionID>
    <extensionID>com.distriqt.Core</extensionID>
    <extensionID>com.distriqt.AndroidSupport</extensionID>
    <extensionID>com.distriqt.Application</extensionID>
    <extensionID>com.distriqt.ApplicationRater</extensionID>
    <extensionID>com.distriqt.DeviceMotion</extensionID>
    <extensionID>com.distriqt.FacebookAPI</extensionID>
    <extensionID>com.distriqt.GoogleAnalytics</extensionID>
    <extensionID>com.distriqt.GameServices</extensionID>
    <extensionID>com.distriqt.GoogleIdentity</extensionID>
    <extensionID>com.distriqt.InAppBilling</extensionID>
    
    <extensionID>com.hasoffers.GAID</extensionID>
    <extensionID>com.freshplanet.KeyboardSize</extensionID>
    <extensionID>com.traviangames.ext.attributiontools</extensionID>
    <extensionID>com.brightfuture.railnation</extensionID>
    <extensionID>com.adjust.sdk</extensionID>
    <extensionID>com.wolfknock.androidexpansionfiles</extensionID>
    <extensionID>com.hasoffers.MobileAppTracker</extensionID>

**Comment by railnation** [comment]
I use these ANE`s removed the firebase ane to be sure that my build works

**Comment by marchbold** [comment]
Do you mean adding the `com.distriqt.Firebase.ane` causes the above error?

Can you make sure you have the latest playservices ANEs?

**Comment by railnation** [comment]
Yes it does cause the error

**Comment by marchbold** [comment]
Are you positive you are using the latest playservices v9.6.1?

**Comment by railnation** [comment]
I will test now with the latest playservices.

**Comment by marchbold** [comment]
Did you update all the playservices ANEs or just Base? Would you mind testing a project without all your other ANEs?

**Comment by marchbold** [comment]
Ah great! We'll have a new release soon but love to hear how you go with FCM.

**Comment by railnation** [comment]
Do you have a working example for Fireabase Analytics?

**Comment by marchbold** [comment]
Hi,

You should find the core example contains the basic usage of analytics:

https://github.com/distriqt/ANE-Firebase/tree/master/example/core

It was missing some files that I've just corrected.

**Comment by marchbold** [comment]
In particular this class:

https://github.com/distriqt/ANE-Firebase/blob/master/example/core/starling/src/com/distriqt/test/firebase/FirebaseCoreTests.as

**Comment by railnation** [comment]
Thank you. How can I get my distriqt application ane key working with firebase?

**Comment by marchbold** [comment]
I've added the Firebase ANE to your subscription so you can add it to your apps.

**Comment by railnation** [comment]
Thank you. I will try it today

**Comment by marchbold** [comment]
You need to regenerate the key. Just click regenerate beside the key you are using.

**Comment by railnation** [comment]
Thank, now it works 👍

**Comment by railnation** [comment]
How long does it took for firebase to show anything up? My test events are successfully sent but nothing shows comes up in the dashboard

**Comment by marchbold** [comment]
Hi,

Analytics events can take a while around 24 hours. 

Please note that there is currently a bug in the Firebase iOS SDK that means you wont get analytics on iOS. They are aware of the error and have promised us a fix soon.

**Comment by railnation** [comment]
Hi, 

Why is it so slow, GA is a way more faster :) Okay, thanks for your information. I am just trying only on Android.

**Comment by marchbold** [comment]
Agreed! They have been teasing at new analytics, but we haven't seen any details yet.

**Comment by railnation** [comment]
I dont see any data shown up in the firebase dashboard

**Comment by marchbold** [comment]
Double check your configuration, and if you've set any certificate signatures that they match the one you are using to test with.

You can have a look in the logs for any errors: `adb logcat` in a terminal.

**Comment by railnation** [comment]
I checked my config:

11-17 14:30:50.128: D/com.distriqt.Firebase(20420): FirebaseController::initialiseApp()
11-17 14:30:50.128: D/com.distriqt.Firebase(20420): FirebaseController::initialiseApp(): Using supplied options
11-17 14:30:50.128: D/com.distriqt.Firebase(20420): FirebaseController::initialiseApp(): apiKey = XXXX
11-17 14:30:50.128: D/com.distriqt.Firebase(20420): FirebaseController::initialiseApp(): googleAppID = XXXXXX
11-17 14:30:50.128: D/com.distriqt.Firebase(20420): FirebaseController::initialiseApp(): databaseURL = XXXX
11-17 14:30:50.128: D/com.distriqt.Firebase(20420): FirebaseController::initialiseApp(): gcmSenderID = 133134653187
11-17 14:30:50.128: D/com.distriqt.Firebase(20420): FirebaseController::initialiseApp(): storageBucket = XXXX
11-17 14:30:50.163: D/com.distriqt.Firebase(20420): FirebaseAnalyticsController::setUserID( XXXX)
11-17 14:35:16.148: D/com.distriqt.Firebase(20420): LogEventFunction::params[currency] (String) = 
11-17 14:35:16.148: D/com.distriqt.Firebase(20420): LogEventFunction::params[quantity] (int) = 
11-17 14:35:16.148: D/com.distriqt.Firebase(20420): LogEventFunction::params[cost] (int) = 
11-17 14:35:16.148: D/com.distriqt.Firebase(20420): FirebaseAnalyticsController::logEvent( [GOLD_TRAIN_MECHANIC], Bundle{
11-17 14:35:16.148: D/com.distriqt.Firebase(20420):  quantity => 1;
11-17 14:35:16.148: D/com.distriqt.Firebase(20420):  cost => 10;
11-17 14:35:16.148: D/com.distriqt.Firebase(20420):  currency => GOLD;
11-17 14:35:16.148: D/com.distriqt.Firebase(20420):  }Bundle )

**Comment by marchbold** [comment]
What method are you using to configure your application? We highly suggest using the resources method if you can.

**Comment by railnation** [comment]
I just use the code method.

**Comment by marchbold** [comment]
Could you try the resources method see if there's an issue with the code method for me?

**Comment by railnation** [comment]
Okay, I hope I can try it this week.
