### ISSUE TITLE
java.lang.NoClassDefFoundError latest version

### ISSUE THREAD

**Issue by railnation** [distriqt/ANE-Firebase#150]
##### Expected behaviour

App should start normal

##### Actual behaviour

App process will die

##### Environment 

- AIR SDK version: 29
- Device OS: Android 6
- Device version: 
- Development IDE:  FDT 
- Development OS: Windows

##### Logs
```
FATAL EXCEPTION: main
06-05 07:32:42.128: E/AndroidRuntime(1942): Process: com.traviangames.railnationworld, PID: 1942
06-05 07:32:42.128: E/AndroidRuntime(1942): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/Preconditions;
06-05 07:32:42.128: E/AndroidRuntime(1942): 	at com.google.firebase.perf.provider.FirebasePerfProvider.attachInfo(Unknown Source)
06-05 07:32:42.128: E/AndroidRuntime(1942): 	at android.app.ActivityThread.installProvider(ActivityThread.java:6874)
06-05 07:32:42.128: E/AndroidRuntime(1942): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6469)
06-05 07:32:42.128: E/AndroidRuntime(1942): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6409)
06-05 07:32:42.128: E/AndroidRuntime(1942): 	at android.app.ActivityThread.access$1800(ActivityThread.java:229)
06-05 07:32:42.128: E/AndroidRuntime(1942): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
06-05 07:32:42.128: E/AndroidRuntime(1942): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-05 07:32:42.128: E/AndroidRuntime(1942): 	at android.os.Looper.loop(Looper.java:148)
06-05 07:32:42.128: E/AndroidRuntime(1942): 	at android.app.ActivityThread.main(ActivityThread.java:7331)
06-05 07:32:42.128: E/AndroidRuntime(1942): 	at java.lang.reflect.Method.invoke(Native Method)
06-05 07:32:42.128: E/AndroidRuntime(1942): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
06-05 07:32:42.128: E/AndroidRuntime(1942): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
06-05 07:32:42.128: E/AndroidRuntime(1942): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.Preconditions" on path: DexPathList[[zip file "/data/app/com.traviangames.railnationworld-1/base.apk"],nativeLibraryDirectories=[/data/app/com.traviangames.railnationworld-1/lib/arm, /data/app/com.traviangames.railnationworld-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
06-05 07:32:42.128: E/AndroidRuntime(1942): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
06-05 07:32:42.128: E/AndroidRuntime(1942): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
06-05 07:32:42.128: E/AndroidRuntime(1942): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
06-05 07:32:42.128: E/AndroidRuntime(1942): 	... 12 more
06-05 07:32:42.128: E/AndroidRuntime(1942): 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.common.internal.Preconditions
06-05 07:32:42.128: E/AndroidRuntime(1942): 		at java.lang.Class.classForName(Native Method)
06-05 07:32:42.128: E/AndroidRuntime(1942): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
06-05 07:32:42.128: E/AndroidRuntime(1942): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
06-05 07:32:42.128: E/AndroidRuntime(1942): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
06-05 07:32:42.128: E/AndroidRuntime(1942): 		... 13 more
06-05 07:32:42.128: E/AndroidRuntime(1942): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by marchbold** [comment]
Have you updated all the dependent ANEs ? this looks like an issue with the version of Google Play Services.

**Comment by railnation** [comment]
No not yet. I just wanted to see if the app measurement works.

**Comment by marchbold** [comment]
You must update the dependencies as well, otherwise you will run into missing class errors like the above.

**Comment by railnation** [comment]
![updated](https://user-images.githubusercontent.com/11500099/40957879-4a332c44-6897-11e8-8d51-62588bab6532.jpg)

Updated these extensions but my app still crashes

**Comment by marchbold** [comment]
Please post the new log.

**Comment by railnation** [comment]
[log.txt](https://github.com/distriqt/ANE-Firebase/files/2071019/log.txt)

**Comment by marchbold** [comment]
Have you updated the manifest additions? 

https://github.com/distriqt/ANE-Firebase/wiki/Core---Add-the-extensions

**Comment by marchbold** [comment]
Okay then, I can't see the configuration ANE in your list? Have you added your configuration to your application?

https://github.com/distriqt/ANE-Firebase/wiki/Setup---Configuration-Files

**Comment by railnation** [comment]
Sorry, Config.ane was missing from packaging. Now added back again but still crashing

D/FirebasePerformance(14848): onResume com.traviangames.railnationworld.AppEntry:785461
06-05 08:36:27.828: E/UncaughtException(14848): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.firebase.perf.FirebasePerformance.isPerformanceCollectionEnabled()' on a null object reference
06-05 08:36:27.828: E/UncaughtException(14848): 	at com.google.android.gms.internal.firebase-perf.zzg.zzq(Unknown Source)
06-05 08:36:27.828: E/UncaughtException(14848): 	at com.google.android.gms.internal.firebase-perf.zzg.zzp(Unknown Source)
06-05 08:36:27.828: E/UncaughtException(14848): 	at com.google.android.gms.internal.firebase-perf.zzg.zzb(Unknown Source)
06-05 08:36:27.828: E/UncaughtException(14848): 	at com.google.android.gms.internal.firebase-perf.zzh.run(Unknown Source)
06-05 08:36:27.828: E/UncaughtException(14848): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-05 08:36:27.828: E/UncaughtException(14848): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-05 08:36:27.828: E/UncaughtException(14848): 	at java.lang.Thread.run(Thread.java:818)
06-05 08:36:27.833: E/UncaughtException(14848): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.internal.firebase-perf.zzq.zzb(boolean)' on a null object reference
06-05 08:36:27.833: E/UncaughtException(14848): 	at com.google.android.gms.internal.firebase-perf.zzg.zzc(Unknown Source)
06-05 08:36:27.833: E/UncaughtException(14848): 	at com.google.android.gms.internal.firebase-perf.zzk.run(Unknown Source)
06-05 08:36:27.833: E/UncaughtException(14848): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-05 08:36:27.833: E/UncaughtException(14848): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-05 08:36:27.833: E/UncaughtException(14848): 	at java.lang.Thread.run(Thread.java:818)
06-05 08:36:27.838: D/ConnectivityService(2732): returning getNetworkInfo for network type 1 : [type: WIFI[] - WIFI, state: CONNECTED/CONNECTED, reason: (unspecified), extra: "BFKolibri", roaming: false, failover: false, isAvailable: true]
06-05 08:36:27.838: I/Finsky(14599): [1] com.google.android.finsky.p2p.d.a(2): Wrote row to frosting DB: 138
06-05 08:36:27.838: W/System.err(14599): remove failed: ENOENT (No such file or directory) : /data/user/0/com.android.vending/cache/safe_mode810206
06-05 08:36:27.843: V/BroadcastQueue(2732): [background] Process cur broadcast BroadcastRecord{c0d8de7 u0 android.intent.action.PACKAGE_REMOVED qIdx=4}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{80ecd99 14913:com.sec.spp.push/u0a57}
06-05 08:36:27.843: E/UncaughtException(14848): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.firebase.perf.FirebasePerformance.isPerformanceCollectionEnabled()' on a null object reference
06-05 08:36:27.843: E/UncaughtException(14848): 	at com.google.android.gms.internal.firebase-perf.zzg.zzb(Unknown Source)
06-05 08:36:27.843: E/UncaughtException(14848): 	at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source)
06-05 08:36:27.843: E/UncaughtException(14848): 	at com.google.android.gms.internal.firebase-perf.zzi.run(Unknown Source)
06-05 08:36:27.843: E/UncaughtException(14848): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-05 08:36:27.843: E/UncaughtException(14848): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-05 08:36:27.843: E/UncaughtException(14848): 	at java.lang.Thread.run(Thread.java:818)

**Comment by marchbold** [comment]
Will have to look into it. Is other Firebase functionality working?

**Comment by railnation** [comment]
No, the app start but crashes immediately

**Comment by marchbold** [comment]
Can you update your the ComponentDiscoveryService in your manifest to be as below:

```xml
<service android:name="com.google.firebase.components.ComponentDiscoveryService" >
    <meta-data
        android:name="com.google.firebase.components:com.google.firebase.perf.component.FirebasePerfRegistrar"
        android:value="com.google.firebase.components.ComponentRegistrar" />
    <meta-data
        android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
        android:value="com.google.firebase.components.ComponentRegistrar" />
    <meta-data
        android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
        android:value="com.google.firebase.components.ComponentRegistrar" />
</service>
```

**Comment by railnation** [comment]
The app does not crash and starts. Looks like your changes fixed the issue

**Comment by marchbold** [comment]
Excellent, I think we may have missed those additions in the latest release. Will go through our documentation and get that updated.

Thanks for reporting this issue and working through it with us.

**Comment by railnation** [comment]
No problem. I have to say thank you for your great support.
