### ISSUE TITLE
Analytics - screenName vs screenClass

### ISSUE THREAD

**Issue by Lydecker** [distriqt/ANE-Firebase#154]
Sorry for what is probably a basic question!

What is the difference between screenName and screenClass

![image](https://user-images.githubusercontent.com/12632602/41098349-f52e2394-6a52-11e8-8840-bfe890a2a260.png)

In most examples I have seen - only one argument is supplied with a call, not two....

Thanks

**Comment by marchbold** [comment]
When used natively the class is the Java Class of the activity or the UIViewController class name that is currently displayed. You can use this in your AIR application as you see fit, specifying the AS3 class name of your current view or some other distinction.

**Comment by Lydecker** [comment]
Cheers!
