### ISSUE TITLE
Analytics - setUserProperty() - Values Persist?

### ISSUE THREAD

**Issue by Lydecker** [distriqt/ANE-Firebase#155]
According to the documentation:

![image](https://user-images.githubusercontent.com/12632602/41098456-589e21ea-6a53-11e8-985c-881eb707c128.png)

Once a user property value is set, it cannot be changed (i.e if we set a new value for the same user property name - it is not updated in firebase). Is this true?

Reading other sources seems to imply that this can be changed....

Lets take the example I want to record the number of Cars a user owns. If I set setUserProperty("user_car_count", "2")

and the user uses my app for a year.... then they buy a new car and update their profile in their app so they now have 3 cars, are you saying if 

setUserProperty("user_car_count", "3") is called for the same user the next time they launch the app that it won't update the user property on the Firebase Console?

Thanks

**Comment by marchbold** [comment]
It can definitely be changed. 

The documentation means the value persists. I.e. you don't have to repeatedly call this to send a user property along with events and their custom properties.

**Comment by Lydecker** [comment]
OK - great, thanks!
