### ISSUE TITLE
Compilation failed while executing : ld64

### ISSUE THREAD

**Issue by aram-ahak** [distriqt/ANE-Firebase#157]
Hi guys.
We updated Ane`s, and after that we are getting this error.
```
AppData\\Local\\Temp\\f34bb674-ac5c-4efc-975d-866317265aaf/FirebaseAuth.framework/FirebaseAuth(FIRAuthAppDelegateProxy.o), sectionForAddress(0x4000001) address not in any section for architecture arm64
Compilation failed while executing : ld64
```
We use:
- Windows AIR SDK version: 30
- iOS SDK version 11.1
- Firebase vesrion  2.0.043

**Comment by marchbold** [comment]
What IDE are you using? 

That looks like an issue with the iOS linker in the AIR SDK on Windows.

**Comment by aram-ahak** [comment]
We use "IntelliJ IDEA" IDE, but before updating ANEs, we didn't have any problem.

**Comment by marchbold** [comment]
Okay, the updated ANEs may use more recent iOS functionality though so may require a more recent version of the linker. The Windows version has always lagged behind have you tried the 31 beta at all?

**Comment by aram-ahak** [comment]
We are getting this error for SDK 31 beta too.

**Comment by marchbold** [comment]
Can you tell us what version of Windows and Java (JDK) you are using?

**Comment by aram-ahak** [comment]
We use Windows 10, and JDK 1.8.0.172

**Comment by aram-ahak** [comment]
We are getting this error for SDK 28, and 29 too.

**Comment by aram-ahak** [comment]
HI @marchbold, any news on this issue?

**Comment by marchbold** [comment]
We are in progress of putting together a bug report for Adobe. Not much else we can do at this point. 

You can try rolling back to the old ANEs that used the old Firebase frameworks?

**Comment by marchbold** [comment]
Or using macOS which has the more recent iOS linker in the AIR SDK.

**Comment by marchbold** [comment]
Hi, Can you tell me if you are setting any additional options on the compiler in intelliJ? and are you packaging against a version of the iOS SDK?

**Comment by aram-ahak** [comment]
We don't use additional options, and we use iOS SDK 11.1(we tried ISO SDK 11.0 too [from](https://airnativeextensions.github.io/tutorials/iOS-versions) )
![image](https://user-images.githubusercontent.com/7924501/42363984-a2697630-810a-11e8-8f51-844fcd66f676.png)
![image](https://user-images.githubusercontent.com/7924501/42364026-d215dcac-810a-11e8-854d-b8bd68598e76.png)

**Comment by marchbold** [comment]
Thanks for that. 

This appears to be related to the `@available` flag in iOS. This is in use in the Firebase frameworks now and we have been able to resolve it with a fix using the latest linker on macOS however it doesn't work on windows. 

Please vote for the issue in the Adobe tracker here: https://tracker.adobe.com/#/view/AIR-4198557

**Comment by marchbold** [comment]
You could try removing the iOS sdk reference if you wish (it's not needed with the latest AIR SDK I believe).

**Comment by chaurtik** [comment]
I have the same problem with ANE InAppBilling
InAppBilling version 6.1.098
Windows AIR SDK version: 30
iOs sdk reference  removed

Did anybody resolve this problem?

**Comment by marchbold** [comment]
Log an issue in the inappbilling ANE repository and we'll follow up with you.

**Comment by marchbold** [comment]
This should all be resolved now with the latest version of AIR and an updated iOS SDK (or none), please let me know if you are still encountering any issues.
