### ISSUE TITLE
How to read data for a particular user

### ISSUE THREAD

**Issue by Shaunmax** [distriqt/ANE-Firebase#159]
I am using Firebase ane for using realtime database. I would like to know how to read data for a particular user and not the whole database. for example,  i want to know whats the current score stored in the database "test" for the player_id "pl100", where "pl100" is the primary key! 

my db will look like
test 
-pl100
--currentScore: 1000
-pl101
--currentScore: 2000
-pl102
--currentScore: 3000
-pl103
--currentScore: 2000

**Comment by Shaunmax** [comment]
Wow thats so easy, and it worked for me thanks! 
But I have a problem, when there is a network connectivity issues, the event is not triggering failed for no internet, is there a failed event that i should listen for separately

**Comment by Shaunmax** [comment]
Ok now I am checking :- 
public function connectedListener(): void {
			try {
				databaseRef = FirebaseDatabase.service.getReference(".info/connected");
				databaseRef.addEventListener(DatabaseReferenceEvent.VALUE_CHANGED, info_valueChangedHandler);
			} catch (e: Error) {
				trace("Error in connectedListener - ",e.message);
			}
		}
and its working for most of the cases but there is case where at the time of checking wifi is there and after that if it looses connectivity there is no response from player.once( function( value:Object ):void. I dont think thats the right of doing it right, if there is no network then the event should throw error right? Correct me if I am wrong!

**Comment by marchbold** [comment]
You should get a null response if there was an error? Are you not getting that?

Could you tell me how to replicate exactly?

**Comment by Shaunmax** [comment]
Just switch off the wifi and check the once function!

No I dint get the null response~

**Comment by marchbold** [comment]
Okay, so wifi is off before calling `once()` ?

**Comment by Shaunmax** [comment]
Yes, the same for PushNotifications.service.register();

**Comment by marchbold** [comment]
Have you tried enabling persistence? This greatly helps handling offline cases:

```as3
FirebaseDatabase.service.setPersistenceEnabled( true );
```

https://github.com/distriqt/ANE-Firebase/wiki/Database---Offline

**Comment by Shaunmax** [comment]
It is enabled, but I believe thats only for saving offline scores right?

It wont help in getting call back for once ()

**Comment by marchbold** [comment]
It should help if the data is stored locally. I'll have to look into it see why the SDK isn't returning in these cases.

**Comment by Shaunmax** [comment]
You mean to say that, if

FirebaseDatabase.service.setPersistenceEnabled( true );

and there is no internet connection, then once() function should
return return a value from the local data?

What if its a fresh install? or player deleted the app and reinstalled again?

**Comment by marchbold** [comment]
Obviously there are cases that it won't work, but persisting to the local storage allows you to handle disconnects and still access data. Read more in the documentation.

**Comment by Shaunmax** [comment]
No, I understand that, but in my case its mostly with app start, this is
where i fetch score from database and there is no response.
In the doc, I believe its mostly for write cases not for read!

Let me know if there is a call back for once()

I see that for anonymous sign in, i get this "

A network error (such as timeout, interrupted connection or unreachable
host) has occurred" error.


Something like this should be enough for once()

**Comment by marchbold** [comment]
Not sure what to do here, I believe this is working as per Firebase Database documentation.

From the Firebase docs, your approach should be to monitor the connected property:

```as3
var connected:Boolean = false;

var ref:DatabaseReference = FirebaseDatabase.service.getReference( ".info/connected" );
ref.addEventListener( DatabaseReferenceEvent.VALUE_CHANGED, info_valueChangedHandler );

function info_valueChangedHandler( event:DatabaseReferenceEvent ):void
{
	connected = event.snapshot.value;
}
```

The connected property will update based on the current connection to the Firebase db. 

The `once` function can be attached at any time. If you don't have a local (offline) value and you initiate `once` when not connected then you will only get the returned value when the device connects to the database again.

If your issue is only at application start, then I suggest you preload your application with suitable defaults and then update when the database is connected. 

If you are only concerned about the edge case of when it disconnects during a once call then you may have to handle that logic in your connected event listener? 

I can't see any extra error events or information that we can return from Firebase.

**Comment by Shaunmax** [comment]
Ok thanks, will get back to you if it becomes a major concern
