### ISSUE TITLE
GoViral Conflict with Firebase ANE

### ISSUE THREAD

**Issue by KreedaSolutions** [distriqt/ANE-Firebase#16]
We are using Goviral(MilkmanGames) ANE. 

When we tried to update our Push Notification to FCM from GCM ans used FireBase ANE for this purpose, We are not able to compile. 

![image](https://cloud.githubusercontent.com/assets/22871619/20089222/53756e62-a5ab-11e6-979a-7605f57fd994.png)

When we Remove Either of ANE - FireBase(Distriq) or Goviral (Milkman) we are able to compile. 

Note - we also tried with Latest ANEs from Google Play Services (Base, GCM, ADS)

Thanks, 
Aseem

**Comment by marchbold** [comment]
Can you get the rest of that message? Normally with those long messages the actual error is right at the end.

I'd imagine it's something to do with the play services conflicting. Could you list all the ANEs you are using?

**Comment by KreedaSolutions** [comment]
Compiling now after downloading latest FIREBASE ANE..
