### ISSUE TITLE
App crash when trying to upload image or bytearray to firebasestorage

### ISSUE THREAD

**Issue by tomergott** [distriqt/ANE-Firebase#160]
Hi,
i am getting an error when trying to upload an image to storage,
i am using manual configuration

```as3
var options:FirebaseOptions = new FirebaseOptions();  
options.apiKey      = google_api_key;
options.clientID    = default_web_client_id;
options.databaseURL = firebase_database_url
options.gcmSenderID = gcm_defaultSenderId;
options.googleAppID = google_app_id;

Firebase.service.initialiseApp( options );
```

i am using the realtime database and that is working great both read and write to database,
when i'm trying to upload image the app crashes. i am using all the latest ANE's and i get the correct storage path and getbucket() is also fine.
What do you think can be the problem? maybe the file is too big?
Thank you very much
Tomer.

**Comment by marchbold** [comment]
Hi, Hard to say, manual configuration can have some issues with Firebase as it often expects configuration to be available outside of the normal AIR process lifetime. 

Can you include some more information:

- platform
- version
- device logs (https://airnativeextensions.github.io/tutorials/device-logs)

**Comment by tomergott** [comment]
My IDE is Flash Animate using Air 29.0.0.108
i dont have the android sdk installed so i have some problem with getting the device logs, is there another way i can figure out what is the problem?
what i do know is that this is the line that make the app crash:
var task:UploadTask = reference.putFile( file );

Also, i am using  firebase and NFC ANE's and everything is working great the only problem is with the storage.
what do you think i can do? i also can send you my JSON and my manifest for you to review maybe there is a problem there.
Thank you
Tomer.

**Comment by tomergott** [comment]
This is my Samsung Galaxy s7 device log

07-08 18:57:56.202  3791  3857 I WindowManager_SurfaceController: Destroying surface Surface(name=InputMethod) called by com.android.server.wm.WindowStateAnimator.destroySurface:2840 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1070 com.android.server.wm.WindowState.destroyOrSaveSurface:2561 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:499 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:274 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:222 com.android.server.wm.WindowManagerService$H.handleMessage:9180 android.os.Handler.dispatchMessage:102
07-08 18:57:56.202  3194  5706 I SurfaceFlinger: id=44857 Removed JnputMethod (9/11)
07-08 18:57:56.202  3194  4755 I SurfaceFlinger: id=44857 Removed JnputMethod (-2/11)
07-08 18:57:56.336 15278 15278 I FIPS_bssl: FIPS (v1.1) approved mode (1) | 15278 | /system/bin/cat
07-08 18:57:56.357 15280 15280 I FIPS_bssl: FIPS (v1.1) approved mode (1) | 15280 | /system/bin/cat
07-08 18:57:56.359 15251 15251 W System.err: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
07-08 18:57:56.359 15251 15251 W System.err:    at android.app.ContextImpl.checkMode(ContextImpl.java:2364)
07-08 18:57:56.359 15251 15251 W System.err:    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:383)
07-08 18:57:56.359 15251 15251 W System.err:    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:378)
07-08 18:57:56.359 15251 15251 W System.err:    at com.adobe.air.AIRSharedPref.getConfigData(AIRSharedPref.java:113)
07-08 18:57:56.359 15251 15251 W System.err:    at com.adobe.air.Entrypoints.EntryMainWrapper(Native Method)
07-08 18:57:56.359 15251 15251 W System.err:    at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:139)
07-08 18:57:56.359 15251 15251 W System.err:    at com.adobe.air.AndroidActivityWrapper.LaunchApplication(AndroidActivityWrapper.java:1167)
07-08 18:57:56.359 15251 15251 W System.err:    at com.adobe.air.AndroidActivityWrapper.onSurfaceInitialized(AndroidActivityWrapper.java:1416)
07-08 18:57:56.359 15251 15251 W System.err:    at com.adobe.air.AIRWindowSurfaceView.surfaceChanged(AIRWindowSurfaceView.java:790)
07-08 18:57:56.359 15251 15251 W System.err:    at android.view.SurfaceView.updateWindow(SurfaceView.java:664)
07-08 18:57:56.359 15251 15251 W System.err:    at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:172)
07-08 18:57:56.359 15251 15251 W System.err:    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1013)
07-08 18:57:56.359 15251 15251 W System.err:    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2492)
07-08 18:57:56.359 15251 15251 W System.err:    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1509)
07-08 18:57:56.359 15251 15251 W System.err:    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7051)
07-08 18:57:56.359 15251 15251 W System.err:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
07-08 18:57:56.359 15251 15251 W System.err:    at android.view.Choreographer.doCallbacks(Choreographer.java:702)
07-08 18:57:56.359 15251 15251 W System.err:    at android.view.Choreographer.doFrame(Choreographer.java:638)
07-08 18:57:56.359 15251 15251 W System.err:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
07-08 18:57:56.359 15251 15251 W System.err:    at android.os.Handler.handleCallback(Handler.java:751)
07-08 18:57:56.359 15251 15251 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
07-08 18:57:56.359 15251 15251 W System.err:    at android.os.Looper.loop(Looper.java:154)
07-08 18:57:56.359 15251 15251 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6692)
07-08 18:57:56.359 15251 15251 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
07-08 18:57:56.359 15251 15251 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
07-08 18:57:56.359 15251 15251 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
07-08 18:57:56.367 15251 15251 W System.err: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
07-08 18:57:56.367 15251 15251 W System.err:    at android.app.ContextImpl.checkMode(ContextImpl.java:2364)
07-08 18:57:56.367 15251 15251 W System.err:    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:383)
07-08 18:57:56.367 15251 15251 W System.err:    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:378)
07-08 18:57:56.367 15251 15251 W System.err:    at com.adobe.air.AIRSharedPref.getConfigRequestTime(AIRSharedPref.java:70)
07-08 18:57:56.367 15251 15251 W System.err:    at com.adobe.air.Entrypoints.EntryMainWrapper(Native Method)
07-08 18:57:56.367 15251 15251 W System.err:    at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:139)
07-08 18:57:56.367 15251 15251 W System.err:    at com.adobe.air.AndroidActivityWrapper.LaunchApplication(AndroidActivityWrapper.java:1167)
07-08 18:57:56.367 15251 15251 W System.err:    at com.adobe.air.AndroidActivityWrapper.onSurfaceInitialized(AndroidActivityWrapper.java:1416)
07-08 18:57:56.367 15251 15251 W System.err:    at com.adobe.air.AIRWindowSurfaceView.surfaceChanged(AIRWindowSurfaceView.java:790)
07-08 18:57:56.367 15251 15251 W System.err:    at android.view.SurfaceView.updateWindow(SurfaceView.java:664)
07-08 18:57:56.367 15251 15251 W System.err:    at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:172)
07-08 18:57:56.367 15251 15251 W System.err:    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1013)
07-08 18:57:56.367 15251 15251 W System.err:    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2492)
07-08 18:57:56.367 15251 15251 W System.err:    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1509)
07-08 18:57:56.367 15251 15251 W System.err:    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7051)
07-08 18:57:56.367 15251 15251 W System.err:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
07-08 18:57:56.367 15251 15251 W System.err:    at android.view.Choreographer.doCallbacks(Choreographer.java:702)
07-08 18:57:56.367 15251 15251 W System.err:    at android.view.Choreographer.doFrame(Choreographer.java:638)
07-08 18:57:56.367 15251 15251 W System.err:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
07-08 18:57:56.367 15251 15251 W System.err:    at android.os.Handler.handleCallback(Handler.java:751)
07-08 18:57:56.367 15251 15251 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
07-08 18:57:56.367 15251 15251 W System.err:    at android.os.Looper.loop(Looper.java:154)
07-08 18:57:56.367 15251 15251 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6692)
07-08 18:57:56.367 15251 15251 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
07-08 18:57:56.367 15251 15251 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
07-08 18:57:56.367 15251 15251 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
07-08 18:57:56.368 15251 15251 W System.err: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
07-08 18:57:56.368 15251 15251 W System.err:    at android.app.ContextImpl.checkMode(ContextImpl.java:2364)
07-08 18:57:56.368 15251 15251 W System.err:    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:383)
07-08 18:57:56.368 15251 15251 W System.err:    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:378)
07-08 18:57:56.368 15251 15251 W System.err:    at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:171)
07-08 18:57:56.368 15251 15251 W System.err:    at com.adobe.air.AIRSharedPref.setConfigRequestTime(AIRSharedPref.java:148)
07-08 18:57:56.368 15251 15251 W System.err:    at com.adobe.air.Entrypoints.EntryMainWrapper(Native Method)
07-08 18:57:56.368 15251 15251 W System.err:    at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:139)
07-08 18:57:56.368 15251 15251 W System.err:    at com.adobe.air.AndroidActivityWrapper.LaunchApplication(AndroidActivityWrapper.java:1167)
07-08 18:57:56.368 15251 15251 W System.err:    at com.adobe.air.AndroidActivityWrapper.onSurfaceInitialized(AndroidActivityWrapper.java:1416)
07-08 18:57:56.368 15251 15251 W System.err:    at com.adobe.air.AIRWindowSurfaceView.surfaceChanged(AIRWindowSurfaceView.java:790)
07-08 18:57:56.369 15251 15251 W System.err:    at android.view.SurfaceView.updateWindow(SurfaceView.java:664)
07-08 18:57:56.369 15251 15251 W System.err:    at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:172)
07-08 18:57:56.369 15251 15251 W System.err:    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1013)
07-08 18:57:56.369 15251 15251 W System.err:    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2492)
07-08 18:57:56.369 15251 15251 W System.err:    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1509)
07-08 18:57:56.369 15251 15251 W System.err:    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7051)
07-08 18:57:56.369 15251 15251 W System.err:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
07-08 18:57:56.369 15251 15251 W System.err:    at android.view.Choreographer.doCallbacks(Choreographer.java:702)
07-08 18:57:56.369 15251 15251 W System.err:    at android.view.Choreographer.doFrame(Choreographer.java:638)
07-08 18:57:56.369 15251 15251 W System.err:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
07-08 18:57:56.369 15251 15251 W System.err:    at android.os.Handler.handleCallback(Handler.java:751)
07-08 18:57:56.369 15251 15251 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
07-08 18:57:56.369 15251 15251 W System.err:    at android.os.Looper.loop(Looper.java:154)
07-08 18:57:56.369 15251 15251 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6692)
07-08 18:57:56.369 15251 15251 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
07-08 18:57:56.369 15251 15251 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
07-08 18:57:56.369 15251 15251 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
07-08 18:57:56.383  3791  3857 D LockSettingsStorage: mSKTLockState = 2
07-08 18:57:56.385  4087  4087 V WallpaperService: Visibility change in com.android.systemui.ImageWallpaper$DrawableEngine@1dd94d3: 0
07-08 18:57:56.385  3791  3857 D LockSettingsStorage: mSKTLockState = 2
07-08 18:57:56.385  4087  4087 V WallpaperService: onVisibilityChanged(false): com.android.systemui.ImageWallpaper$DrawableEngine@1dd94d3
07-08 18:57:56.385  4087  4087 D ImageWallpaper: onVisibilityChanged: mVisible, visible=true, false
07-08 18:57:56.386  4087  4087 D ImageWallpaper: Visibility changed to visible=false
07-08 18:57:56.387  3791  3857 D ViewRootImpl@82d803f[SofiaColori]: MSG_RESIZED: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
07-08 18:57:56.399  3791  3857 V WindowManager: Relayout Window{3899655d0 u0 Starting air.SofiaColori}: viewVisibility=0 req=1080x1920 WM.LayoutParams{(0,0)(fillxfill) sim=#20 ty=3 fl=#830118 pfl=0x20011 wanim=0x1030001 vsysui=0x400 needsMenuKey=2 naviIconColor=0}

**Comment by marchbold** [comment]
`adb` is included in the AIR SDK so you don't need the Android SDK installed. Could you post more of the logs, doesn't look like the crash is included just the AIR startup?

**Comment by tomergott** [comment]
i will send you the rest of the log later, what are all the errors i see in the log here?

**Comment by marchbold** [comment]
They are just warnings that the AIR SDK (`AIRWindowSurfaceView`) contains some `MODE_WORLD_READABLE` code. Nothing abnormal there.

**Comment by tomergott** [comment]
Thanks, is it possible to get logs ONLY for my air app? i get all the device logs and searching inside the logs is frustrating...

**Comment by tomergott** [comment]
Problem Solved!!!!!
in the firebase storage rules i had to take out  **if request.auth != null;**
allow read, write;

Thanks for your help!

**Comment by marchbold** [comment]
Excellent, glad you isolated the issue. 

I'll have a look to see if it's possible to catch these errors and report them to AS3.

**Comment by tomergott** [comment]
I think you should update the wiki in storage section to let buyers know what they need to do in order to make this work.Thanks for your help!


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Michael <notifications@github.com> Date: 7/10/18  03:54  (GMT+02:00) To: distriqt/ANE-Firebase <ANE-Firebase@noreply.github.com> Cc: tomergott <gt@netvision.net.il>, Author <author@noreply.github.com> Subject: Re: [distriqt/ANE-Firebase] App crash when trying to upload image or
  bytearray to firebasestorage (#160) 
Excellent, glad you isolated the issue.
I'll have a look to see if it's possible to catch these errors and report them to AS3.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/distriqt/ANE-Firebase","title":"distriqt/ANE-Firebase","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/distriqt/ANE-Firebase"}},"updates":{"snippets":[{"icon":"PERSON","message":"@marchbold in #160: Excellent, glad you isolated the issue. \r\n\r\nI'll have a look to see if it's possible to catch these errors and report them to AS3. "}],"action":{"name":"View Issue","url":"https://github.com/distriqt/ANE-Firebase/issues/160#issuecomment-403664679"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/distriqt/ANE-Firebase/issues/160#issuecomment-403664679",
"url": "https://github.com/distriqt/ANE-Firebase/issues/160#issuecomment-403664679",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [distriqt/ANE-Firebase] App crash when trying to upload image or bytearray to firebasestorage (#160)",
"sections": [
{
"text": "",
"activityTitle": "**Michael**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@marchbold",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"distriqt/ANE-Firebase\",\n\"issueId\": 160,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"distriqt/ANE-Firebase\",\n\"issueId\": 160\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/distriqt/ANE-Firebase/issues/160#issuecomment-403664679"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 353318802\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by marchbold** [comment]
Okay will do. 

Cheers
