### ISSUE TITLE
signInWithCredential()  error

### ISSUE THREAD

**Issue by jasonJamEther** [distriqt/ANE-Firebase#161]
I am using the Google Identity extension to authenticate with the firebase auth extension on Android. I have gone through all the steps several times but I am getting an error on the last step of the Authentication. I was hoping someone knew from the error I am getting if I am missing a step somewhere or if it is a bug.

After signing in with google successfully, I call:
private function googleIdentity_signInHandler(event:GoogleIdentityEvent):void
		{			 
var credential:AuthCredential = GoogleAuthProvider.getCredential( event.user.authentication.idToken, event.user.authentication.accessToken);
			FirebaseAuth.service.addEventListener( FirebaseAuthEvent.SIGNIN_WITH_CREDENTIAL_COMPLETE, signInWithCredential_completeHandler);
			FirebaseAuth.service.signInWithCredential( credential );
		}

I have verified that event.user.authentication.idToken returns a value as expected. When I call FirebaseAuth.service.signInWithCredential( credential ); I get an error:

Error #2044: Unhandled error:. text=Attempt to invoke virtual method 'void com.google.firebase.auth.FirebaseAuth.addAuthStateListener(com.google.firebase.auth.FirebaseAuth$AuthStateListener)' on a null object reference

Any ideas?

- AIR SDK version:  29
- Device OS: Android 8.0.0
- Device version: Samsung Galaxy s7
- Development IDE: Adobe Animate
- Development OS: MACoS High Sierra 10.13.5

**Comment by jasonJamEther** [comment]
After searching some of the other similar closed issues I saw an example manifest file that showed I had android:name="com.google.firebase.components:com.google.firebase.auth.FirebaseAuthRegistrar" in the wrong place. Putting it in the correct place fixed the issue I had.

**Comment by marchbold** [comment]
Glad you found the issue.

Is the documentation not clear enough for this addition?

https://github.com/distriqt/ANE-Firebase/wiki/Auth---Add-the-extensions#android-manifest-additions
