### ISSUE TITLE
Is android WAKE_LOCK permission really required?

### ISSUE THREAD

**Issue by chichilatte** [distriqt/ANE-Firebase#163]
Hi, we'd dearly like to turn off `android.permission.WAKE_LOCK` in our app manifest (lots of our users are complaining of phones not sleeping). In our tests it's definitely this permission that's causing the problem. When we remove the permission the test devices sleep normally.

The Distriqt [docs say](https://distriqt.github.io/ANE-Firebase/Core%20-%20Add%20the%20extensions) we need the permission, but is it strictly necessary? We're  using the ANE for Firebase analytics, crash reporting and authentication (with the Distriqt GoogleIdentity ANE) so it doesn't sound like we need it.

**Comment by chichilatte** [comment]
FYI in case there might be some kind of ANE conflict happening, here are the ANEs we're using...

* Distriqt Notifications
* Distriqt Firebase (Firebase, Core, androidsupport.V4, playservices.Base, playservices.Identity, CustomResources, Auth, Crash) 
* Distriqt GoogleIdentity
* DigitalStrawberry ANESounds
* MilkmanGames GoViral
* MilkmanGames RateBox

**Comment by marchbold** [comment]
The permissions we list are simply the ones that the Firebase SDK adds to an Android project. There is nothing specific in the ANE that uses WAKE_LOCK but the Firebase SDK does internally.

From my understanding the WAKE_LOCK permission is required to reliably start a service from a broadcast receiver. This is a process that Firebase analytics uses to accurately measure your app. 

You can try removing it however I can't guarantee that Firebase (particularly analytics) will work as expected.

**Comment by chichilatte** [comment]
Ah, ok. Can I ask if you've experienced this problem at all? We're really not doing anything unusual, just `Firebase.service.analytics.logEvent(eventObject);` once in a while. We do log the occasional event when the app is in the background, perhaps this is the culprit.

**Comment by marchbold** [comment]
What problem are you experiencing?

**Comment by chichilatte** [comment]
Our app was causing the phone to never sleep. But after tons of googling about WAKE_LOCK I ran a batch of tests and found the guilty line in our own code... 

`NativeApplication.nativeApplication.systemIdleMode = SystemIdleMode.KEEP_AWAKE;`

Jeez-oo. My apols for time wasting +thanks for yr help and excellent ANEs!

**Comment by marchbold** [comment]
Ah yep, that'll do it ;) 

Glad you found the issue.
