### ISSUE TITLE
 Firebase.service.analytics.logEvent(event) execution takes too long!

### ISSUE THREAD

**Issue by david-daal** [distriqt/ANE-Firebase#166]
The execution of ` Firebase.service.analytics.logEvent(event);` takes x100 more time than logging the same event via Exponea ANE.

[trace] FIREBASE --------- >>>>> 2405
[trace] EXPONEA --------- >>>>> 21

The tested events have around 30 params.
Similar issue is opened for FB analytics call: https://github.com/distriqt/ANE-FacebookAPI/issues/203.

**Comment by marchbold** [comment]
Can you show the details of the event you are logging so we can replicate?

**Comment by marchbold** [comment]
Also, is this on iOS or Android or both?

**Comment by david-daal** [comment]
This test is done on Android, i will share iOS  results with you soon.
Also consider that we have this issue on Android: https://github.com/distriqt/ANE-Firebase/issues/147

**Comment by david-daal** [comment]
@marchbold is there way to turn on Firebase Analytics Debug mode for iOS?
The official instructions include calling xcode command line parameter, but that doesn't work when you build with AIR.

**Comment by marchbold** [comment]
As far as I'm aware there is no way on iOS to enable debug analytics. We do not have access to those parameters.

Just FYI, Firebase analytics events can't contain more than 25 params.

**Comment by david-daal** [comment]
@marchbold thanks for noting about attributes limit!
I had to switch to previous ANE versions and AIR SDK 28 to be able to debug on iOS. 
With AIR SDK 28 and previous Firebase ANE the event logging speed is good, no issues.

AIR SDK 29 and 30 make it not possible to debug the app and latest ANE-s require AIR SDK 29 at least to run. 
Is there way to debug an iOS app with AIR SDK 30 that you are aware of?

**Comment by david-daal** [comment]
Event logging speed has improved. great job! There is just issue #147, which actually says that Firebase Analytics for Android doesn't work at all.
