### ISSUE TITLE
Would regenerating the app key cause the live app (with old key) to stop working 

### ISSUE THREAD

**Issue by xxxVBxxx** [distriqt/ANE-Firebase#169]
I got NativeWebView ANE from distriqt this summer, and I already created the application and **generated** a key for my app (using bundle id).  And the app is live currently. 

Now I got firebase ane, and in the documentation it is mentioned that I should **regenerate** key for my current bundle in order to enable it for firebase. 

The question is -  would it be okay for my live app if I regenerate a new key, cause it will overwrite the old one, and my live app still will use the old key some time. I want to make sure, that after  I regenerate, the live app (which uses the old key) will continue work fine. 

Thank you in advance.

**Comment by marchbold** [comment]
Hi,
Regenerating your application keys has no affect on previous keys and live applications. They will continue to work indefinitely and your live applications will be unaffected by key generation.

Cheers

**Comment by xxxVBxxx** [comment]
Thanks )
