### ISSUE TITLE
FireBase not verify installation

### ISSUE THREAD

**Issue by xxxVBxxx** [distriqt/ANE-Firebase#171]
Hello
faced such a problem
installed and configured ane
There are no visible problems.
```
Firebase.init(DistriqtController.getKey());

            if (Firebase.isSupported)
            {
                var options:FirebaseOptions = new FirebaseOptions();
                options.apiKey      = "";
                options.clientID    = "";
                options.googleAppID = "";
                options.gcmSenderID = "";
                options.databaseURL = "";
                options.storageBucket = '';



                _isSupported = Firebase.service.initialiseApp(options);
                if (_isSupported) //true
...
```

but on the site shows the message

> Checking if the app has communicated with our servers. You may need to uninstall and reinstall your app.

When trying to send an event
there are no errors
but also in the control panel - the event is also not registered
`var event:EventObject = new EventObject();
                    event.name = 'start';
                    Firebase.service.analytics.logEvent( event );
`

**Comment by marchbold** [comment]
What platform is this occurring on? 

Using runtime options like that is not recommended and most of the time analytics will fail. We recommend using the configuration files method as it is the normal way Firebase configures applications. 

See more in the wiki:

https://github.com/distriqt/ANE-Firebase/wiki/Setup---Configuration-Files

**Comment by xxxVBxxx** [comment]
Problem is solved using configuration files method (recommended one), thanks )

**Comment by ArunIOSM** [comment]
Checking if the app has communicated with our servers. You may need to uninstall and reinstall your app.

**Comment by marchbold** [comment]
@ArunIOSM Have you double checked your configuration files?

**Comment by anujkv** [comment]
Hey,

I am also facing same issue , i did reconnect and reinstall app but still its not communicate with our server.

**Comment by alfredoqt** [comment]
Any updates on this? I have had the same issue for two weeks now.

**Comment by xghita** [comment]
> 
> 
> @ArunIOSM Have you double checked your configuration files?

what do you mean check configuration file?

**Comment by marchbold** [comment]
I am referring to the configuration file you use to inform the Firebase SDK of your application settings:

https://github.com/distriqt/ANE-Firebase/wiki/Setup---Configuration-Files
