### ISSUE TITLE
A lot of java.lang.NoClassDefFoundError in Google Dev. Console

### ISSUE THREAD

**Issue by Marcophono2** [distriqt/ANE-Firebase#174]
Yes, I know, reading my name will let your brain think "Oh no, not again that german pain in my..." and I am really sorry for bothering so much there days. :-)
Recently I registered a really huge amount of ARNS and Crashs and to fix them has priority no. 1 for me. Meanwhile the ARNS are nearly zero but the amount of Crashes is really scaring. One old which is related to AIR > 26 and still not fixed (signal 11 (SIGSEGV), code 1 (SEGV_MAPERR) in libCore.so)  but also a new error since my last implementation of your PushNotifications ANE. Just old Android versions <= 4.4 are affected so I think I just forgot any helper ANE of have a version conflict. I hope your focussed eyes have a clear view for it:

```
15 minutes ago on app version 301000009
Samsung Galaxy S3 Neo (s3ve3g), Android 4.4
Report 1
java.lang.NoClassDefFoundError: 
  at com.google.firebase.FirebaseApp.<clinit> (SourceFile:135)
  at com.google.firebase.provider.FirebaseInitProvider.onCreate (SourceFile:37)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:1591)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:1562)
  at com.google.firebase.provider.FirebaseInitProvider.attachInfo (SourceFile:31)
  at android.app.ActivityThread.installProvider (ActivityThread.java:5112)
  at android.app.ActivityThread.installContentProviders (ActivityThread.java:4707)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:4590)
  at android.app.ActivityThread.access$1600 (ActivityThread.java:169)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1337)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:136)
  at android.app.ActivityThread.main (ActivityThread.java:5476)
  at java.lang.reflect.Method.invokeNative (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1283)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1099)
  at dalvik.system.NativeStart.main (Native Method)
```

```
    <extensionID>com.distriqt.androidsupport.CustomTabs.ane</extensionID>	
	<extensionID>com.distriqt.playservices.Base.ane</extensionID>
	<extensionID>com.distriqt.Firebase.ane</extensionID>
    <extensionID>com.distriqt.PushNotifications</extensionID>
    <extensionID>com.distriqt.NativeWebView</extensionID>
    <extensionID>com.distriqt.Core</extensionID>		
	<extensionID>com.distriqt.androidsupport.V4</extensionID>
    <extensionID>com.distriqt.Contacts</extensionID>
    <extensionID>com.distriqt.InAppBilling</extensionID>
    <extensionID>com.distriqt.Application</extensionID>
    <extensionID>com.distriqt.MediaPlayer</extensionID>
    <extensionID>com.distriqt.androidsupport.AppCompatV7</extensionID>
```

```
			try
			{
				Core.init();
				PushNotifications.init( APP_KEY );
				if (PushNotifications.isSupported)
				{
					trace('PushNotifications.isSupported');
					var service:Service = new Service( Service.ONESIGNAL, oneSignalAppId );
					service.enableNotificationsWhenActive = true;
					
					PushNotifications.service.setup( service );
					PushNotifications.service.addEventListener( AuthorisationEvent.CHANGED, authorisationChangedHandler );					
					
					PushNotifications.service.addEventListener( RegistrationEvent.REGISTERING, registeringHandler );
					PushNotifications.service.addEventListener( RegistrationEvent.REGISTER_SUCCESS, registerSuccessHandler );
					PushNotifications.service.addEventListener( RegistrationEvent.CHANGED, registrationChangedHandler );
					PushNotifications.service.addEventListener( RegistrationEvent.REGISTER_FAILED, registerFailedHandler );
					PushNotifications.service.addEventListener( RegistrationEvent.ERROR, errorHandler );
					
					PushNotifications.service.register();					

				}
			}
			catch (e:Error)
			{
				trace('PushNotifications not working: '+ e );
			}
```

Also your Firebase ANE is embedded with the package without being initialized.
Sure, I could set up the SDK limit a bit to exclude older Android versions but I would prefer to find the issue itsself. Who knows what it affects as well.

Thank you and best regards,
Marc

P.S.: One more word to that other crash report relaited to 
```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)
libCore.so
pid: 0, tid: 0 >>> air.marc.waesche.org.marcophono <<<
backtrace:
   #00  pc 0000000000da14e8  /data/app/air.marc.waesche.org.marcophono-N7wd0eTp3LXWwNP9sT_Asw==/lib/arm/libCore.so
```
Have you any new informations about that issue? Obviously a lot of AIR developers have this problem but surely not everyone. I thought (and I read) that it may be caused by any sound processing. That's why I replaced my mp3 audio playback system with your MediaPayer ANE. Also I downgraded from AIR 31 to 29. But both didn't help. Downgrading to AIR 26 would help but...you know... ;-)

By the way, my Starling version I am using is veeeeery old! It is from 2013. Could that be causing one or both of the described crash reports? I am normally not an AIR developer (as you surely imagined) but due to certain technical restrictions I was forced to switch from Cordova to AIR. In 2013 I paid someone to develope my app in AIR and I reactivated that old source code to develope the app completely new but basing on the code base. "Never change a running system" prevented me i.E. from updating Starling. Funny that I also have no idea what this Starling is for! LOL! :-)

**Comment by marchbold** [comment]
I'm sorry I can't help with the segmentation fault that is occurring in AIR, this is one for the Adobe team.

Regarding the `java.lang.NoClassDefFoundError`, have you set the multidex application correctly in your application descriptor?

https://github.com/distriqt/ANE-Firebase/wiki/Core---Add-the-extensions#multidex-applications

**Comment by NB13** [comment]
Hi @Marcophono2 , do you have news about your "signal 11" crashes?
Here is more info for you - https://forum.starling-framework.org/topic/signal-11-errors (only info, not solution)
