### ISSUE TITLE
Firestore get all documents 

### ISSUE THREAD

**Issue by ozgunsandal** [distriqt/ANE-Firebase#179]
Hi,
I need to get all documents and their objects from a collection on Cloud Database.

```
FirebaseFirestore.service.collection("Users")
				.query()
				.addOnQuerySuccessHandler( function( snapshot:QuerySnapshot ):void
				{
					trace( "addOnQuerySuccessHandler" );
					var document:Array = snapshot.getDocuments();
					txt.text = document[0].email;
				})
				.addOnQueryFailureListener( function( message:String ):void
				{
					trace( "addOnQueryFailureListener: " + message );
					txt.text = message;
				});
```

Also tried this in addOnQuerySuccessHandler;

```
var document:DocumentSnapshot = new DocumentSnapshot();
var objects:Object = document.getData();
txt.text = objects.email;
```

But it is not working. Where am i wrong?

**Comment by marchbold** [comment]
This is querying all the documents in the "Users" collection.

Firstly you can't simply create a `new DocumentSnapshot()` and expect it to contain anything you have to retrieve them through queries.

The result of a query is an array of `DocumentSnapshot`s, you get the data from a snapshot by calling  `getData()` 

so in your success handler, you need to get the snapshot of interest and then retrieve the data from it:

```as3
trace( "addOnQuerySuccessHandler" );
var document:DocumentSnapshot = snapshot.getDocuments()[0];
txt.text = document.getData().email;
```

**Comment by ozgunsandal** [comment]
Hi again @marchbold ,

Thank you for your help. And it works clearly.
So How can i get that all document's names from a collection.

```
var documents:DocumentSnapshot = snapshot.getDocuments()[0];
var docName:String = documents.getReference().getId();
```
or
`var docName:String = documents.getReference().getDocument().getId();`

It's not working. Also I've tried lots of things but i couldnt make it.

**Comment by marchbold** [comment]
Can you explain what you are attempting to do exactly?

**Comment by ozgunsandal** [comment]
How can i get all document's names from a collection.

**Comment by ozgunsandal** [comment]
```
var datas:Object = {
				name:"Jack",
				read:0
			}
			
			var document:CollectionReference  = FirebaseFirestore.service.collection("Users");
			
			document.addEventListener( CollectionReferenceEvent.ADD_SUCCESS, successHandler );
			document.add(datas);
```

```
private function successHandler(e:CollectionReferenceEvent):void
		{
			
			e.currentTarget.removeEventListener( CollectionReferenceEvent.ADD_SUCCESS, successHandler );
			e.currentTarget.removeEventListener( CollectionReferenceEvent.ADD_ERROR, errorHandler );
			
			var docID:String= e.document.getId();
}
```
I can get document id If i add some data in Users collection with an auto document id.
After that, I want to get all document ids in Users collection but i could't.
```
FirebaseFirestore.service.collection("Users")
				.query()
				
				
				.addOnQuerySuccessHandler( function( snapshot:QuerySnapshot ):void
				{
					trace( "addOnQuerySuccessHandler");
					
					getAllDocumentID(snapshot);
				})
				.addOnQueryFailureListener( function( message:String ):void
				{
					trace( "addOnQueryFailureListener: " + message );
				});
```

```
private function getAllDocumentID(snapshot:QuerySnapshot):void
		{
			txt.text = "got in";
			var document:DocumentSnapshot = snapshot.getDocuments()[0];
			if(document == null)
				txt.text = "null doc";
			txt.text = document.getReference().getId(); //*****************
		}
```

**Comment by ozgunsandal** [comment]
is there a no way to do this ?

**Comment by marchbold** [comment]
That looks okay, what is failing exactly?

**Comment by marchbold** [comment]
Can you tell me which exact part of this line is failing? Or what it is returning? 

```
txt.text = document.getReference().getId();
```

**Comment by ozgunsandal** [comment]
`document.getReference()`
this part is returning [DocumentReference], and it is okay.

But this part is returning is nothing (not empty but nothing),
 document.getReference().getId();

**Comment by marchbold** [comment]
Right, thanks for that, we will investigate and see if we can replicate the issue.

**Comment by ozgunsandal** [comment]
Thanks, this issue is important for me. I am waiting for the update. Really i am waiting.

**Comment by marchbold** [comment]
Hi, We've isolated the issue, let us know if you still have issues after the update.

**Comment by ozgunsandal** [comment]
Hi, The app is now crashing at launch at first. And trying to launch again, this time app is openning clearly.
And trying to sign in with google, but it's not signing in with google. Before the update, that all was working.

I've updated ANEs and manifest file. These files are that i updated.
![ss](https://user-images.githubusercontent.com/776838/49894307-ac8b6e80-fe5e-11e8-8076-5243c2955b26.PNG)

**Comment by ozgunsandal** [comment]
Do you want me to send logs?

**Comment by marchbold** [comment]
Please make sure you update ALL the ANEs, including Core and Google Play Services. 

Updating just one can have unexpected results depending on how old your other ANEs are.

I don't understand the code above there are referenced functions that I can't see, you'll need to clarify what isn't working?

**Comment by ozgunsandal** [comment]
I've updated all these anes except CustomResources.ane
![ekran alintisi](https://user-images.githubusercontent.com/776838/49915426-999c8c80-fea6-11e8-8ced-3972d57111ef.PNG)

Sign in with google;
```
var options:GoogleIdentityOptions = new GoogleIdentityOptionsBuilder(Settings.serverClientID)
				.requestIdToken()
				.setServerClientID( Settings.serverClientID )
				.build();
			
			GoogleIdentity.service.setup( options );
			
			
			GoogleIdentity.service.addEventListener( GoogleIdentityEvent.SIGN_IN, signInHandler );
			GoogleIdentity.service.addEventListener( GoogleIdentityEvent.ERROR, errorHandler );
GoogleIdentity.service.signIn();
```
Signed in clearly;
```
private function signInHandler( event:GoogleIdentityEvent ):void
		{
                        txt.text = event.user.profile.email;
			Check();
		}
```

And stuck this function;

```
private function Check():void
		{
			txt.text = "Stuck here?";
			FirebaseFirestore.service.collection("Falcilar")
				.query()
				
				.addOnQuerySuccessHandler( function( snapshot:QuerySnapshot ):void
				{
					trace( "addOnQuerySuccessHandler");
					//var document:DocumentSnapshot = snapshot.getDocuments()[0];
					txt.text = "come here 2?";
					//tumFalcilariAl(snapshot);
					//falciMiDegilMi(snapshot);
					
					
					if(!Settings.falciMi)
						dispatchEvent(new NavigationEvent(NavigationEvent.CHANGE_SCREEN,{screen:"main"},true));
					else
						dispatchEvent(new NavigationEvent(NavigationEvent.CHANGE_SCREEN,{screen:"falci"},true));
				})
				.addOnQueryFailureListener( function( message:String ):void
				{
					txt.text = "ERRORR";
					trace( "addOnQueryFailureListener: " + message );
				});
		}
```

**Comment by ozgunsandal** [comment]
There is somehing like that in logs file;

`W/System.err(17521): java.lang.NullPointerException: Firestore component is not present.`

**Comment by marchbold** [comment]
Can you explain more where you code is having issues? What makes you think the `collection` call is the issue? That code seems to work without an issue here.

Would be helpful if you could post the logs as well.

**Comment by ozgunsandal** [comment]
[logs.txt](https://github.com/distriqt/ANE-Firebase/files/2674498/logs.txt)

**Comment by marchbold** [comment]
Hmm can you post your manifest additions? Looks as though you may have missed something from there. Did you place that service inside the application node in the manifest additions?

**Comment by ozgunsandal** [comment]
```
<service android:name="com.google.firebase.components.ComponentDiscoveryService" >
			<meta-data
        		android:name="com.google.firebase.components:com.google.firebase.firestore.FirestoreRegistrar"
       			android:value="com.google.firebase.components.ComponentRegistrar" />
    		<meta-data
       			android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
        		android:value="com.google.firebase.components.ComponentRegistrar" />
    		<meta-data
        		android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
        		android:value="com.google.firebase.components.ComponentRegistrar" />
		</service>
```

**Comment by ozgunsandal** [comment]
all manifest
[manifest.txt](https://github.com/distriqt/ANE-Firebase/files/2674511/manifest.txt)

**Comment by marchbold** [comment]
Hi,

You have added the Firebase manifest additions twice and only updated one of them to reflect the above. You need to remove the duplicate entries.

**Comment by ozgunsandal** [comment]
oh god i'm stupid. Thanks it works now.

**Comment by marchbold** [comment]
Not at all, manifests are complex and can get confusing. Glad its working for you now!
