### ISSUE TITLE
Error Firebase FCM Integration

### ISSUE THREAD

**Issue by rrohaill** [distriqt/ANE-Firebase#180]
I am getting an error while running code on ActionScript 3. 

Following is the error: "Your key was not able to be verified for the com.distriqt.Firebase native extension"

I have followed following issues but not working: 

https://github.com/distriqt/ANE-Firebase/issues/15

https://airnativeextensions.com/knowledgebase/faq/10

I have regenerated the key and ANE files are copied from. Double checked copied keys.

I am using firebase.ane, pushnotifications.ane, core.ane and playservices.base.ane

I receive exception after following the line of code:

Firebase.service.initialiseApp();

or

Firebase.service.initialiseApp( options );

I am initializing with the following line of code:

Core.init();

Firebase.init(APP_KEY);
PushNotifications.init(APP_KEY);
API_KEY is from distriqt account.

**Comment by marchbold** [comment]
If you have double checked your keys, the most common cause is using an older version of one of the support extensions. Make sure you have the latests versions:

https://github.com/distriqt/ANE-Firebase/wiki/Core---Add-the-extensions

**Comment by marchbold** [comment]
Are you sure the application id's match? 

Can you tell me what the application id you are using is?

**Comment by rrohaill** [comment]
Here it is: air.io.eliq.eliq.android

**Comment by marchbold** [comment]
Do you have `air.` in your application descriptor? 

What id did you use to create the key?

**Comment by maheenkhalid** [comment]
I am using ActionScript 3. I have the problem after Firebase.service.initialiseApp(options);

Error msg: Your key was not able to be verified for the com.distriqt.Firebase native extension.

Let me know what could be the solution to this.

**Comment by marchbold** [comment]
@maheenkhalid Apologies we missed your question here. You need to use your application key generated from our site (https://airnativeextensions.com/). You will need a valid license for this ANE to be able to create one.

**Comment by marchbold** [comment]
@rrohaill Not sure if you finally figured out your issue, but don't use the air prefix to generate your application key. You just need your AIR application id there not the Android java package name.
