### ISSUE TITLE
Firebase.service.initialiseApp() return false

### ISSUE THREAD

**Issue by maheenkhalid** [distriqt/ANE-Firebase#182]
I am using PushNotifications ANE for android app only. And when I try to initialise Firebase, I get false as result. I created Resource ANE to configure files. I have tried App IDs with and without "air." prefix. But nothing seems to be working. 

I have also referred to an old similar issue. But that user had an issue with iOS app. And this is purely android app.  

Do you have any idea what can be the problem?

**Comment by marchbold** [comment]
Can you post the logs from the device? They normally contain information about the failure reason.

https://airnativeextensions.github.io/tutorials/device-logs

**Comment by maheenkhalid** [comment]
It says that Firebase App not configured. But I am not sure what step I missed. Also I can see some issues regarding OneSignal. But I am not using that ANE. I am using com.distriqt.PushNotifications.FCM.ane

```
12-07 08:46:46.432 20161 20161 D com.distriqt.Firebase: FirebaseController::initialiseApp()
12-07 08:46:46.432 20161 20161 D com.distriqt.Firebase: FirebaseController::initialiseApp(): Init default
12-07 08:46:46.457 20161 20161 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.distriqt.extension.pushnotifications.onesignal.OneSignalController>
12-07 08:46:46.457 20161 20161 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.distriqt.extension.pushnotifications.onesignal.OneSignalController>
12-07 08:46:46.469 20161 20161 D com.distriqt.PushNotifications: ServicesController::setup( [fcm, , false] )
12-07 08:46:46.472 20161 20161 D com.distriqt.PushNotifications: ServicesController::authorisationStatus()
12-07 08:46:46.472 20161 20161 D com.distriqt.PushNotifications: ServicesController::hasAuthorisation()
12-07 08:46:46.481 20161 20161 D com.distriqt.PushNotifications: ServicesController::register() 
12-07 08:46:46.481 20161 20161 D com.distriqt.PushNotifications: FcmController::register()
12-07 08:46:46.481 20161 20161 D com.distriqt.PushNotifications: FcmController::ERROR::Firebase App not configured
12-07 08:46:46.483 20161 20161 D com.distriqt.PushNotifications: ServicesController::checkStartupData() 
```

Also this is how my extensions look:

```
<extensions>
        <extensionID>com.distriqt.PushNotifications</extensionID>
        <extensionID>com.distriqt.Core</extensionID>
        <extensionID>com.distriqt.androidsupport.V4</extensionID>
        <extensionID>com.distriqt.playservices.Base</extensionID>
        <extensionID>com.distriqt.Firebase</extensionID>
</extensions>
```

Also I just want to implement push notifications and nothing else.

**Comment by maheenkhalid** [comment]
Also I read somewhere that I do not need Firebase.ane if I am just need PushNotifications. So I tried by removing all Firebase ANE related code. It still gave me the same error.

**Comment by marchbold** [comment]
That's not correct. If you want to use FCM you need to include the Firebase ANE and your Firebase configuration custom resources ANE.

https://github.com/distriqt/ANE-Firebase/wiki/Setup---Configuration-Files#android-create-resource-ane

**Comment by marchbold** [comment]
If you need help creating the custom resources ANE send us your generated values.xml (airnativeextensions@distriqt.com) and we'll create it for you.

**Comment by maheenkhalid** [comment]
I just sent your files on email. Thanks a lot for your help :)

**Comment by marchbold** [comment]
We've built it and sent it back, let me know how it goes.

**Comment by maheenkhalid** [comment]
Hey Micheal,

Thank you for sending the new Customs Resources ANE. And sorry for being to get back to you. 

Unfortunately I am still getting the same error. I am beginning to think that probably there is some mistake in the code.

```
 try{
            Core.init(this.DISTRICT_API_KEY);

            var result:int = GoogleApiAvailability.instance.isGooglePlayServicesAvailable();
            if (result != ConnectionResult.SUCCESS) {
                if (GoogleApiAvailability.instance.isUserRecoverableError(result)) {
                    GoogleApiAvailability.instance.showErrorDialog(result);
                }
                else {
                    trace("Google Play Services aren't available on this device");
                }
            }
            else {
                trace("Google Play Services are Available");

                Firebase.init(this.DISTRICT_API_KEY);

                PushNotifications.init(this.DISTRICT_API_KEY);

                var service:Service = new Service(Service.FCM);

                service.channels.push(
                        new ChannelBuilder()
                                .setId( "test_channel" )
                                .setName( "Test Channel" )
                                .build()
                );

                //Call setup to configure
                PushNotifications.service.setup(service);

                PushNotifications.service.addEventListener( AuthorisationEvent.CHANGED, authorisationChangedHandler );

                this.checkAuthorisation();
            }
} catch (e: Error) {
            trace(e);
            trace(e);
}
```

Do you think there is something wrong here?

**Comment by marchbold** [comment]
Can you tell me at what point this code is failing?
