### ISSUE TITLE
FCM Push Notification Android Oreo Support

### ISSUE THREAD

**Issue by shaktisinghtanwar** [distriqt/ANE-Firebase#183]
Before purchasing this push notification FCM ANE, please confirm me that FCM push notification will work perfectly fine in android oreo or not ?

**Comment by marchbold** [comment]
This is not the Push Notifications ANE but the Firebase ANE. Please make sure you understand that FCM is provided through the Push Notifications ANE. 

Yes the PushNotifications ANE supports Oreo
