### ISSUE TITLE
I don't see my app in stream view

### ISSUE THREAD

**Issue by Dima107** [distriqt/ANE-Firebase#184]
If you are reporting a bug please make sure you fill out the following information, otherwise delete this template and ask your question.

##### Expected behaviour
My new version off App is showed in Stream VIew

##### Actual behaviour
I don't see my app in stream. But I can debug my app in DebugView.
I don't any functions that can set app version to Firebase. I think App version must be determinated automaticly.
Is it normal behaviur for non published version of existing App?

Is see obly one problem clientID=null
FirebaseOptions:[
[trace] 	apiKey=---------------------------------------------------------------
[trace] 	clientID=null
[trace] 	gcmSenderID=705694783682
[trace] 	googleAppID=1:705694783682:android:68923122316a6ac7
[trace] 	databaseURL=https://moto-x3m.firebaseio.com
[trace] 	storageBucket=moto-x3m.appspot.com
[trace] ]

I use custom resource ane. May be my build is bad
Can you build it for me? I'll send you values.xml

##### Environment 

- AIR SDK version 29,31: 
- Device OS many versions of Android: 
- Device version: many android devices

**Comment by marchbold** [comment]
Can you explain the issue a little more, I'm not quite sure I understand you?

The `null` value for client id is expected and nothing to be concerned about. Android doesn't return this value.
