### ISSUE TITLE
Doubt about the size of the com.distriqt.firebase.Crashlytics 20mb

### ISSUE THREAD

**Issue by megajogos** [distriqt/ANE-Firebase#185]
on the page:
https://distriqt.github.io/ANE-Firebase/Crashlytics%20-%20Add%20the%20extension

you said:

The only required additional ANE is the Crashlytics ANE located in this repository:
com.distriqt.firebase.Crashlytics : https://github.com/distriqt/ANE-Firebase

I find the lib Crashlytics is 20 MB!

https://github.com/distriqt/ANE-Firebase/blob/master/lib/com.distriqt.firebase.Crashlytics.ane

Isn't it too BIG?

Is there a way to put this lib without the need to use 20 Megabytes?

**Comment by marchbold** [comment]
That is the size of the ANE and is not a reflection of the additional size to your app. The ANE contains all the libraries for multiple platforms (iOS arm, iOS x86, Android arm, Android x86 etc..)

**Comment by megajogos** [comment]
ok, so I tested the size didn't grown.
