### ISSUE TITLE
verify phone number not working

### ISSUE THREAD

**Issue by dgurney75** [distriqt/ANE-Firebase#187]
I can't get the verification to work for phone. I'm using this but it always comes back as false. I've already added the FCM Push Notifications to the manifest and have both dev and prod environments setup. I've been at this for days and cannot figure out what i'm doing wrong. Please help. 

Im sending the phone number as a string using this format: "+15553334444"
```
FirebaseAuth.service.addEventListener(FirebaseAuthEvent.VERIFY_PHONE_NUMBER_FAILED, verifyPhoneNumber_failedHandler);
			FirebaseAuth.service.addEventListener(FirebaseAuthEvent.VERIFY_PHONE_NUMBER_CODE_SENT, verifyPhoneNumber_codeSentHandler);
			FirebaseAuth.service.addEventListener(FirebaseAuthEvent.SIGNIN_WITH_CREDENTIAL_COMPLETE, signInWithPhoneNumber_completeHandler);

var success: Boolean = FirebaseAuth.service.verifyPhoneNumber("+1" + phoneNumber);
trace("verifyPhoneNumber()=" + success);
```

##### Expected behaviour
Should call one of the 3 listeners above

##### Actual behaviour
Doesn't do anything but verifyPhoneNumber()=false

##### Environment 

- AIR SDK version: 32
- Device OS: iOS
- Device version: XR
- Development IDE: Animate CC
- Development OS: Mac

**Comment by marchbold** [comment]
Firstly ensure you have correctly called `init` with your application key, failing to do this can make this return false.

Then can you post the logs from the device? There may be an exception processing the number.
