### ISSUE TITLE
Storage download problem

### ISSUE THREAD

**Issue by ozgunsandal** [distriqt/ANE-Firebase#188]
Hello,
I'm uploading some images to firebase storage from different devices. But I can't download images uploaded from **some devices**.

Does the device resolution affect download?

And download task getBytes is 15 mb, image size is about 13 mb.
`var task:DownloadTask = reference.getBytes(1024*1024*15);`

**Comment by marchbold** [comment]
I doubt the device resolution would affect the download, however the available memory may. 

Can you get the logs from a device that fails?

**Comment by ozgunsandal** [comment]
[log.txt](https://github.com/distriqt/ANE-Firebase/files/2751358/log.txt)
