### ISSUE TITLE
Firebase purchase not working

### ISSUE THREAD

**Issue by gustavosanabio27** [distriqt/ANE-Firebase#19]
Hi!
I am trying to purchase the Firebase ANE to get my key but the page is unavailable. 

Thanks in advance!

**Comment by marchbold** [comment]
Hi,

As this ANE is still in development we haven't made it an active purchase on our site yet. However we are taking donations to the development. For any donations over US$ 50 we are currently giving a 3 year license for the ANE.

https://github.com/distriqt/ANE-Firebase

Cheers

**Comment by marchbold** [comment]
Just to make this easier we have added the purchase to our site, if you wish to subscribe to the extension and use the current feature set. 

http://airnativeextensions.com/extension/com.distriqt.Firebase

**Comment by gustavosanabio27** [comment]
Thanks!

**Comment by c3goui** [comment]
If we by the collection package did we have acces to test it, (getting the app in our application to generate de key?)

**Comment by marchbold** [comment]
Hi,

Yes you should be able to regenerate a key and the Firebase extension should be available then.
