### ISSUE TITLE
PlayServicesBase.service.version not returning version

### ISSUE THREAD

**Issue by Lydecker** [distriqt/ANE-Firebase#190]
Hi - I reported this for the Android Support ANEs a while back, but the same issue with the PlayServicesBase.ane

If I call
`PlayServicesBase.service.version`

on iOS it returns 
`1.iOS.1.0`

rather than a meaningful version number.

Please can this be fixed?
Thanks

**Comment by marchbold** [comment]
Sure, I'll get this into the next release of the GPS libs.

**Comment by Lydecker** [comment]
Thanks 👍

**Comment by marchbold** [comment]
Let me know if you are still having any issues.
