### ISSUE TITLE
Minimum iOS Version

### ISSUE THREAD

**Issue by Lydecker** [distriqt/ANE-Firebase#191]
Hi there,

Is there a minimum iOS version I should be specifying when using the latest Firebase ANE with Air32? - or for that matter a minimum iOS version I should be using with Air32 / your ANEs.....

I've never really been sure what the best practice is here?

Thanks

**Comment by marchbold** [comment]
We state v14+ on our [site](https://airnativeextensions.com/extension/com.distriqt.Firebase), but suggest you use v19+ unless you have any real need to support those older devices.

**Comment by Lydecker** [comment]
Thanks - was asking about iOS - but can clearly see the iOS requirements on the link you provided. It seems most ANEs require iOS8 as a minimum.

Thanks
