### ISSUE TITLE
Disable FirebaseCrashlytics?

### ISSUE THREAD

**Issue by Lydecker** [distriqt/ANE-Firebase#192]
With analytics, you can toggle on and off data collection with
`Firebase.service.analytics.setAnalyticsCollectionEnabled(false);`
and
`Firebase.service.analytics.setAnalyticsCollectionEnabled(true);`

Is it possible to DISABLE crashlytics ? I can only see:
`FirebaseCrashlytics.service.enableCollection()`

Which lets me turn them on, but not off....

**Comment by marchbold** [comment]
By default, Firebase Crashlytics automatically collects crash reports for all your app's users.

If you set a flag in your application descriptor to false: 
- iOS, info addition boolean: `firebase_crashlytics_collection_enabled`
- Android: meta-data value: `firebase_crashlytics_collection_enabled`

Then you can selectively enable the crash reporting for opt-in reporting.

There is no way to disable it once enabled as far as we are aware.
