### ISSUE TITLE
Analytics setUserProperty() Value Length

### ISSUE THREAD

**Issue by Lydecker** [distriqt/ANE-Firebase#194]
Hi here in the documentation:
![image](https://user-images.githubusercontent.com/12632602/51626439-70582d00-1f37-11e9-9d8d-2f100f5f8858.png)

It says that a user property value is max 36 chars. Do I need to make sure I'm not putting in more than 36chars to that function - or does the ANE / Firebase automatically truncate anything greater than 36 chars?

Thanks

**Comment by marchbold** [comment]
We do not truncate or change values before passing to the Firebase SDK, however you should expect the SDK to truncate them or potentially fail if your properties are too long.

**Comment by Lydecker** [comment]
Useful to know - I'll make sure I truncate any values that could exceed 36. Cheers
