### ISSUE TITLE
Can Analytics setUserID() be used to UPDATE a user's ID?

### ISSUE THREAD

**Issue by Lydecker** [distriqt/ANE-Firebase#195]
![image](https://user-images.githubusercontent.com/12632602/51628883-173fc780-1f3e-11e9-858e-5d1e36364f2c.png)

I know you can change/update a User Property Value mid way through using an App (using setUserProperty(), but can you change a userID midway through?

e.g a user logs into your app - the setUserID() is called to set their ID. An hour later, the user swaps accounts in the app (perhaps by logging out of one account and login in with another) - can you call the setUserID() again with their new ID to associate their actions going forward with the new account they are logged into?

The same question goes for - `FirebaseCrashlytics.service.setUserIdentifier()` - can this be updated mid app? 
Thanks

**Comment by marchbold** [comment]
Yes

setting the user id will change the id used in any further analytics data.

**Comment by Lydecker** [comment]
Thanks
