### ISSUE TITLE
Custom Event's Parameters Not Being Tracked - iOS

### ISSUE THREAD

**Issue by Lydecker** [distriqt/ANE-Firebase#197]
Hi - using iOS 12.1.2 with Air 32 and the following ANEs:
Core Version: 3.2.244
Firebase Version:  2.4.072
Firebase Crashlytics Version:  2.4.072
PlayServices Base Version: 16.0.5

User Properties are being tracked fine - so we know Firebase is being initialised correctly and communicating fine with the console.

However we can't get ANY parameters for custom events to work.

Here is an example of our custom event 'refresh':
```
 if (Firebase.isSupported) {
                var event:EventObject = new EventObject();
                event.name = "refresh";            
                event.params["manual"] = 1;
                event.params["area"] = "TestArea";
                event.params[Params.VALUE] = 88;
                Firebase.service.analytics.logEvent( event );
            }
```

When we launch the app and call the above code 7 times from browsing - the EVENT itself is logged as 'refresh' however the parameters (custom AND Params.VALUE) are not recorded. We can't get any parameters set using  `event.params[....` to log back to the console.

Here is what our console looks like for the event:
![image](https://user-images.githubusercontent.com/12632602/51856853-a70fb800-2328-11e9-8c14-75c4f5a98690.png)

The 'Parameter name' drop down list is empty in the above screenshot when clicked.

I assume this is a bug with the ANE?

**Comment by marchbold** [comment]
In order to use custom parameters you need to edit the parameters for an event and add them to your parameter list.

https://support.google.com/firebase/answer/7397304?hl=en&utm_id=ad&authuser=1

![screen shot 2019-01-29 at 09 57 31](https://user-images.githubusercontent.com/442356/51874369-635e9200-23ac-11e9-9b95-3c4fe42374cb.png)
![screen shot 2019-01-29 at 09 57 55](https://user-images.githubusercontent.com/442356/51874372-66598280-23ac-11e9-9495-117084f01584.png)

**Comment by Lydecker** [comment]
Hi - sorry, we thought we included these photos in the initial post - We have already had the custom parameters set up in the console from day one:

![image](https://user-images.githubusercontent.com/12632602/51894016-897d3580-239e-11e9-866f-03ff401497f4.png)


![image](https://user-images.githubusercontent.com/12632602/51893998-7b2f1980-239e-11e9-91b0-1488be4b9915.png)


As you can see the Events are being passed to firebase, but not the parameter VALUES attached to it..

In the dashboard for the refresh event - if we look at the area PARAMETER panel - it says the data for this parameter is not set:

![image](https://user-images.githubusercontent.com/12632602/51894146-e547be80-239e-11e9-855e-86bc88e97ec0.png)

**Comment by marchbold** [comment]
Are you sure you are passing a value in for this event? We haven't had any issues getting values through.

**Comment by Lydecker** [comment]
100%

This is the (only) event code we are using:
 ```
 if (Firebase.isSupported) {
                var event:EventObject = new EventObject();
                event.name = "refresh";            
                event.params["manual"] = 1;
                event.params["area"] = "TestArea";
                event.params[Params.VALUE] = 88;
                Firebase.service.analytics.logEvent( event );
            }
```

Has this definitely been verified to work on air32 with the latest firebase ane?

Thanks

**Comment by Lydecker** [comment]
sigh.... resolved....

Sorry - it was the same issue as #198 - there was a dependency between the bundle ID on the firebase main console and the app. Strange how screen_view events with parameters made it through fine, and custom events made it through fine. It was just values of event parameters that didn't..


Sorry to have bothered you!

**Comment by marchbold** [comment]
Glad to hear, it is very odd that you got part of the analytics with a configuration error. It's only ever been an obvious "not working" scenario in the past for me. Will have to make a note of that.

**Comment by SHDgames** [comment]
@Lydecker 

Can you show a sample of your code? I am having issues with this as well.... 


My code :

```
event.name = "Mission";
event.params["Started"] = "Safehouse";
event.params["Win"] = "Safehouse";	

Firebase.service.analytics.logEvent( event );
```

In my Firebase Analytics Console - the events are triggering for "Mission" with parameters Started and Win, as text parameters - but there is nothing registered for their event count, and no "Safehouse" parameter is shown anywhere for the events.

Any help would be great - thanks !

**Comment by Lydecker** [comment]
The issue for me was the bundle ID in the Firebase Console Global Settings was not identical to the the ID in my app descriptor. 

Is your project IOS or Android?

**Comment by olowoshiai** [comment]
Hi! Can anyone help me with this exact same issue. I have compared my project's Bundle ID, Project ID, AppID in the Google pList and it matches the information in the project settings on Firebase. I can see the events been sent in the debug view (I'm sending it from an iOS simulator). 

I am just confused as to why the "Event Count" is 13 but the actual parameter graph is blank and count is 0. Note, this is after enabling parameter reporting and waiting over 24hrs. PLEASE HELP! Thanks!!

FYI, i'm using Xamarin and this is how I'm sending the event:
var dict = new Dictionary<object, object>();
				dict["ActionType"] = actionType;
				dict["ActionName"] = name;
				dict["UserType"] = GetUserType();
				Firebase.Analytics.Analytics.LogEvent("Event", dict);

<img width="1360" alt="Screen Shot 2019-08-08 at 3 55 34 PM" src="https://user-images.githubusercontent.com/15255929/62737261-fda33080-b9f4-11e9-9316-c485834b4d5b.png">
