### ISSUE TITLE
dSYM only in Release?

### ISSUE THREAD

**Issue by Lydecker** [distriqt/ANE-Firebase#199]
Hi - the 'how to get your dSYM' section of the documentation (Wiki) is blank.

I assume the dSYM file is packaged in the IPA?

Is this ONLY for release builds? As My IPA (which is not a release build) has no dSYM file in it.

Thanks

**Comment by marchbold** [comment]
Hi,

Getting the dsym seemed to have changed with the recent versions of AIR so we took down the outdated documentation. We haven't had a chance to figure out how to get it as yet. Probably a good question for the adobe / starling forums?

**Comment by Lydecker** [comment]
Okay - been doing some reading up.

Apparently since AIR 26, Adobe added a new command to the adt `-embedBitcode yes`

If you set this to `yes` for a release build, then upload the IPA to via iTunesConnect, you can then download the dSYM from iTunesConnect. 

I haven't tried this yet - but what I'm reading says that any ANEs used in the IPA must also have been compiled with bitcode.  Have they?

THanks

**Comment by marchbold** [comment]
Ah interesting, do you have a reference at all? We had noticed the documentation was wrong around 26 so that would reinforce our issues.

Yes all our ANEs are compiled with bitcode enabled.

**Comment by Lydecker** [comment]
This is probably the most encouraging link I've found:

https://docs.fabric.io/apple/crashlytics/missing-dsyms.html

Like I say - I haven't tried it yet - but will let you know how I get on.

Thanks

**Comment by marchbold** [comment]
What makes you think the `embedBitcode` flag changes the dsym output? 

Or is it just that the app store generates it for you if you supply bitcode?

**Comment by Lydecker** [comment]
Correct - the app store generates it, but only if you supply bitcode. 

Or is that nonsense?!

**Comment by marchbold** [comment]
No that's correct as far as I'm aware. 

Just thought we should be able to generate the dsym's without using bitcode as well somehow as we did in the past.

**Comment by Lydecker** [comment]
I'm struggling to get my ipa compiled with bitcode.

If I add this switch to the ADT in IntelliJ:
![image](https://user-images.githubusercontent.com/12632602/52382933-29a61f00-2a6f-11e9-9a69-232d58f7cc6c.png)

I end up with the following error message pretty much as soon as I package the project.

![image](https://user-images.githubusercontent.com/12632602/52382956-47738400-2a6f-11e9-84ed-a2db18003789.png)


If I change the new switch from 'yes' to 'no' - same error.

If I remove the switch - no issue at all.

Any ideas?

Thanks

**Comment by marchbold** [comment]
That would indicate it's in the wrong position in the adt command line. Is that intelliJ? I found you have to use the command line for it to work as IntelliJ didn't put it in the correct position.

**Comment by Lydecker** [comment]
Had a feeling it was to do with the order of the arguments.

OK - I built a release manually with the adt (or tried to), however unfortunately it appears that your Crashlytics ANE has not been compiled with bitcode. This is the error I get:

`ld: bitcode bundle could not be generated because 'C:\Users\Me\AppData\Local\Temp\f9bbff5b-966d-4e49-9063-de9b18f3bffa\libcom.distriqt.firebase.Crashlytics.a(DTFB_CL_Controller.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
ld: bitcode bundle could not be generated because 'C:\Users\Me\AppData\Local\Temp\f9bbff5b-966d-4e49-9063-de9b18f3bffa\libcom.distriqt.firebase.Crashlytics.a(DTFB_CL_Controller.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
Compilation failed while executing : ld64`

This error marries up with the AIR documentation - saying it is caused if the ANE author has failed to compile the ANE with bitcode.

Please could you give me a bitcode compiled Crashlytics ANE file to try?

Thanks

**Comment by marchbold** [comment]
Try this version:

https://www.dropbox.com/s/nohc6whgxmmh5ut/com.distriqt.Firebase.v2.4.074.zip?dl=0

**Comment by Lydecker** [comment]
Great - that got rid of that error.

Next up - the Calendar ANE please  :)

`ld: bitcode bundle could not be generated because 'C:\Users\Me\AppData\Local\Temp\ccc2e239-8d5c-4706-92df-bd52e8c02bd2\libcom.distriqt.Calendar.a(DTCAEventDispatcher.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7`

Thanks

**Comment by Lydecker** [comment]
Hi - thanks for providing the bitcode version of Calendar ANE.

We now have an issue with com.distriqt.playservices.Base.ane not being compiled for bitcode

```
ld: bitcode bundle could not be generated because 'C:\Users\zach\AppData\Local\Temp\c78e8643-bbee-4eb6-a847-1c8eb47378cb\libcom.distriqt.playservices.Base.a(PlayServicesBase.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
ld: bitcode bundle could not be generated because 'C:\Users\zach\AppData\Local\Temp\c78e8643-bbee-4eb6-a847-1c8eb47378cb\libcom.distriqt.playservices.Base.a(PlayServicesBase.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
Compilation failed while executing : ld64
```

Please can you provide a bitcode compiled version of this ANE?

Thanks

**Comment by marchbold** [comment]
Oh right, you can probably just drop the GPS ANEs out of your build for the moment?

Seems building with bitcode enabled isn't enough, they need to have some flags set as well which we haven't set on all our ANEs currently.

**Comment by Lydecker** [comment]
If I drop the GPS ANE out and remove all references to it I get this:

```
ld: can't create buffer of 236997528 bytes for output for architecture armv7
ld: can't create buffer of 236585732 bytes for output for architecture arm64
Compilation failed while executing : ld64
```

**Comment by marchbold** [comment]
Sounds like you are running out of memory or something ?

**Comment by Lydecker** [comment]
Agreed, but I don’t understand why - I don’t run out of memory / get that message when it’s a non bitcode build.

The build machine is 32Gb or RAM.

It can’t have anything to do with the IDE as it’s being build with ADT outside of the IDE....

Hmmmm....

**Comment by Lydecker** [comment]
So I tried building it on a MAC - compiles fine with bitcode - no memory issues (and that is with a 4Gb mac vs my 32Gb windows). Perhaps it is a Java issue?

Please can you release a GPlayServices ANE which is bitcode compiled so I can upload the bitcode ipa to itunes connect and see if I can download a dsym?

Thanks!

**Comment by marchbold** [comment]
You should be able to just remove the GPS ANEs. They aren't needed for iOS.

**Comment by Lydecker** [comment]
Ahh - gottya, ok - i’ll try that, thanks

**Comment by Lydecker** [comment]
Ok - so my findings are this - 

Compile with bitcode and upload to itunesconnect allows you to manually download the dsym from itunesconnect at any time. I can compile an ipa with bitcode on OSX, but not Windows (due to the buffer issue above).

However, what’s also interesting is that if I compile without bitcode (ie turned off) on OSX, it auto dumps the dsym file in the same folder as the ipa! (No such luck for Windows though).

**Comment by Lydecker** [comment]
So if I compile the app with bitcode enabled, and the Calendar ANE version 3.1.032 (the old non bitcode one) - it fails as expected.

However if I compile it with bitcode disabled on OSX - it compiles fine AND generates a dsym file too/still!

**Comment by Lydecker** [comment]
Have it working on Windows now.

I didn't twig that my adt was beeing called from the Java version installed by IntelliJ - therefore I updated IntelliJ from 2018.1.1 to 2018.3.4. Now it compiles bitcode fine on windows with no buffer error!

It must have updated the Java at this location: 

`C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.4\jre64\bin\java.exe`

**Comment by marchbold** [comment]
What version of the AIR SDK are you using for these final tests? Adobe must have fixed the dsym export because that was definitely failing in our tests a few months ago.

Glad to hear its working though!

**Comment by marchbold** [comment]
I'll make sure we get those additional build flags added to all our ANEs for complete bitcode support.

**Comment by Lydecker** [comment]
I was using Air32 - however still potentially issues on macOS.

Even though a DSYM folder is created on macOS for any build -  the contents of the DSYM folder is very different (structure) to that of the itunesconnect one downloaded for a bitcode build.

I also couldn't get the Firebase Crashlytics console to use the uploaded DSYMs from Air's output on MAC to decode the crash reports (making sure the app version that created the crash married up with the dsym build from air). However itunesconnect ones uploaded work great.... I ended up testing the Crashlytics with TestFlight on itunesconnect.

**Comment by marchbold** [comment]
Well at least we have a method that's working now, which is great news! Thanks for working through this! 

When I have some time I'll look into what's produced by AIR currently and see if we can get Adobe to resolve it correctly.

**Comment by Lydecker** [comment]
No worries - hope this helps others going forward. Thanks for your help!
