### ISSUE TITLE
Firebase Wiki - Clearer GPS Requirement Documentation

### ISSUE THREAD

**Issue by Lydecker** [distriqt/ANE-Firebase#201]
Hi - Please can you update the Firebase Wiki / Guide to make it more clear that Google Play Services ANE is only required for Android? Currently the way the page (https://github.com/distriqt/ANE-Firebase/wiki/Core---Add-the-extensions) reads implies that the ANE is needed for both iOS and Android.

Might just save some confusion for others in the future.

Thanks!

**Comment by marchbold** [comment]
Will do, we had originally considered this, but left it to reduce the complexity of integration. However we will add some notes to this effect.
