### ISSUE TITLE
Crashlytics - understanding Non-fatal reports

### ISSUE THREAD

**Issue by Lydecker** [distriqt/ANE-Firebase#202]
Hi, now that I have crashlytics returning data - a few questions please:

1. I assume `recordError()` triggers a 'Non-fatal' report in the Firebase Console?

2. If I use `log()` I gather this builds up a set of ongoing logs UPTO 64Kb (then loops around and overwrites so the trail of logs so they are never bigger than 64Kb) - however are these logs ONLY sent to the Firebase Console if either `recordError()` is called OR the app full on crashes?

Thanks

**Comment by marchbold** [comment]
Probably best to consult the google documentation on the details of when they send the logs / data. This will be handled by the SDK and independent of the ANE code. 

Notes:

1. Yes recording an error is referred to as a non-fatal crash 
2. Logs are generally recorded to be attached to a crash report so you can see the state of the app as it crashed (i,e, what happened leading to the crash). You won't get the complete log since launch, just the recent log up to the limit.

**Comment by Lydecker** [comment]
So I found this:

> When you log an NSError, though, the app does not immediately terminate. Because we will only send the logged error report on the next app launch, and because we must limit the amount of space allocated for logs on disk, it is possible to log enough after an NSError is recorded so that all relevant logs are rotated out by the time we send the report from the device.

Not sure how I feel about that. That means that I can generate a nonfatal crash - but may not see it for 48 hours as the app may not be pushed to relaunch by the OS until that time frame. In that 48 hours, the details of the nonfatal log may have been overridden.... Hmmmm

**Comment by marchbold** [comment]
Where did you find that? Is that referencing the automatic error logging? 

They may simply be saying that if you log a lot of data that in the time between the error and the application terminating you may cause the log to rotate through.

**Comment by Lydecker** [comment]
It was from the firebase api documentation.

It’s referencing when the user makes a manual non-fatal call / report.

But yes your second paragraph is correct.

I’ve also figured out that if I want to make a non fatal call because my app has ended up in a state it shouldn’t be in, but it hasn’t crashed and it’s not the result of an actual error being thrown - I can just use log() then create a new as3 Error object - and pass the empty Error object to the recoredError() function to make sure the logs make themselves to the console the next time the app restarts...
