### ISSUE TITLE
FCM with iOS Push Notifications

### ISSUE THREAD

**Issue by cevansOTBS** [distriqt/ANE-Firebase#204]
Hello,

I'm doing the FCM / iOS Push Notification implementation. It seems everything is setup correctly (APN certs and everything). The iOS device gets the permission prompt to allow notifications and I also
receive the Firebase registration token. However on the registration call, the RegistrationEvent stops at "registering". I don't get any further errors or status messages. The iOS device also isn't receiving any
push notifications when I test the app. So even though I'm getting the registration token from Firebase, I suspect something is going wrong with the communication to the Apple APN server which is why I'm not getting the "success" registration event message.

So do any idea why it's stopping at the "registering" event? Do you know of any cases where this occurs or how best to troubleshoot this? I'm using dev APN .12 certs and I've updated the <entitlements> in the app.

Also I use FCM for Push Notifications on Android and everything works fine. I'd like to use FCM with iOS, so I can utilize the same app server & code.

Thanks

**Comment by marchbold** [comment]
Firstly make sure you are calling Core.init in your application and have you correctly packaged the Firebase configuration plist file with your application? 

Are you using any ANEs from other providers? They sometimes can interfere with these processes.

It is often helpful if you can post the logs:

https://airnativeextensions.github.io/tutorials/device-logs

**Comment by cevansOTBS** [comment]
Looks like Core.init was the issue. The app uses about 15 ANEs , all distriqt ANEs. What's odd is that I hadn't encountered any issues previously with Push Notifications on Android or any of the other ANEs even though Core hadn't been initialized. Wish there was some error status message indicating the need to initialize the Core ANE. Would have saved me a lot of time. 

Either way, glad it's working now.

Thanks

**Comment by marchbold** [comment]
Hi,

`Core.init()` sets up the iOS application delegate overrides which is what causes the issue you mentioned. 

Not sure how easy it is for us to implement checks in every ANE that utilises the overrides but it's a good suggestion and something we'll consider in the future.

**Comment by marchbold** [comment]
Glad it's working for you now!
