### ISSUE TITLE
AIR flair?

### ISSUE THREAD

**Issue by Lydecker** [distriqt/ANE-Firebase#205]
Hi - what is 'AIR flair' please?

It is mentioned here: https://github.com/distriqt/ANE-Firebase/wiki/Setup---Create-a-Firebase-Project

![image](https://user-images.githubusercontent.com/12632602/52891786-20ab0100-3185-11e9-884e-e01c6eb25c56.png)

THanks

**Comment by marchbold** [comment]
"AIR flair" is the `air.` prefix appended to your application id automatically on Android to create your Android application package name. 

So an AIR application with an id `com.distriqt.test` creates and Android application package name `air.com.distriqt.test`.

You can remove this `air.` prefix by setting the `AIR_NOANDROIDFLAIR` environment variable within your build environment. 

This is what we are referring to here.

**Comment by Lydecker** [comment]
Good thing I asked this before publishing!

So if I’m using a windows machine (IntelliJ IDE), do I literally add an Environment Variable to the windows OS of AIR_NOANDROIDFLAIR?

**Comment by marchbold** [comment]
As long as it's set within the environment you are building your application.  A global environment variable definitely should cover it.

Just be aware that changing this will change your android package name and hence anything that you have tied to this package name (Firebase config / Google Play Game services / Play store entries). 

So only change it if you haven't configured anything relying on it, otherwise you'll end up in a world of difficult migrations.

**Comment by Lydecker** [comment]
Got it - thanks for the info!

If I then up with an iOS app and and Android app with the same bundle id -as a result of this - I assume that causes obvious conflicts / issues that you are aware of with app stores / services?

Thanks

**Comment by marchbold** [comment]
The package name of an Android app and the bundle id iOS app are not tied together. They are generated from your AIR application id. 

There is no reason removing the Android only AIR flair should affect your iOS application unless you change the AIR application id in your application descriptor.

**Comment by Lydecker** [comment]
(I meant to type 'no obvious conflicts' above - sorry!)

What I'm trying to get to the bottom of - previously I have always had air.com.myapp1 for android and com.myapp1 for iOS for a given app.

If with the next app I create I remove air flair - I will end up with a package name of com.myapp2 on android and a bundle id of com.myapp2 on iOS. Just want to check that having an identical package name and bundle id don't cause any issues when they are 'in the wild'. But as you say that bundle ids are treated as a separate unique identifiers to package names - I assume there would be no issues... thanks!

**Comment by marchbold** [comment]
Yep, completely different ecosystems and not related at all. There is no issue being the same or different.

**Comment by marchbold** [comment]
Just be aware, that if you have some apps built with the air prefix and are still maintaining them, that you'll need to remove the environment variable to build those in the future.

**Comment by Lydecker** [comment]
Yea - that gear was just turning in my head - thanks for the heads up!
