### ISSUE TITLE
Invalid Input

### ISSUE THREAD

**Issue by mstcode** [distriqt/ANE-Firebase#206]
Hi,

I compile my application for IOS, but I get an error. I'm sending the error screen attached. Where am I making a mistake?
![screen shot 2019-03-04 at 15 39 07](https://user-images.githubusercontent.com/16031882/53784617-e2ecfd00-3f26-11e9-8119-e17e40d51d93.png)

Mac mini 2011
Mac Os Sierra (10.12.6)
Adobe Animate CC
Adobe AIR SDK (32.0.0.89)

All add-ons used in the application
Dialog.ane
FPUniqueld.ane
Scanner.ane
CameraUI.ane
Share.ane
PDFReader.ane
Core.ane
PushNotifications.Onesignal.ane
Firebase.ane

**Comment by marchbold** [comment]
Please make sure you are using the latest version of all our ANEs, in particular the Core ANE.

**Comment by mstcode** [comment]
Totally my fault, I should have checked the latest versions. Now everything works fine. Thank you for your help.

**Comment by marchbold** [comment]
Glad it was an easy fix! 👍
