### ISSUE TITLE
dSYMS no longer on iTunesConnect?

### ISSUE THREAD

**Issue by Lydecker** [distriqt/ANE-Firebase#208]
Following on from #199, it appears that as of this month dSYM files are no longer available to download through itunes connect for new IPAs uploaded :(

I can't find any information about Apple having changed anything in itunesconnect, and I haven't changed the AIR version I was using successfully before. 

I have tried building (and uploading ipas) with bitcode on Windows and macOS - with AIR32 build 89 and build 103....

Would be interested if someone else could confirm they no longer have a dSYM download link anymore for new uploads to itunesconnect.

Thanks

**Comment by Lydecker** [comment]
This seems to be a recent known issue in the Apple forums:
https://forums.developer.apple.com/thread/114655?q=dsym*

**Comment by Lydecker** [comment]
Apple seemed to have changed something and this is now working again,

**Comment by marchbold** [comment]
Yeah we noticed this recently too, not sure what Apple are doing with this.
