### ISSUE TITLE
FirebaseCrashlytics.service.enableCollection() Crashes App When Called

### ISSUE THREAD

**Issue by Lydecker** [distriqt/ANE-Firebase#209]
Using Air 32 (tried builds 89 stable, and 103 beta).
Using iPhone X iOS 12.1.2
ANE Versions:
[trace] Core Version: 3.3.253
[trace] Firebase Version:  2.4.078
[trace] Firebase Crashlytics Version:  2.4.078

I have an issue that I can't pin down.

When I call `FirebaseCrashlytics.service.enableCollection();` it CRASHES (the app quits) my app, but ONLY for an App Store Distribution build/release. I have no issues on Android.

Firebase is initialising fine, and even if I init all the firebase + crashlytics stuff, then attach `FirebaseCrashlytics.service.enableCollection();` to a button - when I press the button - the app quits - so it's not a timing initialisation issue.

The Firebase settings are being imported correctly as I've used `Firebase.service.getOptions()` and the values are being reported correctly. Firebase Cloud Messaging and Analytics are working an being reported correctly.

If I build a distribution version for Ad Hoc - everything works fine. If I do any sort of Development build - everything works fine. It is ONLY when I Build the app for the App Store. 

This is a pain as it means there is no way to get any logs out!

Am I missing some permission or something in my descriptor? 

Here is my Deployment App Descriptor:
```
<?xml version="1.0" encoding="utf-8"?>
<application xmlns="http://ns.adobe.com/air/application/32.0">

    <id>REMOVED</id>

    <filename>REMOVED</filename>

    <name>REMOVED</name>

    <versionNumber>0.1.12</versionNumber>

    <copyright>REMOVED</copyright>

    <extensions>
        <extensionID>com.distriqt.Core</extensionID>
        <extensionID>com.distriqt.Dialog</extensionID>
        <extensionID>com.distriqt.NetworkInfo</extensionID>
        <extensionID>com.distriqt.PDFReader</extensionID>
        <extensionID>com.distriqt.Message</extensionID>
        <extensionID>com.distriqt.Calendar</extensionID>
        <extensionID>com.distriqt.Application</extensionID>
        <extensionID>com.distriqt.PushNotifications</extensionID>
        <extensionID>com.distriqt.Firebase</extensionID>
        <extensionID>com.distriqt.firebase.Crashlytics</extensionID>
        <extensionID>com.distriqt.LocalAuth</extensionID>
        <extensionID>com.distriqt.NativeWebView</extensionID>
        <extensionID>com.distriqt.Vibration</extensionID>
    </extensions>


    <initialWindow>

        <content>SWF file name is set automatically at compile time</content>

        
        <visible>true</visible>

  
        <autoOrients>false</autoOrients>
        <fullScreen>false</fullScreen>

        <renderMode>auto</renderMode>

    </initialWindow>

    <icon>
        <image29x29>/assets/appIconsiOS/Icon-App-29x29@1x.png</image29x29>
        <image40x40>/assets/appIconsiOS/Icon-App-20x20@2x.png</image40x40>
        <image50x50>/assets/appIconsiOS/Icon-Small-50x50@1x.png</image50x50>
        <image57x57>/assets/appIconsiOS/Icon-App-57x57@1x.png</image57x57>
        <image58x58>/assets/appIconsiOS/Icon-App-29x29@2x.png</image58x58>
        <image60x60>/assets/appIconsiOS/Icon-App-20x20@3x.png</image60x60>
        <image72x72>/assets/appIconsiOS/Icon-App-72x72@1x.png</image72x72>
        <image76x76>/assets/appIconsiOS/Icon-App-76x76@1x.png</image76x76>
        <image80x80>/assets/appIconsiOS/Icon-App-40x40@2x.png</image80x80>
        <image87x87>/assets/appIconsiOS/Icon-App-29x29@3x.png</image87x87>
        <image100x100>/assets/appIconsiOS/Icon-Small-50x50@2x.png</image100x100>
        <image114x114>/assets/appIconsiOS/Icon-App-57x57@2x.png</image114x114>
        <image120x120>/assets/appIconsiOS/Icon-App-40x40@3x.png</image120x120>
        <image144x144>/assets/appIconsiOS/Icon-App-72x72@2x.png</image144x144>
        <image152x152>/assets/appIconsiOS/Icon-App-76x76@2x.png</image152x152>
        <image167x167>/assets/appIconsiOS/Icon-App-83.5x83.5@2x.png</image167x167>
        <image180x180>/assets/appIconsiOS/Icon-App-60x60@3x.png</image180x180>
        <image512x512>/assets/appIconsiOS/iTunesArtwork@1x.png</image512x512>
        <image1024x1024>/assets/appIconsiOS/iTunesArtwork@2x.png</image1024x1024>
    </icon>
    <iPhone>
        <!-- A list of plist key/value pairs to be added to the application Info.plist -->
        <InfoAdditions>
            <![CDATA[
            <key>UIDeviceFamily</key>
            <array>
                <string>1</string>
            </array>
              <key>MinimumOSVersion</key>
            <string>9.0</string>

            <key>CFBundleURLTypes</key>
            <array>
                <dict>
                  <key>CFBundleURLName</key>
                  <string>REMOVED</string>
                  <key>CFBundleURLSchemes</key>
                  <array>
                    <string>REMOVED</string>
                  </array>
                </dict>
            </array>

            <key>NSCalendarsUsageDescription</key>
	        <string>Access to calendar is required to save events.</string>


            <key>NSFaceIDUsageDescription</key>
            <string>FaceID required to unlock app.</string>

            <key>FirebaseAppDelegateProxyEnabled</key>
            <false/>

            <key>firebase_crashlytics_collection_enabled</key>
            <false/>
            ]]>
        </InfoAdditions>

        <!-- A list of plist key/value pairs to be added to the application Entitlements.plist -->
        <Entitlements>
            <![CDATA[


            <!-- APNS DIST-->
		<key>get-task-allow</key>
        <false/>

		<key>aps-environment</key>
		<string>production</string>

        <key>application-identifier</key>
		<string>REMOVED</string>

		<key>keychain-access-groups</key>
		<array>
			<string>REMOVED.*</string>
		</array>



		<!--END APNS -->


            ]]>
        </Entitlements>
        <requestedDisplayResolution>high</requestedDisplayResolution>

    </iPhone>



</application>
```

Here is my init (which is fine):

```
try {
                Firebase.init(distriqtKey);
                if (Firebase.isSupported) {
                    trace("Firebase Version:  " + Firebase.service.version);
                    trace("FIREBASE INIT: " + Firebase.service.initialiseApp());
                    Firebase.service.analytics.setAnalyticsCollectionEnabled(false);
                    trace(Firebase.service.getOptions());
                    FirebaseCrashlytics.init(distriqtKey);
                    trace("Firebase Crashlytics Version:  " + FirebaseCrashlytics.service.version);
                    trace("Crashlytics Supported: " + FirebaseCrashlytics.isSupported)


//The next line will crash on release build for app store
   //FirebaseCrashlytics.service.enableCollection();
                

                }
            } finally {

            }
```

What exactly does `FirebaseCrashlytics.service.enableCollection();` do - does it communicate out to Firebase over the internet for the enable collection?

I'm stumped - and help would be appreciated. Thanks

**Comment by marchbold** [comment]
Can you post the console log and crash report? 

`enableCollection` basically enables the crash reporting disabled by the `firebase_crashlytics_collection_enabled` flag. 

Have you tried removing that flag from the info additions? Does it crash then as well?

**Comment by Lydecker** [comment]
Hi, thank you for the rapid response.

I have removed         ```
<key>firebase_crashlytics_collection_enabled</key>
            <false/>
```

from the descriptor - rebuilt as an app store released, and uplaoded to apple.

The app launches fine and does not crash on launch. There is obviously no call to `FirebaseCrashlytics.service.enableCollection();` anymore.....

The issues is I don't always want to collect crash info - only if a specific user is logged in - which is why I need to make use of the `firebase_crashlytics_collection_enabled` flag.

I didn't realise I could get logs out for App Store builds. I'll add back in the      ```
<key>firebase_crashlytics_collection_enabled</key>
            <false/>
``` and call `FirebaseCrashlytics.service.enableCollection();` and get you the logs in a few minutes. Thanks

**Comment by Lydecker** [comment]
OK - have done the above. (also added in `FirebaseCrashlytics.service.setDebug( true );` after the firebase init() )

The logs are attached. Includes everything from launching the app - to clicking the button attached to `FirebaseCrashlytics.service.enableCollection();` to the app quitting.

I did a sync with itunes, but there are no .crash files for my app after February - implying it's not 'crashing' but just quitting the app?

Logs here: 
[lydecker_ios_log2.log](https://github.com/distriqt/ANE-Firebase/files/2964055/lydecker_ios_log2.log)

Please let me know your thoughts. thanks

**Comment by Lydecker** [comment]
This looks like the magic line:

`*** Terminating app due to uncaught exception 'FABException', reason: '[Fabric] Value of Info.plist key "Fabric" must be a NSDictionary.'`

no idea what it means

**Comment by marchbold** [comment]
Are you initialising your Firebase App? 

```as3
Firebase.service.initialiseApp();
```

**Comment by Lydecker** [comment]
Wait a minute.

Is it because I have:

`trace("FIREBASE INIT: " + Firebase.service.initialiseApp());`

and trace() commands are stripped out of a App Store build?

**Comment by marchbold** [comment]
Hmm potentially. Definitely would suggest pulling it out of there. The only way I've been able to replicate that crash is if you haven't called `initialiseApp`.

**Comment by Lydecker** [comment]
Let me try that tonight and get back to you.

I defiantly had an app store release working last month - and I added the trace around the init recently....

On another note - is:

```
<key>firebase_crashlytics_collection_enabled</key>
            <false/>
```

Required so that the firebase settings can be init before collection - or is this optional. If I always want to collect crashlytics data - can I remove that descriptor entry and everything will work fine after calling:
```
Firebase.init(distriqtKey);
Firebase.service.initialiseApp()
FirebaseCrashlytics.init(distriqtKey);
```

?

Thanks

**Comment by Lydecker** [comment]
Taking it out of the trace() solved the issue. Interesting how only the AppStore provisioning profile ignores the trace commands.

So can i remove the flag in the app descriptor then crashlytics will work as soon as ive initialised Firebase?

**Comment by marchbold** [comment]
Yeah this will be the difference with the interpreter mode. 

Regarding the flag, I highly recommend leaving it in and enabling it in your app. Allows you to respond to GDPR privacy type issues.

**Comment by Lydecker** [comment]
I’ve covered the gdpr side in the privacy policy / terms of sevice. I was asking more from a functioning point of view... thanks

**Comment by marchbold** [comment]
Ah okay, yeah should be fine either way, the flag is just to ensure it doesn't automatically start.

**Comment by Lydecker** [comment]
Great.
Thank you so much for helping me pin point this issue!
