### ISSUE TITLE
Google Auth

### ISSUE THREAD

**Issue by c3goui** [distriqt/ANE-Firebase#21]
I got this message when I try to FirebaseAuth.service.signInWithCredential();
12-21 12:35:12.377  4905  5976 I AuthChimeraService: Error description received from server: {
12-21 12:35:12.377  4905  5976 I AuthChimeraService:  "error": {
12-21 12:35:12.377  4905  5976 I AuthChimeraService:   "errors": [
12-21 12:35:12.377  4905  5976 I AuthChimeraService:    {
12-21 12:35:12.377  4905  5976 I AuthChimeraService:     "domain": "global",
12-21 12:35:12.377  4905  5976 I AuthChimeraService:     "reason": "invalid",
12-21 12:35:12.377  4905  5976 I AuthChimeraService:     "message": "Invalid Idp Response: the Google id_token is not allowed to be used with this application. Its audience (OAuth 2.0 client ID) is 775039511022-rm5bded7jbc9g89i61eml8d0oa9hsv6d.apps.googleusercontent.com, which is not authorized to be used in the project with project_number: 245511105276."
12-21 12:35:12.377  4905  5976 I AuthChimeraService:    }
12-21 12:35:12.377  4905  5976 I AuthChimeraService:   ],
12-21 12:35:12.377  4905  5976 I AuthChimeraService:   "code": 400,
12-21 12:35:12.377  4905  5976 I AuthChimeraService:   "message": "Invalid Idp Response: the Google id_token is not allowed to be used with this application. Its audience (OAuth 2.0 client ID) is 775039511022-rm5bded7jbc9g89i61eml8d0oa9hsv6d.apps.googleusercontent.com, which is not authorized to be used in the project with project_number: 245511105276."

I just dont know where it take the project number 245511105276 !!! 

Any idea?

**Comment by marchbold** [comment]
How are you configuring Firebase? Check the values you have provided in your config extension.

**Comment by c3goui** [comment]
Allez value are ok I double ckeck everythings. I get all latest ane.

Le 21 déc. 2016 5:03 PM, "Michael" <notifications@github.com> a écrit :

How are you configuring Firebase? Check the values you have provided in
your config extension.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/distriqt/ANE-Firebase/issues/21#issuecomment-268653575>,
or mute the thread

**Comment by marchbold** [comment]
Can you post the entire log, from when you start your application?

**Comment by c3goui** [comment]
Yes but tomorrow  (time difference ).

Thanks

**Comment by lucasmouse** [comment]
Same problem
