### ISSUE TITLE
no default_web_client_id data for value.xml

### ISSUE THREAD

**Issue by Mintonist** [distriqt/ANE-Firebase#212]
Hi!
I have no value for {YOUR_CLIENT}/oauth_client/client_id (client_type == 3) in google-services.json
So service https://distriqt.github.io/ANE-Firebase/tools/google-services-json-to-xml.html doesn't work.
Can I miss default_web_client_id tag?

And I have no ga_trackingId tag. I plan use only FCM service.

Thx!

P.S.
Where vakues.xml need to be placed inside .apk? I add my icons to AIR\lib\android\lib\resources\app_entry and AIR\lib\android\lib\resources\captive_runtime before building .apk and have same result as using CustomResources.ane.

**Comment by marchbold** [comment]
`values.xml` needs to be added into a custom ANE as a resource as `res/values/values.xml`. AIR currently doesn't have the ability to package Android resources.

Make sure you have been through the complete Firebase setup for your app and downloaded the latest version through the Firebase console. If it still doesn't have the correct client let me know.

**Comment by marchbold** [comment]
Also regarding the custom resources ANE, here is a link to the repo to help you create your own:

https://github.com/distriqt/ANE-CustomResources

Or you can email your resources to us and we'll create it for you: airnativeextensions@distriqt.com

**Comment by Mintonist** [comment]
I have one autoimport project and cteate second project with manual import from https://console.developers.google.com/

In both case I have no value for
{YOUR_CLIENT}/oauth_client/client_id (client_type == 3) and
{YOUR_CLIENT}/services/analytics-service/analytics_property/tracking_id

in google-services.json

May be google changes format?

**Comment by Mintonist** [comment]
I create new empty test project in Firebase Console and have the same result.

**Comment by marchbold** [comment]
We just created several new projects within the last few weeks and haven't had any issues so I don't believe the format has changed.

Can you describe how you are creating your projects?

**Comment by Mintonist** [comment]
Simple create project via import from https://console.developers.google.com/. It's my old project (I created it 5 years ago).
I think I have no enought settings in console.developers.google.com. But I don't know which(

**Comment by Mintonist** [comment]
1. Finally I copied default_web_client_id from console.developers.google.com manyally.
I find similar problem - https://github.com/firebase/FirebaseUI-Android/issues/1381. Seems it's a bug.

2. I have GA (https://analytics.google.com) projects for my games. I track necessary events from client code. So can I place ga_trackingId from it?

**Comment by marchbold** [comment]
Glad you found the client id. The tracking id is not required so you can ignore that one if you wish.
