### ISSUE TITLE
[iOS] Compilation failed - FCM 

### ISSUE THREAD

**Issue by wanderersolutions** [distriqt/ANE-Firebase#214]
Hi,

I'm trying to use the FCM in iOS. I followed the setup in your page. However I'm getting an error while compiling on device. The issue comes from the com.distriqt.firebase.ane. Once I remove it it compiles fine.

What do you think i'm missing?

Thanks 

* Error:

> Invalid input.
> 
> Undefined symbols for architecture arm64:
>   "_OBJC_CLASS_$_FIRComponent", referenced from:
>       objc-class-ref in FIRAnalyticsConnector(FIRAnalyticsConnector_a5c2bcc5e9e9c84aa1bd7fe4f86f89af.o)
>   "_OBJC_CLASS_$_FIRComponentContainer", referenced from:
>       objc-class-ref in FIRAnalyticsConnector(FIRAnalyticsConnector_a5c2bcc5e9e9c84aa1bd7fe4f86f89af.o)
> ld: symbol(s) not found for architecture arm64
> Undefined symbols for architecture armv7:
>   "_OBJC_CLASS_$_FIRComponent", referenced from:
>       objc-class-ref in FIRAnalyticsConnector(FIRAnalyticsConnector_dd183331a9d3f53c9e7603d5611c34c4.o)
>   "_OBJC_CLASS_$_FIRComponentContainer", referenced from:
>       objc-class-ref in FIRAnalyticsConnector(FIRAnalyticsConnector_dd183331a9d3f53c9e7603d5611c34c4.o)
> ld: symbol(s) not found for architecture armv7

**Comment by marchbold** [comment]
What ANEs do you have in your project? 

This can occur if there's a duplicate framework.

**Comment by wanderersolutions** [comment]
I have the below ANEs:

- com.distriqt.Share.ane
- com.distriqt.Camera.ane
- com.distriqt.CameraRollExtended.ane
- com.distriqt.Application.ane
- com.distriqt.NativeWebView.ane
- com.distriqt.Core.ane
- com.distriqt.Firebase.ane
- com.distriqt.PushNotifications.FCM.ane

**Comment by marchbold** [comment]
Can you make sure you are using the latest version of the Firebase ANE. This can be caused by using an outdated ANE.

**Comment by wanderersolutions** [comment]
Yes i'm using the latest version. And once I use the old version, I get another error related to minimum version of sdk

**Comment by wanderersolutions** [comment]
Thanks a million @divlaine. It solved my issue.

**Comment by divlaine** [comment]
> Thanks a million @divlaine. It solved my issue.

You are welcome! Thanks to @marchbold _) Awesome support!

**Comment by marchbold** [comment]
Apologies @wanderersolutions  I should have thought to ask you the same questions about the Frameworks. Glad you have it working now.
