### ISSUE TITLE
VerifyError: Error #1014: Class com.distriqt.extension.firebase::FirebaseOptions could not be found.

### ISSUE THREAD

**Issue by sfxworks** [distriqt/ANE-Firebase#22]
Completely new to ANEs and this extension so forgive me if this is a simple question. I am trying to test out Firebase. I am using Firebase Options to connect. However, as soon as I launch the movie, it says it cannot find FirebaseOptions.

I have core, base firebase, and android v4 included. Can I only test this sort of thing on my android phone?

```
package 
{
	import com.distriqt.extension.firebase.Firebase;
	import com.distriqt.extension.firebase.FirebaseOptions;
	import flash.display.MovieClip;

	public class TestMain extends MovieClip
	{
		
		public function TestMain() 
		{
			//Services init
			stop();
			
			try
			{
				Firebase.init("[MyKey]");
				//Services config
			}
			catch (e:Error)
			{
				trace(e);
			}
			
			if (Firebase.isSupported)
			{
				var options:FirebaseOptions = new FirebaseOptions();  
				options.apiKey      = "myapikey";
				options.clientID    = "myclientnumber-";
				options.databaseURL = "https://mappscape.firebaseio.com"
				options.gcmSenderID = "senderid";
				options.googleAppID = "appid";
				
				Firebase.service.initialiseApp( options );
			}
			else
			{
				trace("Firebase is not supported.");
			}
		}
		
	}

}
```

`VerifyError: Error #1014: Class com.distriqt.extension.firebase::FirebaseOptions could not be 'found.'`

**Comment by marchbold** [comment]
Hi,

That issue sounds like you haven't correctly packaged the ANE with your application. We have a tutorial for this located here:

https://airnativeextensions.com/knowledgebase/tutorial/1

Also we highly suggest not using FirebaseOptions at the moment, it's a little unreliable (we are still working on making it easier). If possible use the configuration ANE and the info plist file. 

This functionality is available on both iOS and Android. 

Cheers

**Comment by sfxworks** [comment]
![image](https://cloud.githubusercontent.com/assets/5921035/21950620/dd6a1e58-d9ca-11e6-89c1-d7cabfb41e9d.png)
I have already done that. I even went through the wiki. Even through double checking I haven't the slightest clue why it can find Firebase but not FirebaseOptions since they're in the same package...
![image](https://cloud.githubusercontent.com/assets/5921035/21950655/2a5e0c9c-d9cb-11e6-9395-fb2eec360f06.png)

**Comment by marchbold** [comment]
Are you testing on a device?

**Comment by sfxworks** [comment]
No, I am using Adobe Animate's debug feature. Should I be testing on a device?

**Comment by marchbold** [comment]
Yeah, the simulator is not currently supported. It should return isSupported = false

I'll double check to see if that class was missed in that implementation.

**Comment by sfxworks** [comment]
Gotcha. Yeah I was even putting the function to initialize the app inside a conditional that check'd to see whether isSupported returned true or not. I appreciate your help!
