### ISSUE TITLE
Firebase Android 64bit support

### ISSUE THREAD

**Issue by marchbold** [distriqt/ANE-Firebase#220]
Update the extension to include support for Android 64bit

>
> Starting August 1, 2019, your apps published on Google Play will need to support 64-bit architectures. 64-bit CPUs deliver faster, richer experiences for your users. Adding a 64-bit version of your app provides performance improvements, makes way for future innovation, and sets you up for devices with 64-bit-only hardware.
>

**Comment by marchbold** [comment]
Beta: https://www.dropbox.com/s/4a9mgbuk5tsry6p/com.distriqt.Firebase.v3.0.001.zip?dl=0

**Comment by jasonJamEther** [comment]
I have been updating and using your 64bit anes which have been working great. Thanks for getting so many out so quickly. Is this one (firebase) getting close to coming out of beta?

**Comment by marchbold** [comment]
Yes, we are hoping to have these final few out within a week.
