### ISSUE TITLE
Android error with custom token login

### ISSUE THREAD

**Issue by janberga** [distriqt/ANE-Firebase#221]
I'm using a custom auth token to login to firebase, as described in solution to #71, and it works as expected on iOS. On android however, I'm getting an error message immediately after using FirebaseAuth.service.signInWithCustomToken(customToken). 

Error message:
Error #2044: Unhandled error:. text=Attempt to invoke virtual method 'void com.google.firebase.auth.FirebaseAuth.addAuthStateListener(com.google.firebase.auth.FirebaseAuth$AuthStateListener)' on a null object reference

Any ideas?

Best,
Jan

##### Expected behaviour
FirebaseAuthEvent.SIGNIN_WITH_CUSTOMTOKEN_COMPLETE returns e.success = true and user is logged in to Firebase. 

##### Actual behaviour
Error message thrown before event listener is triggered. 

##### Environment 

- AIR SDK version: 32.0.0.116
- Device OS: Android 8.0.0
- Device version: Galaxy S7
- Development IDE: Animate CC
- Development OS: Mac OS 10.14.4

##### Logs

Device logs if relevant

**Comment by marchbold** [comment]
Can you post the logs from your device? 

https://airnativeextensions.github.io/tutorials/device-logs

Also can you make sure you are using the latest Google Play Services and Firebase ANEs.

**Comment by janberga** [comment]
My bad. 
I had failed to add the google services auth ane for android...

No action required on your part, except possibly adding a reminder in each android section in the wiki to add the corresponding google services ane, if there are other users as absent-minded as me :-)

Closing this. Thanks!

**Comment by marchbold** [comment]
Glad you found the issue. Will look into adding some extra notes in the docs
