### ISSUE TITLE
Doubt about ga_trackingId

### ISSUE THREAD

**Issue by megajogos** [distriqt/ANE-Firebase#222]
Hello I configured my project using the template of this page:

https://github.com/distriqt/ANE-Firebase/wiki/Setup---Configuration-Files

one config was:
```
<string name="ga_trackingId" translatable="false">UA-65557217-3</string>
```
the **ga_trackingId** was not present on my  **google-services.json**. 

Can you tell where to find this info? once it is not on .json?

Maybe I did not setup Google Analytics/Firebase correctly?

Thanks

**Comment by marchbold** [comment]
Hi,

This value is only needed when converting old GA installations across to Firebase, generally in a new setup it is not needed. So just leave it out.

Cheers
