### ISSUE TITLE
RegistrationEvent never fires

### ISSUE THREAD

**Issue by steveRedMinnow** [distriqt/ANE-Firebase#223]
I have been using the Firebase Coud Messaging ANE for 2 months and it has worked as expected. However, on 7/13/2019 something changed. This may be Google's final migration from Google Cloud Messaging to Firebase Cloud Messaging.

Either way, I have 6 listeners set up for all Registration Event types. None of them ever fire now. 

The app does receive a AuthorisationStatus.AUTHORISED message via PushNotifications.service.authorisationStatus(). This is where I set up the 6 RegistrationEvent listeners and then call PushNotifications.service.register(); But the app does not receive any response including an error or fail events.

Prior to 7/13/2019, the app had successfully received RegistrationEvent.REGISTER_SUCCESS messages consistently as we log users' deviceID's into our system based on the returned data from successful registration event.

I am still receiving push notifications on devices that have registered prior to 7/13/2019, although messages no longer popup on iOS devices. I have checked settings and they should appear on-screen, yet they do not. The app still receives them and responds appropriately, however. 

I am using Adobe Flash Builder 4.7, Feathers 4 SDK, Air 32 on a Mac and testing currently on iOS devices.

Again, this has worked well until 7/13/2019. Here is the code if you would like to take a look

**Comment by steveRedMinnow** [comment]
Sorry, here is the code.....

[PushNotificationHelper.as.zip](https://github.com/distriqt/ANE-Firebase/files/3406355/PushNotificationHelper.as.zip)

**Comment by steveRedMinnow** [comment]
I believe I have found the issue and it had to to with the Push Notification certificate, which was modified by someone else. 

We have everything back the way it should be.

**Comment by marchbold** [comment]
Are you sure nothing has changed in your setup? It seems unusual that it should just stop working.

**Comment by steveRedMinnow** [comment]
yes it is very unusual. It appears that something has changed on Firebase’s side IMO. Newer devices that connect, (if they can connect), now get an entirely different formatted Push Notification than devices that have been registered.

This has been remarkably stable for the last 2 months until last Sat, July 13. Then everything changed. After calling PushNotifications.service.register(), Sometimes the registration occurs successfully and all is good. Other times there is no information back.  It doesn’t return a fail, an error, even an unregistered. It just does nothing. Sadly this happens as much now as a successful registration, which we cannot have.

We know that Firebase was phasing out GCM and thought that had occurred a while ago. Our backend system is calling the Firebase web API: https://fcm.googleapis.com/fcm/send <https://fcm.googleapis.com/fcm/send>
We were a bit surprised with the formatting of the data at first. Here is an example of the Push Notification before last Sat:

{
  "gcm.notification.priority" : "1",
  "google.c.a.e" : "1",
  "aps" : {
    "badge" : 1,
    "alert" : {
      "title" : "",
      "body" : "it is time to start the event."
    },
    "sound" : "default"
  },
  "gcm.notification.callbackid" : "114",
  "gcm.notification.alert" : "ACA Alert",
  "gcm.notification.msgid" : "114",
  "gcm.notification.vibrate" : "true",
  "gcm.message_id" : "1562505512665166",
  "gcm.notification.viewname" : "CREATOR_START"
}

And here is the data now:

{
  "from" : "1064782071784",
  "collapse_key" : "com.signature4.ACA",
  "notification" : {
    "body" : "it is time to start the event.",
    "viewname" : "CREATOR_START",
    "sound" : "default",
    "badge" : "1",
    "priority" : "1",
    "callbackid" : "207",
    "msgid" : "142",
    "icon" : "myicon",
    "e" : "1",
    "sound2" : "default",
    "alert" : "ACA Alert",
    "vibrate" : "true"
  }
}

The app still receives the data and can respond, but since there is no alert object anymore, the device is not displaying the PN message….which is really the reason to have PNs in the first place



Steve Easley
Red Minnow Interactive, LLC
903 Eastwind Dr.
Westerville, OH 43081
614.893.8169

**Comment by steveRedMinnow** [comment]
I figured out the problem. At some point, the Core.init() call got commented out in the main app class. That messed everything up with Push Notifications and made it ver unstable.

Sorry to bug you with all of this but thanks for your response.

Steve Easley
Red Minnow Interactive, LLC
903 Eastwind Dr.
Westerville, OH 43081
614.893.8169

**Comment by marchbold** [comment]
Ah yeah, that would definitely do it! Without that call I would expect lots of iOS notification functionality to fail. 

Glad you found the issue.
