### ISSUE TITLE
Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by divlaine** [distriqt/ANE-Firebase#225]
Hi. Undefined symbols for architecture armv7 with __isOSVersionAtLeast i resolved.
But there is another part of that error

```
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_FIRComponent", referenced from:
      objc-class-ref in FIRAnalyticsConnector(FIRAnalyticsConnector_dd183331a9d3f53c9e7603d5611c34c4.o)
  "_OBJC_CLASS_$_FIRComponentContainer", referenced from:
      objc-class-ref in FIRAnalyticsConnector(FIRAnalyticsConnector_dd183331a9d3f53c9e7603d5611c34c4.o)
ld: symbol(s) not found for architecture armv7
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIRComponent", referenced from:
      objc-class-ref in FIRAnalyticsConnector(FIRAnalyticsConnector_a5c2bcc5e9e9c84aa1bd7fe4f86f89af.o)
  "_OBJC_CLASS_$_FIRComponentContainer", referenced from:
      objc-class-ref in FIRAnalyticsConnector(FIRAnalyticsConnector_a5c2bcc5e9e9c84aa1bd7fe4f86f89af.o)
ld: symbol(s) not found for architecture arm64
Compilation failed while executing : ld64
```

Its became only after including Firebase ANE

I updated all your ANE's but still got this errors

Air SDK 32

ps. Related to https://github.com/distriqt/ANE-Firebase/issues/214 but there are no udpates

**Comment by marchbold** [comment]
Are you including any other ANEs? This could be the result of a conflicting extension.

**Comment by divlaine** [comment]
Yes, ofc there are other extensions.
Ok, I'll clean project one more time from all ANEs and write you about changes. Cause in clean project I remember only "__isOSVersionAtLeast " error.

**Comment by divlaine** [comment]
ps on android there is another behavior #226

**Comment by divlaine** [comment]
I cleaned all ANE's. updated all ANE to last but it doesn't work.
```
<extensionID>com.distriqt.Firebase</extensionID>
<extensionID>com.distriqt.PushNotifications</extensionID>
<extensionID>com.distriqt.Core</extensionID>
<extensionID>com.distriqt.playservices.Base</extensionID>
<extensionID>com.distriqt.androidsupport.AppCompatV7</extensionID>
<extensionID>com.distriqt.androidsupport.V4</extensionID>
<extensionID>com.distriqt.playservices.GCM</extensionID>
<extensionID>com.distriqt.playservices.Identity</extensionID>
<extensionID>com.distriqt.playservices.Location</extensionID>
```

**Comment by divlaine** [comment]
Found your note
```
Note

If you wish to use Firebase on iOS you must disable the “Hide ANE-Library-Symbols” option in your packaging settings.
```

Does it have some influence? Didn't find how to implement it.

**Comment by divlaine** [comment]
Found next comment:
"symbol FIRComponent" was started in Firebase 5.5.0 abd was defined in FirebaseCore and linked in FirebaseAuth.
Needs at least FirebaseCore v 5.1.0

**Comment by marchbold** [comment]
Please make sure you add `com.distriqt.Core.ane` not the `noair` version. 

Can you give us more information about your build environment so we can attempt to replicate this error?

**Comment by divlaine** [comment]
I tried both of them Core and Core no air. The result is the same.
Flex 4.16.1
Air SDK 32 beta (July 5)
JDK 1.8 v111
Windows 10 Pro

manifest
```
<?xml version="1.0" encoding="utf-8" ?> 
<application xmlns="http://ns.adobe.com/air/application/32.0">
...

<iPhone>
    <requestedDisplayResolution>high</requestedDisplayResolution>
    <assetsCar>Assets.car</assetsCar>
    <InfoAdditions>
		<![CDATA[
			<key>UIViewControllerBasedStatusBarAppearance</key>
			<false/>
			<key>UIRequiresPersistentWiFi</key>
			<string>NO</string>
			<key>UIApplicationExitsOnSuspend</key>
			<false/>
			<key>UIDeviceFamily</key>
			<array>
				<string>1</string>
				<string>2</string>
			</array>
			<key>UIPrerenderedIcon</key>
			<true/>
			<key>UIStatusBarStyle</key>
			<string>UIStatusBarStyleBlackOpaque</string>
			<key>NSAppTransportSecurity</key>
			<dict>
				<key>NSAllowsArbitraryLoads</key>
				<true/>
			</dict>
			<key>MinimumOSVersion</key>
			<string>9.0</string>
			<key>FirebaseAppDelegateProxyEnabled</key>
			<false/>
		]]>
	</InfoAdditions>
    <Entitlements>
		<![CDATA[
			<!--<key>get-task-allow</key>
			<true/>-->
			<key>aps-environment</key>
			<string>development</string>
			<key>com.apple.developer.team-identifier</key>
			<string>GROUPID</string>
			<key>application-identifier</key>
			<string>GROUPID.APPID</string>
			<key>keychain-access-groups</key>
			<array>
				<string>GROUPID.*</string>
			</array>
		]]>
	</Entitlements>
  </iPhone>
  <extensions>
	<extensionID>com.distriqt.Firebase</extensionID>
	<extensionID>com.distriqt.PushNotifications</extensionID>
		
	<extensionID>com.distriqt.Core</extensionID>
	<extensionID>com.distriqt.playservices.Base</extensionID>
	<!--<extensionID>com.distriqt.androidsupport.AppCompatV7</extensionID>-->
	<extensionID>com.distriqt.androidsupport.V4</extensionID>
	<extensionID>com.distriqt.CustomResources</extensionID>
    <!--<extensionID>com.distriqt.playservices.GCM</extensionID>
    <extensionID>com.distriqt.playservices.Identity</extensionID>
    <extensionID>com.distriqt.playservices.Location</extensionID>-->
  </extensions>
</application>
```

<a href="https://ibb.co/wY5s9n3"><img src="https://i.ibb.co/wY5s9n3/shot.jpg" alt="shot" border="0"></a>

**Comment by marchbold** [comment]
Please make sure you only have one of the Core ANE's in your extension directory, having both can cause issues.

**Comment by marchbold** [comment]
The same goes for push notifications, please remove the ANEs you aren't using in your project.

**Comment by divlaine** [comment]
I removed it as you ask
<a href="https://ibb.co/z5F8hNw"><img src="https://i.ibb.co/z5F8hNw/2.png" alt="2" border="0"></a>

The result is the same
```
Warning: Using default implementation for native extension 'com.distriqt.CustomResources'
Warning: Using default implementation for native extension 'com.distriqt.playservices.Base'
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_FIRComponent", referenced from:
      objc-class-ref in FIRAnalyticsConnector(FIRAnalyticsConnector_dd183331a9d3f53c9e7603d5611c34c4.o)
  "_OBJC_CLASS_$_FIRComponentContainer", referenced from:
      objc-class-ref in FIRAnalyticsConnector(FIRAnalyticsConnector_dd183331a9d3f53c9e7603d5611c34c4.o)
ld: symbol(s) not found for architecture armv7
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIRComponent", referenced from:
      objc-class-ref in FIRAnalyticsConnector(FIRAnalyticsConnector_a5c2bcc5e9e9c84aa1bd7fe4f86f89af.o)
  "_OBJC_CLASS_$_FIRComponentContainer", referenced from:
      objc-class-ref in FIRAnalyticsConnector(FIRAnalyticsConnector_a5c2bcc5e9e9c84aa1bd7fe4f86f89af.o)
ld: symbol(s) not found for architecture arm64
Compilation failed while executing : ld64

APK setup creation FAILED.

Troubleshooting:
- verify AIR SDK target version in application.xml
```

**Comment by divlaine** [comment]
Any fresh ideas?

**Comment by marchbold** [comment]
We are still trying to replicate this issue, we are unsure what is causing it as we can't seem to get it to occur.

**Comment by marchbold** [comment]
What IDE / packaging method are you using ?

**Comment by divlaine** [comment]
mb it will be better to send you a project ?

**Comment by divlaine** [comment]
mb it will be better to send you a project ?

**Comment by divlaine** [comment]
Flash Develop. Flex 4.16.1 Air 32 and all standard Flash Develop methods. Custor Resources was packaged by ant v 1.9.4

**Comment by marchbold** [comment]
Have you tried packaging directly using ADT at all?

**Comment by divlaine** [comment]
no i didn't do that.
but packager command in flash Develop for Ios is 
```
call adt -installApp -platform ios -package "%OUTPUT%"
```

**Comment by marchbold** [comment]
It's the package command not the install that is the failing one.

**Comment by divlaine** [comment]
oh yes. i wrote and than saw it

**Comment by divlaine** [comment]
```
call adt -package -target %TYPE%%TARGET% %OPTIONS% %SIGNING_OPTIONS% "%OUTPUT%" "%APP_XML%" %FILE_OR_DIR% -extdir lib
```

**Comment by marchbold** [comment]
Does FlashDevelop still do something weird with the ANE's and requiring SWC's? No chance you are incorrectly packaging the SWC instead of the ANE?

**Comment by divlaine** [comment]
You know i used a lot of ANE and swc. And never had unresolved embedd problems. There are always one problem to connect few different ANE from different providers. But im trying to embed ANE to clean project.

Didn't think that its something with flash develop.

Listen, can I really send you that clean project.  Mb really I made something wrong. Have no idea.

**Comment by divlaine** [comment]
> Found next comment:
> "The FIRComponent symbol was introduced in the Firebase 5.5.0 release with a definition in the FirebaseCore pod and reference in the FirebaseAuth pod.
> Make sure you have at least version 5.1.0 of the FirebaseCore pod installed."

And what do you think about that comment?

**Comment by marchbold** [comment]
We are well beyond 5.1. Is there any chance you have a version of the FirebaseCore framework in your AIR SDK? 

Have you used another provider's ANE in the past?

Or have you double checked you have the latest Firebase ANE?

**Comment by divlaine** [comment]
1. FirebaseCore framework... have to check sdk
2. Yes, ofc i used: yours and myflashlabs. but now im testing totally your ANE (no any others)
3. I checked, but to 100% Ill download again all ANE from your git and try again

ps. Android works well.

**Comment by divlaine** [comment]
Wow... @marchbold Have no words. Thought about frameworks was incredible.
I really have them. Last year i tested firebase from myflashlabs and had to add
![image](https://user-images.githubusercontent.com/16689405/63093007-a52fde00-bf74-11e9-93b7-5ea8f6426c09.png)

**Comment by divlaine** [comment]
Im ready to Dance - 1 week of searching...
@marchbold Thanks a lot project compiled succesfully and my FCM works.

It's a good lesson i think.

**Comment by marchbold** [comment]
Ah! I don't understand why they tell people to do that! They should be packaged with the ANE.

Anyways, glad you have it running.
