### ISSUE TITLE
Firebase Events Not Showing up in Firebase

### ISSUE THREAD

**Issue by bftrepo** [distriqt/ANE-Firebase#227]
I'm getting success responses from Firebase.isSupported and Firebase.service.initialiseApp() but I'm not seeing any data come through to Firebase itself. I've included some logs below. I've tried running adb shell setprop debug.firebase.analytics.app YOUR_APPLICATION_PACKAGE in terminal, but nothing seems to happen there either.

##### Expected behaviour
Events appear in Firebase Analytics and/or Firebase DebugView

##### Actual behaviour
Events are not showing up

##### Environment 

- AIR SDK version: 29.0.0.122
- Device OS: Android
- Device version: 8.1
- Development IDE: Animate CC
- Development OS: Mac OS 10.13.6

##### Logs
08-09 16:19:55.340 15564 15564 D com.distriqt.Firebase: FirebaseAnalyticsController::logEvent( [view_item], Bundle{
08-09 16:19:55.340 15564 15564 D com.distriqt.Firebase:  item_name => data/videos/Voyager.mp4;
08-09 16:19:55.340 15564 15564 D com.distriqt.Firebase:  }Bundle )
08-09 16:19:55.341 15564 15564 I air.IntelliConnectRetailDisplay: event: view_item , data/videos/Voyager.mp4
08-09 16:19:55.343 15564 15742 E FA      : Failed to load metadata: Metadata bundle is null
08-09 16:19:55.344 15564 15742 E FA      : Failed to load metadata: Metadata bundle is null

**Comment by marchbold** [comment]
How are you initialising Firebase? The most common cause for this is not correctly setting up the custom resources ANE with your Firebase project values.

**Comment by bftrepo** [comment]
I'm using the custom resources ANE that you generated for me based on the values.xml file I sent you. However, one thing I noticed is that the web api key that is displayed in my project settings in the Firebase console is different than the API key it put in the google-services.json file it generated that I used to create my values.xml file. Should that be the case or should those things match?

**Comment by marchbold** [comment]
I should expect it to match, which values exactly aren't matching?

**Comment by bftrepo** [comment]
The field called "Web API Key" in the console and "api_key" in the JSON file.

**Comment by marchbold** [comment]
Yeah I wouldn't expect those to match, they are different fields. 

I suggest you update the AIR version you are using, using such an old version could cause issues.

**Comment by bftrepo** [comment]
Thanks, upgrading my version of AIR seemed to fix the issue.
