### ISSUE TITLE
Linking with Google Games account?

### ISSUE THREAD

**Issue by rainbowcreatures** [distriqt/ANE-Firebase#229]
I've got Google Play Game Services ane integrated (to use leaderboards etc), which features sign in. How would I link this sign-in with Firebase? We want to be able to link user events from Firebase to those leaderboard accounts when figuring out cheaters etc.

Firebase dashboard has options to enable Google account sign in (was my first choice as Google Play Games seems to be using that) and also Play Services, but not sure how to use that one (seems more related to leaderboards but I'm not sure how to link this one from within your ANE). 

So far I tried linking Google account, as I did link Facebook accounts successfully using the ane in a previous project.

This is what I'm doing: 

- In Game Services ANE, I tried to set game services service.serverClientId to the "Web client (auto created by Google Service)". But as soon as I do that, I can't login to Google Play Games - the dashboard shows up for a bit with the spinning wheel, then disappears. In the Android log I see:

**08-22 11:07:03.176 29092 10093 E SignInAuthenticator: **** APP NOT CORRECTLY CONFIGURED TO USE GOOGLE PLAY GAME SERVICES**

(details follow why this might be happening, like specifying wrong fingerprint, package name etc.)

- In Firebase dashboard, I filled in the SHA1 for the app which I obtained from release certificate to enable Google account authentication.

- My idea was to further use this:

`GameServices.service.authUtil.getToken();
`

Get the idToken and then hopefully be able to do this:

`var credential: AuthCredential = GoogleAuthProvider.getCredential(event.data.idToken, null);
FirebaseAuth.service.getCurrentUser().linkWithCredential(credential);
`

- I guess I'd need to use getToken each time the play game services login is done either silently or interactively?

Anyway, I can't get to try the above as I fail right at trying to set the serverClientId for the service.   I'm not even sure if this is a valid path for what I'm trying to accomplish.

**Comment by marchbold** [comment]
Honestly I haven't tried it with the GameServices ANE before, normally we'd use the Google Identity ANE in this situation as it gives you more control over the Google login. 

You can use the Google Identity ANE to manage login for both Game Services and Firebase then. 

- https://distriqt.github.io/ANE-GoogleIdentity/u.Setup#games-signin
- https://github.com/distriqt/ANE-Firebase/wiki/Auth---Provider---Google-Identity

**Comment by rainbowcreatures** [comment]
Thanks, I'll try that if my solution doesn't work. In the meantime I figured out I can simply save some of the players data (like leaderboard display name) as Firebase user properties. In Firebase DebugView it seems to work, all the events have leaderboard name attached after login. 
That way I think it should be possible to trace Firebase events to individual leaderboard players without technically logging them into Firebase.
