### ISSUE TITLE
Wiki for different sign in types?

### ISSUE THREAD

**Issue by sfxworks** [distriqt/ANE-Firebase#23]
https://github.com/distriqt/ANE-Firebase/wiki/Auth---Provider---Google-Identity
https://github.com/distriqt/ANE-Firebase/wiki/Auth---Provider---GitHub
https://github.com/distriqt/ANE-Firebase/wiki/Auth---Provider---Facebook
https://github.com/distriqt/ANE-Firebase/wiki/Auth---Provider---Twitter

All those articles are empty. I am completely new to firebase so I can't figure out how to give users the ability to sign in with google or facebook.

**Comment by marchbold** [comment]
Apologies we are still working on documentation for that. 

The process is :
- sign in using the provider (eg using the GoogleIdentity ANE or the FacebookAPI ANE)
- get the required auth tokens or access tokens for the platform
- create a credential with those fields eg: `GoogleAuthProvider.getCredential( idToken, accessToken );`
- sign into Firebase with this credential using `signInWithCredential()`


We have an example application using the Google Identity sign in:

https://github.com/distriqt/ANE-Firebase/blob/master/example/auth/google/src/com/distriqt/test/firebase/FirebaseAuthTests.as

**Comment by sfxworks** [comment]
I've got the access token through stage web view by following [this](http://fabricemontfort.com/firebase-and-as3-ep-2-login-with-oauth-2-0/) tutorial. What do I use as the ID?

I've tried feeding it my firebase id and my web client id. Nothing worked. I just get a false for isSignedIn after the auth state handler fires.

**Comment by marchbold** [comment]
You should be able to pass `null` for the `idToken` in that case I believe for Google Auth. Let me know if that doesn't work and I'll go back and double check the docs.

**Comment by sfxworks** [comment]
That didn't work. I even made sure to match up the scope with the example that you had.
`					options.requestIdToken = true;
					options.scopes.push( "https://www.googleapis.com/auth/plus.login" );
					options.scopes.push( "https://www.googleapis.com/auth/plus.me" );
					options.scopes.push( "profile" );`



`		private function googleLogin():void
		{
			trace("Google login init");
			
			swv = new StageWebView();
			swv.stage = this.stage;
			swv.viewPort = new Rectangle(0, 0, stage.stageWidth, stage.stageHeight);
			
			var oauth2:OAuth2 = new OAuth2("https://accounts.google.com/o/oauth2/auth", "https://accounts.google.com/o/oauth2/token", LogSetupLevel.ALL);
			var grant:IGrantType = new AuthorizationCodeGrant(swv,
				"secret",
				"supersecret",
				"https://kinda-secret.firebaseapp.com/__/auth/handler",
				"https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.me profile",
				null);
			oauth2.addEventListener(GetAccessTokenEvent.TYPE, tokenHandler);
			oauth2.getAccessToken(grant);
		}
		
		private function tokenHandler(token:GetAccessTokenEvent):void
		{
			if (token.errorCode == null && token.errorMessage == null)
			{
				trace("Token is " + token.accessToken);
				//I get it.
			}
			else
			{
				trace("token fail." + token.errorMessage);
			}
			
			var credential:AuthCredential = GoogleAuthProvider.getCredential(null, token.accessToken);
			trace("credential = " + credential);
			if (FirebaseAuth.service.signInWithCredential(credential))
			{
				trace("Sigining in");
				//Attempts to sign in.
			}
			else
			{
				trace("Failed.");
			}
			//Smore ui code
		}`



`		private function authState_changedHandler(e:FirebaseAuthEvent):void 
		{
			trace( "auth state changed: " + FirebaseAuth.service.isSignedIn() );
			//Throws 'auth state changed: false'
			var fbuser:FirebaseUser = FirebaseAuth.service.getCurrentUser();
			if (fbuser != null)
			{
				trace("displayname: "  + fbuser.displayName);
				trace("email : " + fbuser.email);
				trace("phto uri: " + fbuser.photoUrl);
				trace("identifier = " + fbuser.identifier);
				
				for each (var info:UserInfo in fbuser.providers)
					{
						trace( "provider:    " + info.providerId );
						trace( "identifier:  " + info.identifier );
						trace( "displayName: " + info.displayName );
						trace( "email:       " + info.email );
						trace( "all : "  + info);
					}
			}
						
		}`

**Comment by sfxworks** [comment]
This also doesn't work when I get an idToken and an oAuth token by following this guide: https://github.com/PhantomAppDevelopment/firebase-as3/tree/master/auth

**Comment by marchbold** [comment]
Could you post the logs from the device when you are attempting to authenticate? 

https://airnativeextensions.com/knowledgebase/faq/11

This probably means you aren't providing the accessToken / idToken as named by Google. Perhaps the naming is a little off in that tutorial?

**Comment by sfxworks** [comment]
http://stackoverflow.com/questions/41877285/how-do-i-authenticate-against-firebase yes I believe I was using the wrong token. I'll post updates tomorrow. Sorry about that.

**Comment by marchbold** [comment]
No problems, let me know how it goes!

**Comment by sfxworks** [comment]
Hey,
I've tried passing in my auth-token I get. I have had no success. Would it not accept an auth-token provided by it using a different sign-in method? (Rest API)

**Comment by marchbold** [comment]
It shouldn't matter if you use the rest api to authenticate as long as you are passing the correct token.

**Comment by sfxworks** [comment]
I still cannot get this to work and would need a guide to move forward. Can you please demonstrate how you would do this using a rest api?

**Comment by marchbold** [comment]
We haven't used a rest api to authenticate, I don't see why there would be a limitation though as long as the token has the correct permissions. 

Could you explain what you have tried?

**Comment by sfxworks** [comment]
I have used the rest API provided by https://github.com/PhantomAppDevelopment/firebase-as3/tree/master/auth to get my token.  After my user is logged in (or signed up) using the rest api, I turn the access_token into a credential and try to use FirebaseAuth.service.signInWithCredential to login. This method fails.

**Comment by marchbold** [comment]
`signInWithCredential` is supposed to be used with an `AuthCredential`:

-  `EmailAuthCredential`
- `FacebookAuthCredential`
- `GithubAuthCredential`
- `GoogleAuthCredential`
- `TwitterAuthCredential`

 There is no credential for Firebase so can you explain exactly what you are doing?

**Comment by sfxworks** [comment]
Is my token a firebase token? I have them sign in using facebook.com or google.com as a provider. I get the token from whichever one the user chooses. Am I not understanding the process?

**Comment by marchbold** [comment]
Okay, Sounds like you might not quite understand the process, I am writing documentation for this but briefly the process is as follows:

- log in with one of the other providers
  - eg Facebook using the Facebook API ANE 
- get an access token (or similar) from the provider
  - eg the Facebook access token string
- create an `AuthCredential` using this access token
- use this to sign into Firebase using `signInWithCredential`

So the token should be from the provider (Facebook).

**Comment by sfxworks** [comment]
Thanks. Sorry yeah if you could go into much detail as possible that would be great. This is my first time using 0auth. I have only written a simple user/pass one in php & sql. Nothing with tokens and sign-in sessions and the like.

**Comment by sfxworks** [comment]
Where do I put the access token in the AuthCredential class since AuthCredential has no params for constructing and only has a providerId var

**Comment by sfxworks** [comment]
I am able to get a success from an authstatechanged by passing in  oauthaccesstoken https://github.com/PhantomAppDevelopment/firebase-as3/issues/12

However, when I try ````_currentUser = FirebaseAuth.service.getCurrentUser();```` I get a null value..

**Comment by marchbold** [comment]
Firstly I suggest you create your credentials using the builder functions, eg:

```as3
var credential:AuthCredential = GoogleAuthProvider.getCredential( idToken );
```

If you are getting a null user, then something is still wrong with the sign in. 

Could you post a log from the device when doing this login? I'll see if I can find the error.

**Comment by sfxworks** [comment]
I added that in place of the googleAuthCredential. Passing in null for the id token and oauthidtoken for the authtoken these are the logs I get..

`I/air.quantomtechnologies.mappKey( 2250): Registration complete:
I/air.quantomtechnologies.mappKey( 2250): Raw data:
I/air.quantomtechnologies.mappKey( 2250): {
I/air.quantomtechnologies.mappKey( 2250):  "kind": "identitytoolkit#VerifyAssertionResponse",
I/air.quantomtechnologies.mappKey( 2250):  "federatedId": "https://accounts.google.com/118377649731620957745",
I/air.quantomtechnologies.mappKey( 2250):  "providerId": "google.com",
I/air.quantomtechnologies.mappKey( 2250):  "localId": "BnUs5hQZkJWLU9jGlpx9Ifq5ocf2",
I/air.quantomtechnologies.mappKey( 2250):  "emailVerified": true,
I/air.quantomtechnologies.mappKey( 2250):  "email": "sfxworks@gmail.com",
I/air.quantomtechnologies.mappKey( 2250):  "oauthIdToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjAyNDhiOTE4MDQ0ZjU0NDVkMDc0ZDk3YjhiYmM1ZGQ4NmY0Y2IwZDcifQ.eyJhenAiOiI3NTA1MjE1NTI5NzMtNzkwamNzZWY0MmppdDVkbDc1NWJ2NDZpc2hhcGdkZjQuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI3NTA1MjE1NTI5NzMtNzkwamNzZWY0MmppdDVkbDc1NWJ2NDZpc2hhcGdkZjQuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTgzNzc2NDk3MzE2MjA5NTc3NDUiLCJlbWFpbCI6InNmeHdvcmtzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiaWF0IjoxNDkxNTc3ODM0LCJleHAiOjE0OTE1ODE0MzQsIm5hbWUiOiJTYW11ZWwgV2Fsa2VyIiwicGljdHVyZSI6Imh0dHBzOi8vbGg0Lmdvb2dsZXVzZXJjb250ZW50LmNvbS8tVUwwY0p6X1RUcVEvQUFBQUFBQUFBQUkvQUFBQUFBQUFBamcvTG90Tjk3ME1IUVkvczk2LWMvcGhvdG8uanBnIiwiZ2l2ZW5fbmFtZSI6IlNhbXVlbCIsImZhbWlseV9uYW1lIjoiV2Fsa2VyIn0.NrazafWAVK6YqZ6JeAsMLhEH6oqMwb4TkQ5UN-oVOTcRCRi_RzUGDV9eK_SHq9FuBmtfVw5oyA7t27Zcav-SyTjNCWbPqvd-18t-ELiVF00356ehPVn2O31LGgWSMknt05L7Im1cVnFgJr1ORSTUHgMgpIrUgQ7R-HPg2j38IBFb29SpN5MXbt2NH-ifPlpK-X1n3Jz-DyA4GpRJEbUmqvB7OTMAv6Q1HdHAL1zEP12kIDVkPEaQPH8KI5OnGPz0cgYtcYZfUYOAR6
I/air.quantomtechnologies.mappKey( 2250):  "firstName": "Samuel",
I/air.quantomtechnologies.mappKey( 2250):  "lastName": "Walker",
I/air.quantomtechnologies.mappKey( 2250):  "fullName": "Samuel Walker",
I/air.quantomtechnologies.mappKey( 2250):  "displayName": "Samuel Walker",
I/air.quantomtechnologies.mappKey( 2250):  "idToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjljY2RmMjc1NmVkYWUxYjk2YjdiMjhhYzU1MTNlZGYyOTlmMTU5MjgifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbWFwcGtleS1kZDRhZCIsIm5hbWUiOiJTYW11ZWwgV2Fsa2VyIiwicGljdHVyZSI6Imh0dHBzOi8vc2NvbnRlbnQueHguZmJjZG4ubmV0L3YvdDEuMC0xL3AxMDB4MTAwLzE2MjY2MDE5XzEwMjExMDA3OTQ2NTcwNDU0XzM4Mzg5Njg4NzgyNjY2NTUxNDFfbi5qcGc_b2g9MTQ4YWVlNjc4YjQwMjY0YjIwNGQ5OTQ4YTIxN2M3ZWUmb2U9NTk0ODJBRjciLCJhdWQiOiJtYXBwa2V5LWRkNGFkIiwiYXV0aF90aW1lIjoxNDkxNTc3ODM5LCJ1c2VyX2lkIjoiQm5VczVoUVprSldMVTlqR2xweDlJZnE1b2NmMiIsInN1YiI6IkJuVXM1aFFaa0pXTFU5akdscHg5SWZxNW9jZjIiLCJpYXQiOjE0OTE1Nzc4MzksImV4cCI6MTQ5MTU4MTQzOSwiZW1haWwiOiJzZnh3b3Jrc0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJnb29nbGUuY29tIjpbIjExODM3NzY0OTczMTYyMDk1Nzc0NSJdLCJlbWFpbCI6WyJzZnh3b3Jrc0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJnb29nbGUuY29tIn19.U21V4lMAoxbPDcOd4ZnyiaG9Run9WODpQfeAB3E1-zuoVZ9YFQSN9dnsDY1TfTQy8zH-KolImlSHjEpu-SE4qxs-s62iKNCtyDio5L1hDrHYdMhBXEhl4rZxTyqqqGt6DB-VH37eWpbficY-a8t-cxI3Ao
I/air.quantomtechnologies.mappKey( 2250):  "photoUrl": "https://lh4.googleusercontent.com/-UL0cJz_TTqQ/AAAAAAAAAAI/AAAAAAAAAjg/LotN970MHQY/s96-c/photo.jpg",
I/air.quantomtechnologies.mappKey( 2250):  "context": "",
I/air.quantomtechnologies.mappKey( 2250):  "refreshToken": "AJly3UW1Fc2hki5_7NuVXIaGY1olYih3F7ohWvLL_j-q_D6oDr4JqxHpZwxo8--ZLrjsWGgF4bmM5O3jMhOwYaAqc9ve5uZD7FMnxJumAOxUjAxqEWmScrAQBGVykjnjAwapZycnyZBUWFLTy125nR7_VFxJjCoo-lL8E7HG6WqylYSrbARLlHTsFuitjbePeGMzK2V2pSt4xig8SmeysD4u_EV_Aat5V5dFzVaM9Cy5jrmCVis6s9EHgiQxmd2kPEP3lC1x9nbsWjMpFtnTQxfizEW2YrDPrh0vegaSTh8oE1ufWm0a5yo-wmya8rHEHV828eVbrNkS1hHZzmduxGRVD5w9Z0pDrJfE1PgF5MNEXhVxERJcvic",
I/air.quantomtechnologies.mappKey( 2250):  "expiresIn": "3600",
I/air.quantomtechnologies.mappKey( 2250):  "rawUserInfo": "{\"azp\":\"750521552973-790jcsef42jit5dl755bv46ishapgdf4.apps.googleusercontent.com\",\"aud\":\"750521552973-790jcsef42jit5dl755bv46ishapgdf4.apps.googleusercontent.com\",\"sub\":\"118377649731620957745\",\"email\":\"sfxworks@gmail.com\",\"email_verified\":true,\"iss\":\"accounts.google.com\",\"iat\":1491577834,\"exp\":1491581434,\"name\":\"Samuel Walker\",\"picture\":\"https://lh4.googleusercontent.com/-UL0cJz_TTqQ/AAAAAAAAAAI/AAAAAAAAAjg/LotN970MHQY/s96-c/photo.jpg\",\"given_name\":\"Samuel\",\"family_name\":\"Walker\"}"
I/air.quantomtechnologies.mappKey( 2250): }
I/air.quantomtechnologies.mappKey( 2250):
D/com.distriqt.Firebase.Auth( 2250): FirebaseAuthController::signInWithCredential()
D/com.distriqt.Firebase.Auth( 2250): FirebaseAuthController::onAuthStateChanged(): signed out
I/air.quantomtechnologies.mappKey( 2250): Auth changed.
I/air.quantomtechnologies.mappKey( 2250): Success = true
I/air.quantomtechnologies.mappKey( 2250):
D/com.distriqt.Dialog( 2250): DialogViewController::getViewByIdentifier( 61 )
D/com.distriqt.Dialog( 2250): DialogView_Activity::dismiss()
D/com.distriqt.Dialog( 2250): DialogView_Activity::handleAction( 0, -1 )
D/com.distriqt.Firebase.Auth( 2250): FirebaseAuthController::getCurrentUser()
I/air.quantomtechnologies.mappKey( 2250): Current user = null
I/air.quantomtechnologies.mappKey( 2250): TypeError: Error #1009: Cannot access a property or method of a null object reference.
I/air.quantomtechnologies.mappKey( 2250):       at service::Core/handleAuthChanged()[C:\Users\Samuel Walker\Documents\MappKey\service\Core.as:151]
I/air.quantomtechnologies.mappKey( 2250):       at flash.events::EventDispatcher/dispatchEventFunction()
I/air.quantomtechnologies.mappKey( 2250):       at flash.events::EventDispatcher/dispatchEvent()
I/air.quantomtechnologies.mappKey( 2250):       at com.distriqt.extension.firebase.auth::FirebaseAuth/dispatchEvent()
I/air.quantomtechnologies.mappKey( 2250):       at com.distriqt.extension.firebase.auth::FirebaseAuth/extension_statusHandler()
I/AVC     ( 2250): b8cda0a0
I/AuthChimeraService(30131): Error description received from server: {
I/AuthChimeraService(30131):  "error": {
I/AuthChimeraService(30131):   "errors": [
I/AuthChimeraService(30131):    {
I/AuthChimeraService(30131):     "domain": "global",
I/AuthChimeraService(30131):     "reason": "invalid",
I/AuthChimeraService(30131):     "message": "Invalid Idp Response: access_token is invalid"
I/AuthChimeraService(30131):    }
I/AuthChimeraService(30131):   ],
I/AuthChimeraService(30131):   "code": 400,
I/AuthChimeraService(30131):   "message": "Invalid Idp Response: access_token is invalid"
I/AuthChimeraService(30131):  }
I/AuthChimeraService(30131): }
D/com.distriqt.Firebase.Auth( 2250): FirebaseAuthController::signInWithCredential():onComplete:false
I/installd(  277): Collected cache files: 146 directories, 18 files
I/installd(  277): DEL (mod 1464175754) /data/data/air.quantomtechnologies.mappKey/cache/.AIR/certificates/javaTrustStore.tmp
I/installd(  277): DEL (mod 1464175754) /data/data/air.quantomtechnologies.mappKey/cache/.AIR/certificates/curl-ca-bundle.crt
I/installd(  277): DEL DIR /data/data/air.quantomtechnologies.mappKey/cache/.AIR/certificates/
I/installd(  277): DEL DIR /data/data/air.quantomtechnologies.mappKey/cache/.AIR/
I/installd(  277): DEL (mod 1491577817) /data/data/air.quantomtechnologies.mappKey/cache/org.chromium.android_webview/index-dir/the-real-index
I/installd(  277): DEL DIR /data/data/air.quantomtechnologies.mappKey/cache/org.chromium.android_webview/index-dir/
I/installd(  277): DEL (mod 1491577818) /data/data/air.quantomtechnologies.mappKey/cache/org.chromium.android_webview/ce53f511fa167110_0
I/installd(  277): DEL (mod 1491577818) /data/data/air.quantomtechnologies.mappKey/cache/org.chromium.android_webview/708de4652a400efb_0
I/installd(  277): DEL (mod 1491577818) /data/data/air.quantomtechnologies.mappKey/cache/org.chromium.android_webview/9a9e9db1d1b8cb4f_0
V/WLAN_PSA(  283): NL MSG, len[4072], NL type[0x1C] WNI type[0x5900] len[53263]
V/WLAN_PSA(  283): NL MSG, PID: 283
I/installd(  277): DEL (mod 1491577818) /data/data/air.quantomtechnologies.mappKey/cache/org.chromium.android_webview/1baf1d6acb3fbcb3_0
I/installd(  277): DEL (mod 1491577819) /data/data/air.quantomtechnologies.mappKey/cache/org.chromium.android_webview/1551f6ce48ddf59d_0
I/installd(  277): DEL (mod 1491577819) /data/data/air.quantomtechnologies.mappKey/cache/org.chromium.android_webview/8d841904bb0a425d_0
I/installd(  277): DEL (mod 1491577819) /data/data/air.quantomtechnologies.mappKey/cache/org.chromium.android_webview/9a9e9db1d1b8cb4f_1
I/installd(  277): DEL (mod 1491577819) /data/data/air.quantomtechnologies.mappKey/cache/org.chromium.android_webview/77e017f8d2e72cb6_0
I/installd(  277): DEL (mod 1491577828) /data/media/0/Android/data/com.twitter.android/cache/http-responses/journal
I/installd(  277): DEL DIR /data/media/0/Android/data/com.twitter.android/cache/http-responses/
I/installd(  277): DEL (mod 1491577833) /data/data/air.quantomtechnologies.mappKey/cache/com.android.opengl.shaders_cache
I/installd(  277): DEL (mod 1491577834) /data/data/air.quantomtechnologies.mappKey/cache/org.chromium.android_webview/80dd353fc4327292_0
I/installd(  277): DEL (mod 1491577835) /data/data/air.quantomtechnologies.mappKey/cache/org.chromium.android_webview/ae936df0231d3df3_0
I/installd(  277): DEL (mod 1491577835) /data/data/air.quantomtechnologies.mappKey/cache/org.chromium.android_webview/ae936df0231d3df3_1
I/installd(  277): DEL (mod 1491577835) /data/data/air.quantomtechnologies.mappKey/cache/org.chromium.android_webview/3356e568c281cfc4_0
I/installd(  277): DEL (mod 1491577835) /data/data/air.quantomtechnologies.mappKey/cache/org.chromium.android_webview/377213a36771317e_0
I/installd(  277): DEL DIR /data/data/air.quantomtechnologies.mappKey/cache/org.chromium.android_webview/`

**Comment by sfxworks** [comment]
Surely this is an error on the back since it is saying that I have a successful login after the authchange.

**Comment by marchbold** [comment]
Could you post the new code you are using? The error is there in the logs: **access_token is invalid** so whichever token you are using is the incorrect one.

**Comment by sfxworks** [comment]
> I added that in place of the googleAuthCredential. Passing in null for the id token and oauthidtoken for the authtoken these are the logs I get..

````
		private function registerComplete(e:Event):void 
		{
			e.target.removeEventListener(Event.COMPLETE, registerComplete);
			e.target.removeEventListener(IOErrorEvent.IO_ERROR, handleIOError);
			
			trace("Registration complete:");
			var rawData:Object = JSON.parse(e.currentTarget.data);
			trace("Raw data:");
			trace(e.currentTarget.data);
			
		/* Trace:
			 * 
				Raw data:
				{
				 "kind": "identitytoolkit#VerifyAssertionResponse",
				 "federatedId": "https://accounts.google.com/118377649731620957745",
				 "providerId": "google.com",
				 "localId": "BnUs5hQZkJWLU9jGlpx9Ifq5ocf2",
				 "emailVerified": true,
				 "email": "sfxworks@gmail.com",
				 "oauthIdToken": "eyJhbGciOiJSUzI1NiIsIm[ReallyLongString]..I probably shouldn't give this out.",
				 "firstName": "Samuel",
				 "lastName": "Walker",
				 "fullName": "Samuel Walker",
				 "displayName": "Samuel Walker",
				 "idToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjNiYmJiM2VlYTU0NzU1YmJkNWFkM2[ReallyLongString]..I probably shouldn't give this out.",
				 "photoUrl": "https://lh4.googleusercontent.com/-UL0cJz_TTqQ/AAAAAAAAAAI/AAAAAAAAAjg/LotN970MHQY/s96-c/photo.jpg",
				 "context": "",
				 "refreshToken": "AJly3UV_ZpH8OfLR4Vml3wqoQWykNipEr52xVHupDj_lcjVKTz_fbq0mStJW8w03dpnI_poyK3Ao[ReallyLongString]..I probably shouldn't give this out.",
				 "expiresIn": "3600",
				 "rawUserInfo": "{\"azp\":\"750521552973-790jcsef42jit5dl755bv46ishapgdf4.apps.googleusercontent.com\",\"aud\":\"750521552973-790jcsef42jit5dl755bv46ishapgdf4.apps.googleusercontent.com\",\"sub\":\"118377649731620957745\",\"email\":\"sfxworks@gmail.com\",\"email_verified\":true,\"iss\":\"accounts.google.com\",\"iat\":1491418008,\"exp\":1491421608,\"name\":\"Samuel Walker\",\"picture\":\"https://lh4.googleusercontent.com/-UL0cJz_TTqQ/AAAAAAAAAAI/AAAAAAAAAjg/LotN970MHQY/s96-c/photo.jpg\",\"given_name\":\"Samuel\",\"family_name\":\"Walker\"}"
				}
			 */ 
			
			if (rawData.hasOwnProperty("oauthIdToken"))
			{
				
				if (rawData.providerId == "google.com")
				{
					
					**var googleAuthCredential:AuthCredential = GoogleAuthProvider.getCredential(rawData.idToken, rawData.oauthIdToken);**
					
					FirebaseAuth.service.signInWithCredential(googleAuthCredential);
				}
				else if (rawData.providerId == "facebook.com")
				{
					**var facebookAuthCredential:AuthCredential = FacebookAuthProvider.getCredential(rawData.oauthIdToken);**
					
					FirebaseAuth.service.signInWithCredential(facebookAuthCredential);
				}
			}
			else
			{
				throw new Error("No email returned through registration process");
			}
		}


````

**Comment by sfxworks** [comment]
Please demonstrate that this actually works without your ANEs as I have been waiting since **January** to fix this.

**Comment by sfxworks** [comment]
For some reason upon further examination of the email login I get two auth responses. I am conducting more tests.

These responses come when I listen for authstatechange and not login_with_email_success
````
sfxworks@gmail.com :: password123
Auth changed.
Success = true

Auth changed.
Success = true

Login success.`
````

**Comment by sfxworks** [comment]
Using the existing code above, I modified my authChange handler to simply trace a success status and message, and added a credential sign-in handler. This is the new registerComplete function:

````
		private function registerComplete(e:Event):void 
		{
			e.target.removeEventListener(Event.COMPLETE, registerComplete);
			e.target.removeEventListener(IOErrorEvent.IO_ERROR, handleIOError);
			
			trace("Registration complete:");
			var rawData:Object = JSON.parse(e.currentTarget.data);
			trace("Raw data:");
			trace(e.currentTarget.data);
			
		/* Trace: short on cash. will trade equity for your investor for a bit more per week
			 * 
				Raw data:
				{
				 "kind": "identitytoolkit#VerifyAssertionResponse",
				 "federatedId": "https://accounts.google.com/118377649731620957745",
				 "providerId": "google.com",
				 "localId": "BnUs5hQZkJWLU9jGlpx9Ifq5ocf2",
				 "emailVerified": true,
				 "email": "sfxworks@gmail.com",
				 "oauthIdToken": "eyJhbGciOiJSUzI1NiIsIm[ReallyLongString]..I probably shouldn't give this out.",
				 "firstName": "Samuel",
				 "lastName": "Walker",
				 "fullName": "Samuel Walker",
				 "displayName": "Samuel Walker",
				 "idToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjNiYmJiM2VlYTU0NzU1YmJkNWFkM2[ReallyLongString]..I probably shouldn't give this out.",
				 "photoUrl": "https://lh4.googleusercontent.com/-UL0cJz_TTqQ/AAAAAAAAAAI/AAAAAAAAAjg/LotN970MHQY/s96-c/photo.jpg",
				 "context": "",
				 "refreshToken": "AJly3UV_ZpH8OfLR4Vml3wqoQWykNipEr52xVHupDj_lcjVKTz_fbq0mStJW8w03dpnI_poyK3Ao[ReallyLongString]..I probably shouldn't give this out.",
				 "expiresIn": "3600",
				 "rawUserInfo": "{\"azp\":\"750521552973-790jcsef42jit5dl755bv46ishapgdf4.apps.googleusercontent.com\",\"aud\":\"750521552973-790jcsef42jit5dl755bv46ishapgdf4.apps.googleusercontent.com\",\"sub\":\"118377649731620957745\",\"email\":\"sfxworks@gmail.com\",\"email_verified\":true,\"iss\":\"accounts.google.com\",\"iat\":1491418008,\"exp\":1491421608,\"name\":\"Samuel Walker\",\"picture\":\"https://lh4.googleusercontent.com/-UL0cJz_TTqQ/AAAAAAAAAAI/AAAAAAAAAjg/LotN970MHQY/s96-c/photo.jpg\",\"given_name\":\"Samuel\",\"family_name\":\"Walker\"}"
				}
			 */ 
			
			if (rawData.hasOwnProperty("oauthIdToken"))
			{
				
				FirebaseAuth.service.addEventListener(FirebaseAuthEvent.SIGNIN_WITH_CREDENTIAL_COMPLETE, handleSignInWithCredentail);
				
				if (rawData.providerId == "google.com")
				{
					
					var googleAuthCredential:AuthCredential = GoogleAuthProvider.getCredential(rawData.idToken, rawData.oauthIdToken);
					
					FirebaseAuth.service.signInWithCredential(googleAuthCredential);
				}
				else if (rawData.providerId == "facebook.com")
				{
					var facebookAuthCredential:AuthCredential = FacebookAuthProvider.getCredential(rawData.oauthIdToken);
					
					FirebaseAuth.service.signInWithCredential(facebookAuthCredential);
				}
			}
			else
			{
				throw new Error("No email returned through registration process");
			}
		}
````

Here is the handleSignInWithCredential function
````
		private function handleSignInWithCredentail(e:FirebaseAuthEvent):void 
		{
			trace("Credential signin success.");
			trace("success = " + e.success);
			trace("Message = " + e.message);
			trace(FirebaseAuth.service.getCurrentUser().identifier); // <- error thrown here. stacktrace shown below.
		}
````

This is the resulting output.


````
Raw data:
{
 json object with my info 
}

Auth changed.
Success = true

Credential signin success.
success = false
Message = An internal error has occurred. [ Invalid id_token in IdP response ]
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at service::Core/handleSignInWithCredentail()[C:\Users\Samuel Walker\Documents\MappKey\service\Core.as:566]
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at com.distriqt.extension.firebase.auth::FirebaseAuth/dispatchEvent()
	at com.distriqt.extension.firebase.auth::FirebaseAuth/extension_statusHandler()
````

**Comment by sfxworks** [comment]
> You should be able to pass null for the idToken in that case I believe for Google Auth. Let me know if that doesn't work and I'll go back and double check the docs.

I tried this method and I still get the same error. I am aware that the null reference happens due to the login failing but I do not understand why the id_token is not being accepted.

**Comment by marchbold** [comment]
I'm not sure what the oauthidtoken is that you are using, I'd suggest using:

```as3
GoogleAuthProvider.getCredential( rawData.idToken, null );
```

A valid Google Id token works in all our tests as above.

https://distriqt.github.io/ANE-Firebase/asdocs/com/distriqt/extension/firebase/auth/GoogleAuthProvider.html

**Comment by sfxworks** [comment]
I get the same error when passing idToken, null.

````
Message = An internal error has occurred. [ Invalid id_token in IdP response ]
````

**Comment by sfxworks** [comment]
var googleAuthCredential:AuthCredential = GoogleAuthProvider.getCredential(rawData.oauthIdToken, null);
Putting in the oauthIdToken in the first argument solves this.

**Comment by marchbold** [comment]
Glad you found the correct id token. That response you are using seems quite confusing.
