### ISSUE TITLE
IOS: not possible to 

### ISSUE THREAD

**Issue by megajogos** [distriqt/ANE-Firebase#230]
Hello @marchbold ,

I'm having this problem when I call the line:

var APP_KEY = "my key: I removed here to post on this issue";
Firebase.init(APP_KEY);

`Your key was not able to be verified for the com.distriqt.Firebase native extension`

I have already regenerated the key, and the libs are on the correct date. 
I also have downloaded/updated the last .ane libs.

What could be wrong?

It works perfectly on Android.

**Comment by marchbold** [comment]
Does the application id match the one you used to generate the key? 

Also make sure you have updated the dependency ANEs as well (Core/GPS/AndroidSupport).

**Comment by megajogos** [comment]
Yes the application id is correctly set. It is used in another libs not only on Firebase.

And I downloaded every lib

I copied your code from the examples:

```
		public function getOptions():void
		{
			ExtensionManager.log("DistriqtAnalyticsExtension.getOptions()");
			if (Firebase.isSupported)
			{
				ExtensionManager.log("DistriqtAnalyticsExtension.getOptions() 2");
				var options:FirebaseOptions = Firebase.service.getOptions();
				ExtensionManager.log("DistriqtAnalyticsExtension.options: " + options);
				
				if (options != null)
				{
					ExtensionManager.log(options.toString());
				}
				else
				{
					ExtensionManager.log( "APPLICATION NOT CONFIGURED" );
				}
			}
		}	
```

When I call:

`var options:FirebaseOptions = Firebase.service.getOptions();`

it breaks, it throws this exception:

`Error: Your key was not able to be verified for the com.distriqt.Firebase native extension`

very weird.

I also noted you said on:

https://distriqt.github.io/ANE-Firebase/Core%20-%20Add%20the%20extensions

> Note: The Google Play Services and Android Support ANEs are only required on Android devices. There is no problem packaging these ANEs with all platforms as there are default implementations available which will allow your code to package without errors however if you are only building an iOS application feel free to remove the Google Play Services ANEs from your application.

I maintained the libs, the distriqt ones I'm using are these:

```
	    <extensionID>com.distriqt.PushNotifications</extensionID>
	    <extensionID>com.distriqt.Core</extensionID>
	    <extensionID>com.distriqt.GameServices</extensionID>
	    <extensionID>com.distriqt.Firebase</extensionID>
	    <extensionID>com.distriqt.androidsupport.V4</extensionID>
	    <extensionID>com.distriqt.androidsupport.AppCompatV7</extensionID>
	    <extensionID>com.distriqt.androidsupport.CustomTabs</extensionID>
	    <extensionID>com.distriqt.playservices.Base</extensionID>
	    <extensionID>com.distriqt.playservices.Drive</extensionID>
	    <extensionID>com.distriqt.playservices.Analytics</extensionID>
	    <extensionID>com.distriqt.playservices.Location</extensionID>
	    <extensionID>com.distriqt.playservices.Games</extensionID>
	    <extensionID>com.distriqt.playservices.Auth</extensionID>
	    <extensionID>com.distriqt.firebase.Auth</extensionID>
	    <!-- <extensionID>com.distriqt.CustomResources</extensionID> -->
	    <extensionID>com.distriqt.Adverts</extensionID>
	    <extensionID>com.distriqt.playservices.Ads</extensionID>
	    <!-- <extensionID>com.distriqt.square.okhttp</extensionID> -->
	    <!-- <extensionID>com.distriqt.playservices.Identity</extensionID> -->
	    <!-- <extensionID>com.distriqt.GoogleIdentity</extensionID> -->
	 	<extensionID>com.distriqt.firebase.Crashlytics</extensionID>
	 	<extensionID>com.distriqt.JobScheduler</extensionID>
	 	<extensionID>com.distriqt.InAppBilling</extensionID>
	 	<extensionID>com.distriqt.FacebookAPI</extensionID>
	 	<extensionID>com.distriqt.Bolts</extensionID>
	 	<extensionID>com.distriqt.androidsupport.CardViewV7</extensionID>
	 	<extensionID>com.distriqt.androidsupport.Design</extensionID>
	 	<extensionID>com.distriqt.androidsupport.RecyclerViewV7</extensionID>	
```

**Comment by marchbold** [comment]
The error can indicate two things:

- You don't have the latest Core ANE;
- You are using an invalid application key.

If you have downloaded the latest Core ANE, then make sure your application key had the correct application id and that the Firebase ANE is included in the key. Then make sure you have copied it exactly from the site into your application with no spaces or carriage returns.
