### ISSUE TITLE
Firebase Auth still requires key

### ISSUE THREAD

**Issue by jasonJamEther** [distriqt/ANE-Firebase#232]
I just pulled the latest version of the ane with 64 bit for android. When I tried to access the firebase auth library I got an error saying I needed to first initialize it with a key. Was it intentional to keep the key required for this Ane? I have the master collection so I can spin up a new key, but I would rather remove the key it is intended to no longer be required like your other ANEs.

**Comment by marchbold** [comment]
Keys are still required for the Firebase ANEs.

**Comment by jasonJamEther** [comment]
Ok thank you.
