### ISSUE TITLE
Crashlytics displays just 1 crash, Android console displays 30 crashs

### ISSUE THREAD

**Issue by Marcophono2** [distriqt/ANE-Firebase#235]
Sorry for bothering again.
The Firebase CrashLytics ANE works fine since I was able to bring the Firebase ANE to run for Android (I had forgotten to add the customResouces ANE).
I have rolled out 36 hours ago new app version for Android and now there is only one entry in the CrashLytics while there are 30 in the Android console. Do you have an idea how this can happen? Does this mean that 29 of that 30 crashs happened before the CrashLytics code was initialized?
On the other hand side the only tracked crash with the ANE was not listed in the Android console. That's strange. 
I have attached an image of the Android console crashs and a txt file with the traces from the only registered crash in the CrashLytics ANE.

Best regards
Marc
![Android_console](https://user-images.githubusercontent.com/22599855/65798008-eb31b180-e170-11e9-8194-efb3c079bb43.png)
[ANE.txt](https://github.com/distriqt/ANE-Firebase/files/3664339/ANE.txt)

**Comment by marchbold** [comment]
It is expected that a reporting tool will generally gather less than the system level tools the android console gives you. They are always the best source. Other tools like crashlytics only gather certain types of crashes so there are always going to be some they just can't handle, or that occur before they are initialised. 

Those signal 11 crashes from the AIR libCore are one that we have seen a lot that don't seem to appear in crashlytics, so if you are getting a lot of those you'd expect a discrepancy.
