### ISSUE TITLE
com.distriqt.firebase.Config.ane

### ISSUE THREAD

**Issue by cph007g** [distriqt/ANE-Firebase#24]
UPDATE: SO I have to create this file (I was hoping to avoid this part)...... hmmmm

**Comment by cph007g** [comment]
Basically, I am getting two types of errors when trying to get this to work on the Android side(iOS side works)
1. [OPERATION_NOT_ALLOWED]
2. [PASSWORD_LOGIN_DISABLED]

I have all the sign-in types enabled on the Firebase console(I know because my iOS implementation works). I have also tried various apiKey/clientID credentials, with no luck. I have even checked the SHA1 Fingerprint, but I am not sure if initializing Firebase to use a Facebook token even requires the SHA1 at this point (I am assuming this is mostly a Google Identity thing).

Please help!! (I should have asked for help 12 hours ago) lol

**Comment by cph007g** [comment]
So I was able to successfully build the firebase.Config.ane, but when I add it to my project I get a long list of errors that start with: "unexpected failure: duplicate entry: air/com/apppackage/R.class"

I followed all the steps to build the Config.ane, took a while. Now what? :(

**Comment by cph007g** [comment]
Mission accomplished! I just rebuilt the Config.ane with ".test" added to the package name in the build_config. All errors are now gone, and Facebook Authentication now works! Hallelujah!!!

**Comment by marchbold** [comment]
Excellent glad you figured it out! Let me know if there's anything that could have been explained better in the docs.

**Comment by cph007g** [comment]
For the most part, the docs are clear, even the recommendation to create the Config.ane. However, I believe I assumed the package name would be identical to the package name we always use in the manifest files. Naturally, since I have been doing this sort of work for years, I decided to add .test to the package name when editing the build_config. So that particular sentence might need a little more clarification. 

In addition, I just decided to drop Google Plus authentication. I don't use Google Plus, and I think Facebook, Twitter, and e-mail authentication is enough for our users to choose from. At least for now.

Other minor issues I ran into were setting up Push Notifications on Android(I was getting duplicate and blank notifications), and having to ditch an AdMob ANE I bought a few months ago because of old Google Play implementations(but I found a free solution). The last ANE I will add to the mix is the inApp Billing, and most likely I will purchase this ANE from Distriqt in order to avoid any potential ANE conflicts/issues. I still desperately am searching for a Twitter ANE that will provide a token directly from the Twitter app so my users don't have to use a StageWebView sign-in flow(I typically don't like to login to other sites from within an app web browser). 

All in all, everything is working and I can go back to regular app customizations/implementations. Sometimes prioritizing the difficult tasks(ANE setup) is better, in that now it is all down hill from here with easy app updates/implementations.

Best Regards!! Keep up the good work!

**Comment by cph007g** [comment]
Michael,

It seems now I am having a ANE conflict with the Push Notification ANE and an Admob ANE from another vendor. Could you add a beta test version of the Distriqt Adverts ANE and the In-App Billing so I can determine if this is the case. As soon as I implement both, I will purchase both. Thanks in advance!

**Comment by KreedaSolutions** [comment]
Just want to understand why we need this - 

""I just rebuilt the Config.ane with ".test" added to the package name in the build_config.""

so if my package name is "air.kreeda.apple", shall i set built cofing this way - 
# 
android.package = air.kreeda.apple.test
android.resources = res

If so, then just want to understand why? and is this for something like Development of even for production?
