### ISSUE TITLE
conflict libraries

### ISSUE THREAD

**Issue by Tantanyel** [distriqt/ANE-Firebase#240]
I use ironsource libraries:
https://dl.bintray.com/ironsource-mobile/adobeair-adapters/SupportV4_v1.0.1.ane
https://bintray.com/ironsource-mobile/adobeair-adapters/download_file?file_path=GooglePlayServices_v12.0.1.ane

They conflict with firebase libraries:
com.distriqt.androidsupport.V4.ane
com.distriqt.playservices.Base.ane

What am I to do? Without these, the ironsource library does not work.

**Comment by marchbold** [comment]
You should be able to replace the ones IronSource use with ours, you can only include one version of a library on Android.
