### ISSUE TITLE
Help to Change GA Data to Firebase Code

### ISSUE THREAD

**Issue by apofis1969** [distriqt/ANE-Firebase#241]
Could you please give me an advice how I can move the Events I created with the Google Analytics ANE to the Firebase. Such as my Button Events inside the app. What would be the best way to code this?
Please see this example:
tracker.send( 
new EventBuilder()
.setCategory( "Mouse Event" )
.setLabel( trackerButtonLabel )
.setAction( "click" )
.build() );

Could this be the right way?
public static function buttonEvents(button:String):void{
	var event:EventObject = new EventObject();
	event.name = EventObject.SELECT_CONTENT;
	event.params[Params.GROUP_ID] = "Mouse_Event";
	event.params[Params.CONTENT_TYPE] = button;
        Firebase.service.analytics.logEvent( event );
}

No one of my events created with iOS is not appearing in the Firebase Web+App property I created.
The only event is working is the screen event

One more question: do I have to combine phrases such as iOS v. 1.1.494, which worked with GA, always to iOS_v_11494, because the custom event with the spelling as I used with GA did not appear at the Firebase Console.

I say thank you for your advice!

I just created the custom resources ane. You do not need to send it to me and generate.

**Comment by marchbold** [comment]
Probably best to ask Firebase support about the best way to migrate from GA. We only really have used Firebase directly for our needs so haven't had to do a migration.
