### ISSUE TITLE
Google app+web property, not reporting data

### ISSUE THREAD

**Issue by jasonbuscema** [distriqt/ANE-Firebase#242]
I've done all that I can to get Firebase ANE working with Google Analytics and I cannot get it working with Android, only iOS. 

I am using a Custom ANE following your guide for android. I am using the 64bit version and creating the ANE which gets included at build time. I have been doing this for awhile now for the icons so adding in the values.xml file info was not hard. I have updated the descriptor file to match what you have in your guide. 

In Firebase, my app is setup as air.com.company.projectname for android, and com.company.projectname for iOS. 

I am using the app+web property (google analytics) which is automatically created by Firebase.

iOS works fine and I see real-time analytics. I cannot get android devices to show any data at all.

Again here is the high level:

- Created air.com.company.projectnamee android app in firebase
- Downloaded the google-services.json file
- Used the converter to create values.xml
- Place values.xml in res/values/values.xml for custom ANE
- build ANE
- ANE is included in app at build time
- Using Harman Adobe SDK 33.0.2.246 to do the build (64bit support)
- Load APK to test device(s)
- App loads but no data is being reported to Firebase using APK

What am I missing? Is it possible the Firebase ANE doesn't fully support the new Google app+web property?

**Comment by marchbold** [comment]
Could you post the logs from the device? 

Does your values xml have the analytics property set?
