### ISSUE TITLE
Unable to generate the configuration ANE

### ISSUE THREAD

**Issue by robertsayegh1** [distriqt/ANE-Firebase#244]
Hello,

Two days ago we have purchased Firebase ANE, and now trying to set it up for Google Analytics, but we are facing some difficulties. Can you please help with the below:

We have reached the point to generate the ANE for ANDROID configuration, we have created the Firebase Project with Success and downloaded both config files from there, and Firebase has created a new property in Googl Analytics , We have started adjusting the Values.xml and reached the point to pull the ga_trackingId from the config file but with no success because it is not there, so we went to the newly created property in Google Analytics and obtained the number from there, and we noticed that its format is different than the one in your documentation, all files are attached, is that OK?

By the way the app we are going to add the ANE in has Push notifications ON, with a component from a different supplier, do you think installing Firebase ANE will affect the Push notifications?
Moving forward and following you documentation, we have done the required setup for all required components, We already have Adobe Air SDK 32 and 33, we have installed ANT latest version and we have Android studio installed with the SDK in the location as per the config file attached, when we try to generate the ANE we get the below result, also attached. We have attached all the needed, we do not have a problem if you generate the ANE for us or if you help us to generate the ANE. 
C:\inetpub\wwwroot\VirginMobileAppV3\Anaylitcs\ANE-CustomResources-master>ant
Buildfile: C:\inetpub\wwwroot\VirginMobileAppV3\Anaylitcs\ANE-CustomResources-master\build.xml
[taskdef] Could not load definitions from resource flexTasks.tasks. It could not be found.
clean:
[taskdef] Could not load definitions from resource flexTasks.tasks. It could not be found.
clean_actionscript:
[taskdef] Could not load definitions from resource flexTasks.tasks. It could not be found.
clean_default:
[taskdef] Could not load definitions from resource flexTasks.tasks. It could not be found.
clean_android:
build:
[taskdef] Could not load definitions from resource flexTasks.tasks. It could not be found.
build_actionscript:
[echo] Building actionscript library...
BUILD FAILED
C:\inetpub\wwwroot\VirginMobileAppV3\Anaylitcs\ANE-CustomResources-master\build.xml:218: The following error occurred while executing this line:
C:\inetpub\wwwroot\VirginMobileAppV3\Anaylitcs\ANE-CustomResources-master\build.xml:115: Problem: failed to create task or type compc
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
Total time: 0 seconds
Kindly note that we have created the three variables as well 
Thank you
Robert

**Comment by marchbold** [comment]
Hi, 

Looks as though you haven't correctly set the path to the AIR SDK in the configuration files. Can you double check the path you have set?

**Comment by robertsayegh1** [comment]
Following my research on your forums, we have reached this case and this is why we moved all the folder of the Airsdk to root to try it and it did not work.  Should this be the link to the root of the SDK or to any folder inside the SDK?

**Comment by marchbold** [comment]
Not really sure what you mean. Those tasks are loaded from the AIR SDK so the script isn't getting the correct path to your AIR SDK. You need to set the path in your `build.config` file:

> On Windows it will look something like the following, you must make sure to use two backslashes to correctly escape a backslash:
>
> ```
> # AIR SDK
> air.sdk = C:\\Users\\username\\sdks\\air\\AIRSDK_22.0.0.153
> 
> # ANDROID
> android.sdk = C:\\Users\\username\\AppData\\Local\\Android\\sdk
> ```

**Comment by marchbold** [comment]
https://github.com/distriqt/ANE-CustomResources/#custom-android-resources
