### ISSUE TITLE
Do we need to log reserved events?

### ISSUE THREAD

**Issue by Faketa** [distriqt/ANE-Firebase#247]
Hi, do we need to log Firebase reserved events like in_app_purchase or those events will be logged automatically?

**Comment by marchbold** [comment]
They are logged automatically by the Firebase SDK. You should not have to do anything to get these events in the console apart from correctly configure your application.

https://support.google.com/firebase/answer/6317485?hl=en

**Comment by Faketa** [comment]
Thanks
