### ISSUE TITLE
iOS 10.2.1 and AIR SDK 25 beta

### ISSUE THREAD

**Issue by cph007g** [distriqt/ANE-Firebase#25]
Anyone else experiencing issues with these two updates?

**Comment by marchbold** [comment]
Can you elaborate a little more?

**Comment by cph007g** [comment]
At the moment I think I have isolated AIR 25 SDK errors to all functions with URLRequest and URLLoader. So I don't think any url requests are making their way out of my app via firebase on iOS.  .load seems to work, but as stated above, everything else is broken.

**Comment by marchbold** [comment]
Is this related to app transport security at all? I'm assuming you are using https for everything?

Are you getting any errors otherwise could you post the logs from the device?

https://airnativeextensions.com/knowledgebase/faq/11

**Comment by cph007g** [comment]
Yes, I am using https for everything. I will see about posting the logs as soon as I am back in the office.

**Comment by cph007g** [comment]
I decided to stay with AIR 23 SDK and wait until a non-beta version of the AIR 25 SDK is available.

**Comment by marchbold** [comment]
Honestly thats a good idea, there are normally a few issues with the betas. We will be testing all our ANEs with 25 over the coming weeks.
