### ISSUE TITLE
Implementation of Crash Reporting

### ISSUE THREAD

**Issue by marchbold** [distriqt/ANE-Firebase#26]
Firebase Crash Reporting 

https://firebase.google.com/docs/crash/

**Comment by sfxworks** [comment]
I was wondering...It seems you already have an [exception tracker](https://github.com/distriqt/ANE-Exceptions) that I was planning on using. Would it be hard to patch this to the Firebase build within a few hours? It seems like exception submission is just a few lines of code for [Android](https://firebase.google.com/docs/crash/android) and [iOS](https://firebase.google.com/docs/crash/ios).

**Comment by marchbold** [comment]
Just finished up the implementation of this actually. Will release over the weekend.

Cheers

**Comment by sfxworks** [comment]
Awesomeness! Great work!
