### ISSUE TITLE
Analytics not working on IOS 10.2.1 and AIR 25 beta

### ISSUE THREAD

**Issue by mwelk** [distriqt/ANE-Firebase#27]
I get the following error trying to use the Firebase Analytics Service  v10.0.1 on IOS 10.2.1 and AIR 25 beta:

```
<FIRAnalytics/ERROR> Data loss. Cannot record raw event. Error: Error Domain=com.google.gmp.measurement.ErrorDomain Code=3 "Database operation "execute statement" failed with sqlite code 20 and error message "could not convert floating point value to integer without loss of data."" UserInfo=\{FIRAMonitorContext=execute statement,20,A,4, NSLocalizedDescription=Database operation "execute statement" failed with sqlite code 20 and error message "could not convert floating point value to integer without loss of data."\}
<Notice>: <FIRAnalytics/ERROR> Transaction failed
```
Configuration is done by `GoogleService-Info.plist`

It is working fine on Android with AIR 25 beta.

**Comment by marchbold** [comment]
Hi,

There is currently an issue with Firebase Analytics on iOS and AIR that is causing this issue. We have reported it to the Firebase team however we are waiting for a fix from them. Appears there is some sql issue which you may have noticed from the error.

**Comment by mwelk** [comment]
Hi,
thanks for the update.
Meanwhile I found the same issue reported on the github firebase project [https://github.com/firebase/quickstart-ios/issues/34](url)
It seems, that the bug is fixed since 2 days. I'm looking forward to see the new sdk version linked to this ANE.

**Comment by ambient-sky** [comment]
Likewise, as a paying customer, no that the Firebase team has fixed the bug in version 3.7 we're eagerly awaiting a new Distriqt ANE. Thanks for doing what you can to expedite a new build.

**Comment by marchbold** [comment]
Ah thanks for pointing that out. Will get the update into the build today.

**Comment by ambient-sky** [comment]
Super! We've confirmed the latest Firebase ANE is now working with our AIR 23 app on iOS. Thanks for the quick turnaround!

**Comment by marchbold** [comment]
Excellent, thanks for confirming. 

Still seems to have a long delay, hopefully they will improve it to become at least comparable to GA eventually.
