### ISSUE TITLE
Building Config ANE fails with "replace" error

### ISSUE THREAD

**Issue by chichilatte** [distriqt/ANE-Firebase#28]
A quick tip for anyone struggling with building the Config ANE... 

Running the ant command I was getting the error:
```
ANE-Firebase/config/build.xml:45: javax.script.ScriptException: sun.org.mozilla.javascript.internal.EvaluatorException: The choice of Java constructor replace matching JavaScript argument types (function,string) is ambiguous; candidate constructors are:
class java.lang.String replace(java.lang.CharSequence,java.lang.CharSequence)
class java.lang.String replace(char,char)
```
I fixed it by changing a line in the build.xml script from...
`	attributes.get( "value" ).replace( /\./g, "/" ) );
`
to 
`	attributes.get( "value" )+"".replace( /\./g, "/" ) );
`

I was also getting the error:
`
Asset package include '/opt/android-sdk/platforms/android-23/android.jar' not found.
`
All that was needed was to open up the Android SDK Manager and install the **SDK Platform (API version 23)**.

**Comment by marchbold** [comment]
That change doesn't look quite right. What platform/version are you running the script on?

**Comment by chichilatte** [comment]
Argh, I think you're right, it needs some brackets, like...
```(attributes.get( "value" )+"").replace( /\./g, "/" ) );```

Firebase doesn't seem to be receiving my events (takes 24 hours so is hard to test!), and this might be the problem.

FYI I'm on OSX10.10.5, and my java says it's version 1.6.0_65. The Distriqt firebase is just the latest version from this repo.

**Comment by marchbold** [comment]
Yeah that looks better. Interesting there must be a null value or something being passed to that script at some point. 

What events are you talking about? If you are talking about analytics they are really slow, no where near as good as Google Analytics, and currently don't work on iOS due to a conflict with AIR and the Firebase SDK. They are aware of it and we are hoping for a fix soon.

**Comment by chichilatte** [comment]
I think java doesn't know which type the `replace` params are, `java.lang.CharSequence` or just `char`. No idea why. Maybe because my java version is quite old (from 2013). I got it all working after much thumb twiddling.

Also, another handy tip: if you link your Firebase to Google BigQuery (on the Firebase console's Events page) you can see the events come in live, if you know a bit of SQL. I think you also need to tell your phone to send events immediately instead of in batches – you'd do this in the terminal...
`adb shell setprop debug.firebase.analytics.app <your_app_package_name>`

We didn't use GA because you can't get access to raw events without paying $150,000 per year!
