### ISSUE TITLE
getCurrentUser() and UID

### ISSUE THREAD

**Issue by philvessey** [distriqt/ANE-Firebase#29]
Can you amend the getCurrentUser() call to provide the UID that firebase gives that user - as shown in attached screenshot - would be useful to be able to use that UID as a key to link to items in the database - you could do it by email address but would then have a nightmare if the user wants to update their email address - the key is better, its unique.

![firebase](https://cloud.githubusercontent.com/assets/814882/23104115/a42146c8-f6bf-11e6-8b0e-81f888c9c653.PNG)

**Comment by marchbold** [comment]
Have you checked the `identifier` value:

https://distriqt.github.io/ANE-Firebase/asdocs/com/distriqt/extension/firebase/auth/user/FirebaseUser.html#identifier

**Comment by philvessey** [comment]
Ah yes, that's the UID - thanks. Not sure how I missed that to be honest :)
