### ISSUE TITLE
getCurrentUser().displayName Not Updating Correctly

### ISSUE THREAD

**Issue by philvessey** [distriqt/ANE-Firebase#30]
getCurrentUser().displayName isn't updating after a call to FirebaseAuth.service.getCurrentUser().updateProfile(request);

The actual update happens correctly in the backend but the getCurrentUser().displayName value doesn't update with the new value until you sign out and then sign back in again.

**Comment by marchbold** [comment]
Is this occurring on iOS or Android and what versions have you tested? 

Cheers

**Comment by philvessey** [comment]
Android - I'm using the latest versions of the extensions that I downloaded from the repo yesterday a few hours before posting the issue.

**Comment by marchbold** [comment]
Sorry, I meant what versions of Android?

**Comment by philvessey** [comment]
7.1.1 on a Pixel XL

**Comment by marchbold** [comment]
Cheers, I'll check into it.

**Comment by marchbold** [comment]
Could you post the code you are using to cause this issue, having troubles replicating it.

**Comment by philvessey** [comment]
Sure:

`
var builder:UserProfileChangeRequestBuilder = new UserProfileChangeRequestBuilder();
builder.setDisplayName("Test Name");
builder.setPhotoUri(FirebaseAuth.service.getCurrentUser().photoUrl);

FirebaseAuth.service.getCurrentUser().addEventListener(FirebaseUserEvent.UPDATE_PROFILE_COMPLETE, handlerUser);
FirebaseAuth.service.getCurrentUser().updateProfile(builder.build());
`

**Comment by philvessey** [comment]
Were you able to reproduce with the example I sent?

**Comment by marchbold** [comment]
Still working on it.

**Comment by marchbold** [comment]
Just a small update here, this appears to be a bug in the Firebase SDK that apparently was introduced in v9.8.0 and everyone is waiting for a fix.

- http://stackoverflow.com/questions/41435182/cant-update-user-display-name-and-photo-url-in-firebase
- http://stackoverflow.com/questions/41266768/firebase-updating-displayname-via-android-app

We've just tried the most recent update (10.2.0) and the bug still remains.

**Comment by philvessey** [comment]
Ok thanks.

**Comment by marchbold** [comment]
This appears to be resolved in the v11.0.0 update. Let me know if you are still having issues after updating.
