### ISSUE TITLE
Add Display Name To createUser method

### ISSUE THREAD

**Issue by dannycortesv** [distriqt/ANE-Firebase#31]
Add DisplayName to this method: FirebaseAuth.service.createUserWithEmailAndPassword 
This is very useful, so we can send confirmation email with users name :)

**Comment by marchbold** [comment]
Have you got a link to the functionality in the SDK that implements this?

**Comment by marchbold** [comment]
Hi, As we can't find anything like this in the SDK I'm going to close this issue. If you find a link to the functionality you want implemented, please let me know.
