### ISSUE TITLE
photoUri and photoUrl

### ISSUE THREAD

**Issue by philvessey** [distriqt/ANE-Firebase#32]
There looks to be some inconsistency in the ANE for storing the users photo. In UserProfileChangeRequestBuilder() its referred to as setPhotoUri and in FirebaseAuth.service.getCurrentUser() its referred to as photoUrl

Is this intentional or is it an error as it can cause confusion.

**Comment by marchbold** [comment]
Yeah that's an inconsistency. Will get that corrected.
