### ISSUE TITLE
ServerValue

### ISSUE THREAD

**Issue by oxmond** [distriqt/ANE-Firebase#34]
Are you planing on including constants for server values?

**Comment by marchbold** [comment]
Can you be a little more specific on what values you are referring too?

**Comment by oxmond** [comment]
ServerValue.TIMESTAMP

**Comment by marchbold** [comment]
So appears you are referring to classes in the Firebase Database component:

- https://firebase.google.com/docs/reference/ios/firebasedatabase/api/reference/Classes/FIRServerValue
- https://firebase.google.com/docs/reference/android/com/google/firebase/database/ServerValue


 Will get this into the next release.
