### ISSUE TITLE
"Invalid Bundle Structure" when using the Storage.ane and uploading to Appstore

### ISSUE THREAD

**Issue by oxmond** [distriqt/ANE-Firebase#35]
![screen shot 2017-02-28 at 10 57 23](https://cloud.githubusercontent.com/assets/455228/23400644/f7a2b3cc-fda4-11e6-9dec-ed1316fa4c50.png)

**Comment by marchbold** [comment]
Thanks for reporting this, we will check into it.

**Comment by marchbold** [comment]
I can't seem to replicate this error, what version of AIR are you using to package your application?

**Comment by oxmond** [comment]
24.0.0.180

**Comment by marchbold** [comment]
What other ANEs are you using in your project?

**Comment by phihochzwei** [comment]
Got the same problem but with Firebase and PushNotifications

`Invalid Bundle Structure - The binary file 'Call_of_Duty.app/FirebaseInstanceID.framework/FirebaseInstanceID' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide for information on the iOS app bundle structure.

Invalid Bundle Structure - The binary file 'Call_of_Duty.app/GoogleSymbolUtilities.framework/GoogleSymbolUtilities' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide for information on the iOS app bundle structure.

Invalid Bundle Structure - The binary file 'Call_of_Duty.app/GoogleInterchangeUtilities.framework/GoogleInterchangeUtilities' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide for information on the iOS app bundle structure.

Invalid Bundle Structure - The binary file 'Call_of_Duty.app/FirebaseCore.framework/FirebaseCore' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide for information on the iOS app bundle structure.

Once these issues have been corrected, you can then redeliver the corrected binary.`

**Comment by marchbold** [comment]
How are you packaging your application to get this error?

**Comment by phihochzwei** [comment]
Via mxmlc through an ANT-Task run by a Jenkins

**Comment by marchbold** [comment]
Are you including the ANE as an asset or something in your application?

**Comment by phihochzwei** [comment]
Not really. I package them via -extdir into the ipa. doing this for ages and never any complains from apple

**Comment by phihochzwei** [comment]
Here is how the ANT-Target looks like:

`<target name="package.apple">

        <property name="APPLE.PROV" value="${ZIPTMP}/${PROVISIONING.${STATE}}.mobileprovision"/>

        <echo message="Packaging iOS Device with ${APPLE.PROV} and ${CERTIFICATE.APPLE.${STATE}.FILE}"/>
        <exec executable="${ADT}" dir="${DEPLOY_DIR}/apple">
            <arg line="-package -target '${APPLE.TARGET}'"/>
            <arg line="-provisioning-profile '${APPLE.PROV}'"/>
            <arg line="-storetype pkcs12"/>
            <arg line="-keystore '${CERTIFICATE.APPLE.${STATE}.FILE}'"/>
            <arg line="-storepass '${CERTIFICATE.APPLE.${STATE}.PASSWORD}'"/>
            <arg line="'${PROJECTNAME}.ipa'"/>
            <arg line="'${DEPLOY_DIR}/${MANIFEST}'"/>
            <arg line="'${PROJECTNAME}.swf'"/>
            <arg line="icons html ${splashscreen} default GoogleService-Info.plist"/>
            <arg line="-extdir ${ANE_DIR}"/>
            <arg line="-platformsdk ${IOSSDK}"/>
        </exec>
        <move file="${DEPLOY_DIR}/apple/${PROJECTNAME}.ipa" tofile="${DEPLOY_DIR}/${PROJECTNAME}.ipa"/>
    </target>`

**Comment by marchbold** [comment]
Well this error occurs because the frameworks are in your ipa. They shouldn't be there, so something is going wrong with the packaging process. They are in the ANE but should be compiled into your applications executable and not included in the `ipa`

Can you unzip your `ipa` and check if the `framework` folders are being included?

**Comment by phihochzwei** [comment]
just a second

**Comment by phihochzwei** [comment]
I think the answer is yes: 
![bildschirmfoto 2017-03-23 um 09 51 56](https://cloud.githubusercontent.com/assets/10193885/24239537/9833f466-0fae-11e7-9047-39b08ecd36df.png)

**Comment by marchbold** [comment]
Have you got those frameworks somewhere in your project? Or have you extracted the ANE somewhere?

**Comment by phihochzwei** [comment]
No. I just included the ANE´s like I always do.

**Comment by marchbold** [comment]
Are you using the latest version of the ANE? If it was the current ANE there should be some additional frameworks there.

**Comment by phihochzwei** [comment]
Not the latest, just got a message about a new commit. I use the one from the 15th of march

**Comment by marchbold** [comment]
Which version of AIR are you using?

**Comment by phihochzwei** [comment]
AIR 25

**Comment by marchbold** [comment]
Could you try the most recent version, it's been built with AIR 25.

**Comment by phihochzwei** [comment]
okay. just a minute

**Comment by marchbold** [comment]
Did you check the `ipa`? Any frameworks in there?

**Comment by phihochzwei** [comment]
Jepp, still there and same response from Apple

![bildschirmfoto 2017-03-23 um 10 29 19](https://cloud.githubusercontent.com/assets/10193885/24241016/bfc799ba-0fb3-11e7-8884-2b946cbcb9dd.png)

**Comment by marchbold** [comment]
Hmmm, they aren't even the same frameworks in the current ANE. Are you sure you don't have them somewhere on your file system?

**Comment by phihochzwei** [comment]
I just looked into the ANE and I found those 4 folders in there.

**Comment by marchbold** [comment]
Should have these in it:

FirebaseAnalytics.framework
FirebaseCore.framework
FirebaseInstanceID.framework
GoogleToolboxForMac.framework

**Comment by marchbold** [comment]
We've just pushed another update for another fix, perhaps grab the most recent and make sure you've cleared any caches on your machine.

**Comment by phihochzwei** [comment]
fetching/pulling. just a second

**Comment by phihochzwei** [comment]
pulled it, now moving it to the jenkins and try again. just a second

**Comment by phihochzwei** [comment]
okay, with that version I only have FirebaseCore.framework and FirebaseInstanceID.framework in the IPA

**Comment by marchbold** [comment]
hmmm, better but still not right... what target are you using?

**Comment by phihochzwei** [comment]
ipa-app-store

**Comment by marchbold** [comment]
So I've just done a very simple test:

```
adt -package -target ipa-app-store \
	-provisioning-profile distriqt_test_distribution_profile.mobileprovision \
	-storetype pkcs12 \
	-keystore Certificates.p12 \
	-storepass XXXXXXX \
	TestFirebase.ipa \
	TestFirebase-app.xml \
	TestFirebase.swf \
	icons GoogleService-Info.plist \
	-extdir anes \
	-platformsdk /Users/marchbold/work/sdks/ios/iPhoneOS10.2.sdk 
```

And it hasn't included those frameworks. Which exact version of AIR are you using?

**Comment by marchbold** [comment]
Actually, what other ANEs are you using?

**Comment by phihochzwei** [comment]
Cant find a subversion number in the AIR folder. Any clues?

**Comment by marchbold** [comment]
Are you using the release version of 25? i.e. didn't grab it off labs?

**Comment by phihochzwei** [comment]
all ANEs 
<img width="335" alt="bildschirmfoto 2017-03-23 um 11 28 58" src="https://cloud.githubusercontent.com/assets/10193885/24243629/04941a16-0fbc-11e7-85e5-1133d26b7fa8.png">

**Comment by phihochzwei** [comment]
I think it´s the Labs version.

**Comment by phihochzwei** [comment]
Will grab the latest version swiftly. Just a minute

**Comment by phihochzwei** [comment]
Just a second, seems the Apache Installer is broken. Installing manually

**Comment by phihochzwei** [comment]
Okay, lastest version of AIR (just downloaded) but still FirebaseCore.framework and FirebaseInstanceID.framework in the IPA

**Comment by marchbold** [comment]
Gosh, this is our fault. It's been accidentally included in the Push Notifications all services ANE...

Will get a fix done ASAP!

**Comment by marchbold** [comment]
Major apologies about that, not sure how those frameworks slipped into the PushNotifications ANE. 

Update is uploading now, could you grab it and let us know if you are still having any issues?

**Comment by phihochzwei** [comment]
Will do asap. Currrently in the road

Von meinem iPhone gesendet

**Comment by phihochzwei** [comment]
Looks good. App now in Submission (as a sidenote: I hate apple for their "redundant binary"-bullsh

**Comment by marchbold** [comment]
I hear ya! 

Thanks for working with us on this issue.

**Comment by phihochzwei** [comment]
as always, my pleasure :) Thanks for the fast help
