### ISSUE TITLE
[Android] NotificationReceiver null

### ISSUE THREAD

**Issue by railnation** [distriqt/ANE-Firebase#36]
Hi, 
On Android there is no Notification coming up. 
[log.txt](https://github.com/distriqt/ANE-Firebase/files/806332/log.txt)
Looks like the NotificationReceiver is null. 

Some notes from my side:

1. IOS Push works fine
2. Both the manual FireBaseConfig and the Config.ane does not work
3. The device token from Pushnotification looks fine

any hint?

Best regards

Edit: Maybe it is the interface between our backend and GCM/FCM. Test message from Firebase console shows up

**Comment by marchbold** [comment]
What payload are you sending? You need to send the specific fields to display a notification. See the Push Notifications docs for more.
