### ISSUE TITLE
Errors not reporting?

### ISSUE THREAD

**Issue by sfxworks** [distriqt/ANE-Firebase#37]
I am using Firebase Core and Firebase crash reporting. I have a scenario where I am running a lot of functions under a try catch and if there is an error, it throws the error to this function.

````
NativeMaps.service.hideMap();
			toggleContent(999); //Hides everything
			trace(e.errorID + "  " + e.name + "  " + e.message + "\n" + e.getStackTrace());
			exception_txt.text = e.errorID + "  " + e.name + "  " + e.message + "\n" + e.getStackTrace();
			exception_txt.visible = true;
			FirebaseCrash.service.report(e);
````

I am able to successfully get a test error and other errors displayed on my phone. However, they do not show up in my Firebase project.
![image](https://cloud.githubusercontent.com/assets/5921035/23438250/2a4cd368-fddf-11e6-93d4-4ababa1ae5b0.png)
![image](https://cloud.githubusercontent.com/assets/5921035/23438265/34f96704-fddf-11e6-98e0-e38837f7ff36.png)

I have my google json file in my main directory and firebase core and crash init just fine with my app key..

**Comment by marchbold** [comment]
Please double check that you have correctly created the configuration ANE and are including that with your application:

https://github.com/distriqt/ANE-Firebase/wiki/Setup---Configuration-Files#create-android-resource

**Comment by sfxworks** [comment]
Hi.
I am using the Delayed Configuration method. I will mention I forgot to include my google-services.json file but I have it included now and I still don't see any errors. Does Firebase update instantly or daily? (I really wish FirebaseCrash would let me know what I am doing wrong through an error or something)

**Comment by marchbold** [comment]
Please try the resource method, it's much more reliable. The delayed configuration currently still has some issues.

**Comment by marchbold** [comment]
Hi, I'm going to close this issue for now, but please let me know if you are having issues with the new resources ane script.
