### ISSUE TITLE
"Error creating files." on Android when i updated to v1.1.002

### ISSUE THREAD

**Issue by oxmond** [distriqt/ANE-Firebase#38]
![error](https://cloud.githubusercontent.com/assets/455228/23455924/bb10a9fa-fe71-11e6-9acb-fc8ec2d85d85.PNG)

**Comment by philvessey** [comment]
Just got a similar error when I updated the extensions also. I'm using AIR 23.

![2017-03-01](https://cloud.githubusercontent.com/assets/814882/23479769/7d8c7568-febd-11e6-8f1b-405f7851f35a.png)

**Comment by marchbold** [comment]
Have you updated the Google Play Services ANEs as well?

**Comment by philvessey** [comment]
Yes

**Comment by marchbold** [comment]
Ah apologies, I've found the error, will update momentarily.

**Comment by philvessey** [comment]
Awesome thanks.

**Comment by philvessey** [comment]
Thanks, compiling and packaging correctly now.
