### ISSUE TITLE
SWC outdated

### ISSUE THREAD

**Issue by phihochzwei** [distriqt/ANE-Firebase#39]
When trying to compile through mxmlc I receive the following problem error

`Error: Call to a possibly undefined method initialiseApp through a reference with static type com.distriqt.extension.firebase:Firebase
`

I took the SWC from the ANE I pulled the GIT

**Comment by marchbold** [comment]
Thanks for reporting this, will get this corrected asap.

**Comment by phihochzwei** [comment]
Is it possible, that you did not commit the file :) ? 

Because there is no new firebase.ane in the commit

**Comment by marchbold** [comment]
Apologies, something went wrong with our release script. Will update shortly.

**Comment by phihochzwei** [comment]
Awesome, works like charm 👍
