### ISSUE TITLE
FirebaseAuthEvent.SIGNIN_WITH_CREDENTIAL_COMPLETE not dispatching on android

### ISSUE THREAD

**Issue by oxmond** [distriqt/ANE-Firebase#40]
And I get no message from FirebaseAuthEvent. But success is true.

**Comment by marchbold** [comment]
Can you post the logs from this device? What version of Android are you running and what credential provider are you using?

**Comment by oxmond** [comment]
I dont know how to get the Device log on android. Tried Logcat but to no effect. 
I'm running Android version 6.0 and i'm using FacebookAuthProvider
`FirebaseAuth.service.addEventListener(FirebaseAuthEvent.SIGNIN_WITH_CREDENTIAL_COMPLETE,onSignInResult);
FirebaseAuth.service.signInWithCredential(FacebookAuthProvider.getCredential(Session.fbToken));`

The setup works as intended on ios but nothing happens on android.

I am using Delayed Configuration for the google-services.json
and calling signInWithCredential a few seconds later (I have tried waiting longer)

**Comment by marchbold** [comment]
Have you tried using the resources config method, the delayed method is unreliable still.

**Comment by oxmond** [comment]
Ok i just managed to make the com.distriqt.firebase.Config.ane to test the resources config method. 
But i get the following error when publishing:
![udklip](https://cloud.githubusercontent.com/assets/455228/23698907/9248f906-03ed-11e7-8e72-6f33d0471a6f.PNG)

**Comment by marchbold** [comment]
Could you tell me what version of java and the android sdk you are using to create the config ane?

**Comment by oxmond** [comment]
jdk1.8.0_91
Android SDK 25.3.0

**Comment by marchbold** [comment]
What version of Windows are you using?

**Comment by marchbold** [comment]
Could you try the updated script in the CustomResources repository and let us know if you are still having this issue?
