### ISSUE TITLE
Storage points to bucket distriqt-firebase-test

### ISSUE THREAD

**Issue by philvessey** [distriqt/ANE-Firebase#41]
Hi

Been trying to get FirebaseStorage to hook up to my storage bucket but when I trace out the below:

var storage:StorageReference = FirebaseStorage.service.getReference("me.jpg");
trace(storage.getBucket());

I get distriqt-firebase-test.appspot.com as the bucket. I'm pretty sure something in the extension is still pointing to your test bucket and not the bucket for my project.

**Comment by marchbold** [comment]
Have you correctly added the storage bucket to your resources ANE? Is this on Android or iOS BTW?

**Comment by philvessey** [comment]
Android 7.1.1. I have checked the Config.ANE and there is nothing in that referring to distriqt-firebase-test.appspot.com

**Comment by philvessey** [comment]
Should there be an entry in values.xml that refers to the storage bucket? There isn't one in the template in the config directory in the repo or on the wiki

**Comment by marchbold** [comment]
Hmm yeah must have missed updating that, will get that updated next week. In the meantime you should have the following:

```as3
<?xml version="1.0" encoding="utf-8"?>
<resources>
	<string name="google_app_id" translatable="false">XXX</string>
	
	<string name="gcm_defaultSenderId" translatable="false">XXX</string>
	<string name="default_web_client_id" translatable="false">XXX</string>
	<string name="ga_trackingId" translatable="false"></string>
	<string name="firebase_database_url" translatable="false">XXX</string>
	<string name="google_api_key" translatable="false">XXX</string>
	<string name="google_crash_reporting_api_key" translatable="false">XXX</string>
	
	<string name="google_storage_bucket" translatable="false">XXX</string>

</resources>
```

**Comment by philvessey** [comment]
<string name="google_storage_bucket" translatable="false">XXX</string> is missing from config/res/values/values.xml and the wiki so it definitely needs to be updated.

One thing that's strange though, if the lines missing for the storage bucket, how does the extension know to use distriqt-firebase-test.appspot.com as the bucket?

I will update my config ane today and report back if that corrects the error and it can connect to the correct bucket.

**Comment by philvessey** [comment]
Works fine with that line added, now points to the correct bucket and I can download a file. Once the wiki is updated and config/res/values/values.xml has the new line added to the template you should be able to close.

**Comment by marchbold** [comment]
Thanks for the confirmation
