### ISSUE TITLE
Storage Documentation Errors

### ISSUE THREAD

**Issue by philvessey** [distriqt/ANE-Firebase#42]
Finally managed to get the Storage extension to download a jpg file from my storage bucket. Noticed a few issues with the documentation in doing so. Firstly when downloading a file I had to listen to the DownloadTaskEvent.COMPLETE event and not the SUCCESS event. The SUCCESS event never gets triggered and I'm not sure what the difference between SUCCESS and COMPLETE is.

Secondly the wiki refers to var data:ByteArray = event.snapshot.bytes; when using getBytes() but in the extension its event.taskSnapshot.bytes - could catch a few people out if not using intellisense etc.

**Comment by marchbold** [comment]
What platform/version where you having issues with the success event? It should be the correct event to listen for, complete will get triggered after a success or failure so it may not indicate everything is okay, just that the task is complete.

**Comment by philvessey** [comment]
I'm using Android 7.1.1 and the latest extensions from the repo. I can see
both complete and success firing from the logs but the success event is
never triggered on the actionscript side, only complete does.

**Comment by philvessey** [comment]
Success seems to trigger fine when using getFile() and putFile() but tits when using getBytes() and putBytes() where the issue seems to be and I'm having to use the COMPLETE event.

**Comment by philvessey** [comment]
Hi - the same issue seems to be causing putBytes() to not trigger the success event either. Its been fixed for getByyes() but putBytes() still has the issue.

**Comment by marchbold** [comment]
On Android still?

**Comment by philvessey** [comment]
Yes

On 6 Mar 2017 10:34 pm, "Michael" <notifications@github.com> wrote:

On Android still?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/distriqt/ANE-Firebase/issues/42#issuecomment-284556482>,
or mute the thread

**Comment by philvessey** [comment]
Any update?

**Comment by marchbold** [comment]
putBytes seems to be working for us, so we are just trying to work out why it wouldn't be working for you. Could you post the code you are using for the putBytes call?

**Comment by philvessey** [comment]
Ah its my fault. Just loaded up my upload class and saw my error straight away. Looked at this over an hour the other day :( Yeah its working fine :)

**Comment by marchbold** [comment]
Ah excellent, glad you found the issue, definitely was struggling to reproduce that one.

Anything we need to be aware of?

Cheers

**Comment by philvessey** [comment]
No it was an issue myself. My upload class was still using complete but I
was listening for success.

Downloads and Uploads all working fine now.
