### ISSUE TITLE
Rejected by Apple. Crash on launche

### ISSUE THREAD

**Issue by oxmond** [distriqt/ANE-Firebase#45]
Just got  Chrash log back fron Apple:
[attachment-3620205035696742547crashlog-E2810902-9601-4FA1-A2C0-51F7C0A24716.txt](https://github.com/distriqt/ANE-Firebase/files/821396/attachment-3620205035696742547crashlog-E2810902-9601-4FA1-A2C0-51F7C0A24716.txt)
It looks like this line causes a problem:
com.google.firebase.auth.globalWorkQueue

I have tested on my iPhone 5s and iPhone 6 before submitting and found no issue myself. I have tested on a IPv6 environment to comply with Apples guidelines.

**Comment by phihochzwei** [comment]
Have you included the GoogleService-Info.plist in your project?

**Comment by oxmond** [comment]
yes

**Comment by phihochzwei** [comment]
ok. just asking, because I got an instant-crash on my mxmlc compiled apps, where I forgot to compile those files into the apps.

**Comment by oxmond** [comment]
Had no problem testing on my end. The problem came when the Apple review team tested.

**Comment by phihochzwei** [comment]
How do I say this politically correct..... They are typewriting monkeys. We submit usually 5-10 apps per month, either for new submission or for resubmission. All apps have the exact same code-base, only some assets and some endpoints differ. And per month, EXACTLY ONE APP gets rejected. Either because "it instantly crashed" or "we do not own the rights to the used material" (which is especially funny on apps, which get updates after being in the Appstore for 2 years). Sorry, drifting away. My point is: Is the app maybe depending on things you usually have (e.g. internet connection) which might cause this?

**Comment by marchbold** [comment]
If it's the globlWorkQueue that's crashed, it's a queue internal to the SDK so not sure there's a lot we can do about it except report it to the Firebase team. 

Have you seen any reports of this error anywhere else?

**Comment by phihochzwei** [comment]
I think there is a problem there. We had each of our apps crash on startup (seems during the registration of topics) on iOS 10.3.1 on all our iOS-Devices. After yesterdays update it is working on all devices. Only on our iphone 5s the apps still crash. But only ever SECOND start, which is a little bit weird. If you disable notifications for the app, it starts as usual.

**Comment by marchbold** [comment]
Hi, Yesterdays update was just an update to some of the Firebase Database functionality. 

Could you let me know all the parts of Firebase you are using and exactly what you think is causing the issue?

**Comment by phihochzwei** [comment]
No, with "yesterdays update" i was actually talking about the iOS Update to 10.3.2 :)

We are using only the Messaging functions.

**Comment by marchbold** [comment]
By messaging do you mean Push Notifications? 

Could you provide the crash log and console logs from the device when this crash occurred?

**Comment by phihochzwei** [comment]
Yes.

**Comment by marchbold** [comment]
Any luck getting the crash log and console logs from the device?
