### ISSUE TITLE
Implement once()

### ISSUE THREAD

**Issue by philvessey** [distriqt/ANE-Firebase#47]
This would be really handy to have.

https://firebase.google.com/docs/database/web/read-and-write#read_data_once

When data only needs to be queried once e.g. if that data doesn't get updated very often instead of listening to all changes on it.

**Comment by philvessey** [comment]
Is this a big task to implement - could really use this feature for the project I'm building.

**Comment by marchbold** [comment]
Will have a look into it later this week.

**Comment by marchbold** [comment]
Hi, I've added this addition in this morning and will release soon. Cheers

**Comment by marchbold** [comment]
Documentation: https://github.com/distriqt/ANE-Firebase/wiki/Database---Read-Data-and-Change-Events#read-data-once

**Comment by sfxworks** [comment]
I am unable to use this. Given the code, it gets the value but it's not calling my callback. It only traces the function.
