### ISSUE TITLE
Latest release completly crashes on Android

### ISSUE THREAD

**Issue by railnation** [distriqt/ANE-Firebase#48]
Hi, 

Just to mention, the latest release crashes the app on startup on Android.

Best

**Comment by philvessey** [comment]
They are working fine for me - just downloaded the latest versions of all 5 ANE and no crashes?

**Comment by railnation** [comment]
I updated Firebase.ANE and Crash.ANE the other one I dont use.

**Comment by philvessey** [comment]
Maybe its an issue with Crash ANE then as I don't include that in my build yet as still developing, the rest are working fine.

**Comment by marchbold** [comment]
Hi,

Make sure you've updated all the dependant ANEs as well, in particular the Google Play Services and the Android Support ANEs.

**Comment by marchbold** [comment]
Did that resolve your issue?

If not , could you post the logs from your device when the crash occurs? 

https://airnativeextensions.com/knowledgebase/faq/11
