### ISSUE TITLE
Demonstration of Filters?

### ISSUE THREAD

**Issue by sfxworks** [distriqt/ANE-Firebase#50]
I am trying to follow the [wiki](https://github.com/distriqt/ANE-Firebase/wiki/Database---Lists) on how to filter my database list. However I am not sure how I am suppose to create multiple queries (start at + end at) after I do an orderByChild. 

````
private function handleFeedRequest():void
		{
			//Get event.
			var eventReference:DatabaseReference = FirebaseDatabase.service.getReference("event");
			var query:Query = eventReference.orderByChild("latitude");
			query.startAt(
			query.endAt(
		}
````

I fetch my current latitude and longitude using Location. Would I query and then add event listeners to the query or has the query already starting after I do an orderByChild? And how would I go about filtering by multiple values (latitude and longitude within a hundredth of a decimal range)? Would I have to check each and every value after my event is fired and put it in a separate array if it matches or can I put it in a reference and query it again somehow?

**Comment by marchbold** [comment]
Something like this should work:

```as3
var eventReference:DatabaseReference = FirebaseDatabase.service.getReference("event");
var query:Query = eventReference
    .orderByChild("latitude")
    .startAt( 126.02 )
    .endAt( 127.05 );
```

You can only use one order by method, so if you are needing anything more you are going to have to rethink your structure.

**Comment by sfxworks** [comment]
Hmm... 
How would I refine my structure to handle both a lat and long value to get events near the user? The only way I can think of doing this is through a workaround by checking each returned result's longitude..

**Comment by marchbold** [comment]
I haven't looked into this personally, but a quick search revealed something called GeoFire which is built ontop of Firebase for location data.

They use a "hashCode" to search which is a combination of latitude and longitude. I'm not really sure how it works but this is the java that generates it.

```java
public int hashCode() {
    int result;
    long temp;
    temp = Double.doubleToLongBits(latitude);
    result = (int) (temp ^ (temp >>> 32));
    temp = Double.doubleToLongBits(longitude);
    result = 31 * result + (int) (temp ^ (temp >>> 32));
    return result;
}
```

**Comment by marchbold** [comment]
I haven't looked into this personally, but a quick search revealed something called GeoFire which is built ontop of Firebase for location data.

They use a "hash" to search which is a combination of latitude and longitude. I'm not really sure how it works but this is the java that generates it.

https://github.com/firebase/geofire-java/blob/master/src/main/java/com/firebase/geofire/core/GeoHash.java

**Comment by sfxworks** [comment]
Can you add this into this ANE in the future? I don't know much Java so I wouldn't be able to immediately add this.

**Comment by marchbold** [comment]
If there is enough interest we'll definitely add it in, but no plans at this point, I only just found it when you asked yesterday.
