### ISSUE TITLE
[Android] Analytics doesn't work

### ISSUE THREAD

**Issue by pedrochristopher** [distriqt/ANE-Firebase#51]
Hello.
Im testing your Firebase Analytics implementation.
I use google-services.json to configure Firebase with initialiseApp() call.
All needed items are added to my .xml file.

FCM works well with my settings but I can't get Analytics working.
All stuff is setup in Firebase console, I even turned on Debug Mode for Analytics Events but it just doesn't work.

In logs:
D/com.distriqt.Firebase(28891): FirebaseController::initialiseApp()
D/com.distriqt.Firebase(28891): FirebaseController::initialiseApp(): Using supplied options
D/com.distriqt.Firebase(28891): FirebaseController::initialiseApp(): apiKey = xxx
D/com.distriqt.Firebase(28891): FirebaseController::initialiseApp(): googleAppID = xxx
D/com.distriqt.Firebase(28891): FirebaseController::initialiseApp(): databaseURL = https://xxx.firebaseio.com
D/com.distriqt.Firebase(28891): FirebaseController::initialiseApp(): gcmSenderID = xxx
D/com.distriqt.Firebase(28891): FirebaseController::initialiseApp(): storageBucket = xxx.appspot.com

E/FA      (28891): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
E/FA      (28891): Uploading is not possible. App measurement disabled

Could you please update me on this problem? Is there any way to set google_app_id manually to get your ANE working? 
Thank you.

**Comment by marchbold** [comment]
Hi,

The delayed method isn't working consistently yet, could you try the resources method and let us know if you have issues there?

**Comment by pedrochristopher** [comment]
Hi @marchbold . I tried resources method but ant build doesn't work for me due to problem with ant-tasks.jar which is missed in latest Android Studio sdk tools ( you have a bug about that ). Is there any new ant build script I could use to create a config ane?

**Comment by marchbold** [comment]
We are working on the new script. This change in the Android SDK only occurred last week so it caught us by surprise. 

If you contact our support at airnativeextensions@distriqt.com we'll build one for you as soon as we can.

**Comment by phihochzwei** [comment]
Hi there, 

any news on this :) ? Because I hope to get the nice Analytics for Android like we get for iOS (where this works perfectly!)

**Comment by marchbold** [comment]
Hi,

A new version of the resources script is available in the custom resources repository:

https://github.com/distriqt/ANE-CustomResources/

We will be updating the script here in the next release, but for the meantime you can use that one.

**Comment by marchbold** [comment]
Hi, If you are still having problems with the script please let me know. I'll close out this issue for now.
