### ISSUE TITLE
Implementation of FirebaseAnalytics.setCurrentScreen

### ISSUE THREAD

**Issue by mwelk** [distriqt/ANE-Firebase#52]
FirebaseAnalytics setCurrentScreen:

[https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.html#setCurrentScreen(android.app.Activity, java.lang.String, java.lang.String)](url)

At least setting the screenName should be possible.

Thanks,
Matthias

**Comment by marchbold** [comment]
Will get this in today. Cheers

**Comment by mwelk** [comment]
That was really fast :+1: 

Thank you very much!

**Comment by marchbold** [comment]
No problems, let us know if there are any issues.
