### ISSUE TITLE
onDisconnect functionality for DatabaseReference

### ISSUE THREAD

**Issue by KreedaSolutions** [distriqt/ANE-Firebase#55]
Hi, 

In firebase Database ANE, It seems onDisconnect functionality for DatebaseReference is missing. 

https://firebase.google.com/docs/reference/android/com/google/firebase/database/DatabaseReference.html#onDisconnect()

This seems to be important from the perspective of tracking users online/offline, as mentioned below.. 

"Sample Presence App" in https://firebase.google.com/docs/database/android/offline-capabilities.

It will be really great if we can get this..  This can help us Build - Track Friends, Online chat etc.. 

Thanks, 
Aseem

**Comment by marchbold** [comment]
Yeah looks like we missed that functionality.

Will get it into the next release ASAP.

**Comment by KreedaSolutions** [comment]
Great, Thanks 👍
