### ISSUE TITLE
Can't setup on Android

### ISSUE THREAD

**Issue by david-daal** [distriqt/ANE-Firebase#59]
Hi

We was not able to run ANE on Android.
We've build Config ane using the manual but when calling 
`var success : Boolean = Firebase.service.initialiseApp();`
`success` is always false.
Also looks like there is nothing noteworthy in logcat.

```
05-23 18:49:33.800  25514-25514/? D/com.distriqt.Firebase﹕ FirebaseController::initialiseApp()
05-23 18:49:33.810  25514-25514/? I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.FirebaseApp$1>
05-23 18:49:33.810  25514-25514/? I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.FirebaseApp$1>
```

this is all we have. 
Any help is appreciated :)

**Comment by marchbold** [comment]
Have you correctly added all the dependent ANEs in your application? 

https://github.com/distriqt/ANE-Firebase/wiki/Core---Add-the-extensions

**Comment by david-daal** [comment]
Thanks for help.
I was following instructions
