### ISSUE TITLE
FirebaseCrash to Crashlytics

### ISSUE THREAD

**Issue by railnation** [distriqt/ANE-Firebase#60]
Hi, 

Do you plan to migrate the code to crashlytics or do you need nothing to change?

Best regards

**Comment by marchbold** [comment]
Hi, 

Not sure what you are asking here? Crashlytics is a separate service from Firebase as far as we are aware.

**Comment by marchbold** [comment]
Just to clarify this, we are aware that Firebase Crash Reporting is pushing you to Crashlytics from their console. Currently there is no direct integration though, so setting up Crashlytics is a separate service from Firebase.

We do plan to integrate the service once the Firebase migration has been performed.

**Comment by railnation** [comment]
Thank you for your reply and your clarification!

**Comment by adventurereaders** [comment]
Following up on this.
[Crash Reporting](https://firebase.google.com/docs/crash/) is now showing as deprecated, and is sending you to Crashlytics and then Fabric within the console. Do you have a roadmap for further developing this?

Thanks,
Daniel

**Comment by marchbold** [comment]
Hi, yes this is in development, we will update this thread when we have a beta available

**Comment by adventurereaders** [comment]
Thanks for the info and quick reply!

**Comment by gosgame** [comment]
Since Firebase crash service is closing in 10 days, this improvement should be a priority.

**Comment by marchbold** [comment]
Yes this is our top priority at the moment.

**Comment by gosgame** [comment]
Thanks, it works. Is there a way to send custom error logs instead of native crashes? Old crash ane had that ability.

**Comment by marchbold** [comment]
Glad to hear, add a separate enhancement request for the custom error log and we'll look into it.
