### ISSUE TITLE
SetValue problem on Android

### ISSUE THREAD

**Issue by david-daal** [distriqt/ANE-Firebase#61]
Hi guys.
We stuck to some error while implemented Firebase ANE for Android.

```
    public function setValue(node:String, value:Object, callback:Function):void {
        var ref:DatabaseReference = FirebaseDatabase.service.getReference(node);
        ref.addEventListener(DatabaseReferenceEvent.SET_VALUE_COMPLETE, setValueCompleteHadnler);
        ref.addEventListener(DatabaseReferenceEvent.SET_VALUE_ERROR, setValueErrorHadnler);
        ref.setValue(value);

        function setValueCompleteHadnler(event:DatabaseReferenceEvent):void {
            ref.removeEventListener(DatabaseReferenceEvent.SET_VALUE_COMPLETE, setValueCompleteHadnler);
            ref.removeEventListener(DatabaseReferenceEvent.SET_VALUE_ERROR, setValueErrorHadnler);

            callback({isSuccessful: true});
        }

        function setValueErrorHadnler(event:DatabaseReferenceEvent):void {
            ref.removeEventListener(DatabaseReferenceEvent.SET_VALUE_COMPLETE, setValueCompleteHadnler);
            ref.removeEventListener(DatabaseReferenceEvent.SET_VALUE_ERROR, setValueErrorHadnler);

            callback({isSuccessful: false});
        }
    }
```

In some cases `setValue` call doesn't work.
For example if we set something like `value = {"a":"b"}` everything works like a charm.
value is saved in Firebase database and `SET_VALUE_COMPLETE` Event is called.
But in more complex cases call fails.
For example.
`{"ccc":{"ssss":[],"aaaa":[]},"socialId":"12214","ggg":{"xxx":true}}`

ActionScript output:

```
[trace] Error #2044: Unhandled error:. text=Invalid Type
[trace] SyntaxError: Error #1132: Invalid JSON parse input.
[trace] SyntaxError: Error #1132: Invalid JSON parse input.
```

Logcat output:
```
05-24 18:28:58.918    5696-5696/? W/System.err﹕ java.lang.Exception: Invalid Type
05-24 18:28:58.918    5696-5696/? W/System.err﹕ at com.distriqt.extension.firebase.database.util.ObjectTypeUtils.getObjectByType(ObjectTypeUtils.java:116)
05-24 18:28:58.918    5696-5696/? W/System.err﹕ at com.distriqt.extension.firebase.database.util.ObjectTypeUtils.getObjectByType(ObjectTypeUtils.java:50)
05-24 18:28:58.918    5696-5696/? W/System.err﹕ at com.distriqt.extension.firebase.database.util.ObjectTypeUtils.getObjectByType(ObjectTypeUtils.java:96)
05-24 18:28:58.918    5696-5696/? W/System.err﹕ at com.distriqt.extension.firebase.database.util.ObjectTypeUtils.valueFromValueWithProperties(ObjectTypeUtils.java:42)
05-24 18:28:58.918    5696-5696/? W/System.err﹕ at com.distriqt.extension.firebase.database.functions.databasereference.SetValueFunction.call(SetValueFunction.java:45)
05-24 18:28:58.918    5696-5696/? W/System.err﹕ at com.adobe.air.customHandler.callTimeoutFunction(Native Method)
05-24 18:28:58.918    5696-5696/? W/System.err﹕ at com.adobe.air.customHandler.handleMessage(customHandler.java:22)
05-24 18:28:58.918    5696-5696/? W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
05-24 18:28:58.918    5696-5696/? W/System.err﹕ at android.os.Looper.loop(Looper.java:145)
05-24 18:28:58.918    5696-5696/? W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5942)
05-24 18:28:58.918    5696-5696/? W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
05-24 18:28:58.918    5696-5696/? W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
05-24 18:28:58.918    5696-5696/? W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
05-24 18:28:58.918    5696-5696/? W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
```

For IOS same call works without any problem. 

Any ideas?

**Comment by marchbold** [comment]
Can you identify which data type in your object is failing?

**Comment by david-daal** [comment]
I've tried to minimize JSON and `SetValue` failed for 
`{"ccc":[]}` or `{"ccc":["a","b"]}` values.

**Comment by marchbold** [comment]
Right so an Array value is causing the issue?

**Comment by david-daal** [comment]
Looks like that:)

**Comment by marchbold** [comment]
Hi, Unfortunately that type of data isn't currently supported, either on iOS or Android. I.e. a complex `Object` data. 

We highly recommend breaking your data into simple objects that Firebase can handle easily. 
 
```as3
ref.child("ccc").child("ssss").setValue( arrayData );
```

Alternatively if you really need that structure you could try encoding your object as JSON and writing it as a string. 

```as3
ref.setValue( JSON.stringify( complexObjectData ));
```

**Comment by david-daal** [comment]
Hi marchbold.
Unfortunately we can't change data structure as we have already running game with it's data and thousands of active players.

**Comment by marchbold** [comment]
Hi, you don't need to change your structure just map it correctly to Firebase references as I suggested in the first suggestion above.

**Comment by david-daal** [comment]
Hi guys. 
We tried to refactor  the way how we access Firebase database to avoid nested Array calls.
So instead of calling setValue on whole object we call updateChildren with required fields, but still get same error.
What is the problem here now?  

```
 {
"progress":[], 
"guide":[{"data":{"index":0},"id":"someId","type":"simple","state":0}],
"inventory":{},
"igcBalance":{"coin":100}
}
```

**Comment by marchbold** [comment]
Hi, You still have quite complex structure there, Array of objects with objects. 

What exactly are you trying to achieve here? The advantage of Firebase's references is that you can modify and listen changes of individual values. If you aren't going to be using that functionality but just storing a blob of data you should perhaps just use the second method I suggested of storing it as a JSON String.

**Comment by david-daal** [comment]
Hi 
Storing it as String means changing current structure, doesn't it?  And that impossible in our case.
Also nodes in example are deepest references we can access. 
We don't know modified array element index to update it directly. :(

**Comment by david-daal** [comment]
Dear marchbold that means changing database structure
which is impossible.

That missing functionality makes ANE useless for us.
Is there any chance that you will implement it?

**Comment by marchbold** [comment]
Hi, Could you explain your issue a little more? I don't think we understand what you are trying to achieve. Do you have an existing Firebase Database?

**Comment by david-daal** [comment]
Hi marchbold.
Yes we have existing game which has runs for thousands players on four different platforms and shares same database.
So it's almost impossible and quite thankless job to change database structure :)   

As you advised we changed the way we work with database and try to write minimal chunk of data but we are not able to minimize it to primitive objects. In some cases we have to work with nested objects and arrays.

**Comment by marchbold** [comment]
Ah okay, sorry I was not aware of that.

In that case you have to continue correcting how you reference the values.  The last issue was with the "guide" where you had an array of objects:

```
"guide":[{"data":{"index":0} ...
```

I'll look into adding this feature in the next release, though we will still not recommend using it due to the amount of processing it requires to convert a complex Object to a native object, and if your data is quite complex it could have an impact on your application.

**Comment by david-daal** [comment]
Hi marchbold
Thanks. Looking forward for it.
I see your point. We will try to keep structure as simple as possible.
Do you have any roadmap when next release will be available?

**Comment by marchbold** [comment]
Not as yet. We have a few other pressing development priorities at the moment, but will push this up the list.

**Comment by marchbold** [comment]
Alpha version for you to test:

https://www.dropbox.com/s/w8vf1ulox8k7ylf/com.distriqt.firebase.Database.ane?dl=0

**Comment by david-daal** [comment]
Hi
I got same error.

Here is the data I try to update.

```
{
"progress":[],
"inventory":{"constructionItems":[],"items":[]},
"igcBalance":{"coin":100},
"guide":{"guideFirstMapFirstPlay":true},
"secondaryProgress":{},
"tasks":[{"state":0,"id":"playLevel_0","data":{"packIndex":0},"type":"playLevel"}]
}
```

and the logcat says

```
W/System.err﹕ java.lang.Exception: Invalid Type
W/System.err﹕ at com.distriqt.extension.firebase.database.util.ObjectTypeUtils.getObjectByType(ObjectTypeUtils.java:116)
W/System.err﹕ at com.distriqt.extension.firebase.database.util.ObjectTypeUtils.getObjectByType(ObjectTypeUtils.java:50)
W/System.err﹕ at com.distriqt.extension.firebase.database.util.ObjectTypeUtils.getObjectByType(ObjectTypeUtils.java:96)
W/System.err﹕ at com.distriqt.extension.firebase.database.functions.databasereference.UpdateChildrenFunction.call(UpdateChildrenFunction.java:62)
W/System.err﹕ at com.adobe.air.customHandler.callTimeoutFunction(Native Method)
W/System.err﹕ at com.adobe.air.customHandler.handleMessage(customHandler.java:22)
W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err﹕ at android.os.Looper.loop(Looper.java:145)
W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5942)
W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
```

After minimizing JSON I've found that the UpdateChildren failed because of 

`{"tasks":[{"data":{"packIndex":0},"id":"playLevel_0","type":"playLevel","state":0}]}`

**Comment by marchbold** [comment]
What is the structure of the data you are attempting to read?

**Comment by marchbold** [comment]
Actually that error indicates the reference is not valid. What is the value of `node` you are using?

**Comment by david-daal** [comment]
Hi
` node = "users/pvzvShKDSjNBgImPfFl6hUIhizP2"`

And here is the `ref` in debugger

![screen shot 2017-06-16 at 11 42 47 am](https://user-images.githubusercontent.com/2318278/27216967-ff955812-5288-11e7-9bbd-a1ffa195753a.png)

**Comment by marchbold** [comment]
That looks like an invalid reference, are you sure your path is correct? You'll probably find `once` is returning `false`.

**Comment by marchbold** [comment]
How did you go, did you get it to work with a valid reference?

**Comment by david-daal** [comment]
Hi.
I've checked. database ref is valid everything is correct. 
The exception occurs in `once` method so I doesn't returning anything.

**Comment by marchbold** [comment]
Have you tried the most recent in the repository, it is more featured than the alpha now.

**Comment by david-daal** [comment]
No. Should I update all ANEs? Or only Database?

**Comment by marchbold** [comment]
All ANEs, including all dependent ANEs.

**Comment by david-daal** [comment]
Hi 
I updated latest ANEs. 
Everything works. 
I didn't tested fully yet, but at least a flow related to setValue and updateChildren method calls passed without any exception on Android.
Will continue testing and let you know.
Thanks a lot.

**Comment by marchbold** [comment]
Excellent, thanks for working with us and your patience. Let me know if you run into any issues.
