### ISSUE TITLE
Few additional Capabilities - related to ".info/"

### ISSUE THREAD

**Issue by KreedaSolutions** [distriqt/ANE-Firebase#64]
Hi, 

We tried few capabalitied mentioned in here - https://firebase.google.com/docs/database/web/offline-capabilities. 

Namely - 
1) FirebaseDatabase.service.getReference(".info/connected");
2) FirebaseDatabase.service.getReference(".info/serverTimeOffset");

Guess something is stopping us from using these capabilities. we are getting following error

Error #1081: Property on not found on com.distriqt.extension.firebase.database._DatabaseReference and there is no default value.

Thanks, 
Aseem

**Comment by marchbold** [comment]
Hi, Is there any more information in the error or is it possible for you to post the logs from the device?

**Comment by KreedaSolutions** [comment]
Will Take the Andorid Logs and update..

**Comment by KreedaSolutions** [comment]
D/DataOperation( 3837): }
D/Connection( 3837): conn_1 - Sending data: {d={a=p, r=5, b={d={1570243156353205
=fb, 10155459736297868=fb}, p=frnds/IUNFnvCBL1UIzdWvseRtqtnNrvy1}}, t=d}
D/WebSocket( 3837): ws_1 - Reset keepAlive. Remaining: 44996
D/RepoOperation( 3837): Aborting transactions for path: /frnds/IUNFnvCBL1UIzdWvs
eRtqtnNrvy1. Affected: /frnds/IUNFnvCBL1UIzdWvseRtqtnNrvy1
I/air.kreedasolutions.pattebaaz.dev( 3837): 2017:5:4:4:11:53:474: FirebaseDataBa
se_Class: userObj.pushNotificationToken= cLKBTWAhHDk:APA91bF_KCdub0ZR_fXAdbELvqR
BfMu3MWT5XSr9Y2WnrGZKy9DkMGRxKTEJqCj91sCK16MNSFXghf2h-AS917nD7B8s28IUtp3ZuZtmu_m
YcW5sC3nD7yCIB8KkJUmmV50WiBlQ0_K7
I/air.kreedasolutions.pattebaaz.dev( 3837): 2017:5:4:4:11:53:478: FirebaseDataBa
se_Class: now= Thu Jun 8 09:41:53 GMT+0530 2017
I/air.kreedasolutions.pattebaaz.dev( 3837): 2017:5:4:4:11:53:481: FirebaseDataBa
se_Class: timestamp= 1496895113477
D/com.distriqt.firebase.Database( 3837): DatabaseController::getReference( /Logi
n/IUNFnvCBL1UIzdWvseRtqtnNrvy1/Rqst )
D/com.distriqt.firebase.Database( 3837): DatabaseController::getReferenceFromIde
ntifier( /Login/IUNFnvCBL1UIzdWvseRtqtnNrvy1/Rqst/ )
D/com.distriqt.firebase.Database( 3837): DatabaseReferenceController::setValue(
)
D/RepoOperation( 3837): set: /Login/IUNFnvCBL1UIzdWvseRtqtnNrvy1/Rqst
D/DataOperation( 3837): set: /Login/IUNFnvCBL1UIzdWvseRtqtnNrvy1/Rqst {
D/DataOperation( 3837):   fbkAt=EAAawt5UuwEkBAI8j9HZB5PVqItKFY9vivZAD8VwXo3EmUZC
qnfZA3IO7Q2enollDTdv0dFVoUJZAwktsRZCWTQJM8GKfIG7D5XT...
D/DataOperation( 3837):   fbsJwt=eyJhbGciOiJSUzI1NiIsImtpZCI6ImEyMzgxMjZlNDFhODE
yYjAwYmYzN2RkNTcyNjg5ZWU4NTI0NmU1Y2QifQ.eyJpc3MiOiJod...
D/DataOperation( 3837):   fcmTkn=cLKBTWAhHDk:APA91bF_KCdub0ZR_fXAdbELvqRBfMu3MWT
5XSr9Y2WnrGZKy9DkMGRxKTEJqCj91sCK16MNSFXghf2h-AS917nD...
D/DataOperation( 3837): }
D/com.distriqt.firebase.Database( 3837): DatabaseController::getReference( /Logi
n/IUNFnvCBL1UIzdWvseRtqtnNrvy1/Resp )
D/Connection( 3837): conn_1 - Sending data: {d={a=p, r=6, b={d={fcmTkn=cLKBTWAhH
Dk:APA91bF_KCdub0ZR_fXAdbELvqRBfMu3MWT5XSr9Y2WnrGZKy9DkMGRxKTEJqCj91sCK16MNSFXgh
f2h-AS917nD7B8s28IUtp3ZuZtmu_mYcW5sC3nD7yCIB8KkJUmmV50WiBlQ0_K7, fbsJwt=eyJhbGci
OiJSUzI1NiIsImtpZCI6ImEyMzgxMjZlNDFhODEyYjAwYmYzN2RkNTcyNjg5ZWU4NTI0NmU1Y2QifQ.e
yJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcGF0dGUtYmFhei1kZXYiLCJuYW1lI
joiU2FnYXIgTWFzYWwiLCJwaWN0dXJlIjoiaHR0cHM6Ly9zY29udGVudC54eC5mYmNkbi5uZXQvdi90M
S4wLTEvcDEwMHgxMDAvMTIzNDY0MzNfOTc1NzM3NTE5MTg3MzQxXzc4NzQ5NDQwMDY2ODEyNzU4NjFfb
i5qcGc_b2g9OWI0ZTA1NDk1NWJkNTJhNzBmZDE0YjVmM2E1N2E0Njcmb2U9NTlCMTkwNUEiLCJhdWQiO
iJwYXR0ZS1iYWF6LWRldiIsImF1dGhfdGltZSI6MTQ5Njg5NTExMiwidXNlcl9pZCI6IklVTkZudkNCT
DFVSXpkV3ZzZVJ0cXRuTnJ2eTEiLCJzdWIiOiJJVU5GbnZDQkwxVUl6ZFd2c2VSdHF0bk5ydnkxIiwia
WF0IjoxNDk2ODk1MTE0LCJleHAiOjE0OTY4OTg3MTQsImVtYWlsIjoic20ubWFzYWxAZ21haWwuY29tI
iwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImZhY2Vib29rL
mNvbSI6WyIxMzQ0OTcwMzM4OTMwNzIyIl0sImVtYWlsIjpbInNtLm1hc2FsQGdtYWlsLmNvbSJdfSwic
2lnbl9pbl9wcm92aWRlciI6ImZhY2Vib29rLmNvbSJ9fQ.0Zef7V9XYLCCayqPZV_aT2-pBmWIbDqTU2
8KADOaNbcbzt5fLVYhzi1lt8cJuHzFUbBMKCyB1ivxeVrqivkn0pp3JqpQMIRB_M5fuAELk5hmRol9HR
ic8CvyuSb3z304aecwqRe2Iaexe0VI_7Tsq8PmmyZAPPGWCHh-QOEh0AR4aplmSO_Eg1GBo0-mwO9nrj
PPO2ZWuCqfiLz5k1cVZD_S326GesevuM4eYOOahANjiowg5Ut6JGUOWmVHSOoBAlv6zfR8SHtyPbdkYV
lIeuok7H2CBMaHGSohR9GKYdASm9rIAOmeVYLUJG80FN37uN9YZTXjhRBBaBcN6JzqTg, fbkAt=EAAa
wt5UuwEkBAI8j9HZB5PVqItKFY9vivZAD8VwXo3EmUZCqnfZA3IO7Q2enollDTdv0dFVoUJZAwktsRZC
WTQJM8GKfIG7D5XThcsQle6qOfFXU09FB6K2pNzvLEJZAXmZBiZAAM3MriBXUTVnoLZBuiHnC5XaneYt
0jWW0bbUraj5tcUuAuBTPhZB3gyfJ5t8dxPefZADfIRkPmTaYLlOyOTZB9}, p=Login/IUNFnvCBL1U
IzdWvseRtqtnNrvy1/Rqst}}, t=d}
I/air.kreedasolutions.pattebaaz.dev( 3837): addEventListener( dbref:value:change
d)
D/WebSocket( 3837): ws_1 - Reset keepAlive. Remaining: 44974
D/com.distriqt.firebase.Database( 3837): DatabaseController::getReferenceFromIde
ntifier( /Login/IUNFnvCBL1UIzdWvseRtqtnNrvy1/Resp/ )
D/com.distriqt.firebase.Database( 3837): DatabaseReferenceController::addValueEv
entListener()
D/com.distriqt.firebase.Database( 3837): DatabaseController::getReference( .info
/connected )
D/RepoOperation( 3837): Aborting transactions for path: /Login/IUNFnvCBL1UIzdWvs
eRtqtnNrvy1/Rqst. Affected: /Login/IUNFnvCBL1UIzdWvseRtqtnNrvy1/Rqst
I/air.kreedasolutions.pattebaaz.dev( 3837): 2017:5:4:4:11:53:496: error :  Fireb
aseDataBase_Class: writeValue: Error #1081: Property on not found on com.distriq
t.extension.firebase.database._DatabaseReference and there is no default value.
D/PersistentConnection( 3837): pc_0 - Listening on Login/IUNFnvCBL1UIzdWvseRtqtn
Nrvy1/Resp (params: {})
D/PersistentConnection( 3837): pc_0 - Adding listen query: Login/IUNFnvCBL1UIzdW
vseRtqtnNrvy1/Resp (params: {})
D/Connection( 3837): conn_1 - Sending data: {d={a=q, r=7, b={h=, p=Login/IUNFnvC
BL1UIzdWvseRtqtnNrvy1/Resp}}, t=d}
D/WebSocket( 3837): ws_1 - Reset keepAlive. Remaining: 44981
D/com.distriqt.Firebase.Auth( 3837): FirebaseAuthController::getCurrentUser()
D/wpa_supplicant( 1245): wlan0: Control interface command 'SIGNAL_POLL'
D/WebSocket( 3837): ws_1 - ws message: {"t":"d","d":{"r":4,"b":{"s":"ok","d":""}
}}
D/WebSocket( 3837): ws_1 - ws message: {"t":"d","d":{"r":5,"b":{"s":"ok","d":""}
}}
D/WebSocket( 3837): ws_1 - Reset keepAlive. Remaining: 44879
D/WebSocket( 3837): ws_1 - HandleNewFrameCount: 1
D/WebSocket( 3837): ws_1 - handleIncomingFrame complete frame: {d={r=4, b={d=, s
=ok}}, t=d}
D/Connection( 3837): conn_1 - received data message: {r=4, b={d=, s=ok}}
D/PersistentConnection( 3837): pc_0 - p response: {d=, s=ok}
D/WebSocket( 3837): ws_1 - Reset keepAlive. Remaining: 44998
D/WebSocket( 3837): ws_1 - HandleNewFrameCount: 1
D/WebSocket( 3837): ws_1 - handleIncomingFrame complete frame: {d={r=5, b={d=, s
=ok}}, t=d}
D/Connection( 3837): conn_1 - received data message: {r=5, b={d=, s=ok}}
D/PersistentConnection( 3837): pc_0 - p response: {d=, s=ok}
D/WebSocket( 3837): ws_1 - ws message: {"t":"d","d":{"r":6,"b":{"s":"ok","d":""}
}}
D/WebSocket( 3837): ws_1 - Reset keepAlive. Remaining: 44851
D/WebSocket( 3837): ws_1 - HandleNewFrameCount: 1
D/WebSocket( 3837): ws_1 - handleIncomingFrame complete frame: {d={r=6, b={d=, s
=ok}}, t=d}
D/Connection( 3837): conn_1 - received data message: {r=6, b={d=, s=ok}}
D/PersistentConnection( 3837): pc_0 - p response: {d=, s=ok}
D/WebSocket( 3837): ws_1 - ws message: {"t":"d","d":{"b":{"p":"Login/IUNFnvCBL1U
IzdWvseRtqtnNrvy1/Resp","d":{"pioAuth":"1496894963:df82059e1e9a9e8b3fa99b9d0c4ef
86b7a8b38c72d10161ea390817b96c42e69","plyrInfo":"01~1496894963~patte-baaz-dev~IU
NFnvCBL1UIzdWvseRtqtnNrvy1~1344970338930722~Sagar Masal~https://scontent.xx.fbcd
n.net/v/t1.0-1/p50x50/12346433_975737519187341_7874944006681275861_n.jpg?oh=90dc
6c3ad96f4aba90a798f5c3b247b0&oe=59AD8A54~sm.masal@gmail.com","sts":"0000","unqId
":"uniqueIUNFnvCBL1UIzdWvseRtqtnNrvy1"}},"a":"d"}}
D/WebSocket( 3837): ws_1 - ws message: {"t":"d","d":{"r":7,"b":{"s":"ok","d":{}}
}}
D/WebSocket( 3837): ws_1 - Reset keepAlive. Remaining: 44997
D/WebSocket( 3837): ws_1 - HandleNewFrameCount: 1
D/WebSocket( 3837): ws_1 - handleIncomingFrame complete frame: {d={a=d, b={d={un
qId=uniqueIUNFnvCBL1UIzdWvseRtqtnNrvy1, pioAuth=1496894963:df82059e1e9a9e8b3fa99
b9d0c4ef86b7a8b38c72d10161ea390817b96c42e69, sts=0000, plyrInfo=01~1496894963~pa
tte-baaz-dev~IUNFnvCBL1UIzdWvseRtqtnNrvy1~1344970338930722~Sagar Masal~https://s
content.xx.fbcdn.net/v/t1.0-1/p50x50/12346433_975737519187341_787494400668127586
1_n.jpg?oh=90dc6c3ad96f4aba90a798f5c3b247b0&oe=59AD8A54~sm.masal@gmail.com}, p=L
ogin/IUNFnvCBL1UIzdWvseRtqtnNrvy1/Resp}}, t=d}
D/Connection( 3837): conn_1 - received data message: {a=d, b={d={unqId=uniqueIUN
FnvCBL1UIzdWvseRtqtnNrvy1, pioAuth=1496894963:df82059e1e9a9e8b3fa99b9d0c4ef86b7a
8b38c72d10161ea390817b96c42e69, sts=0000, plyrInfo=01~1496894963~patte-baaz-dev~
IUNFnvCBL1UIzdWvseRtqtnNrvy1~1344970338930722~Sagar Masal~https://scontent.xx.fb
cdn.net/v/t1.0-1/p50x50/12346433_975737519187341_7874944006681275861_n.jpg?oh=90
dc6c3ad96f4aba90a798f5c3b247b0&oe=59AD8A54~sm.masal@gmail.com}, p=Login/IUNFnvCB
L1UIzdWvseRtqtnNrvy1/Resp}}
D/PersistentConnection( 3837): pc_0 - handleServerMessage: d {d={unqId=uniqueIUN
FnvCBL1UIzdWvseRtqtnNrvy1, pioAuth=1496894963:df82059e1e9a9e8b3fa99b9d0c4ef86b7a
8b38c72d10161ea390817b96c42e69, sts=0000, plyrInfo=01~1496894963~patte-baaz-dev~
IUNFnvCBL1UIzdWvseRtqtnNrvy1~1344970338930722~Sagar Masal~https://scontent.xx.fb
cdn.net/v/t1.0-1/p50x50/12346433_975737519187341_7874944006681275861_n.jpg?oh=90
dc6c3ad96f4aba90a798f5c3b247b0&oe=59AD8A54~sm.masal@gmail.com}, p=Login/IUNFnvCB
L1UIzdWvseRtqtnNrvy1/Resp}
D/RepoOperation( 3837): onDataUpdate: /Login/IUNFnvCBL1UIzdWvseRtqtnNrvy1/Resp
D/RepoOperation( 3837): onDataUpdate: /Login/IUNFnvCBL1UIzdWvseRtqtnNrvy1/Resp {
unqId=uniqueIUNFnvCBL1UIzdWvseRtqtnNrvy1, pioAuth=1496894963:df82059e1e9a9e8b3fa
99b9d0c4ef86b7a8b38c72d10161ea390817b96c42e69, sts=0000, plyrInfo=01~1496894963~
patte-baaz-dev~IUNFnvCBL1UIzdWvseRtqtnNrvy1~1344970338930722~Sagar Masal~https:/
/scontent.xx.fbcdn.net/v/t1.0-1/p50x50/12346433_975737519187341_7874944006681275
861_n.jpg?oh=90dc6c3ad96f4aba90a798f5c3b247b0&oe=59AD8A54~sm.masal@gmail.com}
D/EventRaiser( 3837): Raising 1 event(s)
D/WebSocket( 3837): ws_1 - Reset keepAlive. Remaining: 44991
D/WebSocket( 3837): ws_1 - HandleNewFrameCount: 1
D/WebSocket( 3837): ws_1 - handleIncomingFrame complete frame: {d={r=7, b={d={},
 s=ok}}, t=d}
D/Connection( 3837): conn_1 - received data message: {r=7, b={d={}, s=ok}}
D/EventRaiser( 3837): Raising /Login/IUNFnvCBL1UIzdWvseRtqtnNrvy1/Resp: VALUE: {
unqId=uniqueIUNFnvCBL1UIzdWvseRtqtnNrvy1, pioAuth=1496894963:df82059e1e9a9e8b3fa
99b9d0c4ef86b7a8b38c72d10161ea390817b96c42e69, sts=0000, plyrInfo=01~1496894963~
patte-baaz-dev~IUNFnvCBL1UIzdWvseRtqtnNrvy1~1344970338930722~Sagar Masal~https:/
/scontent.xx.fbcdn.net/v/t1.0-1/p50x50/12346433_975737519187341_7874944006681275
861_n.jpg?oh=90dc6c3ad96f4aba90a798f5c3b247b0&oe=59AD8A54~sm.masal@gmail.com}
D/com.distriqt.firebase.Database( 3837): QueryController::[/Login/IUNFnvCBL1UIzd
WvseRtqtnNrvy1/Resp/]:onDataChange()
I/air.kreedasolutions.pattebaaz.dev( 3837): dbref:value:changed::{"id":"/Login/I
UNFnvCBL1UIzdWvseRtqtnNrvy1/Resp/","snapshot":{"value":{"plyrInfo":"01~149689496
3~patte-baaz-dev~IUNFnvCBL1UIzdWvseRtqtnNrvy1~1344970338930722~Sagar Masal~https
://scontent.xx.fbcdn.net/v/t1.0-1/p50x50/12346433_975737519187341_78749440066812
75861_n.jpg?oh=90dc6c3ad96f4aba90a798f5c3b247b0&oe=59AD8A54~sm.masal@gmail.com",
"pioAuth":"1496894963:df82059e1e9a9e8b3fa99b9d0c4ef86b7a8b38c72d10161ea390817b96
c42e69","unqId":"uniqueIUNFnvCBL1UIzdWvseRtqtnNrvy1","sts":"0000"},"children":[{
"value":"1496894963:df82059e1e9a9e8b3fa99b9d0c4ef86b7a8b38c72d10161ea390817b96c4
2e69","exists":true,"key":"pioAuth"},{"value":"01~1496894963~patte-baaz-dev~IUNF
nvCBL1UIzdWvseRtqtnNrvy1~1344970338930722~Sagar Masal~https://scontent.xx.fbcdn.
net/v/t1.0-1/p50x50/12346433_975737519187341_7874944006681275861_n.jpg?oh=90dc6c
3ad96f4aba90a798f5c3b247b0&oe=59AD8A54~sm.masal@gmail.com","exists":true,"key":"
plyrInfo"},{"value":"0000","exists":true,"key":"sts"},{"value":"uniqueIUNFnvCBL1
UIzdWvseRtqtnNrvy1","exists
I/air.kreedasolutions.pattebaaz.dev( 3837): 2017:5:4:4:11:53:948:  FirebaseDataB
ase_Class: LoginResp_valueChangedHandler 1 :event.snapshot.value= [object Object
]
I/air.kreedasolutions.pattebaaz.dev( 3837): 2017:5:4:4:11:53:952:  FirebaseDataB
ase_Class: LoginResp_valueChangedHandler 2
I/air.kreedasolutions.pattebaaz.dev( 3837): 2017:5:4:4:11:53:956:  FirebaseDataB
ase_Class: LoginResp_valueChangedHandler 3
I/air.kreedasolutions.pattebaaz.dev( 3837): 2017:5:4:4:11:53:959:  FirebaseDataB
ase_Class: LoginResp_valueChangedHandler 4
I/air.kreedasolutions.pattebaaz.dev( 3837): 2017:5:4:4:11:53:961:  FirebaseDataB
ase_Class: LoginResp_valueChangedHandler reqNewtimeStamp: 1496895103
I/air.kreedasolutions.pattebaaz.dev( 3837): 2017:5:4:4:11:53:965:  FirebaseDataB
ase_Class: LoginResp_valueChangedHandler respFinaltimeStamp: 1496894963
I/air.kreedasolutions.pattebaaz.dev( 3837): 2017:5:4:4:11:53:970: FirebaseDataBa
se_Class: LoginResp_valueChangedHandler:= DataSnapshot[exists=true] Resp:{"plyrI
nfo":"01~1496894963~patte-baaz-dev~IUNFnvCBL1UIzdWvseRtqtnNrvy1~1344970338930722
~Sagar Masal~https://scontent.xx.fbcdn.net/v/t1.0-1/p50x50/12346433_975737519187
341_7874944006681275861_n.jpg?oh=90dc6c3ad96f4aba90a798f5c3b247b0&oe=59AD8A54~sm
.masal@gmail.com","pioAuth":"1496894963:df82059e1e9a9e8b3fa99b9d0c4ef86b7a8b38c7
2d10161ea390817b96c42e69","unqId":"uniqueIUNFnvCBL1UIzdWvseRtqtnNrvy1","sts":"00
00"}
I/air.kreedasolutions.pattebaaz.dev( 3837): 2017:5:4:4:11:53:975: FirebaseDataBa
se_Class: LoginResp_valueChangedHandler: value=  [object Object]
I/air.kreedasolutions.pattebaaz.dev( 3837): 2017:5:4:4:11:53:978: FirebaseDataBa
se_Class: LoginResp_valueChangedHandler: event.snapshot.value.sts= 0000
I/air.kreedasolutions.pattebaaz.dev( 3837): 2017:5:4:4:11:53:981: FirebaseDataBa
se_Class: LoginResp_valueChangedHandler: event.snapshot.value.pioAuth= 149689496
3:df82059e1e9a9e8b3fa99b9d0c4ef86b7a8b38c72d10161ea390817b96c42e69
I/air.kreedasolutions.pattebaaz.dev( 3837): 2017:5:4:4:11:53:985: FirebaseDataBa
se_Class: LoginResp_valueChangedHandler: event.snapshot.value.unqId= uniqueIUNFn
vCBL1UIzdWvseRtqtnNrvy1
I/air.kreedasolutions.pattebaaz.dev( 3837): 2017:5:4:4:11:53:988: FirebaseDataBa
se_Class: LoginResp_valueChangedHandler: event.snapshot.value.plyrInfo= 01~14968
94963~patte-baaz-dev~IUNFnvCBL1UIzdWvseRtqtnNrvy1~1344970338930722~Sagar Masal~h
ttps://scontent.xx.fbcdn.net/v/t1.0-1/p50x50/12346433_975737519187341_7874944006
681275861_n.jpg?oh=90dc6c3ad96f4aba90a798f5c3b247b0&oe=59AD8A54~sm.masal@gmail.c
om
D/com.distriqt.firebase.Database( 3837): DatabaseController::getReferenceFromIde
ntifier( /Login/IUNFnvCBL1UIzdWvseRtqtnNrvy1/Resp/ )
D/com.distriqt.firebase.Database( 3837): DatabaseReferenceController::removeValu
eEventListener()
D/PersistentConnection( 3837): pc_0 - unlistening on Login/IUNFnvCBL1UIzdWvseRtq
tnNrvy1/Resp (params: {})
I/air.kreedasolutions.pattebaaz.dev( 3837): dbref:value:changed::{"id":"/Login/I
UNFnvCBL1UIzdWvseRtqtnNrvy1/Resp/","snapshot":{"value":{"plyrInfo":"01~149689496
3~patte-baaz-dev~IUNFnvCBL1UIzdWvseRtqtnNrvy1~1344970338930722~Sagar Masal~https
://scontent.xx.fbcdn.net/v/t1.0-1/p50x50/12346433_975737519187341_78749440066812
75861_n.jpg?oh=90dc6c3ad96f4aba90a798f5c3b247b0&oe=59AD8A54~sm.masal@gmail.com",
"pioAuth":"1496894963:df82059e1e9a9e8b3fa99b9d0c4ef86b7a8b38c72d10161ea390817b96
c42e69","unqId":"uniqueIUNFnvCBL1UIzdWvseRtqtnNrvy1","sts":"0000"},"children":[{
"value":"1496894963:df82059e1e9a9e8b3fa99b9d0c4ef86b7a8b38c72d10161ea390817b96c4
2e69","exists":true,"key":"pioAuth"},{"value":"01~1496894963~patte-baaz-dev~IUNF
nvCBL1UIzdWvseRtqtnNrvy1~1344970338930722~Sagar Masal~https://scontent.xx.fbcdn.
net/v/t1.0-1/p50x50/12346433_975737519187341_7874944006681275861_n.jpg?oh=90dc6c
3ad96f4aba90a798f5c3b247b0&oe=59AD8A54~sm.masal@gmail.com","exists":true,"key":"
plyrInfo"},{"value":"0000","exists":true,"key":"sts"},{"value":"uniqueIUNFnvCBL1
UIzdWvseRtqtnNrvy1","exists
D/PersistentConnection( 3837): pc_0 - removing query Login/IUNFnvCBL1UIzdWvseRtq
tnNrvy1/Resp (params: {})
D/Connection( 3837): conn_1 - Sending data: {d={a=n, r=8, b={p=Login/IUNFnvCBL1U
IzdWvseRtqtnNrvy1/Resp}}, t=d}
D/WebSocket( 3837): ws_1 - Reset keepAlive. Remaining: 44933
D/StatusBar.NetworkController( 1310): onSignalStrengthsChanged received on slotI
d :0signalStrength=SignalStrength: 99 0 -120 -160 -120 -1 -1 12 -117 -13 12 2147
483647 2147483647 gsm|lte level=2 cdmdlevel=0 evdolevel=0
D/WebSocket( 3837): ws_1 - ws message: {"t":"d","d":{"r":8,"b":{"s":"ok","d":""}
}}
D/WebSocket( 3837): ws_1 - Reset keepAlive. Remaining: 44725
D/WebSocket( 3837): ws_1 - HandleNewFrameCount: 1
D/WebSocket( 3837): ws_1 - handleIncomingFrame complete frame: {d={r=8, b={d=, s
=ok}}, t=d}
D/Connection( 3837): conn_1 - received data message: {r=8, b={d=, s=ok}}
I/XiaomiFirewall( 1873): firewall pkgName:com.google.android.gms, result:0x0
I/Analytics-Core-JobSchedulerService( 2964): onStartJob
D/StatusBar.NetworkController( 1310): onSignalStrengthsChanged received on slotI
d :0signalStrength=SignalStrength: 99 0 -120 -160 -120 -1 -1 12 -116 -14 6 21474
83647 2147483647 gsm|lte level=2 cdmdlevel=0 evdolevel=0
D/StatusBar.NetworkController( 1310): onSignalStrengthsChanged received on slotI
d :1signalStrength=SignalStrength: 8 0 -120 -160 -120 -1 -1 99 2147483647 214748
3647 2147483647 2147483647 2147483647 gsm|lte level=3 cdmdlevel=0 evdolevel=0
D/wpa_supplicant( 1245): wlan0: Control interface command 'SIGNAL_POLL'
D/StatusBar.NetworkController( 1310): onSignalStrengthsChanged received on slotI
d :0signalStrength=SignalStrength: 99 0 -120 -160 -120 -1 -1 11 -115 -11 22 2147
483647 2147483647 gsm|lte level=3 cdmdlevel=0 evdolevel=0
D/wpa_supplicant( 1245): wlan0: Control interface command 'SIGNAL_POLL'
I/MSM-irqbalance(  795): Decided to move IRQ240 from CPU7 to CPU5
D/wpa_supplicant( 1245): wlan0: Control interface command 'SIGNAL_POLL'

**Comment by marchbold** [comment]
Does this occur on iOS as well or only Android? What versions of Android have you tested?

**Comment by KreedaSolutions** [comment]
for now we are testing on Android only , don't know about the iOS.
DEVICE INFO ============================
name:
brand: Xiaomi
manufacturer: Xiaomi
device: ferrari
model: Mi 4i
product: ferrari
OPERATING SYSTEM =======================
name: Android
type: android
version: 5.0.2
API Level: 21

**Comment by marchbold** [comment]
This should be fixed for the next release:

```as3
var ref:DatabaseReference = FirebaseDatabase.service.getReference( ".info/connected" );
ref.addEventListener( DatabaseReferenceEvent.VALUE_CHANGED, info_valueChangedHandler );
```

```as3
private function info_valueChangedHandler( event:DatabaseReferenceEvent ):void
{
	trace( "connected: " + event.snapshot.value );
}
```

**Comment by KreedaSolutions** [comment]
Awesome.. Thanks again for quick resposne :)

**Comment by marchbold** [comment]
Let me know if you have any issues with the update. (You'll need to update the google play services and android support libs as well).

**Comment by KreedaSolutions** [comment]
Works like a charm.. Thanks :)
