### ISSUE TITLE
[Android] Error compile in last update 2017.06.10 [v1.4.005]  

### ISSUE THREAD

**Issue by MyMyGames** [distriqt/ANE-Firebase#65]
`NEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/firebase/zza;
        at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
        at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
        at com.android.dx.command.dexer.Main.processClass(Main.java:737)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
        at com.android.dx.command.dexer.Main.access$300(Main.java:83)
        at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:637)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
        at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
        at com.android.dx.command.dexer.Main.run(Main.java:245)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)
1 error; aborting`

**Comment by marchbold** [comment]
Hi, Make sure you have updated all the Firebase and Google Play Services ANEs and if you are using FCM or Push update the Push Notifications ANE.

**Comment by MyMyGames** [comment]
Android build success.
Now in IOS build:

`Undefined symbols for architecture armv7:
  "_kFIRAppDiagnosticsSDKVersionKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_4b80f326c64c203b80c3466b899dcbf3.o)
  "_kFIRAppDiagnosticsNotification", referenced from:
      +[FIRDiagnostics load] in FirebaseCoreDiagnostics(FIRDiagnostics_4b80f326c64c203b80c3466b899dcbf3.o)
  "_kFIRAppDiagnosticsFIRAppKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_4b80f326c64c203b80c3466b899dcbf3.o)
  "_kFIRAppDiagnosticsSDKNameKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_4b80f326c64c203b80c3466b899dcbf3.o)
  "_kFIRAppDiagnosticsErrorKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_4b80f326c64c203b80c3466b899dcbf3.o)
  "_kFIRAppDiagnosticsConfigurationTypeKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_4b80f326c64c203b80c3466b899dcbf3.o)
ld: symbol(s) not found for architecture armv7
Undefined symbols for architecture arm64:
  "_kFIRAppDiagnosticsConfigurationTypeKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_5fae2e67e4a7b4383df55126bc52c2ef.o)
  "_kFIRAppDiagnosticsSDKNameKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_5fae2e67e4a7b4383df55126bc52c2ef.o)
  "_kFIRAppDiagnosticsErrorKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_5fae2e67e4a7b4383df55126bc52c2ef.o)
  "_kFIRAppDiagnosticsFIRAppKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_5fae2e67e4a7b4383df55126bc52c2ef.o)
  "_kFIRAppDiagnosticsSDKVersionKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_5fae2e67e4a7b4383df55126bc52c2ef.o)
  "_kFIRAppDiagnosticsNotification", referenced from:
      +[FIRDiagnostics load] in FirebaseCoreDiagnostics(FIRDiagnostics_5fae2e67e4a7b4383df55126bc52c2ef.o)
ld: symbol(s) not found for architecture arm64`

**Comment by marchbold** [comment]
What version of AIR are you using to package? Is anyone else having this issue?

**Comment by MyMyGames** [comment]
25.0

**Comment by marchbold** [comment]
Are you packaging against a version of the iOS SDK?

**Comment by MyMyGames** [comment]
How can i upgrade my sdk to latest version?

**Comment by marchbold** [comment]
Information on using the iOS SDK can be found here:

https://airnativeextensions.com/knowledgebase/tutorial/1#ios

You'll find links to the iOS SDK downloads there too.

**Comment by MyMyGames** [comment]
AIR Version: 25
IOS SDK: iPhoneOS10.3.sdk.zip    25-May-2017 22:58   14M (from http://resources.airnativeextensions.com/ios/)
MinimumOSVersion: 8.0

```
  <extensions>
    <extensionID>com.chartboost.plugin.air</extensionID>
    <extensionID>com.devtodev.SDK</extensionID>
    <extensionID>com.distriqt.Notifications</extensionID>
    <extensionID>com.distriqt.NetworkInfo</extensionID>
    <extensionID>com.distriqt.NativeWebView</extensionID>
    <extensionID>com.distriqt.InAppBilling</extensionID>
    <extensionID>com.distriqt.androidsupport.V4</extensionID>
    <extensionID>com.distriqt.Core</extensionID>
    <extensionID>com.distriqt.FacebookAPI</extensionID>
    <extensionID>com.distriqt.Bolts</extensionID>
    <extensionID>com.distriqt.androidsupport.CardViewV7</extensionID>
    <extensionID>com.distriqt.androidsupport.AppCompatV7</extensionID>
    <extensionID>com.distriqt.androidsupport.CustomTabs</extensionID>
    <extensionID>com.marpies.ane.androidutils</extensionID>
    <extensionID>com.distriqt.CustomResources</extensionID>
    <extensionID>com.distriqt.GoogleAnalytics</extensionID>
    <extensionID>com.distriqt.playservices.Analytics</extensionID>
    <extensionID>com.distriqt.playservices.Base</extensionID>
    <extensionID>com.distriqt.Firebase</extensionID>
  </extensions>
```

```
Undefined symbols for architecture armv7:
  "_kFIRAppDiagnosticsSDKVersionKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_4b80f326c64c203b80c3466b899dcbf3.o)
  "_kFIRAppDiagnosticsNotification", referenced from:
      +[FIRDiagnostics load] in FirebaseCoreDiagnostics(FIRDiagnostics_4b80f326c64c203b80c3466b899dcbf3.o)
  "_kFIRAppDiagnosticsFIRAppKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_4b80f326c64c203b80c3466b899dcbf3.o)
  "_kFIRAppDiagnosticsSDKNameKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_4b80f326c64c203b80c3466b899dcbf3.o)
  "_kFIRAppDiagnosticsErrorKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_4b80f326c64c203b80c3466b899dcbf3.o)
  "_kFIRAppDiagnosticsConfigurationTypeKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_4b80f326c64c203b80c3466b899dcbf3.o)
ld: symbol(s) not found for architecture armv7
Undefined symbols for architecture arm64:
  "_kFIRAppDiagnosticsConfigurationTypeKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_5fae2e67e4a7b4383df55126bc52c2ef.o)
  "_kFIRAppDiagnosticsSDKNameKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_5fae2e67e4a7b4383df55126bc52c2ef.o)
  "_kFIRAppDiagnosticsErrorKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_5fae2e67e4a7b4383df55126bc52c2ef.o)
  "_kFIRAppDiagnosticsFIRAppKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_5fae2e67e4a7b4383df55126bc52c2ef.o)
  "_kFIRAppDiagnosticsSDKVersionKey", referenced from:
      +[FIRDiagnostics logDiagnostics:] in FirebaseCoreDiagnostics(FIRDiagnostics_5fae2e67e4a7b4383df55126bc52c2ef.o)
  "_kFIRAppDiagnosticsNotification", referenced from:
      +[FIRDiagnostics load] in FirebaseCoreDiagnostics(FIRDiagnostics_5fae2e67e4a7b4383df55126bc52c2ef.o)
ld: symbol(s) not found for architecture arm64
Compilation failed while executing : ld64
Picked up _JAVA_OPTIONS:  -Xmx512M

APK setup creation FAILED.
```

**Comment by marchbold** [comment]
Hi, 
Can you make sure you have the latest versions of all the Firebase ANEs and that you aren't using hide ane symbols in your settings.

**Comment by MyMyGames** [comment]
i'm using the  latest version.  
Can you explain, what do you mean by "hidden symbols" please

**Comment by marchbold** [comment]
Hi, 

I'm referring to this option. I can be set in different places depending on your IDE.

http://help.adobe.com/en_US/flashbuilder/using/WSe4e4b720da9dedb5-2e7310a1136ab7c1811-8000.html#WSe4e4b720da9dedb52cb000931394dc3d45a-8000

**Comment by MyMyGames** [comment]
Hi
Very strange.
After I removed the extensions "com.chartboost.plugin.air" & ">com.devtodev.SDK".
Everything has been corrected.

I added extensions again, but the error did not appear

**Comment by marchbold** [comment]
Very odd. What IDE are you using? Sounds like an issue with the build

**Comment by MyMyGames** [comment]
FlashDevelop

**Comment by marchbold** [comment]
Yeah okay, must say we have had a lot of people have issues with the build process using ANEs with FlashDevelop. And often the solution has been something that seemed to update the IDE, (perhaps a cache or similar). 

Glad you have it working now though.

**Comment by MyMyGames** [comment]
Now I have a critical crash on "Firebase.init( DS_APPLICATION_KEY_IOS );"

**Comment by MyMyGames** [comment]
Hi
My mistake.
I removed all "non-distriqt" extensions, including Firebase.
There is still an error with the Firebase extension:
"Compilation failed while executing : ld64"

**Comment by marchbold** [comment]
Can you tell me exactly how you are building? A command line or something to replicate?

**Comment by MyMyGames** [comment]
FlashDevelop standart Packager.bat

```
:: iOS packaging
set IOS_DIST_CERT_FILE=cert\iosDistributionCertificates.p12
set IOS_PROVISION=cert\RainbowSquad_Distribution.mobileprovision
set IOS_ICONS=icons/ios
set IOS_DIST_SIGNING_OPTIONS=-storetype pkcs12 -keystore "%IOS_DIST_CERT_FILE%" -provisioning-profile %IOS_PROVISION%

:: Application descriptor
set APP_XML=application.xml

:ios-dist-config
set CERT_FILE=%IOS_DIST_CERT_FILE%
set SIGNING_OPTIONS=%IOS_DIST_SIGNING_OPTIONS%
set ICONS=%IOS_ICONS%
set DIST_EXT=ipa
set TYPE=ipa
goto start


:start
if not exist "%CERT_FILE%" goto certificate
:: Output file
set FILE_OR_DIR=%FILE_OR_DIR% -C "%ICONS%" .
if not exist "%DIST_PATH%" md "%DIST_PATH%"
set OUTPUT=%DIST_PATH%\%DIST_NAME%.%DIST_EXT%
:: Package
echo Packaging: %OUTPUT%
echo using certificate: %CERT_FILE%...
echo.
call adt -package -target %TYPE%%TARGET% %OPTIONS% %SIGNING_OPTIONS% "%OUTPUT%" "%APP_XML%" %FILE_OR_DIR% -extdir extensions/
echo.
if errorlevel 1 goto failed
goto end
```


app.xml 
ios section:
```

<InfoAdditions><![CDATA[<key>ITSAppUsesNonExemptEncryption</key>
<false />
<key>UIRequiresPersistentWiFi</key>
<string>NO</string>
<key>MinimumOSVersion</key>
<string>8.0</string>
<key>UIDeviceFamily</key>
<array>
	<string>1</string>
	<string>2</string>
</array>
<key>FacebookAppID</key>
<string>XXXXXXXXX</string>
<key>FacebookDisplayName</key>
<string>Rainbow Squad</string>
<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>fbXXXXXXXXX</string>
			<string>com.mymygames.RainbowSquad</string>
		</array>
	</dict>
</array>
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSExceptionDomains</key>
	<dict>
		<key>facebook.com</key>
		<dict>
			<key>NSIncludesSubdomains</key>
			<true />
			<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
			<false />
		</dict>
		<key>fbcdn.net</key>
		<dict>
			<key>NSIncludesSubdomains</key>
			<true />
			<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
			<false />
		</dict>
		<key>akamaihd.net</key>
		<dict>
			<key>NSIncludesSubdomains</key>
			<true />
			<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
			<false />
		</dict>
	</dict>
</dict>
<key>LSApplicationQueriesSchemes</key>
<array>
	<string>fb</string>
	<string>fbapi</string>
	<string>fb-messenger-api</string>
	<string>fbauth2</string>
	<string>fbshareextension</string>
</array>
<key>UIApplicationExitsOnSuspend</key>
<false />
<key>UIStatusBarStyle</key>
<string>UIStatusBarStyleBlackOpaque</string>]]></InfoAdditions>
    <Entitlements><![CDATA[<key>keychain-access-groups</key>
<array>
	<string>XXXXXXXXX.*</string>
</array>
<key>application-identifier</key>
<string>XXXXXXXXX.com.mymygames.RainbowSquad</string>
<key>com.apple.developer.team-identifier</key>
<string>XXXXXXXXX</string>
<key>aps-environment</key>
<string>production</string>
<key>beta-reports-active</key>
<true />]]></Entitlements>
```

**Comment by marchbold** [comment]
What extensions are in your extensions directory? And can you tell me what `%OPTIONS%` you are using?

**Comment by MyMyGames** [comment]
For ios build "%OPTIONS%"  is empty




Extensions (in my extensions directory)  Only "distriqt", like this:

```
  <extensions>
    <extensionID>com.distriqt.Notifications</extensionID>
    <extensionID>com.distriqt.NetworkInfo</extensionID>
    <extensionID>com.distriqt.NativeWebView</extensionID>
    <extensionID>com.distriqt.InAppBilling</extensionID>
    <extensionID>com.distriqt.Core</extensionID>
    <extensionID>com.distriqt.FacebookAPI</extensionID>
    <extensionID>com.distriqt.Bolts</extensionID>
    <extensionID>com.distriqt.GoogleAnalytics</extensionID>
    <extensionID>com.distriqt.playservices.Analytics</extensionID>
    <extensionID>com.distriqt.playservices.Base</extensionID>
    <extensionID>com.distriqt.Firebase</extensionID>
  </extensions>
```

**Comment by marchbold** [comment]
So you only have those ANEs in your extensions directory?

Could you try updating to AIR 26 and see if that helps you?
