### ISSUE TITLE
FirebaseDatabase.service.getReference("what_should i put here");

### ISSUE THREAD

**Issue by taktitech** [distriqt/ANE-Firebase#66]
Im new to databases and stuff.
what string should be in .getReference"WHAT");
the name of my database?
the tree titles?
However i get this error 
dbref:once:error::{"errorDescription":"Permission denied","id":"/node/","errorCode":-3}

can someone help me understand better...
Thank you very much :)

**Comment by marchbold** [comment]
Firebase Database data is stored similar to JSON, so you can think of the database as a cloud-hosted JSON tree. There are no tables or records like in SQL or other databases.

When you call `getReference( "key" )` you are retrieving a node in the JSON structure:

For example, `getReference( "/users/someUser" )` would return the "someUser" object in the example structure below:

```
{
  "users": {
    "someUser": {
      "name": "Some User",
    },
    "otherUsername": { ... }
  }
}
```

The "permission denied" error you are receiving is related to your database permissions. You set these up in the console, the default just requires an authenticated firebase user, however you can set them as you require. For more on this read the docs on security:

https://firebase.google.com/docs/database/security/

**Comment by marchbold** [comment]
Did that answer your question? Let me know if you need any further help getting started.

**Comment by taktitech** [comment]
Yes Thanks :)
