### ISSUE TITLE
Application crashes when using realtime database

### ISSUE THREAD

**Issue by taktitech** [distriqt/ANE-Firebase#70]
Hi,
since i updated the new FireBase ANE's my app is crashing with no errors
when i code the next line:
var success:Boolean = Firebase.service.initialiseApp();

with the last ane's everything worked great
Waiting for reply
Tomer.

**Comment by marchbold** [comment]
Hi,

Have you updated all the dependent anes as well? It's important that you have the latest google play services, android support and core ANEs.

**Comment by taktitech** [comment]
Hi,
I updated all the anes just now and i still get the same crashing.
the strange thing is that i dont get any errors so i dont know how to start dealing with the bug however
i am almost ure that this line:
var success:Boolean = Firebase.service.initialiseApp();

is making the problem

**Comment by marchbold** [comment]
Could you post the logs from the device, and include some information about the platform and version you are encountering this issue on?

https://airnativeextensions.com/knowledgebase/faq/11

**Comment by taktitech** [comment]
i attached the logcat, i hope you will find the problem.
waiting forward...
thnx
[logcat.txt](https://github.com/distriqt/ANE-Firebase/files/1093760/logcat.txt)

**Comment by marchbold** [comment]
Appears you have additions for FCM but don't have the PushNotifications ANE listed in your extensions? Looks as though your crash is related to that. 

You'll need to make sure you've added the PushNotifications ANE or remove the FCM references from your manifest additions.

**Comment by taktitech** [comment]
amazing, i added the push ane and everything is fine!
Thanks

**Comment by marchbold** [comment]
Sweet! Glad we found the issue!
