### ISSUE TITLE
AUTH - Support for Custom Auth

### ISSUE THREAD

**Issue by KreedaSolutions** [distriqt/ANE-Firebase#71]
Hi, 

If we can get this - https://firebase.google.com/docs/auth/android/custom-auth,

We can implmenet our own AuthSystem and also have more providers like Linkedin/instagram. 

We need to have following flow - 
1) Send Linkedin ID Token/Access Token to Firebase Cloud Functions 
2) Cloud Functions Verifies the user and create "Firebase Custom Token"
3) send "Firebase Custom Token" to client
4) Login in at client via "Firebase Custom Token" 

Will this be possible to add this feature?

Thanks, 
Aseem

**Comment by marchbold** [comment]
Will look into it and see what we can do. From a brief look doesn't seem like it should be a problem.

**Comment by KreedaSolutions** [comment]
great :)
