### ISSUE TITLE
DatabaseReferenceChildEvent.CHILD_ADDED triggers twice on first load?

### ISSUE THREAD

**Issue by kakarlus** [distriqt/ANE-Firebase#72]
Hi @marchbold 

im currently using the custom resources you sent me so i can proceed.
im having trouble with getting a list in the database and listening to a CHILD_ADDED event to it.
here's a snippet, the problem is it fetches the same data twice on its initial load.

```
var ref:DatabaseReference = FirebaseDatabase.service.getReference( userData.localId );
ref.child('/items').addEventListener( DatabaseReferenceChildEvent.CHILD_ADDED, child_addedHandler);
```

regards,
Carlos

**Comment by marchbold** [comment]
Sorry can you explain a little more what you are seeing?

**Comment by kakarlus** [comment]
![screen shot 2017-06-23 at 4 32 45 pm](https://user-images.githubusercontent.com/809310/27473388-a3cb276a-5831-11e7-8378-633f8e8e9fee.png)

i have these in my db, and my child_addedHandler gets called twice on first load, and i see the list twice on my display --> zz, zz, name2, name2, name, name

**Comment by marchbold** [comment]
What do you mean by first/initial load? Could you show some more code or what you are doing to trigger the events?

**Comment by kakarlus** [comment]
this is how i did it

```
private function loadUserItems():void{
	var ref:DatabaseReference = FirebaseDatabase.service.getReference( userData.localId );
	ref.child('/items').addEventListener( DatabaseReferenceChildEvent.CHILD_ADDED, child_addedHandler);
	ref.child('/items').orderByChild('name');
}

private function child_addedHandler(e: DatabaseReferenceChildEvent):void {
	var item: Object = e.snapshot.value;
	item.id = item.key;

	var tile: ItemTile = new ItemTile(item);
	tiles.push(tile);
	tile.addEventListener(Event.TRIGGERED, tile_triggeredHandler);
	addChild(tile);
}
```

**Comment by kakarlus** [comment]
not sure how to correctly implement this, i tried using `ref.child('/items').once( myFunc )` to display the list of my items and add a `DatabaseReferenceChildEvent.CHILD_ADDED` listener under the same `myFunc` function.

problem is the listener gets called immediately, that's why im getting duplicates of my items list

**Comment by marchbold** [comment]
Could you show a complete example demonstrating the issue so we can look into it?  We aren't quite sure what you are doing from these snippets

**Comment by kakarlus** [comment]
got it working, i knew it was a wrong implementation. i should add the `DatabaseReferenceChildEvent.CHILD_ADDED` to a `Query` instead of `DatabaseReference`

i don't know why though lol

**Comment by marchbold** [comment]
Glad you got it working. Cheers
