### ISSUE TITLE
RealTime Database - search in nodes

### ISSUE THREAD

**Issue by taktitech** [distriqt/ANE-Firebase#73]
is it possible to search the firebase database nodes and to compare them
for example:
i have a phone number of a user and i want to search the database to see if it's there
is this possible ?

**Comment by marchbold** [comment]
There's no direct "search" functionality, however you can use the [Sorting and Filtering data](https://github.com/distriqt/ANE-Firebase/wiki/Database---Lists#sorting-and-filtering-data) functionality to retrieve data sorted in a particular way.

```as3
FirebaseDatabase.service.getReference( "phonenumbers" )
    .orderByChild( "phone" )
    .startAt( "0444444444" )
    .endAt( "0444444445" );
```

**Comment by taktitech** [comment]
thnx :)

**Comment by marchbold** [comment]
No problems
