### ISSUE TITLE
Error with resources.ane

### ISSUE THREAD

**Issue by sfxworks** [distriqt/ANE-Firebase#79]
```
Adobe Animate 
Error creating files. 
Unknown error. unexpected failure duplicate entry: air/quantumtechnologies/myappname/R.class java.util.zip.ZipException: duplicate entry: air/quantumtechnologies/myappname/R.class at java.util.zip.ZipOutputStream.putNectEntry(ZipOutputStreamjava:232) at java.utiljarJarOutputStream.putNectEntry(larOutputStreamjava:109) at com.adobe.air.apk.ResourceBytecodeGenerator.generateFromRFile(Res ourceBytecodeGeneratorjava:85) at com.adobe.air.apk.APKOutputStream.generateByteCodeFromRFile(APK OutputStreamjava:1054) at com.adobe.air.apk.APKOutputStream.generateResourcesAndManifest( APKOutputStreamjava:1011) at com.adobe.air.apk.APKOutputStream.addApplicationDescriptor(APKOu tputStreamjava:321) at com.adobe.air.ApplicationPackager.addSpecialFiles(ApplicationPackag erjava:352) at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackage rjava:76) 
at com.adobe.air.ADT.parseArgsAndGo(ADTjava:656) at com.adobe.air.ADT.run(ADTjava:450) at com.adobe.air.ADT.main(ADTjava:500) 
OK 
```

After [building](https://github.com/distriqt/ANE-CustomResources/issues/18) my custom resources ane and including it, I come across this error. I am using Adobe Animate.

I am unable to use this service. I was able to use it just fine a few months ago by including the google-services.json. Why is it not working?

Using (and built with) AIR 25

**Comment by marchbold** [comment]
Can you explain the changes you made to the resources config when building the ANE? 

As a means to move you forward you can send your resources to us (airnativeextensions@distriqt.com) and we'll build you the resources ANE.

**Comment by sfxworks** [comment]
I did not have a resources config. The only thing I had inside resources was values/values.xml with the following content:

<?xml version="1.0" encoding="utf-8"?>
<resources>

```
<?xml version="1.0" encoding="utf-8"?>
<resources>

    <string name="google_app_id" translatable="false">1:9000[private]273fa</string>

    <string name="gcm_defaultSenderId" translatable="false">90[private]73</string>
    <string name="default_web_client_id" translatable="false">9[private]73-n2cvaivv4g6k5j8k3a6vm3i57reicaua.apps.googleusercontent.com</string>
    <string name="firebase_database_url" translatable="false">https://[private].firebaseio.com</string>
    <string name="google_api_key" translatable="false">AIza[private]kc</string>
    <string name="google_crash_reporting_api_key" translatable="false">AIza[private]kc</string>
    <string name="google_storage_bucket" translatable="false">[private].appspot.com</string>

</resources>
```

This was my build config. I replaced the default sdk in Animate with the downloadable one on Adobe's site. The one in animate wasn't working. I believe it was looking for flex materials as I had some errors referencing that.

```
## ANE build config


# AIR SDK
air.sdk = C:\\Program Files\\Adobe\\Adobe Animate CC 2017\\AIR25.0

# ANDROID
android.sdk = sdk

# CHANGE THIS PACKAGE NAME IF YOU ARE USING FIREBASE
android.package = air.quantumtechnologies.mobilevapedistro



## 
project.name = Resources
version = 1

output.name = ${android.package}.${project.name}.ane
output.dir = ./build
output.docs = ./build/docs

actionscript.dir = ./platform/actionscript
default.dir = ./platform/default
android.dir = ./platform/android
android.resdir = customresources
android.resources = res
```

**Comment by marchbold** [comment]
Not really sure what you are doing with your build config. Perhaps just try using a clean download of the AIR SDK for this script.

I've sent you back a packaged ane to use.

Cheers

**Comment by sfxworks** [comment]
Ran into this same issue when trying to build a new application at the end. Redownloaded everything for this new project.

Would you mind building this one as well?

**Comment by marchbold** [comment]
Yeah no worries, just send you resources (values/icons etc) to airnativeextensions@distriqt.com

**Comment by sfxworks** [comment]
Appreciate it. Sent it from sfxworks@gmail.com
All it is is the xml file converted from the google-services.json

**Comment by SaleemEM** [comment]
Hi team,

I am having same problem so I am also sending you an email (saleema@extramarks.com) with all required assets.
I'd appreciate if you please build and send back resource ANE asap.

Regards,
Team Extramarks

**Comment by SaleemEM** [comment]
Hi Team,

I just sent an email, please help us regarding this issue.

**Comment by marchbold** [comment]
Hi @SaleemEM, we've sent you the ANE.
