### ISSUE TITLE
shallow

### ISSUE THREAD

**Issue by sfxworks** [distriqt/ANE-Firebase#80]
I have a database with a lot of nested data. I just need to skim the top for names. I would like to be able to use the shallow feature when retrieving data.

https://firebase.google.com/docs/database/rest/retrieve-data#shallow

**Comment by marchbold** [comment]
As far as we are aware that parameter isn't available in the mobile SDKs. 

You should be able to use the REST API if you require through normal web queries, though we haven't tried that ourselves.
