### ISSUE TITLE
How do I query? It is null.

### ISSUE THREAD

**Issue by sfxworks** [distriqt/ANE-Firebase#83]
Following the steps on the guide on your wiki, I am trying to query and get the results.

```
		private function getTotalSales():void
		{
			var ordersQuery = FirebaseDatabase.service.getReference("orders").child("assigned")
							.orderByKey()
							.equalTo(true, "paid")
							.equalTo("-KmatpIR5erS-8SgrICS", "owner");
			ordersQuery.addEventListener(DatabaseReferenceChildEvent.CHILD_ADDED, handleQueryChildAdded); //Cannot access a property or method of a null object reference.
		}
```

However, It seems that I am unable to get any results from my query as it is still null after I make it.

```
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at src.ui.scenes::DriverOverview/getTotalSales()[C:\Users\Samuel\Creative Cloud Files\[anapp]\src\ui\scenes\DriverOverview.as:50]
	at src.ui.scenes::DriverOverview()[C:\Users\Samuel\Creative Cloud Files\[anapp]\src\ui\scenes\DriverOverview.as:41]
	at flash.display::MovieClip/gotoAndStop()
	at src.ui.scenes::Menu/handlePhaseTimer()[C:\Users\Samuel\Creative Cloud Files\[anapp]\src\ui\scenes\Menu.as:231]
	at flash.utils::Timer/_timerDispatch()
	at flash.utils::Timer/tick()

```

How do I do this?

**Comment by marchbold** [comment]
That means that the node you have queried doesn't exist. You'll have to narrow down which query returns null and rectify the issue with your data.

**Comment by sfxworks** [comment]
Do I need to include the root element? It definitely exists.. 
![what](https://user-images.githubusercontent.com/5921035/27891047-1feb6b6a-61c5-11e7-8585-c4a85c9f0764.png)

**Comment by marchbold** [comment]
No you don't need to include root. Your query should correctly find the assigned node. 

Can you identify which query is resulting in the null?

i.e. break up the chaining and step through your code to see where the null occurs. This should help you identify the issue:

```
var orders:DatabaseReference = FirebaseDatabase.service.getReference("orders");
var assigned:DatabaseReference = orders.child("assigned");
// etc
```

**Comment by sfxworks** [comment]
Both references are returning just fine. I will note that in this class there is a variable called datastore that does a fetch on orders as well as other top-level nodes from the same database. However, I do not have any problem with those fetches.


````
		private function getTotalSales():void
		{
			var orderRef:DatabaseReference = FirebaseDatabase.service.getReference("orders");
			trace("Order Ref == " + orderRef);
			var assignedRef:DatabaseReference = orderRef.child("assigned");
			trace("Assigned Ref == " + assignedRef);
			
			try
			{
				var ordersQuery = assignedRef
								.orderByKey()
								.equalTo(true, "paid")
								.equalTo("-KmatpIR5erS-8SgrICS", "owner");
				ordersQuery.addEventListener(DatabaseReferenceChildEvent.CHILD_ADDED, handleQueryChildAdded);
				
				var weekOrders = assignedRef
								.orderByKey()
								.startAt(new Date().time, "orderTime")
								.equalTo(true, "paid")
								.equalTo("-KmatpIR5erS-8SgrICS", "owner");
				weekOrders.addEventListener(DatabaseReferenceChildEvent.CHILD_ADDED, handleWeekQueryAdded);
				
			}
			catch (e:Error)
			{
				trace("Error in query");
				trace(e);
			}
			
		}
````


Made some progress though. I didn't see anything in the wiki requiring a start at end at with orderbykey.
```
Order Ref == [object _DatabaseReference]
Assigned Ref == [object _DatabaseReference]
Error in query
TypeError: Error #1009: Cannot access a property or method of a null object reference.
Error #2044: Unhandled error:. text=You must use startAt(String value), endAt(String value) or equalTo(String value) in combination with orderByKey(). Other type of values or using the version with 2 parameters is not supported
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
Error #2044: Unhandled error:. text=Attempt to invoke virtual method 'java.lang.String com.adobe.fre.FREObject.getAsString()' on a null object reference
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
SyntaxError: Error #1132: Invalid JSON parse input.
```

**Comment by sfxworks** [comment]
Hello,

I sent you an email with further detail. Please let me know if I can provide any more information.

**Comment by sfxworks** [comment]
Hello
The only thing I can get working with query is an orderByChild, and an equalTo. I can't combo more than one equalTo. I also cannot use a startAt or endAt at the same time or separate.

**Comment by marchbold** [comment]
Hi, I don't believe Firebase allow you to use multiple equalTo queries with 2 parameters? Are you sure that is supported?

Firebase queries are quite picky. You need to make sure the approach you are using is supported. 
 
When you orderByKey your constraints must be related to the keys, which is why the error is complaining about the 2 parameter versions (with a key and value). 

orderByKey -> startAt( "min key" ) -> endAt( "max key" ) -> equalTo( "key value" )

**Comment by sfxworks** [comment]
So by that last line, I have to work from left to right and I can't skip anything. Is this correct? I don't understand what you mean.

**Comment by marchbold** [comment]
Yes, from left to right, however you should be able to stop after the orderbykey or after the endat calls.

**Comment by sfxworks** [comment]
I'll test that tomorrow, thanks. I remember having trouble with some of the references but I believe it was due to something else I fixed.

**Comment by sfxworks** [comment]
I am still unable to get a value out of this query. When I pull it with a once and cycle through the value with a for loop, I can filter it just fine.

			`var query:Query = orderAssignedRef.orderByKey().startAt(0, "orderTime").endAt(new Date().time, "orderTime").equalTo("KmgdIhiHOc5Fjwk9eVj", "worker");
`

**Comment by marchbold** [comment]
Looks like you are still using the 2 parameter version of those functions which I believe you cannot do in combination with orderByKey. When you orderByKey the limiters (startAt/endAt/equalTo) must be in reference to the key i.e. only use the single parameter version.

**Comment by sfxworks** [comment]
I don't understand what you mean. I can't use two params on my .startAt .endAt .equalTo functions after the return query from .orderByKey? Can you possibly show me a demo of the correct way to do what I am trying to do?

**Comment by marchbold** [comment]
```as3
var query:Query = orderAssignedRef.orderByKey().startAt("startKeyValue").endAt("endKeyValue");
```

**Comment by sfxworks** [comment]
Isn't key the base64 string the list uses though? If I am trying to order by a property in a list called orderTime, and only want results that have the property owner equal to a string how would that work?

**Comment by marchbold** [comment]
Thats correct, `orderByKey` uses the firebase key to order the list. Sounds like you want to use `orderByChild` to order your results by a child value:

```as3
var query:Query = orderAssignedRef.orderByChild( "orderTime" ).startAt( "startValue" ).endAt( "endValue" );
```

**Comment by sfxworks** [comment]
Sorry, that and the property 'owner' I want equal to a string. Would that have to be done after the first query? And is this possible while maintaining the original query's order?

**Comment by marchbold** [comment]
Not sure it's possible to do that. You might have to iterate over the results to filter further.

Have you found some firebase documentation saying it is possible?
