### ISSUE TITLE
Problem creating crash report log

### ISSUE THREAD

**Issue by sleoni** [distriqt/ANE-Firebase#85]
Hi,
I've set Firebase ANE for crash reporting. 
Call to Firebase.service.initialiseApp() returns success.  
Call to Firebase.init and FirebaseCrash.init went fine. 

For testing purpose I executed following:
1) FirebaseCrash.service.log( "Testing a crash log message" );
2) FirebaseCrash.service.forceCrash();

Both calls created logs on Firebase web console.

My problem is that when my app crashes (after taking 30 photos using distriqt CameraUI ANE) I don't get any logs in mi Firebase web console. Is there something else that I need to configure to get crash log for this type of problem?

Thanks

**Comment by marchbold** [comment]
What platform are you on?

Not all crashes can be reported. There are many that will not be detectable by the application, these include out of memory errors on iOS and some other critical crash types.

**Comment by sleoni** [comment]
I'm running on both iOS and Android. But on Android my app is not crushing at all while on iOS it crashes, depending on device, after 25 (older devices) or 50 (newer devices) photos are taken. Btw not related to this ANE but I notices that when using CameraUI distriqt ANE that handler for CameraUIEvent.COMPLETE is firing multiple times.

**Comment by marchbold** [comment]
Okay, could you report that in the CameraUI repository and we'll follow up there.
Cheers
