### ISSUE TITLE
once fails silently if it's callback has an error

### ISSUE THREAD

**Issue by sfxworks** [distriqt/ANE-Firebase#88]
I've been trying to figure out why my once functions won't work at random yet they trace the output just fine. I have a pretty solid theory as to why.

In my class, I call two once functions from two different existing nodes. One populates the UI and runs just fine without errors. The other one was trying to handle a value passed to it that was incorrect.  This broke as it was supposed to display a dialog after it finished parsing the results but it threw no errors and I didn't get a stack trace. Can you look into this? I have example code I can send you if needed. To replicate: if you cause any sort of error in your callback after compiling in a function and set it as a callback it will only trace your results and any trace statements before line the error occurs.

Edit: I can confirm this.
After running a function of mine with the data from the note prefetched I received an error on one of my lines in my debugger. This didn't happen with the same function I had using the once function.
After I fixed my function the once function worked just fine.

**Comment by marchbold** [comment]
Hi, Could you show us what you mean with some code? Not quite sure what you are doing.

**Comment by sfxworks** [comment]
I'll have an example for you tomorrow.

**Comment by sfxworks** [comment]
Hi.
Basically, this. 

```Actionscript
package src.ui.scenes 
{
	public class Example extends CoreScene 
	{
		
		private var undefinedValue:String;
		
		public function Example() 
		{
			super();
			dataStore.database.child("workers").once(handleOnceFunction);
			handlePreloadedObject(dataStore.workers);
		}
		
		private function handleOnceFunction(value:Object):void 
		{
			trace("Do something first."); //Traces
			undefinedValue.indexOf("giveMeAStackTrace"); //... 
			trace("Do something else."); ///
		}
		
		private function handlePreloadedObject(value:Object):void
		{
			trace("Do something first."); //Traces
			undefinedValue.indexOf("giveMeAStackTrace"); //Access of undefined property  
			trace("Do something else."); ///
		}
		
	}

}
```

A litte info: The datastore is a class called DataSyncStore I made that among other things preloads sections of my database with value change events and puts them into objects that other scenes can access. I could obviously throw this error with any argument in the function but I am just using this example because this is how I ran into the error. It also shows that the value exists but it ran into an error inside the function.

**Comment by marchbold** [comment]
I'm still not sure exactly what you are doing and what's failing? Looks like you are calling `once` but immediately checking the value? 

You shouldn't expect this value to be available until the once function is called.

**Comment by sfxworks** [comment]
That's not what I am doing.  In that demo it is bound to handleOnceFunction and not handlePreloadObject. The purpose is to demonstrate two functions that do exactly the same thing but give me an error. It doesn't matter if I am touch the value of the result at all.

What I am trying to say is if there is an error in the. callback(the callback being **handleOnceFunction** and the error: **undefinedValue.indexOf** the debugger doesn't get the error and doesn't print a stacktrace. _However_,in a similar function **handlePreloadedObject** I pass an object that I get in the background using DatabaseReferenceEvent.VALUE_CHANGED before the Example class is constructed. Yet this similar function, which should throw an error and a stacktrace to the debugger because it calls **undefinedValue.indexOf** doesn't. It just fails silently.

**Comment by marchbold** [comment]
The callback is wrapped internally in a try/catch so that an error in the supplied callback doesn't break the Database functionality. 

Is that what your issue is? If you need to catch an error in your handler use a try catch statement inside your handler. 

```as3
private function handleOnceFunction(value:Object):void 
{
	try 
	{
		trace("Do something first."); //Traces
		undefinedValue.indexOf("giveMeAStackTrace"); //... 
		trace("Do something else.");
	}
	catch (e:Error)
	{
		trace( e );
	}
}
```

**Comment by sfxworks** [comment]
Got it. I didn't know that. This will be useful for testing thanks.
