### ISSUE TITLE
Launching Firebase Core Example Project

### ISSUE THREAD

**Issue by embpdaniel** [distriqt/ANE-Firebase#90]
Hi, I'd like to test Firebase from your example project but the example is missing the `com.distriqt.CustomResources` ANE. I guess my first question is, are these examples set up to actually run or are they just code examples? If these examples should run (the config files are valid, etc...) is there some way I can get this particular resources ANE so I can test the example?

Thanks in advance

**Comment by marchbold** [comment]
Hi, 

As we use our certificates tied to particular console applications that we control we can't provide complete compiling examples. This information is contained in the custom resources ANE.

You'll have to change the configuration as per the documentation to your application details and then create your own custom resources extension.

The wiki contains all the information to guide you through this process:

https://github.com/distriqt/ANE-Firebase/wiki/Setup---Configuration-Files

If you have any issues creating the custom resources extension, send us your resources (airnativeextensions@distriqt.com) and we'll create it for you.

**Comment by embpdaniel** [comment]
Sounds good, thanks for clarifying!
