### ISSUE TITLE
Android app crashes on launch

### ISSUE THREAD

**Issue by embpdaniel** [distriqt/ANE-Firebase#91]
Hi, I have set up the Dynamic Links example project  to test on my device (this is not about dynamic links though). I have set it up with a custom resources ANE to provide config details per the Wiki. The custom ANE compiled with no issue, and the app builds with no problem when I include the ANE and all the required ANEs for Firebase, but when I try to launch the app on my Android device it crashes immediately and a dialog with a message shows up reading "Unfortunately, TestFirebase has stopped."

Any idea what could be causing the app to crash? What I know so far (in case it helps):

- I am using the latest ANEs
- I cannot launch the Android build on the Firebase core example either, so it doesn't seem related to the Dynamic Links ANE, specifically
- It seems to work fine on IOS. I can launch it on the simulator at least
- I am using Adobe AIR 23

I can provide the projects if needed. Let me know, thanks!

**Comment by marchbold** [comment]
Hi, 

Most likely this is related to not correctly setting your application package name in the manifest additions: 

The details for the Firebase core extension is here:

https://github.com/distriqt/ANE-Firebase/wiki/Core---Add-the-extensions  

Make sure you correctly replace the `YOUR_APPLICATION_ID` where indicated. 

You can check the logs for a report on why the application isn't launching:

https://airnativeextensions.com/knowledgebase/faq/11

If you can't resolve the issue, post the log here and I'll look through it to see what the issue is.

**Comment by embpdaniel** [comment]
Hi, thanks for this tip. Here is the error I am getting in the log:

```
07-31 13:09:27.766 16981 16981 E AndroidRuntime: FATAL EXCEPTION: main
07-31 13:09:27.766 16981 16981 E AndroidRuntime: Process: air.com.repit.repithighschool, PID: 16981
07-31 13:09:27.766 16981 16981 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzbo; or its super classes (declaration of 'com.google.android.gms.common.internal.zzbo' appears in /data/app/air.com.repit.repithighschool-1/base.apk)
07-31 13:09:27.766 16981 16981 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
07-31 13:09:27.766 16981 16981 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:5243)
07-31 13:09:27.766 16981 16981 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4838)
07-31 13:09:27.766 16981 16981 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4778)
07-31 13:09:27.766 16981 16981 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:157)
07-31 13:09:27.766 16981 16981 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
07-31 13:09:27.766 16981 16981 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-31 13:09:27.766 16981 16981 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-31 13:09:27.766 16981 16981 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5527)
07-31 13:09:27.766 16981 16981 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-31 13:09:27.766 16981 16981 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
07-31 13:09:27.766 16981 16981 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```
Let me know your thoughts, thanks!

**Comment by marchbold** [comment]
That error indicates you don't have matching versions of Google Play Services. Make sure you have the latest versions of all the Firebase and Google Play Services ANEs you are using.

**Comment by embpdaniel** [comment]
Shoot. Thanks @marchbold that was it! It launches now
