### ISSUE TITLE
Firebase.analytics.setCurrentScreen

### ISSUE THREAD

**Issue by railnation** [distriqt/ANE-Firebase#92]
Hi, 

I cant see any screens in the Firebase Dashboard, any other method works fine.

My code as follows:

var success:Boolean = Firebase.service.analytics.setCurrentScreen( dto.screenName, "Screen" );

dto.screenName is similar to com.traviangames.railnation.techtree::Techtree

Success is always true but no data is shown up. Any hints?

Best regards Christian

**Comment by marchbold** [comment]
That call I believe sets the screen name for other events, so you need to make sure you log some events after the call.

**Comment by railnation** [comment]
Thanks for the advice. I will try
