### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by sfxworks** [distriqt/ANE-Firebase#93]
````Actionscript
package src.service 
{
	import com.distriqt.extension.firebase.database.DatabaseReference;
	import com.distriqt.extension.firebase.database.MutableData;
	import com.distriqt.extension.firebase.database.transactions.TransactionHandler;
	import com.distriqt.extension.firebase.database.transactions.TransactionResult;
	
	public class OrderTransactionHandler implements TransactionHandler 
	{
		private var currentOrder:DatabaseReference;
		
		public function OrderTransactionHandler(currentOrder:DatabaseReference) 
		{
			super();
			this.currentOrder = currentOrder;

		}
		
		
		/* INTERFACE com.distriqt.extension.firebase.database.transactions.TransactionHandler */
		
		public function doTransaction(mutableData:MutableData):TransactionResult 
		{
			var data:Object = mutableData.getValue();
			if (data == null)
			{
				mutableData.setValue(0);
				currentOrder.child("number").setValue(0);
				
				return TransactionResult.success(mutableData);
			}
			
			mutableData.setValue(mutableData.getValue() + 1);
			currentOrder.child("number").setValue(mutableData.getValue());
			return TransactionResult.success(mutableData);
		}
		
	}

}
````
I'm trying to give my list an order number. Inside one node that I run the transaction on I have a property called (numberOfOrders). I want to run a transaction on it (increasing it by one) and then taking that value and adding it to my new order (the database reference)

Can any logic really go in here or am I doing something wrong? I am not getting any errors but I do not see any values updated.

**Comment by marchbold** [comment]
You shouldn't attempt to access data outside the scope of the mutable data during the transaction. Instead use the transaction complete event to access the final data state and use that to set your value. doTransaction may be called multiple times during a transaction so your logic should only operate on the mutable data object.

**Comment by sfxworks** [comment]
What do I tag the event listener on to get the final data? The database reference or something else? And what event/type do I use?

**Comment by marchbold** [comment]
The same `DatabaseReference` that you call `runTransaction` on you can listen for the `DatabaseReferenceEvent.TRANSACTION_COMPLETE` event:

https://distriqt.github.io/ANE-Firebase/asdocs/com/distriqt/extension/firebase/database/events/DatabaseReferenceEvent.html
