### ISSUE TITLE
Trouble opening deep link on IOS

### ISSUE THREAD

**Issue by embpdaniel** [distriqt/ANE-Firebase#94]
Hi, I have been able to generate a dynamic short link on my IOS app. However, when clicking on this link from a test web page on IOS, it opens my fallback url and never launches the app. Wondering if maybe I have a misconfiguration somewhere. Also, to note I am using the IOS simulator to test and not an actual device. Should this work on the simulator? If not maybe that is the problem. But if it should work then here is my setup below, let me know if anything looks off:

Iphone settings in app.xml
```
<iPhone>
    <InfoAdditions><![CDATA[
  <key>UIDeviceFamily</key>
  <array>
    <string>1</string>
    <string>2</string>
  </array>
  <key>UIStatusBarStyle</key>
  <string>UIStatusBarStyleBlackTranslucent</string>
  <key>NSAppTransportSecurity</key>
  <dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
  </dict>

  <key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>repithighschool</string>
      </array>
    </dict>
  </array>
]]></InfoAdditions>

    <requestedDisplayResolution>high</requestedDisplayResolution>

    <Entitlements>
      <![CDATA[
			<key>application-identifier</key>
			<string>PREFIXREMOVED.com.repit.repithighschool</string>
			<key>aps-environment</key>
			<string>production</string>
			<key>keychain-access-groups</key>
			<array>
			<string>PREFIXREMOVED.com.repit.repithighschool</string>
			</array>

			<key>com.apple.developer.associated-domains</key>
      <array>
        <string>applinks:v8w6e.app.goo.gl</string>
      </array>
			]]>


    </Entitlements>

  </iPhone>
```
App Code
```

var iosUrlScheme:String = "repithighschool";
var packageName:String = "com.repit.repithighschool";
var url:String = "https://www.someurl.com/news/75";
var dynamicLinkDomain:String = "v8w6e.app.goo.gl";

//During Initialization of Firebase I set this
Firebase.init(theKey);
FirebaseDynamicLinks.init(theKey);
Firebase.service.deepLinkURLScheme = iosUrlScheme;
Firebase.service.initialiseApp();

var builder:DynamicLinkBuilder = new DynamicLinkBuilder();
			builder.setLink( url )
				.setDynamicLinkDomain( dynamicLinkDomain )
				.setAndroidParameters(
					new AndroidParametersBuilder( "air." + packageName )
						.setFallbackUrl("https://airnativeextensions.com")
						.build()
				)
				.setIosParameters(
					new IosParametersBuilder( packageName )
						.setCustomScheme(iosUrlScheme)
						.setFallbackUrl("https://airnativeextensions.com")
						.build()
				)
				.setSocialMetaTagParameters(
					new SocialMetaTagParametersBuilder()
						.setTitle(socialShareTitle)
						.build()
				);

FirebaseDynamicLinks.service.createShortDynamicLink(builder.build());
```

I have also ensured to include GoogleService-info.plist in my app and have confirmed it is included by extracting the .ipa contents.

Is there anything else I am missing here?

Thanks in advance!

**Comment by marchbold** [comment]
Hi, 

I don't think these will work in the simulator. Most app store related features will require a device to test. Can you run on a real device and see if you get the same issue?

If it does you can test your firebase project is correctly configured by opening the following URL (replacing app_code with your app code):

```
https://app_code.app.goo.gl/apple-app-site-association
```

If your app is connected, the apple-app-site-association file contains a reference to your app's App Store ID and bundle ID.

Also try clearing permissions on the device. If you have denied the popup to launch the app you may have to do this to get it working again.

**Comment by embpdaniel** [comment]
The link actually shows my app ID prefix and the bundle ID, and not the store ID. Is that expected? I double-checked the Firebase app settings and the store ID and app ID prefix are set in the proper fields. Let me know, thanks

**Comment by marchbold** [comment]
Ah yes that's correct, sorry used the wrong term above.

Just make sure you have been through the developer console correctly then and updated your provisioning profile:

https://github.com/distriqt/ANE-Firebase/wiki/DynamicLinks---Add-the-extension#ios

**Comment by embpdaniel** [comment]
Hi @marchbold I tested in my iPad, and I noticed that if the app is completely closed and I click on a link, the app is invoked, the `DynamicLinkEvent.RECEIVED` event fires, and I get the expected payload. If the app is open but in the background, and I hit the same link, the app is invoked, but I never receive the `DynamicLinkEvent.RECEIVED` event. Do you know what the issue might be?

**Comment by marchbold** [comment]
Just noticed you are missing the delegate flag from your info additions:

```
<key>FirebaseAppDelegateProxyEnabled</key>
<false/>
```

Could you add this in and test again?

https://github.com/distriqt/ANE-Firebase/wiki/Core---Add-the-extensions#ios-info-additions--entitlements

**Comment by embpdaniel** [comment]
Thanks for catching that @marchbold . I added it in but no luck. Same issue. Any other idea?

**Comment by marchbold** [comment]
Can you post the logs from the device in the two scenarios? 

https://airnativeextensions.com/knowledgebase/faq/11

**Comment by embpdaniel** [comment]
@marchbold I have emailed you the logs to airnativeextensions@distriqt.com. Let me know if you don't get them or if you need anything else!

**Comment by marchbold** [comment]
Thanks for that I've received the logs. 

What other ANEs are you using in your application? Definitely seems like a delegate issue, as none of the distriqt calls seem to appear in the open log. This may indicate that the delegates we use are getting overridden by another extension.

**Comment by embpdaniel** [comment]
Hi @marchbold sorry for my delayed response. Finally got back on this. So we removed some of the extra ANEs we have and left it with these:

```
<extensions>
    <extensionID>com.distriqt.Dialog</extensionID>
    <extensionID>ru.flashpress.FPUniqueId</extensionID>
    <extensionID>com.distriqt.Core</extensionID>
    <extensionID>com.distriqt.androidsupport.V4</extensionID>
    <extensionID>com.distriqt.playservices.Base</extensionID>
    <extensionID>com.distriqt.Firebase</extensionID>
    <extensionID>com.distriqt.firebase.DynamicLinks</extensionID>
    <extensionID>com.distriqt.CustomResources</extensionID>
  </extensions>
```
We are still having trouble getting the `DynamicLinkEvent.RECEIVED` event to fire with this set of extensions. We have ensured the listener is being added like this:
`FirebaseDynamicLinks.service.addEventListener( DynamicLinkEvent.RECEIVED, dynamicLinkReceivedHandler );`

Like I said, works on a brand new launch and not when invoked from background. Please let me know if there is something we can try to get this working. Thanks

**Comment by marchbold** [comment]
Are you testing this on a device now? What versions of iOS have you tested?

**Comment by embpdaniel** [comment]
Yes I am testing on a real device , iPad retina, 4th generation running IOS 10.0.2. This is the only version and device I have tested on.

**Comment by marchbold** [comment]
Are you calling `Core.init();` in your code?

```as3
Core.init();
Firebase.init( KEY );
FirebaseDynamicLinks.init( KEY );

```

**Comment by embpdaniel** [comment]
Yes I am. Here's how my initialization looks like in case it helps:

```
public function init():void {
  if(!_isInitialized) {
    if(Firebase.isSupported) {
      Core.init(FirebaseConfigModel.getInstance().distriqtAPIKey);
      Firebase.init(FirebaseConfigModel.getInstance().distriqtAPIKey);
					
      FirebaseDynamicLinks.init(FirebaseConfigModel.getInstance().distriqtAPIKey);
      if(Constants.IS_IOS)
        Firebase.service.deepLinkURLScheme = FirebaseConfigModel.getInstance().iosDeepLinkURIScheme;
      Firebase.service.initialiseApp();
      _logger.info("Firebase is initialized.");
    } else {
      _logger.warn("Firebase is not supported on this device.");
    }
    _isInitialized = true;
  }
}
```

I have ensured the IOS deep link URI scheme is being set. The URI scheme matches the one set under `CFBundleURLSchemes` under `CFBundleURLTypes` in `infoAdditions`.

**Comment by marchbold** [comment]
Okay that looks good,

Can you post the logs from the device?

**Comment by embpdaniel** [comment]
@marchbold Actually you can see all logs (app and device logs) in the logs email I sent you in August 11th. In the email I also noted the app's name so you can identify logs coming from the app itself. Check those out and let me know.

**Comment by marchbold** [comment]
Apologies, I had forgotten you had sent them through. I'll check through them again.

**Comment by marchbold** [comment]
Can you double check that you have the latest Core ANE? It seems like the delegates just aren't being called in your open application, which could be a result of an old version of the Core ANE.

**Comment by marchbold** [comment]
Also, make sure you have updated the other ANEs. If you have an old version of one of the ANEs it may have the old core framework packaged with it which could cause issues.

**Comment by embpdaniel** [comment]
Hi @marchbold finally got back to this. I have re-downloaded all 4 ANEs from the links in the [wiki](https://github.com/distriqt/ANE-Firebase/wiki/Core---Add-the-extensions#required-anes) and have downloaded the latest Dynamic Links ANE from my account's download page. Still it is a no go :(

I did a sanity check to ensure the deep linking does still work if the app is completely closed, and that does still work just fine. I also made a fresh dynamic link to check with and it still behaves the same. Please let me know what else we can try or what could be keeping my dynamic link from working when the app is in the background. Thanks

**Comment by marchbold** [comment]
Could you post the logs from your device with all the updated ANEs? Just so we can confirm the same issue is still occurring?

**Comment by embpdaniel** [comment]
@marchbold I have emailed you (to airnativeextensions@distriqt.com) the logs using the updated ANEs. Let me know if you need anything else, thanks!

**Comment by embpdaniel** [comment]
@marchbold Lmk if you got the log. I re-emailed it Oct 3rd, since I saw I had not attached it the first time

**Comment by marchbold** [comment]
Thanks for that, yes, we have it now and are looking through it.

**Comment by marchbold** [comment]
Just confirming that this log is from a link received while the app was running in the background?

**Comment by embpdaniel** [comment]
Yes @marchbold that is correct

**Comment by marchbold** [comment]
Are you sure you aren't calling `dispose()` on the extension when the application gets deactivated? That seems to be the only way I can replicate the log you have sent me.

Do you have a deactivate handler?

**Comment by embpdaniel** [comment]
@marchbold I have double-checked and no, we are not calling dispose in any of the Firebase/Distriqt related extensions on deactivate, or at any other time for that matter.

I think what I will do when I get some time is to set it up on a basic project and see how that behaves, so we can eliminate the possibility of it being something related to my project. May take me some time to get around to it but I will keep you posted!

**Comment by marchbold** [comment]
Thanks, that would be helpful.
