### ISSUE TITLE
ERROR ITMS-90034: "Missing or invalid signature."

### ISSUE THREAD

**Issue by qbuchanan** [distriqt/ANE-Firebase#95]
Hi,
I am currently getting this error with the latest core ANE, any ideas?

 ERROR ITMS-90034: "Missing or invalid signature." The bundle 'com.distriqt.extensions.CoreNativeExtension' at bundle path 'Payload/ImpactNext.app/CoreNativeExtension.framework' is not signed using an Apple submission certificate."
  TIA
  -Quinn

**Comment by marchbold** [comment]
Hi,
When are you getting this error, or do you have a method we can reproduce it with?

**Comment by qbuchanan** [comment]
I get this when I try to package for on iOS for App Store distribution (or
test flight as the case may be).  I was wondering if they framework had any
debug code in the build or something like that that could affect signing of
the ANE.  All the other ANEs appear to sign correctly.  The app also signs
correctly for Dev builds and Ad Hoc.

**Comment by marchbold** [comment]
So is this reported when packaging the ipa or when uploading to itunesconnect?

**Comment by qbuchanan** [comment]
uploading to itunes connect as part of the verification process.

(sorry for the bad bug report was after midnight local time)

so to recap,  The error occurs when building for distribution on the App
Store and uploading the ipa to iTunes connect.  Application returns the
error as part of the verification process, and I am unable to continue.  I
think I ran into something a long, long time ago with one of our internal
ANEs where the ANE itself was not compiled / signed correctly (it had some
debug code in it or something - was about 3 years back) so it would work
correctly in debug and ad hoc builds, but not for app store distribution
builds.

**Comment by marchbold** [comment]
What version of AIR are you using to package your application?

**Comment by qbuchanan** [comment]
25.0.0.134 SDK

**Comment by qbuchanan** [comment]
I have tried on multiple machines running 10.11.5, 10.12.4 10.11.6, with
different profiles and I get the same thing :/

**Comment by qbuchanan** [comment]
and here is a screen shot of what Application Loader says

**Comment by qbuchanan** [comment]
Michael,
I had some time to try a few things out checking builds between two
different iOS dev account (both with working certificates)  The issue seems
to arise if I use the version (from around 7/27/2017) of

<extensionID>com.distriqt.NativeWebView</extensionID>

with a newer

<extensionID>com.distriqt.Core</extensionID>


However if I use the version of NativeWebView from 11/10/16 (or there about
- 11/10/16 may have been when I added it to the project).  Everything
compiles as expected and I can submit to the app store.

Here is the list of ANEs used in both project for reference

Project shipping in App Store since 10/2013
<extensions>
<extensionID>com.diadraw.extensions.DiaDrawScreenCast</extensionID>
<extensionID>com.distriqt.Image</extensionID>
<extensionID>com.distriqt.Core</extensionID>
<extensionID>com.distriqt.Bolts</extensionID>
<extensionID>com.distriqt.AndroidSupport</extensionID>
<extensionID>com.distriqt.CameraRollExtended</extensionID>
<extensionID>com.distriqt.NativeWebView</extensionID>
<extensionID>com.freshplanet.AirNativeShare</extensionID>
<extensionID>com.freshplanet.AirImagePicker</extensionID>
<extensionID>com.freshplanet.AirVideo</extensionID>
<extensionID>com.distriqt.MediaPlayer</extensionID>
</extensions>

newer app (with lots of commented out ANEs while we tracked this down

<extensions>
<extensionID>com.diadraw.extensions.DiaDrawScreenCast</extensionID>
<extensionID>com.freshplanet.AirNativeShare</extensionID>
<extensionID>com.freshplanet.AirImagePicker</extensionID>
<extensionID>com.freshplanet.AirVideo</extensionID>
<extensionID>com.distriqt.Image</extensionID>
<extensionID>com.distriqt.Core</extensionID>





<extensionID>com.distriqt.CameraRollExtended</extensionID>
<extensionID>com.distriqt.MediaPlayer</extensionID>
<extensionID>com.distriqt.NativeWebView</extensionID>

</extensions>

as a note the diadraw and fresh planet ANEs listed above are custom ANEs
built in house using those ANEs as a starting point.

**Comment by marchbold** [comment]
Have you tried a package with the latest version of all the distriqt extensions? Is that failing as well?

Are you using hide lib symbols option in your package?

**Comment by qbuchanan** [comment]
I think I am packaging with all the latest versions.  As I mentioned I was able to circumvent by using an older version of the native web view .   When I get back in I will do another update and test again.

**Comment by marchbold** [comment]
If you don't mind could you try the 27 beta as well, there are some fixes for signing packaged frameworks in that update so I'm wondering if it's an AIR related issue. I'll try to reproduce the issue here.

**Comment by marchbold** [comment]
Are you using "hide ane lib symbols" option in your package?

**Comment by qbuchanan** [comment]
I don't think so.   I am not at a place where I can check at the moment
(sorry about that)

**Comment by marchbold** [comment]
What IDE are you using? If you don't know about it then more than likely you aren't using it which is what we want.

**Comment by qbuchanan** [comment]
Using Intellij from jetbrains

**Comment by qbuchanan** [comment]
just tracked this down in intellij - its set to false.  The IDE auto sets
this so that if I set it as a command line option, the IDE is overriding
the value.  Will let you know when I track that down and include a screen
shot of where to set the value.  I am also in the process of downloading
all the latest ANEs from github to test in the app.

more soon

**Comment by qbuchanan** [comment]
so.... I can set it in iOS but not in Android (which doesn't make any
sense) looking around some more....

**Comment by qbuchanan** [comment]
Ok just finished rebuilding with the latest and greatest of everything
(minus the firebase ANEs ATM) and its looking good.  I will add those back
in shortly so I can do a verify for you on those as well.

**Comment by qbuchanan** [comment]
Just added all the firebase back in and everything looks like its working
now.

thank you very much for the help :-)

**Comment by qbuchanan** [comment]
actually I spoke too soon :-(  still investigating will let you know more
soon.

**Comment by qbuchanan** [comment]
ok so this is what I am seeing

If I set -hideAneLibSymbols to yes, I get an nondescript error of ld64
failed from both inside the IDE and if I run adt from a command prompt.

I am unable to upload to iTunes connect if I use the latest version of the
NativeWebView ANE, however if I use the original 2.0 version of the library
I am able to compile and upload to iTunes connect just fine.

Using beta 27 of the AIR SDK did not change any of the results :-/

any more ideas?  ( I can keep using an older version of the ANE for now)

**Comment by qbuchanan** [comment]
Just went through the commit log in git and grab the build checked in on
June 22nd, 2017 and it works fine, its only the latest build that I am
having an issue with :-(

**Comment by marchbold** [comment]
Hi,

I think you misunderstood, We do NOT want you to use that setting, it is an iOS only setting and can cause issues!

We'll keep trying to reproduce the issue here, but could you check that you have a valid version of the Core ANE?

**Comment by qbuchanan** [comment]
How do I do that?  I grabbed the latest out of GitHub today for the test?  July 9th @ 8:38 pm

**Comment by marchbold** [comment]
Yeah that's all I meant, if you've done that then there must be something on our side. 

Have you tried linking with a version of the iOS SDK at all?

**Comment by marchbold** [comment]
I've been able to replicate the issue, apologies for the run around. I'm working on a solution now.

**Comment by qbuchanan** [comment]
Thanks man :)

**Comment by qbuchanan** [comment]
Glad to help out :)

**Comment by marchbold** [comment]
Hey, could you grab the latest NativeWebView and Core ANEs and let me know if you are still seeing this issue?

**Comment by qbuchanan** [comment]
Looking good :-)

Just grab them the latest core and native web view ANEs out of GitHub and did a build.  Build looks good and uploaded to iTunes connect using Application Loader without a problem.  Waiting for it to clear processing on the iTunes connect site and will ping you when I get confirmation its ready for distribution / submittal (probably about 10 minutes from now).  But I think thats got it :-)

  -Quinn

**Comment by qbuchanan** [comment]
And we are good, iTunes connect has accepted and likes the build :-)

Thank You!!!!!

**Comment by marchbold** [comment]
Brilliant! 

Thanks for your patience!
