### ISSUE TITLE
Android with Firebase Crashes on Startup

### ISSUE THREAD

**Issue by cevansOTBS** [distriqt/ANE-Firebase#96]
The app with Firebase with just the Core and related extensions is crashing on startup.

I narrowed down the problem to this area in the Manifest:
		
		<provider
			android:authorities="air.myapp.firebaseinitprovider"
			android:name="com.google.firebase.provider.FirebaseInitProvider"
			android:exported="false"
			android:initOrder="100" />

If I remove that, then the app won't crash on startup. However the Firebase service won't be able to initialize when the app launches due to configuration problems.

If I'm not mistaken that part of the manifest involves Google Play services.  But I'm pretty sure I have everything, here are the extensions included:

  <extensions>
    <extensionID>com.distriqt.androidsupport.V4</extensionID>
    <extensionID>com.distriqt.Core</extensionID>
    <extensionID>com.distriqt.Firebase</extensionID>
    <extensionID>com.distriqt.playservices.Base</extensionID>
    <extensionID>com.distriqt.CustomResources</extensionID>
  </extensions>

Any idea what's causing the crash or what I might be missing? 

##### Environment 

- AIR SDK version: 26
- Device OS: Android
- Device version: 7.0
- Development IDE: Flash CC/FlashBuilder
- Development OS: Windows 7

**Comment by embpdaniel** [comment]
@cevansOTBS Wondering if you had the same issue as I did [here](https://github.com/distriqt/ANE-Firebase/issues/91). I had to make sure I had the latest google play services ANE.

**Comment by cevansOTBS** [comment]
Great, thanks @embpdaniel that did the trick!

**Comment by marchbold** [comment]
Glad you found the issue. Just to note, with Firebase you need to keep the Google Play Services versions matching. They are closely related in the Google ecosystem and you'll experience crashes if you don't match versions, typically on startup.
