### ISSUE TITLE
Exception: Syntax Error

### ISSUE THREAD

**Issue by sfxworks** [distriqt/ANE-Firebase#97]
![scoutoverview](https://user-images.githubusercontent.com/5921035/29320334-d07cb962-81a4-11e7-94d6-af6617ffbe16.png)

Running into issues with using once functions. When getting data from my database, I see a lot of hidden syntax errors. I can't figure out where they are coming from, but it happens for every node. None of my data is corrupt and I can handle my value:Object just fine. But I get this huge list of errors in Adobe Scout.  Nothing but fetch requests and responses appear in the logs. Let me know if you need them. 

Manufacturer: Samsung
Model: SM-T818V
Board: Msm8976
Android API: 24
Android OS: 7.0

**Comment by marchbold** [comment]
Can you post the full details of the error?

**Comment by sfxworks** [comment]
What it is throwing in that black window is the most I can get. Nothing appears in the logs as it appears to come from the ANE.

**Comment by marchbold** [comment]
Can you get the complete lines from that error in the black window at all?

**Comment by sfxworks** [comment]
I, unfortunately, don't know if a way...

**Comment by sfxworks** [comment]
Forgot that once takes my functions. I found the issue in scout under the actionscript pane. This is from the logger. I am sending a lot of notes to it but it doesn't explain why the syntax errors are occurring.

**Comment by marchbold** [comment]
What do you mean by "notes"?

**Comment by sfxworks** [comment]
Inside my once function, I am using FirebaseCrash.log from another class file. Although, trying to remove this doesn't seem to have solved the issue as I still get a ton of syntax errors. I don't know what else to do but to show you the class files pertaining to the issue. Did the scout file help at all?

**Comment by marchbold** [comment]
It looks as though the JSON parsing is taking a long time to pass from the native layer. How much data are you requesting? My guess is that you are attempting to read a large portion of the database and it's taking a long time and potentially encountering some errors.

**Comment by sfxworks** [comment]
Quite a lot.. I'd say a user would fetch nearly all of it in the course of a session. Mainly because I can't use something like a filtered query https://github.com/distriqt/ANE-Firebase/issues/83 (coudln't find anything similar in Firebase's SDK) or shallow https://github.com/distriqt/ANE-Firebase/issues/80 

For instance, I retrieve nodes containing item names, which I believe we already have ~200. But items have sub nodes of flavors and flavors have sub nodes of sizes. All of which belongs only to one manufacturer. Work arounds would include remodeling it somehow to have a general list but then it becomes harder to assign certain variants certain attributes.

**Comment by marchbold** [comment]
Hi, Just wanted to close out this issue, but just want to say that anyone else encountering something like this, should restructure their data. Requesting a large amount of data will always cause issues when parsing and converting from native to as3.
