### ISSUE TITLE
Asynchronous 

### ISSUE THREAD

**Issue by sfxworks** [distriqt/ANE-Firebase#98]
I'm not sure if this already is, but it would be awesome if it was. I am using the dialog on logins and initial reads from the database and that freezes up on heavy processes. It would be great if, for instance, I could run large queries and handle them further in another worker thread. I do have the option of loading everything once and then having a Worker manage the objects but then I'd have to read the object back to the Worker on a change so it would sort of defeat the purpose.

I could achieve some of this with a RestAPI and a Worker, but it would be great if the ANE had it build in for some heavy functions.
https://stackoverflow.com/a/12041005/5488621

**Comment by marchbold** [comment]
What exactly is causing this issue? We nearly always implement asynchronous calls wherever we believe there will be a delay.

**Comment by sfxworks** [comment]
If you do already (with the once function as well) then I believe that this is the main issue... https://github.com/distriqt/ANE-Firebase/issues/97
