### ISSUE TITLE
Problems Accessing Storage bucket

### ISSUE THREAD

**Issue by cevansOTBS** [distriqt/ANE-Firebase#99]
I'm having trouble accessing my Firebase storage bucket. 

This is the AS3 code:

```
var root:StorageReference = FirebaseStorage.service.getReference();
var reference:StorageReference = root.child( "my_files/" );
trace("my bucket: " + root.getBucket() ); // Traces out to XXX
var task:UploadTask = reference.putFile( file );
```

I made sure on the Firebase Console that the anonymous sign-ins are allowed for testing. I also set the rules to public. 

But when I attempt to upload, the app crashes and get the following error:
```
StorageException: StorageException has occurred
.
StorageException: Object does not exist at location.
StorageException:  Code: -13010 HttpResult: 404

StorageException: The server has terminated the upload session
StorageException: java.io.IOException: The server has terminated the upload session
```

My Google Services JSON references the proper Firebase bucket and as I said, I've set the permissions to allow anonymous sign-ins. I tried using "getReferenceFromUrl" but didn't have luck with that either. It couldn't find the gs:// and I get this error "The supplied bucketname does not match the storage bucket of the current instance."

Clearly my app can't find the bucket, but I'm running out of ideas on where the problem might be. Any help would be appreciated. 

Thanks

##### Environment 

- AIR SDK version: 26.0
- Device OS: Android 7.0
- Device version: 
- Development IDE: 
- Development OS:

##### Logs

Device logs if relevant

**Comment by marchbold** [comment]
Have you tried without the `/` in your child reference or with a proper file name?

```as3
var reference:StorageReference = root.child( "my_files/filename.ext" );
```

**Comment by cevansOTBS** [comment]
Yep, I tried it without the "/" and still no luck. That's actually what I had originally. 

What does it mean that it's returning "XXX" when I use getBucket() ?

**Comment by marchbold** [comment]
Oh I had assumed you were blocking out your bucket name. 

That should be returning your configured bucket name, have you correctly added it to your resources? ie. does your values.xml contain the correct value?

**Comment by cevansOTBS** [comment]
Great, thanks that was it!  Can't believe I got the tricky stuff right, but I got undone by overlooking a configuration value. Basically I had the default storage value of "XXX" in values.xml and that's what caused the problem.

**Comment by marchbold** [comment]
Always the simple things hey! Glad it's running for you now.
